### ISSUE TITLE
MediaPipe hands examples gives me errors, using WINDOWS

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#1018]
Hi there, i have a problem with the hands example and i'm stuck on it !!!!!

In the cmd using the command that you recommend: 
" bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu "

I get this error:
**INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Traceback (most recent call last):
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210
                _get_python_lib(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, in _get_python_lib
                execute(repository_ctx, <1 more arguments>)
        File "C:/users/diego/_bazel_diego/p2omsmjl/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
File "<string>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
INFO: Elapsed time: 0.635s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)**

**Comment by dgrnd4** [comment]
Hi @jiuqiant ,
Do you have a solution for that problem?
I have already changed the version of bazel with the one that you said but still this problem
Many thanks.

**Comment by Zumbalamambo** [comment]
@dgrnd4 is my same problem at #1035

**Comment by dgrnd4** [comment]
Solved installing UBUNTU because window for these things is a problem
