### ISSUE TITLE
ModuleNotFoundError mediapipe.python._framework_bindings

### ISSUE THREAD

**Issue by andriiD** [google/mediapipe#1044]
The import of mediapipe in python doesn't work (__version__ = '0.79')
I built and installed everything from scratch on Ubuntu 18.04 but cannot run mediapipe in python

```
import mediapipe as mp

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/home/user/docker_workspace/mediapipe/mediapipe/__init__.py", line 16, in <module>

    import mediapipe.examples.python as examples

  File "/home/user/docker_workspace/mediapipe/mediapipe/examples/python/__init__.py", line 16, in <module>

    from mediapipe.examples.python.upper_body_pose_tracker import UpperBodyPoseTracker

  File "/home/user/docker_workspace/mediapipe/mediapipe/examples/python/upper_body_pose_tracker.py", line 42, in <module>

    import mediapipe.python as mp

  File "/home/user/docker_workspace/mediapipe/mediapipe/python/__init__.py", line 17, in <module>

    from mediapipe.python._framework_bindings import resource_util

ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

```

**Comment by mgyong** [comment]
@andriiD Have you followed the instructions to install MediaPipe python ?https://google.github.io/mediapipe/getting_started/building_examples.html#python

**Comment by andriiD** [comment]
Yes. I've done all steps in the instructions

**Comment by jiuqiant** [comment]
Do you leave the mediapipe repo directory?

**Comment by andriiD** [comment]
I forgot to leave the mediapipe directory. Thank you
