### ISSUE TITLE
Building MediaPipe Examples - Build did not complete successfully

### ISSUE THREAD

**Issue by JoschuaXner** [google/mediapipe#1059]
Hey,

i tried to run the [MediaPipe Explame for Android via Android Studio](https://google.github.io/mediapipe/getting_started/building_examples.html)

But i ran into an issue after i created a new config and tried to run it on my device.
This is the following output:

```
C:\bazel\bazel.exe mobile-install --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
Loading: 
Loading: 0 packages loaded
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/py/python_configure.bzl", line 209
		_check_python_bin(<2 more arguments>)
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, in _check_python_bin
		get_bash_bin(repository_ctx)
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/remote_config/common.bzl", line 66, in get_bash_bin
		which(repository_ctx, "bash")
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, in which
		execute(repository_ctx, <1 more arguments>)
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
INFORMATION: Es konnten keine Dateien mit dem angegebenen
Muster gefunden werden.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Traceback (most recent call last):
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/py/python_configure.bzl", line 209
		_check_python_bin(<2 more arguments>)
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, in _check_python_bin
		get_bash_bin(repository_ctx)
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/remote_config/common.bzl", line 66, in get_bash_bin
		which(repository_ctx, "bash")
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, in which
		execute(repository_ctx, <1 more arguments>)
	File "C:/users/my_user_name/_bazel_my_user_name/bogw2hlz/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed
INFORMATION: Es konnten keine Dateien mit dem angegebenen
Muster gefunden werden.
INFO: Elapsed time: 0.279s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

Did someone experience the same issue and knows how to fix it?

**Comment by jiuqiant** [comment]
As (the install insturction)[https://google.github.io/mediapipe/getting_started/install#installing-on-windows] mentions,  building MediaPipe Android apps is not possible on native Windows.
