### ISSUE TITLE
Building instructions for Windows don't work...

### ISSUE THREAD

**Issue by drhalftone** [google/mediapipe#1061]
I've followed the directions, but I get the following errors.  I know this issue was already posted, but no solution was provided before the issue was closed.  From what I read, the person who closed the issue thinks the issue was due to the person trying to compile an Android program on Windows.  But I am trying to compile the Desktop Hello World application:

C:\Users\dllau\mediapipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//dllau//AppData//Local//Programs//Python//Python38//python" mediapipe/examples/desktop/hello_world
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl", line 213
                _get_numpy_include(<2 more arguments>)
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl", line 198, in _get_numpy_include
                execute(repository_ctx, [python_bin, "-c", "from __future__ import print_function;import numpy; print(numpy.get_include());"], error_msg = "Problem getting numpy include path.", error_details = "Is numpy installed?").stdout.splitlines()
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, in execute
                execute(repository_ctx, <3 more arguments>)
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dllau\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "C:\Users\dllau\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\dllau\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Is numpy installed?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl", line 213
                _get_numpy_include(<2 more arguments>)
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl", line 198, in _get_numpy_include
                execute(repository_ctx, [python_bin, "-c", "from __future__ import print_function;import numpy; print(numpy.get_include());"], error_msg = "Problem getting numpy include path.", error_details = "Is numpy installed?").stdout.splitlines()
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, in execute
                execute(repository_ctx, <3 more arguments>)
        File "C:/users/dllau/_bazel_dllau/3ky6mj3u/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dllau\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "C:\Users\dllau\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\dllau\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Is numpy installed?
INFO: Elapsed time: 31.363s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 11 targets configured)

**Comment by s8sun** [comment]
Do you have numpy installed? I had this error message too on Linux. Later on I realize it needs numpy in python2 and I had it in python3 only. So maybe you can check if you have numpy on both python2 and 3?

**Comment by jiuqiant** [comment]
The issue you have is numpy isn't installed. 

Moreover, MediaPipe Windows support is only working with version v0.7.5. See https://github.com/google/mediapipe/issues/908. You can git checkout v0.7.5 to try the Windows demos.

Since this issue is duplicated with https://github.com/google/mediapipe/issues/908, we are going to merge it back to https://github.com/google/mediapipe/issues/908 and close this one.

**Comment by drhalftone** [comment]
Yes, thank you.  I used Source Tree to open and reset my local repo for mediapipe and checked out version 0.7.5 just like you said.  It is compiling now.
