### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#1083]
I tried to run the iris_tracking on desktop and got into below error , even I typed 'python' on my command prompt then it shows as ptyhon3.5.2 and also python and script path is set properly as ENV/System variable "PYTHON", but still getting this below error.

command:

`bazel.exe' build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/iris_tracking:iris_depth_from_image_desktop
`

error message:
```

INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  C:/users/vasantha/_bazel_vasantha/wcxhmgip/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/vasantha/_bazel_vasantha/wcxhmgip/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/vasantha/_bazel_vasantha/wcxhmgip/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/vasantha/_bazel_vasantha/wcxhmgip/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, column 13, in execute
                fail(
Error in fail: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("D:\Users\Vasantha\AppData\Local\Programs\Python\Python35\python.exe
C:\Users\Vasantha\AppData\Local\Microsoft\WindowsApps\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linese(...)): The system cannot find the file specified.
 (error: 2)
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "2a34fa56d923f774409d23720e60ddf6536e88622d000e6925f7cebbad65e281"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/users/vasantha/_bazel_vasantha/wcxhmgip/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/desktop/iris_tracking:iris_depth_from_image_desktop' failed; build aborted: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("D:\Users\Vasantha\AppData\Local\Programs\Python\Python35\python.exe
C:\Users\Vasantha\AppData\Local\Microsoft\WindowsApps\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linese(...)): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 2.456s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
```

Attached screenshot of error here:

![image](https://user-images.githubusercontent.com/20619142/92223116-fc4d6d00-ee6d-11ea-8cd7-0ff55fc95fc3.png)

**Comment by quickgrid** [comment]
I recently faced this error, 'local_execution_config_python' in ubuntu. I was initially using python 3.8. In my case it was solved by using Miniconda python 3.7 by installing `numpy` and `six` which was already installed.

**Comment by fadi-GitHub** [comment]
I am also facing the same problem if anyone of you solved it please reply.

**Comment by UnickSoft** [comment]
I was able to fix it by passing path of include dir. Change line in script to this:

python_include = "C:/Users/User/AppData/Local/Programs/Python/Python310/include"  #_get_python_include(repository_ctx, python_bin)

**Comment by jinfagang** [comment]
@unicksoft which script??

**Comment by UnickSoft** [comment]
> @UnickSoft which script??

Unfortunately, I cannot find this place right now (I did it year ago).  But I suppose it was in file external/org_tensorflow/third_party/py/python_configure.bzl

**Comment by ShowAppStructure** [comment]
you can use pyhton3.10 , just set    --action_env PYTHON_BIN_PATH
like this  ::


bazel run --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="/opt/homebrew/bin/python3" examples/desktop/hello_world:hello_world
