### ISSUE TITLE
Ccompiling failed!!

### ISSUE THREAD

**Issue by lovehuanhuan** [google/mediapipe#1085]
I use the docker to compile android app,but got error msg.(master version)

command:
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu

err msg:
config.status: executing libtool commands
'src/config.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog_v_0_3_5/config.h.tmp'
'src/glog/logging.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog_v_0_3_5/src/glog/logging.h.tmp'
'src/glog/raw_logging.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog_v_0_3_5/src/glog/raw_logging.h'
'src/glog/stl_logging.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog_v_0_3_5/src/glog/stl_logging.h'
'src/glog/vlog_is_on.h' -> 'bazel-out/android-arm64-v8a-opt/bin/external/com_github_glog_glog_v_0_3_5/src/glog/vlog_is_on.h'
INFO: From ProtoCompile mediapipe/calculators/tflite/ssd_anchors_calculator.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tflite/tflite_converter_calculator.pb.h:
bazel-out/android-arm64-v8a-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
[1,388 / 2,865] 128 actions, 4 running
[1,388 / 2,865] 128 actions, 4 running
    Compiling external/org_tensorflow/tensorflow/lite/kernels/activations.cc; 219s processwrapper-sandbox
[1,388 / 2,865] 128 actions, 4 running
[1,388 / 2,865] 128 actions, 4 running
    Compiling external/org_tensorflow/tensorflow/lite/kernels/activations.cc; 418s processwrapper-sandbox
[1,388 / 2,865] 128 actions, 4 running
    Compiling external/org_tensorflow/tensorflow/lite/kernels/activations.cc; 419s processwrapper-sandbox
    Compiling external/org_tensorflow/tensorflow/lite/kernels/arg_min_max.cc; 417s processwrapper-sandbox
ERROR: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/maven/BUILD:122:1: Dexing external/maven/_dx/androidx_asynclayoutinflater_asynclayoutinflater/classes_and_libs_merged.jar_desugared.jar with applicable dexopts [] failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Stream closed
        at java.base/java.lang.ProcessBuilder$NullOutputStream.write(Unknown Source)
        at java.base/java.io.OutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
        at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:126)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:353)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:190)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:129)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:225)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:122)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:87)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:332)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:123)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:905)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1040)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1011)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:589)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:902)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:292)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/bazel-workers/worker-11-DexBuilder.log ---8<---8<---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/android_tools/all_android_tools_deploy.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
---8<---8<--- End of log ---8<---8<---
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2479.943s, Critical Path: 1610.54s
INFO: 1997 processes: 1878 processwrapper-sandbox, 119 worker.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
Thanks for reporting this issue. 

I didn't try the current version. But, I made some updates to the Dockerfile and setup_android_sdk_and_ndk.sh (they need to be updated anyway). Try the following changes and see if it works for you.
```
diff --git a/Dockerfile b/Dockerfile
index 6267a5f..d622191 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -54,7 +54,7 @@ RUN pip3 install tf_slim
 RUN ln -s /usr/bin/python3 /usr/bin/python

 # Install bazel
-ARG BAZEL_VERSION=2.0.0
+ARG BAZEL_VERSION=3.0.0
 RUN mkdir /bazel && \
     wget --no-check-certificate -O /bazel/installer.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/b\
 azel-${BAZEL_VERSION}-installer-linux-x86_64.sh" && \
diff --git a/setup_android_sdk_and_ndk.sh b/setup_android_sdk_and_ndk.sh
index 3007908..54ed69a 100644
--- a/setup_android_sdk_and_ndk.sh
+++ b/setup_android_sdk_and_ndk.sh
@@ -63,10 +63,10 @@ then
 else
   rm -rf /tmp/android_sdk/
   mkdir  /tmp/android_sdk/
-  curl https://dl.google.com/android/repository/sdk-tools-${platform}-4333796.zip -o /tmp/android_sdk/android_sdk.zip
-  unzip /tmp/android_sdk/android_sdk.zip -d /tmp/android_sdk/
+  curl https://dl.google.com/android/repository/commandlinetools-${platform}-6609375_latest.zip -o /tmp/android_sdk/commandline_tools.zip
+  unzip /tmp/android_sdk/commandline_tools.zip -d /tmp/android_sdk/
   mkdir -p $android_sdk_path
-  /tmp/android_sdk/tools/bin/sdkmanager --update
+  /tmp/android_sdk/tools/bin/sdkmanager --update --sdk_root=${android_sdk_path}
   /tmp/android_sdk/tools/bin/sdkmanager "build-tools;29.0.1" "platform-tools" "platforms;android-29" --sdk_root=${android_sdk_path}
   rm -rf /tmp/android_sdk/
   echo "Android SDK is now installed. Consider setting \$ANDROID_HOME environment variable to be ${android_sdk_path}"
```

You should be able to get something like the following:
```
root@7f85b1470712: bash setup_android_sdk_and_ndk.sh
Warning: android_sdk_path (argument 1) is not specified. Fallback to ~/Android/Sdk/
Warning: android_ndk_path (argument 2) is not specified. Fallback to ~/Android/Sdk/ndk-bundle/android-ndk-<NDK_VERSION>/
Warning: ndk_version (argument 3) is not specified. Fallback to r18b.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82.5M  100 82.5M    0     0  61.1M      0  0:00:01  0:00:01 --:--:-- 61.1M
Archive:  /tmp/android_sdk/commandline_tools.zip
 extracting: /tmp/android_sdk/tools/bin/avdmanager
 extracting: /tmp/android_sdk/tools/bin/sdkmanager
 extracting: /tmp/android_sdk/tools/bin/apkanalyzer
 extracting: /tmp/android_sdk/tools/bin/lint
 extracting: /tmp/android_sdk/tools/bin/screenshot2
......
  inflating: /root/Android/Sdk/ndk-bundle/android-ndk-r18b/CHANGELOG.md
  inflating: /root/Android/Sdk/ndk-bundle/android-ndk-r18b/ndk-stack
Android NDK is now installed. Consider setting $ANDROID_NDK_HOME environment variable to be /root/Android/Sdk/ndk-bundle/android-ndk-r18b
Set android_ndk_repository and android_sdk_repository in WORKSPACE
Done

root@7f85b1470712:/mediapipe# bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = 2a34fa56d923f774409d23720e60ddf6536e88622d000e6925f7cebbad65e281
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "2a34fa56d923f774409d23720e60ddf6536e88622d000e6925f7cebbad65e281"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /mediapipe/WORKSPACE:33:1
......
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu:objectdetectiongpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu/objectdetectiongpu_deploy.jar
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu/objectdetectiongpu_unsigned.apk
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu/objectdetectiongpu.apk
INFO: Elapsed time: 221.488s, Critical Path: 84.01s
INFO: 3099 processes: 2935 processwrapper-sandbox, 164 worker.
INFO: Build completed successfully, 3252 total actions
```

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.

**Comment by teemiik** [comment]
@jiuqiant your solution did not help, the error occurs
