### ISSUE TITLE
Android examples build fails with NPE

### ISSUE THREAD

**Issue by HanaDB** [google/mediapipe#1110]
Command ran: Clone && bash setup_android_sdk_and_ndk.sh && bash build_android_examples.sh 
I also installed jdk 11. I have tried bazel expunge.

Fails repeatedly with:

```
log/d5e37adf1406cf899d7d9ec1d317c47506ccb970.tar.gz
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[969bb0bdb8c096eb9f47806e344169d4fcd31f6f40cc8858cd905e9e2614666f]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[969bb0bdb8c096eb9f47806e344169d4fcd31f6f40cc8858cd905e9e2614666f]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[969bb0bdb8c096eb9f47806e344169d4fcd31f6f40cc8858cd905e9e2614666f]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:587)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:280)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:384)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1034)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1096)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:982)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:83)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:364)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:191)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:888)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:974)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:356)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[969bb0bdb8c096eb9f47806e344169d4fcd31f6f40cc8858cd905e9e2614666f]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[969bb0bdb8c096eb9f47806e344169d4fcd31f6f40cc8858cd905e9e2614666f]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[969bb0bdb8c096eb9f47806e344169d4fcd31f6f40cc8858cd905e9e2614666f]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:587)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:280)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:384)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1034)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1096)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:982)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:83)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
FAILED: Build did NOT complete successfully (72 packages loaded, 2615 targets configured)
```

I'd appreciate any help thanks!

**Comment by sgowroji** [comment]
Hi @HanaDB, Could you please test the above issue with the latest release and let us know if you still facing the same error.
