### ISSUE TITLE
Error running pose tracking android app

### ISSUE THREAD

**Issue by ashrvstv** [google/mediapipe#1134]
I am trying to convert [MultiHand Tracking app](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) into **Pose Tracking** app

It is getting installed on phone but crashing after asking camera permission.

Showing following error at Logcat (android stuido) 

```
2020-09-22 00:38:11.139 13245-13463/com.example.mediapipemultihandstrackingapp E/native: E20200922 00:38:11.139611 13463 graph.cc:407] ; Input Stream "multi_hand_landmarks" for node with sorted index 2 does not have a corresponding output stream.
2020-09-22 00:38:11.152 13245-13463/com.example.mediapipemultihandstrackingapp I/mali_egl: eglDestroySurface() in
2020-09-22 00:38:11.152 13245-13463/com.example.mediapipemultihandstrackingapp I/mali_egl: eglDestroySurface() out
2020-09-22 00:38:11.153 13245-13463/com.example.mediapipemultihandstrackingapp D/GlThread: Stopping GL thread ExternalTextureConverter
2020-09-22 00:38:11.160 13245-13463/com.example.mediapipemultihandstrackingapp E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.example.mediapipemultihandstrackingapp, PID: 13245
    com.google.mediapipe.framework.MediaPipeException: unknown: ; Input Stream "multi_hand_landmarks" for node with sorted index 2 does not have a corresponding output stream.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:534)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:406)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:424)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:350)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:295)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
2020-09-22 00:38:11.277 13245-13463/com.example.mediapipemultihandstrackingapp I/Process: Sending signal. PID: 13245 SIG: 9

```

**Steps to reproduce**

**step 1** - git clone https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example 

**step 2** - create `mp_pose_landmark_aar.aar` following the steps provided here https://google.github.io/mediapipe/getting_started/android_archive_library.html

**step 3** - replace `mp_multi_hand_aar.aar` by `mp_pose_landmark_aar.aar`at `mediapipe_multi_hands_tracking_aar_example/app/libs/`

**step 4** - Replace asset 
`hand_landmark.tflite`
`handedness.txt`
`multi_hand_tracking_mobile_gpu.binarypb`
`palm_detection.tflite`
`palm_detection_labelmap.txt`
by 
`pose_detection.tflite`
`pose_landmark_upper_body.tflite`
`uppper_body_pose_tracking_gpu.binarypb`

at mediapipe_multi_hands_tracking_aar_example/app/src/main/assets/

**step 5**- make some changes at `mainActivity.java`
This is how it looks like after making  changes.

```.java
package com.example.mediapipemultihandstrackingapp;

import android.graphics.SurfaceTexture;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import android.util.Log;
import android.util.Size;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList;
import com.google.mediapipe.components.CameraHelper;
import com.google.mediapipe.components.CameraXPreviewHelper;
import com.google.mediapipe.components.ExternalTextureConverter;
import com.google.mediapipe.components.FrameProcessor;
import com.google.mediapipe.components.PermissionHelper;
import com.google.mediapipe.framework.AndroidAssetUtil;
import com.google.mediapipe.framework.PacketGetter;
import com.google.mediapipe.glutil.EglManager;
import com.google.protobuf.InvalidProtocolBufferException;
import java.util.List;
/** Main activity of MediaPipe example apps. */
public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    
    //CHANGE 1
    //private static final String BINARY_GRAPH_NAME = "multi_hand_tracking_mobile_gpu.binarypb";**
    private static final String BINARY_GRAPH_NAME = "upper_body_pose_tracking_gpu.binarypb";
    
    private static final String INPUT_VIDEO_STREAM_NAME = "input_video";
    private static final String OUTPUT_VIDEO_STREAM_NAME = "output_video";
    private static final String OUTPUT_LANDMARKS_STREAM_NAME = "multi_hand_landmarks";
    
    //CHANGE 2
    //private static final CameraHelper.CameraFacing CAMERA_FACING = CameraHelper.CameraFacing.FRONT;
    private static final CameraHelper.CameraFacing CAMERA_FACING = CameraHelper.CameraFacing.BACK;
    

    // Flips the camera-preview frames vertically before sending them into FrameProcessor to be
    // processed in a MediaPipe graph, and flips the processed frames back when they are displayed.
    // This is needed because OpenGL represents images assuming the image origin is at the bottom-left
    // corner, whereas MediaPipe in general assumes the image origin is at top-left.
    private static final boolean FLIP_FRAMES_VERTICALLY = true;
    static {
        // Load all native libraries needed by the app.
        System.loadLibrary("mediapipe_jni");
        System.loadLibrary("opencv_java3");
    }
    // {@link SurfaceTexture} where the camera-preview frames can be accessed.
    private SurfaceTexture previewFrameTexture;
    // {@link SurfaceView} that displays the camera-preview frames processed by a MediaPipe graph.
    private SurfaceView previewDisplayView;
    // Creates and manages an {@link EGLContext}.
    private EglManager eglManager;
    // Sends camera-preview frames into a MediaPipe graph for processing, and displays the processed
    // frames onto a {@link Surface}.
    private FrameProcessor processor;
    // Converts the GL_TEXTURE_EXTERNAL_OES texture from Android camera into a regular texture to be
    // consumed by {@link FrameProcessor} and the underlying MediaPipe graph.
    private ExternalTextureConverter converter;
    // Handles camera access via the {@link CameraX} Jetpack support library.
    private CameraXPreviewHelper cameraHelper;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        previewDisplayView = new SurfaceView(this);
        setupPreviewDisplayView();
        // Initialize asset manager so that MediaPipe native libraries can access the app assets, e.g.,
        // binary graphs.
        AndroidAssetUtil.initializeNativeAssetManager(this);
        eglManager = new EglManager(null);
        processor =
                new FrameProcessor(
                        this,
                        eglManager.getNativeContext(),
                        BINARY_GRAPH_NAME,
                        INPUT_VIDEO_STREAM_NAME,
                        OUTPUT_VIDEO_STREAM_NAME);
        processor.getVideoSurfaceOutput().setFlipY(FLIP_FRAMES_VERTICALLY);
        processor.addPacketCallback(
                OUTPUT_LANDMARKS_STREAM_NAME,
                (packet) -> {
                    Log.v(TAG, "Received multi-hand landmarks packet.");
                    try {
                        NormalizedLandmarkList multiHandLandmarks =
                                PacketGetter.getProto(packet, NormalizedLandmarkList.class);
                        Log.v(
                                TAG,
                                "[TS:"
                                        + packet.getTimestamp()
                                        + "] "
                                        + getMultiHandLandmarksDebugString(multiHandLandmarks));
                    } catch (InvalidProtocolBufferException exception) {
                        Log.e(TAG, "Failed to get proto.", exception);
                    }
                });
        PermissionHelper.checkAndRequestCameraPermissions(this);
    }
    @Override
    protected void onResume() {
        super.onResume();
        converter = new ExternalTextureConverter(eglManager.getContext());
        converter.setFlipY(FLIP_FRAMES_VERTICALLY);
        converter.setConsumer(processor);
        if (PermissionHelper.cameraPermissionsGranted(this)) {
            startCamera();
        }
    }
    @Override
    protected void onPause() {
        super.onPause();
        converter.close();
    }
    @Override
    public void onRequestPermissionsResult(
            int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        PermissionHelper.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }
    private void setupPreviewDisplayView() {
        previewDisplayView.setVisibility(View.GONE);
        ViewGroup viewGroup = findViewById(R.id.preview_display_layout);
        viewGroup.addView(previewDisplayView);
        previewDisplayView
                .getHolder()
                .addCallback(
                        new SurfaceHolder.Callback() {
                            @Override
                            public void surfaceCreated(SurfaceHolder holder) {
                                processor.getVideoSurfaceOutput().setSurface(holder.getSurface());
                            }
                            @Override
                            public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
                                // (Re-)Compute the ideal size of the camera-preview display (the area that the
                                // camera-preview frames get rendered onto, potentially with scaling and rotation)
                                // based on the size of the SurfaceView that contains the display.
                                Size viewSize = new Size(width, height);
                                Size displaySize = cameraHelper.computeDisplaySizeFromViewSize(viewSize);
                                // Connect the converter to the camera-preview frames as its input (via
                                // previewFrameTexture), and configure the output width and height as the computed
                                // display size.
                                converter.setSurfaceTextureAndAttachToGLContext(
                                        previewFrameTexture, displaySize.getWidth(), displaySize.getHeight());
                            }
                            @Override
                            public void surfaceDestroyed(SurfaceHolder holder) {
                                processor.getVideoSurfaceOutput().setSurface(null);
                            }
                        });
    }
    private void startCamera() {
        cameraHelper = new CameraXPreviewHelper();
        cameraHelper.setOnCameraStartedListener(
                surfaceTexture -> {
                    previewFrameTexture = surfaceTexture;
                    // Make the display view visible to start showing the preview. This triggers the
                    // SurfaceHolder.Callback added to (the holder of) previewDisplayView.
                    previewDisplayView.setVisibility(View.VISIBLE);
                });
        cameraHelper.startCamera(this, CAMERA_FACING, /*surfaceTexture=*/ null);
    }

    private String getMultiHandLandmarksDebugString(NormalizedLandmarkList multiHandLandmarks) {
        String multiHandLandmarksStr = "pose landmarks: " + multiHandLandmarks.getLandmarkCount() + "\n";
        int landmarkIndex = 0;
        for (NormalizedLandmark landmark : multiHandLandmarks.getLandmarkList()) {
            multiHandLandmarksStr +=
                    "\t\tLandmark ["
                            + landmarkIndex
                            + "]: ("
                            + landmark.getX()
                            + ", "
                            + landmark.getY()
                            + ", "
                            + landmark.getZ()
                            + ")\n";
            ++landmarkIndex;
        }
        return multiHandLandmarksStr;
    }
}

```

**Comment by ashrvstv** [comment]
@jiuqiant please have a look.

**Comment by mgyong** [comment]
@ashrvstv You wrapped the multi-hand graph with pose graph. However, you did not change the input and output streams called by your `MainActivity.java` which is what the errors below is saying
`2020-09-22 00:38:11.139 13245-13463/com.example.mediapipemultihandstrackingapp E/native: E20200922 00:38:11.139611 13463 graph.cc:407] ; Input Stream "multi_hand_landmarks" for node with sorted index 2 does not have a corresponding output stream.`

change `private static final String OUTPUT_LANDMARKS_STREAM_NAME = "multi_hand_landmarks";`
to 
`private static final String OUTPUT_LANDMARKS_STREAM_NAME = "pose_landmarks";`

For cleaner code, suggest changing the following variables multiHandLandmarks etc

**Comment by ashrvstv** [comment]
Many thanks @mgyong it worked.
