### ISSUE TITLE
Android single handtracking example App build successfully but stopped unexpectedly with unsatisfied link error.   

### ISSUE THREAD

**Issue by shehramjamil** [google/mediapipe#1183]
OS : Ubuntu 20.04

Run time error :
 java.lang.UnsatisfiedLinkError: com.google.devtools.build.android.incrementaldeployment.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.handtrackinggpu/dex/incremental_classes1.dex"],nativeLibraryDirectories=[/data/user/0/com.google.mediapipe.apps.handtrackinggpu/lib, /system/lib, /system/vendor/lib]]] couldn't find "libmediapipe_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:51)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1182)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2854)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by criminact** [comment]
How did you solve this issue?

**Comment by shehramjamil** [comment]
@criminact 
try to partially sync your hand tracking or other java code file and then try to install the app.
If the java file is not synced, it will cause problem.
