### ISSUE TITLE
Iris Depth Web demo fails with error in app_bundle.js

### ISSUE THREAD

**Issue by nlothian** [google/mediapipe#1209]
Steps to reproduce

1. Visit https://viz.mediapipe.dev/demo/iris_depth (Google Chrome on MacOS)
2. Press the run button
3. UI displays "Waiting..." and nothing happens
4. Inspect, console shows:
```
app_bundle.js:9597 Error: <path> attribute d: Unexpected end of attribute. Expected number, "….29,16L2.89,18L9".
m.setAttribute @ app_bundle.js:9597
```

**Comment by sgowroji** [comment]
Hi @nlothian, Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!

**Comment by nlothian** [comment]
> Hi @nlothian, Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!

Yes, just ran it again today with exactly the same error. 

Chrome is `Version 91.0.4472.114 (Official Build) (x86_64)`

**Comment by sureshdagooglecom** [comment]
Hi @nlothian ,
Could you please reproduce the above error with the latest release and let us know if the issue still exists. Thanks!

**Comment by nick-verida** [comment]
Latest version still has the error:

```
iris_depth_bin.js:9 F0715 08:59:58.958000       1 default_demo.embind.cc:250] Check failed: absl::OkStatus() == ::util::status_internal::AsStatus((graph_->Initialize(graph_configs_, {}))) (OK vs. NOT_FOUND: ValidatedGraphConfig Initialization failed.
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 No registered object with name: ImageFrameToGpuBufferCalculator; Unable to find Calculator "ImageFrameToGpuBufferCalculator" [type.googleapis.com/mediapipe.StatusList='\n\x80\x01\x08\x05\x12|No registered object with name: ImageFrameToGpuBufferCalculator; Unable to find Calculator \"ImageFrameToGpuBufferCalculator\"']
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 === Source Location Trace: === 
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 third_party/mediapipe/framework/tool/status_util.cc:139
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 third_party/mediapipe/framework/validated_graph_config.cc:381
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 third_party/mediapipe/framework/calculator_graph.cc:448
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 ) 
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 *** Check failure stack trace: ***
put_char @ iris_depth_bin.js:9
iris_depth_bin.js:9 undefined
abort @ iris_depth_bin.js:9
iris_depth_bin.js:9 Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (iris_depth_bin.js:9:68135)
    at stackTrace (iris_depth_bin.js:9:68387)
    at abort (iris_depth_bin.js:9:41695)
    at _abort (iris_depth_bin.js:9:180919)
    at iris_depth_bin.wasm:0x65d98f
    at iris_depth_bin.wasm:0x65d846
    at iris_depth_bin.wasm:0x65d9a8
    at iris_depth_bin.wasm:0x1ea85
    at iris_depth_bin.wasm:0x19ac9
    at iris_depth_bin.wasm:0x19b4d
    at abort (iris_depth_bin.js:9:41726)
    at _abort (iris_depth_bin.js:9:180919)
    at iris_depth_bin.wasm:0x65d98f
    at iris_depth_bin.wasm:0x65d846
    at iris_depth_bin.wasm:0x65d9a8
    at iris_depth_bin.wasm:0x1ea85
    at iris_depth_bin.wasm:0x19ac9
    at iris_depth_bin.wasm:0x19b4d
    at Object.changeTextGraph (eval at new_ (iris_depth_bin.js:9:163054), <anonymous>:8:1)
    at DefaultDemoApi.setGraph (default_demo_api.js:79:20)
```

**Comment by sureshdagooglecom** [comment]
Hi ,Are you looking for resolution.

**Comment by alexandernst** [comment]
Is any work made on this?

**Comment by ayushgdev** [comment]
@nlothian To add more information, the error provided in the issue description pops up without running the graph as well.
@mhays-google The error provided [here](https://github.com/google/mediapipe/issues/1209#issuecomment-1185024160) is also reproducible at our end once an image with EXIF data is uploaded. 
Can you please take a look into this issue?
