### ISSUE TITLE
NoClassDefFoundError in Android Archive Example

### ISSUE THREAD

**Issue by lupries** [google/mediapipe#1237]
Following the instructions in https://google.github.io/mediapipe/getting_started/android_archive_library.html I am able to build the Face Detection example app including the .aar library.
However, during startup the app crashes with the following error:

```
2020-10-28 17:27:25.726 15673-15673/com.example.face_detection_aar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.face_detection_aar, PID: 15673
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/camera/lifecycle/ProcessCameraProvider;
        at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:136)
        at com.example.face_detection_aar.MainActivity.startCamera(MainActivity.java:170)
        at com.example.face_detection_aar.MainActivity.onResume(MainActivity.java:129)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7400)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.camera.lifecycle.ProcessCameraProvider" on path: DexPathList[[zip file "/data/app/com.example.face_detection_aar-HPqKzFbqAoi-C0_DfwZDJQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.face_detection_aar-HPqKzFbqAoi-C0_DfwZDJQ==/lib/arm64, /data/app/com.example.face_detection_aar-HPqKzFbqAoi-C0_DfwZDJQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:136) 
        at com.example.face_detection_aar.MainActivity.startCamera(MainActivity.java:170) 
        at com.example.face_detection_aar.MainActivity.onResume(MainActivity.java:129) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413) 
        at android.app.Activity.performResume(Activity.java:7400) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3820) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3860) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
```

I'm using the following dependencies in build.gradle:
```
dependencies {
    ...
    // CameraX core library
    def camerax_version = "1.0.0-beta10"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
}
```

**Comment by jiuqiant** [comment]
Probably need to add `implementation  "androidx.camera:camera-lifecycle:$camerax_version` into the dependencies.

**Comment by lupries** [comment]
Sorry forgot to copy/paste the line. Unfortunately not the reason for this error.
Btw... when I switch to an older commit where `1.0.0-alpha06` was used it's working fine without any errors.
The error only appears since commit c828392681bc343a90e188c5ad5f295bada1eefb 9 days ago and only when using mediapipe as .aar library.

**Comment by XiangBaoSong** [comment]
there is the problem on the newest branch ,but l must use that.how can l sovel the same problem?thanks!!!

but these file both exists here
![image](https://user-images.githubusercontent.com/24597687/112426643-45fe9600-8d73-11eb-916e-e1702acb4c88.png)

**Comment by jpeltone** [comment]
I'm having the same issue and downgrading to 1.0.0-alpha06 does not help, any ideas how to solve this?
