### ISSUE TITLE
Bazel sync failed when building Android examples

### ISSUE THREAD

**Issue by david-siqi-liu** [google/mediapipe#1275]
Hi! I'm trying to build examples using Android Studio:
https://google.github.io/mediapipe/getting_started/building_examples.html#option-2-build-with-bazel-in-android-studio

- macOS: Catalina v10.15.7
- xcode-select: v2373
- Bazel: 3.4.0--homebrew
- SDK: 29
- NDK: r18b
- WORKSPACE:
```
android_ndk_repository(
    name = "androidndk",
    path = "/Users/dliu/Library/Android/ndk/android-ndk-r18b"
)

android_sdk_repository(
    name = "androidsdk",
    path = "/Users/dliu/Library/Android/sdk"
)
```

Error:
```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --

Command: git diff --name-status --no-renames f15da632dec186f2c1d3c780f47086477e2286a9

Computing VCS working set...
  .DS_Store (added)
  .aswb/.bazelproject (added)
  .aswb/.blaze/modules/.project-data-dir.iml (added)
  .aswb/.blaze/modules/.workspace.iml (added)
  .aswb/.idea/.gitignore (added)
  .aswb/.idea/.name (added)
  .aswb/.idea/misc.xml (added)
  .aswb/.idea/modules.xml (added)
  .aswb/.idea/runConfigurations.xml (added)
  .aswb/.idea/vcs.xml (added)
  .cache/content_addressable/sha256/213733991310b904b11b053ac224fee2d4e0179e46b52fe7f8735b8831e04dcc/file (added)
  .cache/content_addressable/sha256/3f2dc1970f397a0e59db72f9fca6ff144b216895c1d606f6c94a507c1e53a025/file (added)
  .cache/content_addressable/sha256/43146e6f56cb5218a8caaab6b5d1601a083f1f31c06ff474a4378a7d35be9cfb/file (added)
  .cache/content_addressable/sha256/5f4dabc2ae21e1f537425d58a49cdca1c49ea11db0d6271e2a4b27e9697548eb/file (added)
  .cache/content_addressable/sha256/b1f2ee97e46d8917a66bcb47452fc510d511829556c93b83e06841b9b35261a5/file (added)
  WORKSPACE (modified)
  WORKSPACE-e (added)
  build_android_examples.sh (modified)
  out_dir/helloworld.apk (added)
  setup_android_sdk_and_ndk.sh (modified)
  (and 1 more)

Querying targets building source files...
Command: /usr/local/bin/bazel query --tool_tag=ijwb:AndroidStudio --output=label_kind --keep_going same_pkg_direct_rdeps(//:.DS_Store+//:.cache/content_addressable/sha256/213733991310b904b11b053ac224fee2d4e0179e46b52fe7f8735b8831e04dcc/file+//:.cache/content_addressable/sha256/3f2dc1970f397a0e59db72f9fca6ff144b216895c1d606f6c94a507c1e53a025/file+//:.cache/content_addressable/sha256/43146e6f56cb5218a8caaab6b5d1601a083f1f31c06ff474a4378a7d35be9cfb/file+//:.cache/content_addressable/sha256/5f4dabc2ae21e1f537425d58a49cdca1c49ea11db0d6271e2a4b27e9697548eb/file+//:.cache/content_addressable/sha256/b1f2ee97e46d8917a66bcb47452fc510d511829556c93b83e06841b9b35261a5/file+//:WORKSPACE-e+//:out_dir/helloworld.apk+//third_party:opencv_android.BUILD-e+//:WORKSPACE+//:build_android_examples.sh+//:setup_android_sdk_and_ndk.sh) --

Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/var/folders/hw/7lr6yp7s3g378s_yzlk33f600000gn/T/intellij-bep-899d5668-b669-4b24-8377-c96ad5c7fa24 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noexperimental_run_validations --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/dliu/Library/Application Support/Google/AndroidStudio4.1/plugins/aswb/aspect" --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-resolve-android,intellij-resolve-java -- //mediapipe/examples/android/...:all //mediapipe/java/...:all

Loading: 
Loading: 0 packages loaded
Analyzing: 76 targets (28 packages loaded, 0 targets configured)
Analyzing: 76 targets (115 packages loaded, 1232 targets configured)
Analyzing: 76 targets (137 packages loaded, 3049 targets configured)
ERROR: /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: While resolving configuration keys for @com_google_absl//absl/memory:memory: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/base:core_headers: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/strings:strings: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/status:status: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/time:time: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_protobuf//:protobuf: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/base:base: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/synchronization:synchronization: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/meta:type_traits: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/container:flat_hash_set: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/algorithm:container: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/types:optional: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/strings:str_format: Analysis of target '@local_config_cc//:toolchain' failed
Analyzing: 76 targets (165 packages loaded, 3892 targets configured)
ERROR: While resolving configuration keys for @com_google_absl//absl/flags:flag: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/container:node_hash_map: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/container:fixed_array: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/container:flat_hash_map: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/base:config: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: While resolving configuration keys for @com_google_absl//absl/base:dynamic_annotations: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Repository remotejdk11_macos instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository android_opencv instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository android_tools instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'android_opencv':
   java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'remotejdk11_macos':
   java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'android_tools':
   java.io.IOException: thread interrupted
INFO: Repository XNNPACK instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule tf_http_archive defined at:
  /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/org_tensorflow/third_party/repo.bzl:131:34: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/30d4b250aef4ee74271c2254943f062a8356a23e.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'XNNPACK':
   java.io.IOException: thread interrupted
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//mediapipe/gpu:pixel_buffer_pool_util BuildConfigurationValue.Key[783822befae68b79cd83848cdf12afcabc76ce1fb9318387762666afd133c245]' (requested by nodes '//mediapipe/gpu:gpu_buffer_multi_pool BuildConfigurationValue.Key[783822befae68b79cd83848cdf12afcabc76ce1fb9318387762666afd133c245]')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:585)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:280)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:384)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1032)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1094)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:980)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:83)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:350)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:185)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:887)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:971)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:354)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more

INFO: Elapsed time: 4.089s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (166 packages loaded, 3932 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//mediapipe/gpu:pixel_buffer_pool_util BuildConfigurationValue.Key[783822befae68b79cd83848cdf12afcabc76ce1fb9318387762666afd133c245]' (requested by nodes '//mediapipe/gpu:gpu_buffer_multi_pool BuildConfigurationValue.Key[783822befae68b79cd83848cdf12afcabc76ce1fb9318387762666afd133c245]')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:585)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:280)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:384)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1032)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1094)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:980)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:83)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:350)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:185)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:887)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:971)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:354)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//mediapipe/gpu:pixel_buffer_pool_util BuildConfigurationValue.Key[783822befae68b79cd83848cdf12afcabc76ce1fb9318387762666afd133c245]' (requested by nodes '//mediapipe/gpu:gpu_buffer_multi_pool BuildConfigurationValue.Key[783822befae68b79cd83848cdf12afcabc76ce1fb9318387762666afd133c245]')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:585)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:280)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:384)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1032)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1094)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:980)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:83)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:350)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:185)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:887)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:971)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:354)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
FAILED: Build did NOT complete successfully (166 packages loaded, 3932 targets configured)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (166 packages loaded, 3932 targets configured)
build invocation result: fatal_error
Sync finished

Timing summary:
BlazeInvocation: 4.8s, Prefetching: 0ms, Other: 0ms
Sync failed
```

Any help is appreciated. Thanks!

**Comment by david-siqi-liu** [comment]
FYI, I am able to run `hello_world`. Hopefully, that means my installation is correct.

**Comment by jiuqiant** [comment]
The issue is `Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/30d4b250aef4ee74271c2254943f062a8356a23e.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found`. 

Please read https://github.com/google/mediapipe/blob/master/docs/getting_started/troubleshooting.md#fail-to-fetch-remote-dependency-repositories.

**Comment by david-siqi-liu** [comment]
Thanks @jiuqiant , seems like Bazel is quite unstable in getting the dependencies. I am not using any VPN as I am based in Canada.

What about the other issues related to toolchain? Any idea?
```
ERROR: /private/var/tmp/_bazel_dliu/d5e78a296bc9de3b2efa425e07a04dd0/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'
ERROR: While resolving configuration keys for @com_google_absl//absl/memory:memory: Analysis of target '@local_config_cc//:toolchain' failed
```

Thanks!

**Comment by david-siqi-liu** [comment]
Fixed the issue - had to do with my XCode installation

**Comment by c1139676919** [comment]
@david-siqi-liu  hello，Can you tell me how you solved it?Can you give a contact information?thanks

**Comment by david-siqi-liu** [comment]
@c1139676919 I just re-installed XCode, nothing else

**Comment by c1139676919** [comment]
> @ c1139676919我刚刚重新安装了XCode，没别的

thanks,Now I have a new question, I don't know if you have encountered,this is my log.

```
Waiting for target device...
Invoking mobile-install...
Command: /Users/hc/bin/bazel mobile-install --tool_tag=ijwb:AndroidStudio --device 65f58306:tcp:5037 "--adb_arg=-s " --adb_arg=65f58306 --adb /Users/hc/Library/Android/sdk/platform-tools/adb --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=/var/folders/gg/mc24xfld0bz95qp_jvr3_tc80000gn/T/intellij-bep-4bdd75f3-be2e-4120-9fee-cdc894c35f12 --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu --nolaunch_app

Loading: 
Loading: 0 packages loaded
ERROR: Skipping '-nolaunch_app': no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /Users/hc/AndroidStudioProjects/mediapipe/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//:-nolaunch_app': target '-nolaunch_app' not declared in package '' defined by /Users/hc/AndroidStudioProjects/mediapipe/BUILD.bazel
INFO: Elapsed time: 0.299s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

```
What is this -nolaunch_app thing?

**Comment by david-siqi-liu** [comment]
@c1139676919 have you tried removing `-nolaunch_app`? I recall getting similar errors and remember reading somewhere that this option has been deprecated, so I just removed it

**Comment by c1139676919** [comment]
> @c1139676919 have you tried removing `-nolaunch_app`? I recall getting similar errors and remember reading somewhere that this option has been deprecated, so I just removed it

sorry,I can't find `-nolaunch_app`,I looked in the project and it told me it didn't find.
![image](https://user-images.githubusercontent.com/43144608/103547463-61c66e80-4edf-11eb-99db-2724a7c20e34.png)

**Comment by david-siqi-liu** [comment]
@c1139676919 it would be in your build configuration. See step 10 in here:
https://google.github.io/mediapipe/getting_started/android.html#option-2-build-with-bazel-in-android-studio

**Comment by david-siqi-liu** [comment]
@c1139676919 but do you see not see `-nolaunch_app` in your configuration? What does yours look like?

**Comment by c1139676919** [comment]
> @ c1139676919，但您`-nolaunch_app`在配置中看不到吗？你长什么样？

![image](https://user-images.githubusercontent.com/43144608/103548653-14e39780-4ee1-11eb-870a-f76de6d91cee.png)
Should I choose this.sorry,my english is not good.

**Comment by david-siqi-liu** [comment]
@c1139676919  try removing `Use mobile-install` ... I wonder what happens

**Comment by c1139676919** [comment]
> @ c1139676919 尝试删除`Use mobile-install`...我想知道会发生什么

thanks.this is my log.
```
Command: /Users/hc/bin/bazel build --tool_tag=ijwb:AndroidStudio --output_groups=+android_deploy_info --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm64 --build_event_binary_file=/var/folders/gg/mc24xfld0bz95qp_jvr3_tc80000gn/T/intellij-bep-c232b1ed-4249-46f6-b54a-bd81f4cce365 --nobuild_event_binary_file_path_conversion -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

Loading: 
Loading: 0 packages loaded
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured)

```
Maybe it will do.it hasn't finished running yet.

**Comment by c1139676919** [comment]
> @ c1139676919 尝试删除`Use mobile-install`...我想知道会发生什么



> @ c1139676919 尝试删除`Use mobile-install`...我想知道会发生什么

Thank you very much, I can now run through on `Android studio`.

**Comment by chensisi0730** [comment]
大佬门，可以留个联系方式吗

**Comment by chensisi0730** [comment]
难道就是重装xcode就解决啦 ？没别的原因 ？

**Comment by jiuqiant** [comment]
FYI, using MediaPipe in Android Studio with Bazel is deprecated. Please see the new gradle approach in https://github.com/google/mediapipe/blob/master/docs/getting_started/android_solutions.md.
