### ISSUE TITLE
BitMap Image packet first time while asking permission not rendered

### ISSUE THREAD

**Issue by Arul2962** [google/mediapipe#1329]
I am Trying to send single bitmap image instead of video in graph for hair segmentation

Converted the imageframe to gpubuffer using the ImageFrameToGpuBufferCalculator calculator.
Build compiles successfully.

The app at starting while asking **_permissions_** for Camera and Storage access,
if we select the image the bitmap image packet is not rendered in output and throws **null at MainActivity for reading width of image**

```
2020-11-24 19:11:05.195 8763-8763/? E/SurfaceView: Exception configuring surface
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference
        at com.google.mediapipe.apps.basic.MainActivity.onPreviewDisplaySurfaceChanged(MainActivity.java:192)
        at com.google.mediapipe.apps.basic.MainActivity$1.surfaceChanged(MainActivity.java:212)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:704)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:152)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2699)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1602)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7655)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
        at android.view.Choreographer.doCallbacks(Choreographer.java:839)
        at android.view.Choreographer.doFrame(Choreographer.java:768)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1020)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7096)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
```

The same time if  **selecting image second time it works fine as expected.**

But the bitmap image is **not null for the first time** and moreover 
while using

```
ImageDecoder.Source source = ImageDecoder.createSource(this.getContentResolver(), data.getData());
bitmap = ImageDecoder.decodeBitmap(source);
```

 this error occurs,

if I use **getBitMapFromUri** which is `depricated` also same error

Need Help

**_Attaching graph for reference_**

**Graph:**
```

**#bitmap_image_stream is the bitmap image packet sended from user**
input_stream: "bitmap_image_stream"
output_stream: "output_video"


node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "bitmap_image_stream"
  output_stream: "input_video"
}


node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:hair_mask"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}


node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 512
      output_height: 512
    }
  }
}


node {
  calculator: "PreviousLoopbackCalculator"
  input_stream: "MAIN:throttled_input_video"
  input_stream: "LOOP:hair_mask"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:previous_hair_mask"
}


node {
  calculator: "SetAlphaCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  input_stream: "ALPHA_GPU:previous_hair_mask"
  output_stream: "IMAGE_GPU:mask_embedded_input_video"
}


node {
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE_GPU:mask_embedded_input_video"
  output_stream: "TENSORS_GPU:image_tensor"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteConverterCalculatorOptions] {
      zero_center: false
      max_num_channels: 4
    }
  }
}


node {
  calculator: "TfLiteCustomOpResolverCalculator"
  output_side_packet: "op_resolver"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteCustomOpResolverCalculatorOptions] {
      use_gpu: true
    }
  }
}


node {
  calculator: "TfLiteInferenceCalculator"
  input_stream: "TENSORS_GPU:image_tensor"
  output_stream: "TENSORS_GPU:segmentation_tensor"
  input_side_packet: "CUSTOM_OP_RESOLVER:op_resolver"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteInferenceCalculatorOptions] {
      model_path: "mediapipe/models/hair_segmentation.tflite"
      use_gpu: true
    }
  }
}

node {
  calculator: "TfLiteTensorsToSegmentationCalculator"
  input_stream: "TENSORS_GPU:segmentation_tensor"
  input_stream: "PREV_MASK_GPU:previous_hair_mask"
  output_stream: "MASK_GPU:hair_mask"
  node_options: {
    [type.googleapis.com/mediapipe.TfLiteTensorsToSegmentationCalculatorOptions] {
      tensor_width: 512
      tensor_height: 512
      tensor_channels: 2
      combine_with_previous_ratio: 0.9
      output_layer_index: 1
    }
  }
}

node {
  calculator: "RecolorCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "MASK_GPU:hair_mask"
  output_stream: "IMAGE_GPU:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.RecolorCalculatorOptions] {
      color { r: 0 g: 0 b: 255 }
      mask_channel: RED
    }
  }
} 
```

**Comment by Arul2962** [comment]
Getting permission from custom activity makes the error above,instead get the permission at extended MainActivity itself resolves the above issue.
