### ISSUE TITLE
The gpu version of the python interface can't work on NVIDIA Jetson Nano

### ISSUE THREAD

**Issue by lernem** [google/mediapipe#1344]
Hi @Source666 and @jiuqiant ,

Thanks to this post #1042 , I also successfully installed the GPU version of Python module on my NVIDIA Jetson Nano.
Then, I ran a python script in the example, and I met another error, could you please help check it? Thanks a lot.

**My environment:**
NVIDIA Jetson Nano
Ubuntu 18.04(NVIDIA JetPack 4.4.1)
MediaPipe's version is latest 0.8.0

**Script:**
```
import cv2
import mediapipe as mp

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

# For webcam input:
pose = mp_pose.Pose(
    min_detection_confidence=0.5, min_tracking_confidence=0.5)
cap = cv2.VideoCapture(0)
while cap.isOpened():
  success, image = cap.read()
  if not success:
    break

  # Flip the image horizontally for a later selfie-view display, and convert
  # the BGR image to RGB.
  image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
  # To improve performance, optionally mark the image as not writeable to
  # pass by reference.
  image.flags.writeable = False
  results = pose.process(image)

  # Draw the pose annotation on the image.
  image.flags.writeable = True
  image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
  mp_drawing.draw_landmarks(
      image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
  cv2.imshow('MediaPipe Pose', image)
  if cv2.waitKey(5) & 0xFF == 27:
    break
pose.close()
cap.release()
```

**And the error:**
```
Traceback (most recent call last):
  File "./jxz_pose.py", line 9, in <module>
    min_detection_confidence=0.5, min_tracking_confidence=0.5)
  File "/home/jetpack/mediapipe/mp_env/lib/python3.6/site-packages/mediapipe/python/solutions/pose.py", line 197, in __init__
    outputs=['pose_landmarks'])
  File "/home/jetpack/mediapipe/mp_env/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 212, in __init__
    validated_graph, side_inputs, outputs)
  File "/home/jetpack/mediapipe/mp_env/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 342, in _initialize_graph_interface
    for tag_index_name in canonical_graph_config_proto.input_stream
  File "/home/jetpack/mediapipe/mp_env/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 342, in <dictcomp>
    for tag_index_name in canonical_graph_config_proto.input_stream
  File "/home/jetpack/mediapipe/mp_env/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 338, in get_stream_packet_type
    get_name(packet_tag_index_name)))
RuntimeError: ; Unable to find the type for stream "image".  It may be set to AnyType or something else that isn't determinable, or the type may be defined but not registered.
```

Do you have any ideas?

**Comment by jiuqiant** [comment]
If you follow https://github.com/google/mediapipe/issues/1042#issuecomment-683506007 to modify the graph, the input stream name becomes to "input_video". Then https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/pose.py#L213 needs to be `return super().process(input_data={'input_video': image})`

**Comment by lernem** [comment]
> If you follow [#1042 (comment)](https://github.com/google/mediapipe/issues/1042#issuecomment-683506007) to modify the graph, the input stream name becomes to "input_video". Then https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/pose.py#L213 needs to be `return super().process(input_data={'input_video': image})`

Hi jiuqiant,

Thanks a lot! I modified the file as your advice, but the error still there.

I think my upper_body_pose_tracking_gpu.pbtxt may be different with the one in [#1042 (comment)](https://github.com/google/mediapipe/issues/1042#issuecomment-683506007)

Following is mine, could you please help check it?
```
# MediaPipe graph that performs upper-body pose tracking with TensorFlow Lite on GPU.

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"
# Pose landmarks. (NormalizedLandmarkList)
output_stream: "pose_landmarks"
 
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "input_video"
  output_stream: "input_video_gpu"
}

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video_gpu"
  input_stream: "FINISHED:output_video_gpu"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Subgraph that detects poses and corresponding landmarks.
node {
  calculator: "PoseLandmarkUpperBodyGpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "LANDMARKS:pose_landmarks"
  output_stream: "DETECTION:pose_detection"
  output_stream: "ROI_FROM_LANDMARKS:roi_from_landmarks"
}

# Calculates size of the image.
node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "SIZE:image_size"
}

# Smoothes pose landmarks in order to reduce jitter.
node {
  calculator: "LandmarksSmoothingCalculator"
  input_stream: "NORM_LANDMARKS:pose_landmarks"
  input_stream: "IMAGE_SIZE:image_size"
  output_stream: "NORM_FILTERED_LANDMARKS:pose_landmarks_smoothed"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarksSmoothingCalculatorOptions] {
      velocity_filter: {
        window_size: 5
        velocity_scale: 10.0
      }
    }
  }
}

# Subgraph that renders pose-landmark annotation onto the input image.
node {
  calculator: "UpperBodyPoseRendererGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_stream: "LANDMARKS:pose_landmarks_smoothed"
  input_stream: "ROI:roi_from_landmarks"
  input_stream: "DETECTION:pose_detection"
  output_stream: "IMAGE:output_video_gpu"
}

node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "output_video_gpu"
  output_stream: "output_video"
}
```

**Comment by lernem** [comment]
Hi @jiuqiant ,
Thinking about the error message,
```
RuntimeError: ; Unable to find the type for stream "image".  It may be set to AnyType or something else that isn't determinable, or the type may be defined but not registered.
```
Maybe the error is related with the lines which contain "IMAGE"?

**Comment by jiuqiant** [comment]
In your modified graph, there is no input stream named "image". But, it the original cpu graph, we have the input stream named "image". Now, I am wondering if you changed the graph path in pose.py To use the gpu graph, you need to modify https://github.com/google/mediapipe/blob/master/mediapipe/python/solutions/pose.py#L70 to be "mediapipe/modules/pose_landmark/pose_landmark_upper_body_gpu.binarypb" and rerun the setup.py.

Can you do a 'git diff' to show all your local changes. It's easier for me to understand your situation.

**Comment by lernem** [comment]
Hi @jiuqiant ,

It looks like the same with [#1042 (comment)](https://github.com/google/mediapipe/issues/1042#issuecomment-683506007)

```
diff --git a/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt b/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt
index 5f60846..84ad2fb 100644
--- a/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt
+++ b/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt
@@ -1,12 +1,16 @@
 # MediaPipe graph that performs upper-body pose tracking with TensorFlow Lite on GPU.
 
-# GPU buffer. (GpuBuffer)
 input_stream: "input_video"
 
-# Output image with rendered results. (GpuBuffer)
 output_stream: "output_video"
 # Pose landmarks. (NormalizedLandmarkList)
 output_stream: "pose_landmarks"
+ 
+node: {
+  calculator: "ImageFrameToGpuBufferCalculator"
+  input_stream: "input_video"
+  output_stream: "input_video_gpu"
+}
 
 # Throttles the images flowing downstream for flow control. It passes through
 # the very first incoming image unaltered, and waits for downstream nodes
@@ -20,8 +24,8 @@ output_stream: "pose_landmarks"
 # subsequent nodes are still busy processing previous inputs.
 node {
   calculator: "FlowLimiterCalculator"
-  input_stream: "input_video"
-  input_stream: "FINISHED:output_video"
+  input_stream: "input_video_gpu"
+  input_stream: "FINISHED:output_video_gpu"
   input_stream_info: {
     tag_index: "FINISHED"
     back_edge: true
@@ -68,5 +72,11 @@ node {
   input_stream: "LANDMARKS:pose_landmarks_smoothed"
   input_stream: "ROI:roi_from_landmarks"
   input_stream: "DETECTION:pose_detection"
-  output_stream: "IMAGE:output_video"
+  output_stream: "IMAGE:output_video_gpu"
 }
+
+node: {
+  calculator: "GpuBufferToImageFrameCalculator"
+  input_stream: "output_video_gpu"
+  output_stream: "output_video"
+}
```

**Comment by jiuqiant** [comment]
How about the other changes such as what Source666 mentioned in https://github.com/google/mediapipe/issues/1042#issue-685374280 and what I mentioned in https://github.com/google/mediapipe/issues/1042#issuecomment-681133474. Or, you just modified the graph only? Please show the full diff that includes all your changes to the mediapipe repo.

**Comment by lernem** [comment]
> How about the other changes such as what Source666 mentioned in [#1042 (comment)](https://github.com/google/mediapipe/issues/1042#issue-685374280) and what I mentioned in [#1042 (comment)](https://github.com/google/mediapipe/issues/1042#issuecomment-681133474). Or, you just modified the graph only? Please show the full diff that includes all your changes to the mediapipe repo.

Hi @jiuqiant ,

Thank you for help checking my graph file.
I made all the modifications in #1042 . I'm using the latest 0.8.0 MediaPipe, so it may be a little different with the version 0.7.5 used by #1042 .
Following is the full diff:

```
diff --git a/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc b/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc
index b77d8d4..cf6f969 100644
--- a/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc
+++ b/mediapipe/examples/desktop/demo_run_graph_main_gpu.cc
@@ -98,14 +98,14 @@ DEFINE_string(output_video_path, "",
     capture >> camera_frame_raw;
     if (camera_frame_raw.empty()) break;  // End of video.
     cv::Mat camera_frame;
-    cv::cvtColor(camera_frame_raw, camera_frame, cv::COLOR_BGR2RGB);
+    cv::cvtColor(camera_frame_raw, camera_frame, cv::COLOR_BGR2RGBA);
     if (!load_video) {
       cv::flip(camera_frame, camera_frame, /*flipcode=HORIZONTAL*/ 1);
     }
 
     // Wrap Mat into an ImageFrame.
     auto input_frame = absl::make_unique<mediapipe::ImageFrame>(
-        mediapipe::ImageFormat::SRGB, camera_frame.cols, camera_frame.rows,
+        mediapipe::ImageFormat::SRGBA, camera_frame.cols, camera_frame.rows,
         mediapipe::ImageFrame::kGlDefaultAlignmentBoundary);
     cv::Mat input_frame_mat = mediapipe::formats::MatView(input_frame.get());
     camera_frame.copyTo(input_frame_mat);


diff --git a/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt b/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt
index 5f60846..84ad2fb 100644
--- a/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt
+++ b/mediapipe/graphs/pose_tracking/upper_body_pose_tracking_gpu.pbtxt
@@ -1,12 +1,16 @@
 # MediaPipe graph that performs upper-body pose tracking with TensorFlow Lite on GPU.
 
-# GPU buffer. (GpuBuffer)
 input_stream: "input_video"
 
-# Output image with rendered results. (GpuBuffer)
 output_stream: "output_video"
 # Pose landmarks. (NormalizedLandmarkList)
 output_stream: "pose_landmarks"
+ 
+node: {
+  calculator: "ImageFrameToGpuBufferCalculator"
+  input_stream: "input_video"
+  output_stream: "input_video_gpu"
+}
 
 # Throttles the images flowing downstream for flow control. It passes through
 # the very first incoming image unaltered, and waits for downstream nodes
@@ -20,8 +24,8 @@ output_stream: "pose_landmarks"
 # subsequent nodes are still busy processing previous inputs.
 node {
   calculator: "FlowLimiterCalculator"
-  input_stream: "input_video"
-  input_stream: "FINISHED:output_video"
+  input_stream: "input_video_gpu"
+  input_stream: "FINISHED:output_video_gpu"
   input_stream_info: {
     tag_index: "FINISHED"
     back_edge: true
@@ -68,5 +72,11 @@ node {
   input_stream: "LANDMARKS:pose_landmarks_smoothed"
   input_stream: "ROI:roi_from_landmarks"
   input_stream: "DETECTION:pose_detection"
-  output_stream: "IMAGE:output_video"
+  output_stream: "IMAGE:output_video_gpu"
 }
+
+node: {
+  calculator: "GpuBufferToImageFrameCalculator"
+  input_stream: "output_video_gpu"
+  output_stream: "output_video"
+}
\ No newline at end of file


diff --git a/mediapipe/python/BUILD b/mediapipe/python/BUILD
index b8cdefc..6858767 100644
--- a/mediapipe/python/BUILD
+++ b/mediapipe/python/BUILD
@@ -55,12 +55,14 @@ cc_library(
     deps = [
         "//mediapipe/calculators/core:pass_through_calculator",
         "//mediapipe/calculators/core:split_normalized_landmark_list_calculator",
-        "//mediapipe/modules/face_detection:face_detection_front_cpu",
-        "//mediapipe/modules/face_landmark:face_landmark_front_cpu",
-        "//mediapipe/modules/hand_landmark:hand_landmark_tracking_cpu",
-        "//mediapipe/modules/palm_detection:palm_detection_cpu",
-        "//mediapipe/modules/pose_detection:pose_detection_cpu",
-        "//mediapipe/modules/pose_landmark:pose_landmark_upper_body_by_roi_cpu",
-        "//mediapipe/modules/pose_landmark:pose_landmark_upper_body_smoothed_cpu",
+        "//mediapipe/modules/face_detection:face_detection_front_gpu",
+        "//mediapipe/modules/face_landmark:face_landmark_front_gpu",
+        "//mediapipe/modules/hand_landmark:hand_landmark_tracking_gpu",
+        "//mediapipe/modules/palm_detection:palm_detection_gpu",
+        "//mediapipe/modules/pose_detection:pose_detection_gpu",
+        "//mediapipe/modules/pose_landmark:pose_landmark_upper_body_by_roi_gpu",
+        "//mediapipe/modules/pose_landmark:pose_landmark_upper_body_smoothed_gpu",
+        "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator",
+        "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator",
     ],
 )


diff --git a/mediapipe/python/solutions/pose.py b/mediapipe/python/solutions/pose.py
index 2f60be8..34fb5aa 100644
--- a/mediapipe/python/solutions/pose.py
+++ b/mediapipe/python/solutions/pose.py
@@ -67,7 +67,7 @@ class PoseLandmark(enum.IntEnum):
   LEFT_HIP = 24
 
 
-BINARYPB_FILE_PATH = 'mediapipe/modules/pose_landmark/pose_landmark_upper_body_smoothed_cpu.binarypb'
+BINARYPB_FILE_PATH = 'mediapipe/modules/pose_landmark/pose_landmark_upper_body_smoothed_gpu.binarypb'
 POSE_CONNECTIONS = frozenset([
     (PoseLandmark.NOSE, PoseLandmark.RIGHT_EYE_INNER),
     (PoseLandmark.RIGHT_EYE_INNER, PoseLandmark.RIGHT_EYE),
@@ -182,15 +182,16 @@ class Pose(SolutionBase):
         Ignored if "static_image_mode" is True, where person detection simply
         runs on every image. Default to 0.5.
     """
+    print('[jxz2]', BINARYPB_FILE_PATH)
     super().__init__(
         binary_graph_path=BINARYPB_FILE_PATH,
         side_inputs={
             'can_skip_detection': not static_image_mode,
         },
         calculator_params={
-            'poselandmarkupperbodycpu__posedetectioncpu__TensorsToDetectionsCalculator.min_score_thresh':
+            'poselandmarkupperbodygpu__posedetectiongpu__TensorsToDetectionsCalculator.min_score_thresh':
                 min_detection_confidence,
-            'poselandmarkupperbodycpu__poselandmarkupperbodybyroicpu__ThresholdingCalculator.threshold':
+            'poselandmarkupperbodygpu__poselandmarkupperbodybyroigpu__ThresholdingCalculator.threshold':
                 min_tracking_confidence,
         },
         outputs=['pose_landmarks'])
@@ -210,4 +211,6 @@ class Pose(SolutionBase):
       landmarks on the most prominent person detected.
     """
 
-    return super().process(input_data={'image': image})
+    # return super().process(input_data={'image': image})
+    print("jxz5")
+    return super().process(input_data={'input_video': image})


diff --git a/setup.py b/setup.py
index 32ccac5..fb23073 100644
--- a/setup.py
+++ b/setup.py
@@ -187,9 +187,9 @@ class BuildBinaryGraphs(build.build):
   def run(self):
     _check_bazel()
     binary_graphs = [
-        'face_landmark/face_landmark_front_cpu',
-        'hand_landmark/hand_landmark_tracking_cpu',
-        'pose_landmark/pose_landmark_upper_body_smoothed_cpu'
+        'face_landmark/face_landmark_front_gpu',
+        'hand_landmark/hand_landmark_tracking_gpu',
+        'pose_landmark/pose_landmark_upper_body_smoothed_gpu'
     ]
     for binary_graph in binary_graphs:
       sys.stderr.write('generating binarypb: %s\n' %
@@ -203,7 +203,8 @@ class BuildBinaryGraphs(build.build):
         'bazel',
         'build',
         '--compilation_mode=opt',
-        '--define=MEDIAPIPE_DISABLE_GPU=1',
+        '--copt=-DMESA_EGL_NO_X11_HEADERS',
+        '--copt=-DEGL_NO_X11',
         '--action_env=PYTHON_BIN_PATH=' + sys.executable,
         os.path.join('mediapipe/modules/', graph_path),
     ]
@@ -257,7 +258,8 @@ class BuildBazelExtension(build_ext.build_ext):
         'bazel',
         'build',
         '--compilation_mode=opt',
-        '--define=MEDIAPIPE_DISABLE_GPU=1',
+        '--copt=-DMESA_EGL_NO_X11_HEADERS',
+        '--copt=-DEGL_NO_X11',
         '--action_env=PYTHON_BIN_PATH=' + sys.executable,
         str(ext.bazel_target + '.so'),
     ]

     
diff --git a/third_party/opencv_linux.BUILD b/third_party/opencv_linux.BUILD
index 26978d5..8e01ef6 100644
--- a/third_party/opencv_linux.BUILD
+++ b/third_party/opencv_linux.BUILD
@@ -15,14 +15,14 @@ cc_library(
     name = "opencv",
     srcs = glob(
         [
-            "lib/x86_64-linux-gnu/libopencv_core.so",
-            "lib/x86_64-linux-gnu/libopencv_calib3d.so",
-            "lib/x86_64-linux-gnu/libopencv_features2d.so",
-            "lib/x86_64-linux-gnu/libopencv_highgui.so",
-            "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
-            "lib/x86_64-linux-gnu/libopencv_imgproc.so",
-            "lib/x86_64-linux-gnu/libopencv_video.so",
-            "lib/x86_64-linux-gnu/libopencv_videoio.so",
+            "lib/aarch64-linux-gnu/libopencv_core.so",
+            "lib/aarch64-linux-gnu/libopencv_calib3d.so",
+            "lib/aarch64-linux-gnu/libopencv_features2d.so",
+            "lib/aarch64-linux-gnu/libopencv_highgui.so",
+            "lib/aarch64-linux-gnu/libopencv_imgcodecs.so",
+            "lib/aarch64-linux-gnu/libopencv_imgproc.so",
+            "lib/aarch64-linux-gnu/libopencv_video.so",
+            "lib/aarch64-linux-gnu/libopencv_videoio.so",
         ],
     ),
     hdrs = glob([
```

**Comment by lernem** [comment]
Hi @jiuqiant ,

By the way, I successfully built and installed the GPU version MediaPipe(0.8.0) in C++ following the guide, and it works well, no such error happened. (The guide did not say the graph file needs to be modified, so I'm kind of confuse here.)

So is it possible that the error is not in the config/graph used both by C++ and Python module, but in one or more certain python scripts?

**Comment by lernem** [comment]
Hi @jiuqiant ,

Are the information I provided enough? Do you have any ideas about this issue? I will be happy to provide more information at any time!

Looking forward to your response. :)

**Comment by mariamrahmaani** [comment]
Anything you found here?

**Comment by lernem** [comment]
> Anything new you found here? have you solved this issue?
> I have the same issue with mediapipe 0.8 and A100 GPU when changing the python code of media pipe as above.
> 
> holistic = mp_holistic.Holistic()
> File "/home/mariam/anaconda3/envs/asl/lib/python3.6/site-packages/mediapipe/python/solutions/holistic.py", line 104, in **init**
> 'face_landmarks'
> File "/home/mariam/anaconda3/envs/asl/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 224, in **init**
> validated_graph, side_inputs, outputs)
> File "/home/mariam/anaconda3/envs/asl/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 353, in _initialize_graph_interface
> for tag_index_name in canonical_graph_config_proto.input_stream
> File "/home/mariam/anaconda3/envs/asl/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 353, in
> for tag_index_name in canonical_graph_config_proto.input_stream
> File "/home/mariam/anaconda3/envs/asl/lib/python3.6/site-packages/mediapipe/python/solution_base.py", line 349, in get_stream_packet_type
> get_name(packet_tag_index_name)))
> RuntimeError: ; Unable to find the type for stream "image". It may be set to AnyType or something else that isn't determinable, or the type may be defined but not registered.

I still did not solve it, maybe mediapipe team will support python gpu interface better in the future.

**Comment by jiuqiant** [comment]
See the code to run mediapipe python v0.8.3.1 on gpu: https://github.com/google/mediapipe/issues/1651#issuecomment-790176010

**Comment by lernem** [comment]
> See the code to run mediapipe python v0.8.3.1 on gpu: [#1651 (comment)](https://github.com/google/mediapipe/issues/1651#issuecomment-790176010)

Thank you jiuqiant. I've been working on another model recently and I'll be back to try your solution in the future.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
