### ISSUE TITLE
Android examples crash (armeabi-v7a c++17 issue)

### ISSUE THREAD

**Issue by vertify-mldev1** [google/mediapipe#1402]
Hello!
On my Honor 6A (Android 7.0) the android examples crash. Also tried using AAR which crashes with the same error.
Seems like aligned_alloc is not available, probably has something to do with the switch to c++17?

Here is the error log:
```
E/AndroidRuntime(32488): FATAL EXCEPTION: main
E/AndroidRuntime(32488): Process: com.google.mediapipe.apps.facedetectiongpu, PID: 32488
E/AndroidRuntime(32488): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.facedetectiongpu-1/lib/arm/libmediapipe_jni.so"...
E/AndroidRuntime(32488): 	at java.lang.Runtime.loadLibrary0(Runtime.java:994)
E/AndroidRuntime(32488): 	at java.lang.System.loadLibrary(System.java:1533)
E/AndroidRuntime(32488): 	at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
E/AndroidRuntime(32488): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(32488): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
E/AndroidRuntime(32488): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
E/AndroidRuntime(32488): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
E/AndroidRuntime(32488): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime(32488): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
E/AndroidRuntime(32488): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(32488): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(32488): 	at android.app.ActivityThread.main(ActivityThread.java:6577)
E/AndroidRuntime(32488): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32488): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/AndroidRuntime(32488): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

Also noteworthy: I built the apk using
`bazel build -c opt --config=android_arm`
instead of
`bazel build -c opt --config=android_arm64`

because the arm64 apk fails to install:
`Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]`

On another phone the arm64 apk/aar works fine.

**Comment by vertify-mldev1** [comment]
I just tried with mediapipe 0.8.0 (pre c++17) and everything works with that version.

**Comment by sbilsky** [comment]
This comment is solution:
https://github.com/google/mediapipe/issues/1224#issuecomment-745190852

**Comment by vertify-mldev1** [comment]
That was it, thanks!
