### ISSUE TITLE
bad_alloc exception when running the YouTube-8M feature extraction graph on Ubuntu 18.04

### ISSUE THREAD

**Issue by r2d3** [google/mediapipe#1420]
Hello,

I am having a `bad_alloc` exception when running `extract_yt8m_features` on an Ubuntu 18.04 box.
I recompiled in debug mode and I got an assertion with any video.

I suspect a version mismatch somewhere between python packages and bazel embedded frameworks.

I managed to make it work on an Ubuntu 20.04 with OpenCV4 but here, I do not get which difference making it "crash" ?!

```
extract_yt8m_features: external/com_google_absl/absl/container/inlined_vector.h:541: absl::lts_2020_09_23::InlinedVector<T, N, A>::resize(absl::lts_2020_09_23::InlinedVector<T, N, A>::size_type)::<lambda()> [with T = long long int; long unsigned int N = 4; A = std::allocator<long long int>]: Assertion `false && "n <= max_size()"' failed.
```

I populated the `/tmp/mediapipe` directory as instructed:
```
mkdir /tmp/mediapipe
cd /tmp/mediapipe
curl -O http://data.yt8m.org/pca_matrix_data/inception3_mean_matrix_data.pb
curl -O http://data.yt8m.org/pca_matrix_data/inception3_projection_matrix_data.pb
curl -O http://data.yt8m.org/pca_matrix_data/vggish_mean_matrix_data.pb
curl -O http://data.yt8m.org/pca_matrix_data/vggish_projection_matrix_data.pb
curl -O http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
tar -xvf /tmp/mediapipe/inception-2015-12-05.tgz
```

I generated the VGG frozen graph:
```
python -m mediapipe.examples.desktop.youtube8m.generate_vggish_frozen_graph
```

I extracted `metadata.pb` for my video 360p:
```
python -m mediapipe.examples.desktop.youtube8m.generate_input_sequence_example \
    --path_to_input_video=/tmp/video.mp4 --clip_end_time_sec=10
```

I compiled `extract_yt8m_features` using:
```
bazel build -c dbg --define MEDIAPIPE_DISABLE_GPU=1 --define no_aws_support=true \
    mediapipe/examples/desktop/youtube8m:extract_yt8m_features
```

Ran with:
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features \
   --calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt \
   --input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.pb \
   --output_side_packets=output_sequence_example=/tmp/mediapipe/features.pb

I20201222 14:05:34.174351 22859 extract_yt8m_features.cc:46] Get calculator graph config contents: input_side_packet: "input_sequence_example"
...
I20201222 14:05:34.242198 22866 audio_decoder.cc:646] Created audio processor 0x7f39c00c0d20 for file "/tmp/video.mp4"
I20201222 14:05:34.242502 22866 audio_decoder.cc:374] Opened audio stream (id: 1, channels: 2, sample rate: 44100, time base: 1/44100).
I20201222 14:05:34.738694 22862 tensorflow_session_from_frozen_graph_calculator.cc:152] Loaded frozen model in: 513144 microseconds.
I20201222 14:05:35.453328 22863 tensorflow_session_from_frozen_graph_calculator.cc:152] Loaded frozen model in: 1227793 microseconds.
2020-12-22 14:05:35.840709: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2900005000 Hz
extract_yt8m_features: external/com_google_absl/absl/container/inlined_vector.h:541: absl::lts_2020_09_23::InlinedVector<T, N, A>::resize(absl::lts_2020_09_23::InlinedVector<T, N, A>::size_type)::<lambda()> [with T = long long int; long unsigned int N = 4; A = std::allocator<long long int>]: Assertion `false && "n <= max_size()"' failed.
```

`gdb` gives me the following backtrace:
```
#2  0x00007f3a063de48a in __assert_fail_base (fmt=0x7f3a06565750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5634a1ffad2a "false && \"n <= max_size()\"", file=file@entry=0x5634a1ffaa98 "external/com_google_absl/absl/container/inlined_vector.h", line=line@entry=541, function=function@entry=0x5634a1ffad60 <absl::lts_2020_09_23::InlinedVector<long long, 4ul, std::allocator<long long> >::resize(unsigned long)::{lambda()#1}::operator()() const::__PRETTY_FUNCTION__> "absl::lts_2020_09_23::InlinedVector<T, N, A>::resize(absl::lts_2020_09_23::InlinedVector<T, N, A>::size_type)::<lambda()> [with T = long long int; long unsigned int N = 4; A = std::allocator<long long"...) at assert.c:92
#3  0x00007f3a063de502 in __GI___assert_fail (assertion=0x5634a1ffad2a "false && \"n <= max_size()\"",     file=0x5634a1ffaa98 "external/com_google_absl/absl/container/inlined_vector.h", line=541,     function=0x5634a1ffad60 <absl::lts_2020_09_23::InlinedVector<long long, 4ul, std::allocator<long long> >::resize(unsigned long)::{lambda()#1}::operator()() const::__PRETTY_FUNCTION__> "absl::lts_2020_09_23::InlinedVector<T, N, A>::resize(absl::lts_2020_09_23::InlinedVector<T, N, A>::size_type)::<lambda()> [with T = long long int; long unsigned int N = 4; A = std::allocator<long long"...) at assert.c:101
#4  0x00005634982d29af in absl::lts_2020_09_23::InlinedVector<long long, 4ul, std::allocator<long long> >::resize(unsigned long)::{lambda()#1}::operator()() const (__closure=0x7f39d394c72f) at external/com_google_absl/absl/container/inlined_vector.h:541
#5  0x00005634982d29fa in absl::lts_2020_09_23::InlinedVector<long long, 4ul, std::allocator<long long> >::resize (this=0x7f39d394cd20, n=18446744073709551615)    at external/com_google_absl/absl/container/inlined_vector.h:541
#6  0x00005634a1470249 in tensorflow::BuildDenseSpec<int> (sparse=..., dense=0x7f39d394c980)    at external/org_tensorflow/tensorflow/core/util/strided_slice_op.cc:81
#7  0x00005634a146f502 in tensorflow::ValidateStridedSliceOp (begin_tensor=0x7f37a80f94c0, end_tensor=0x7f37a80f94e0, strides_tensor=..., input_shape=...,     begin_mask_spec=0, end_mask_spec=0, ellipsis_mask=0, new_axis_mask=0, shrink_axis_mask=1, processing_shape=0x7f39d394cce0, final_shape=0x7f39d394cd00,     is_identity=0x7f39d394cc39, is_simple_slice=0x7f39d394cc3a, slice_dim0=0x7f39d394cc3b, begin=0x7f39d394cd20, end=0x7f39d394cd50, strides=0x7f39d394cd80,     output_to_sparse_mapping=0x0, output_to_processing_mapping=0x0) at external/org_tensorflow/tensorflow/core/util/strided_slice_op.cc:256
#8  0x000056349f072d42 in tensorflow::<lambda(tensorflow::shape_inference::InferenceContext*)>::operator()(tensorflow::shape_inference::InferenceContext *) const    (__closure=0x7f3793de43b8, c=0x7f37a80e2790) at external/org_tensorflow/tensorflow/core/ops/array_ops.cc:1699
#9  0x000056349f081283 in std::_Function_handler<tensorflow::Status(tensorflow::shape_inference::InferenceContext*), tensorflow::<lambda(tensorflow::shape_inference::InferenceContext*)> >::_M_invoke(const std::_Any_data &, tensorflow::shape_inference::InferenceContext *&&) (__functor=...,     __args#0=@0x7f39d394ce18: 0x7f37a80e2790) at /usr/include/c++/7/bits/std_function.h:302
#10 0x00005634a14c043f in std::function<tensorflow::Status (tensorflow::shape_inference::InferenceContext*)>::operator()(tensorflow::shape_inference::InferenceContext*) const (this=0x7f3793de43b8, __args#0=0x7f37a80e2790) at /usr/include/c++/7/bits/std_function.h:706
#11 0x00005634a14b912d in tensorflow::shape_inference::InferenceContext::Run(std::function<tensorflow::Status (tensorflow::shape_inference::InferenceContext*)> const&) (this=0x7f37a80e2790, fn=...) at external/org_tensorflow/tensorflow/core/framework/shape_inference.cc:105
#12 0x00005634a0e15844 in tensorflow::grappler::SymbolicShapeRefiner::InferShapes (this=0x7f37a8083810, node=..., c=0x7f37a8074098)    at external/org_tensorflow/tensorflow/core/grappler/costs/graph_properties.cc:1880
#13 0x00005634a0e0fe72 in tensorflow::grappler::SymbolicShapeRefiner::UpdateNode (this=0x7f37a8083810, node=0x7f37a80d1fa0, refined=0x7f39d394d45f)    at external/org_tensorflow/tensorflow/core/grappler/costs/graph_properties.cc:1097
#14 0x00005634a0e01e64 in tensorflow::grappler::GraphProperties::UpdateShapes (this=0x7f39d394e1a0, shape_refiner=0x7f37a8083810, resource_handles=...,     n=0x7f37a80d1fa0, new_shapes=0x7f39d394d45f) at external/org_tensorflow/tensorflow/core/grappler/costs/graph_properties.cc:2194
#15 0x00005634a0e02233 in tensorflow::grappler::GraphProperties::PropagateShapes (this=0x7f39d394e1a0, shape_refiner=0x7f37a8083810, new_shapes=0x7f39d394da50,     resource_handles=..., num_loops=0) at external/org_tensorflow/tensorflow/core/grappler/costs/graph_properties.cc:2227
#16 0x00005634a0e0406e in tensorflow::grappler::GraphProperties::InferStatically (this=0x7f39d394e1a0, assume_valid_feeds=false,     aggressive_shape_inference=false, include_input_tensor_values=false, include_output_tensor_values=true)    at external/org_tensorflow/tensorflow/core/grappler/costs/graph_properties.cc:2450
#17 0x00005634a0d279fe in tensorflow::grappler::ConstantFolding::RunOptimizationPass (this=0x7f37a8082170, cluster=0x7f39d394fe20, item=0x7f39d394e530,     optimized_graph=0x7f39d394fa90) at external/org_tensorflow/tensorflow/core/grappler/optimizers/constant_folding.cc:3941
#18 0x00005634a0d28276 in tensorflow::grappler::ConstantFolding::Optimize (this=0x7f37a8082170, cluster=0x7f39d394fe20, item=..., optimized_graph=0x7f39d394fa90)    at external/org_tensorflow/tensorflow/core/grappler/optimizers/constant_folding.cc:3997
#19 0x00005634a0b4fa75 in tensorflow::grappler::MetaOptimizer::RunOptimizer (this=0x7f39d394f730, optimizer=0x7f37a8082170, cluster=0x7f39d394fe20,     optimized_item=0x7f39d394fb00, optimized_graph=0x7f39d394fa90, optimization_result=0x7f39d394ed10)    at external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:576
#20 0x00005634a0b4e9b7 in tensorflow::grappler::MetaOptimizer::OptimizeGraph (this=0x7f39d394f730, cluster=0x7f39d394fe20, item=...,     optimized_graph=0x7f39d394fa90) at external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:492
#21 0x00005634a0b51abd in tensorflow::grappler::MetaOptimizer::OptimizeConsumeItem (this=0x7f39d394f730, cluster=0x7f39d394fe20, item=...,     optimized_graph=0x7f39d394fa90) at external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:711
#22 0x00005634a0b53650 in tensorflow::grappler::RunMetaOptimizer (item=..., cfg=..., cpu_device=0x7f39c8001080, cluster=0x7f39d394fe20,     optimized_graph=0x7f39d394fa90) at external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:968
#23 0x00005634a0b3eecd in tensorflow::GraphExecutionState::OptimizeGraph (this=0x7f39ca69cd40, options=..., optimized_graph=0x7f39d3950038,     optimized_flib=0x7f39d3950040) at external/org_tensorflow/tensorflow/core/common_runtime/graph_execution_state.cc:798
#24 0x00005634a0b3f784 in tensorflow::GraphExecutionState::BuildGraph (this=0x7f39ca69cd40, options=..., out=0x7f39d39503c8)    at external/org_tensorflow/tensorflow/core/common_runtime/graph_execution_state.cc:856
#25 0x00005634a0afa63e in tensorflow::DirectSession::CreateGraphs (this=0x7f39c80021a0, subgraph_options=..., outputs=0x7f39d3950990, flib_def=0x7f378c002d80,     run_state_args=0x7f39d3951210, input_types=0x7f37a8009820, output_types=0x7f37a8009838, collective_graph_key=0x7f37a8009990)    at external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:1608
#26 0x00005634a0af82bc in tensorflow::DirectSession::CreateExecutors (this=0x7f39c80021a0, callable_options=..., out_executors_and_keys=0x7f39d3950c98,     out_func_info=0x7f39d3950ca0, run_state_args=0x7f39d3951210) at external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:1314
#27 0x00005634a0af9fd5 in tensorflow::DirectSession::GetOrCreateExecutors (this=0x7f39c80021a0, inputs=..., outputs=..., target_nodes=...,     executors_and_keys=0x7f39d39510f8, run_state_args=0x7f39d3951210) at external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:1556
#28 0x00005634a0af4d7d in tensorflow::DirectSession::Run (this=0x7f39c80021a0, run_options=..., inputs=std::vector of length 1, capacity 1 = {...},     output_names=std::vector of length 1, capacity 1 = {...}, target_nodes=std::vector of length 0, capacity 0, outputs=0x7f39d3951710,     run_metadata=0x7f39d3951570, threadpool_options=...) at external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:856
#29 0x00005634a0af4a15 in tensorflow::DirectSession::Run (this=0x7f39c80021a0, run_options=..., inputs=std::vector of length 1, capacity 1 = {...},     output_names=std::vector of length 1, capacity 1 = {...}, target_nodes=std::vector of length 0, capacity 0, outputs=0x7f39d3951710,     run_metadata=0x7f39d3951570) at external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:826
#30 0x00005634a0af1bda in tensorflow::DirectSession::Run (this=0x7f39c80021a0, inputs=std::vector of length 1, capacity 1 = {...},     output_names=std::vector of length 1, capacity 1 = {...}, target_nodes=std::vector of length 0, capacity 0, outputs=0x7f39d3951710)    at external/org_tensorflow/tensorflow/core/common_runtime/direct_session.cc:462
#31 0x000056349809fa91 in mediapipe::TensorFlowInferenceCalculator::OutputBatch (this=0x5634b0fe28c0, cc=0x5634b0fe21a0,     inference_state=std::unique_ptr<mediapipe::(anonymous namespace)::InferenceState> = {...})    at mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc:539
#32 0x00005634980a4638 in mediapipe::TensorFlowInferenceCalculator::Close (this=0x5634b0fe28c0, cc=0x5634b0fe21a0)    at mediapipe/calculators/tensorflow/tensorflow_inference_calculator.cc:463
#33 0x00005634981912fc in mediapipe::CalculatorNode::CloseNode (this=0x5634b0fc1e10, graph_status=..., graph_run_ended=false)    at mediapipe/framework/calculator_node.cc:555
#34 0x00005634981932b1 in mediapipe::CalculatorNode::ProcessNode (this=0x5634b0fc1e10, calculator_context=0x5634b0fe21a0)    at mediapipe/framework/calculator_node.cc:854
#35 0x0000563498184d97 in mediapipe::internal::SchedulerQueue::RunCalculatorNode (this=0x7ffeaa643c68, node=0x5634b0fc1e10, cc=0x5634b0fe21a0)    at mediapipe/framework/scheduler_queue.cc:260
#36 0x000056349818473e in mediapipe::internal::SchedulerQueue::RunNextTask (this=0x7ffeaa643c68) at mediapipe/framework/scheduler_queue.cc:217
#37 0x000056349818334d in mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}::operator()() const (__closure=0x7f39d3951d20)    at ./mediapipe/framework/executor.h:61
#38 0x0000563498183541 in std::_Function_handler<void (), mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (    __functor=...) at /usr/include/c++/7/bits/std_function.h:316
#39 0x0000563497f759d2 in std::function<void ()>::operator()() const (this=0x7f39d3951d20) at /usr/include/c++/7/bits/std_function.h:706
#40 0x000056349818af05 in mediapipe::ThreadPool::RunWorker (this=0x5634aed38cd8) at mediapipe/framework/deps/threadpool_pthread_impl.cc:166
#41 0x000056349818a84f in mediapipe::ThreadPool::WorkerThread::ThreadBody (arg=0x5634b0fb72e0) at mediapipe/framework/deps/threadpool_pthread_impl.cc:111
#42 0x00007f3a06dca6db in start_thread (arg=0x7f39d3953700) at pthread_create.c:463
#43 0x00007f3a064cf71f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Versions infos:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

$ bazel --version
bazel 3.4.1

$ python --version
Python 3.6.9

$ python -c "import tensorflow; print(tensorflow.__version__);"
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
1.14.0

$ python -c "import cv2; print(cv2.__version__);"
3.2.0

$ python -c "import six; print(six.__version__);"
1.15.0
```

**Comment by r2d3** [comment]
After commenting part of the graph, the problem seems to come from the vggish frozen graph so perhaps a version issue between Python's tensorflow and the version used by bazel

**Comment by qllb** [comment]
Hello

I'm having the same issue 


```

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/youtube8m/extract_yt8m_features   \
 --calculator_graph_config_file=mediapipe/graphs/youtube8m/feature_extraction.pbtxt \
 --input_side_packets=input_sequence_example=/tmp/mediapipe/metadata.pb   \
 --output_side_packets=output_sequence_example=/tmp/mediapipe/features.pb

2021-02-09 19:53:32.286578: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I20210209 19:53:32.314554 17288 audio_decoder.cc:646] Created audio processor 0x7f8d28028780 for file "/tmp/mediapipe/video_480p.mp4"
I20210209 19:53:32.315168 17288 audio_decoder.cc:374] Opened audio stream (id: 1, channels: 2, sample rate: 44100, time base: 1/44100).
I20210209 19:53:33.594485 17284 tensorflow_session_from_frozen_graph_calculator.cc:152] Loaded frozen model in: 1308949 microseconds.
I20210209 19:53:33.753481 17283 tensorflow_session_from_frozen_graph_calculator.cc:152] Loaded frozen model in: 1468035 microseconds.
2021-02-09 19:53:33.980029: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2200000000 Hz
extract_yt8m_features: external/com_google_absl/absl/container/inlined_vector.h:541: absl::lts_2020_09_23::InlinedVector<T, N, A>::resize(absl::lts_2020_09_23::InlinedVector<T, N, A>::size_type)::<lambda()> [with T = long long int; long unsigned int N = 4; A = std::allocator<long long int>]: Assertion `false && "n <= max_size()"' failed
```

The versions are identical

**Comment by qllb** [comment]
@r2d3, can you describe any special steps for making it work on Ubuntu 20.04 with OpenCV4?

**Comment by sgowroji** [comment]
Hi @r2d3, Could you please test the above with the latest release and let us know if you still see the same error. Thanks!
