### ISSUE TITLE
Windows error when trying to run holistic python solution

### ISSUE THREAD

**Issue by AntonioDomenech** [google/mediapipe#1421]
I get the following error if I run the holistic solution in python (windows)

```
Traceback (most recent call last):
  File "Trial.py", line 36, in <module>
    holistic = mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5, upper_body_only=True)
  File "C:\Users\Antonio Domènech\Desktop\prototype_101\venv\lib\site-packages\mediapipe\python\solutions\holistic.py", line 84, in __init__
    super().__init__(
  File "C:\Users\Antonio Domènech\Desktop\prototype_101\venv\lib\site-packages\mediapipe\python\solution_base.py", line 216, in __init__
    validated_graph.initialize(
FileNotFoundError: The path does not exist.
```

I figured out that it says the path doesn't exist because half the path has \ and the other half /. After correcting this manually in the solution_base.py file, I get the following error:

```
Traceback (most recent call last):
  File "Trial.py", line 36, in <module>
    holistic = mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5, upper_body_only=True)
  File "C:\Users\Antonio Domènech\Desktop\prototype_101\venv\lib\site-packages\mediapipe\python\solutions\holistic.py", line 84, in __init__
    super().__init__(
  File "C:\Users\Antonio Domènech\Desktop\prototype_101\venv\lib\site-packages\mediapipe\python\solution_base.py", line 218, in __init__
    validated_graph.initialize(binary_graph_path)
TypeError: initialize(): incompatible function arguments. The following argument types are supported:
    1. (self: mediapipe.python._framework_bindings.validated_graph_config.ValidatedGraphConfig, **kwargs) -> None

Invoked with: <mediapipe.python._framework_bindings.validated_graph_config.ValidatedGraphConfig object at 0x000001E0A0E90FB0>, 'C:\\Users\\Antonio Domènech\\Desktop\\prototype_101\\venv\\lib\\site-packages\\mediapipe\\modules\\holistic_landmark\\holistic_landmark_cpu.binarypb'
```

How can I solve this?

**Comment by docentYT** [comment]
The same problem

**Comment by Everest-2002** [comment]
The same problem

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2050

**Comment by Danil-e** [comment]
I assumed it was saying that the path does not exist because half of the path has a \ and the other half has a /. After manually fixing this, nothing changes in the solution_base.py file. The error remains the same.

**Comment by sgowroji** [comment]
Hi @AntonioDomenech, Could you please provide your code changes to understand the issue much better.
