### ISSUE TITLE
How to leverage NPU on edge device?

### ISSUE THREAD

**Issue by yangcheng** [google/mediapipe#1425]
Hi, I am building some app on an edge device that could utilize mediapipe's model.  I am able to run the model on CPU/GPU successfully.  however, the chip has it's own NPU and a quantized model can run 2-10x faster than use CPU only.  The vendor has provided model conversion tools and SDK , after the conversion/quantization, the model loading and input/output need to go through their C APIs.

What do I need to do to enable the usage of NPU's API ?

Thanks

**Comment by mcclanahoochie** [comment]
Try editing the inference calculator options in the graph, and specify the delegate you want: `delegate { nnapi {} }`

```
 node {
   calculator: "TfLiteInferenceCalculator"
   input_stream: "TENSORS:image_tensors"
   output_stream: "TENSORS:result_tensors"
   options {
     [mediapipe.TfliteInferenceCalculatorOptions.ext] {
       model_path: "model.tflite"
       delegate { nnapi {} }
     }
   }
 }
```

Note: The input/output tensors should be on the CPU when using nnapi delegate

**Comment by mcclanahoochie** [comment]
closing due to lack of activity

**Comment by yangcheng** [comment]
thanks! how do I make sure input/output tensor to be on CPU? 
I am getting the following error which seems to be related

```
03-17 17:13:08.315  4899  4926 E native  : E20210317 17:13:08.315152  4926 graph.cc:407] Input stream "output_video" of calculator "egl_surface_sink_output_video" expects packets of type "mediapipe::GpuBuffer" but the connected output stream will contain packets of type "mediapipe::ImageFrame"
03-17 17:13:08.317  4899  4926 D GlThread: Stopping GL thread ExternalTextureConverter
--------- beginning of crash
03-17 17:13:08.317  4899  4926 E AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
03-17 17:13:08.317  4899  4926 E AndroidRuntime: Process: com.google.mediapipe.apps.posetrackingcpu, PID: 4899
03-17 17:13:08.317  4899  4926 E AndroidRuntime: com.google.mediapipe.framework.MediaPipeException: unknown: Input stream "output_video" of calculator "egl_surface_sink_output_video" expects packets of type "mediapipe::GpuBuffer" but the connected output stream will contain packets of type "mediapipe::ImageFrame"
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:537)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:409)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:427)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:364)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
03-17 17:13:08.320  3709  4078 W ActivityManager:   Force finishing activity com.google.mediapipe.apps.posetrackingcpu/.MainActivity
```

**Comment by mcclanahoochie** [comment]
Try using a calculator to convert to gpu, such as [ImageFrameToGpuBuffer](https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_detection/face_detection_mobile_cpu.pbtxt#L72)

**Comment by yangcheng** [comment]
thanks, is there a way to get result pose directly without rendering ?

**Comment by mcclanahoochie** [comment]
You can comment out the rendering node (PoseRendererGpu) in the graph
https://github.com/google/mediapipe/blob/master/mediapipe/graphs/pose_tracking/pose_tracking_gpu.pbtxt#L65

and replace with 
```
node {
 calculator: "PassThroughCalculator"
 input_stream: "input_video"
 output_stream: "output_video"
}
```
this will skip the rendering and output the original image instead

the pose landmarks will still be output [here](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/MainActivity.java#L42)

**Comment by yangcheng** [comment]
great to know. thanks! if I don't need the output video at all, can I just comment out output_stream: "output_video" at https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/graphs/pose_tracking/pose_tracking_gpu.pbtxt#L7 ?

**Comment by mcclanahoochie** [comment]
yes you can, but i don't remember if the runner app expects output frames or not, so you would have to take care of that too. 

either way, it would be better to skip the rendering as well, rather than just ignore the rendered stream (otherwise you spend cycles on throw away images)

**Comment by yangcheng** [comment]
cool, suppose I drop the rendering, do I need a surfaceview for handle input video? sound's like I don't, but I am not sure why onPreviewDisplaySurfaceChanged() is called in previewDisplayView's call back. the holder object itself is not used in onPreviewDisplaySurfaceChanged 

https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L222

**Comment by yangcheng** [comment]
@mcclanahoochie I was able to remove the output video and get result in the place as you suggested. Thanks!
however, if there is no landmarks detected, then the callback is not invoked.  is there a way to let the callback called with an empty result?

**Comment by mcclanahoochie** [comment]
i see, there are a couple of options:
1. https://github.com/google/mediapipe/issues/1747#issuecomment-810976877
2. you can register a callback with the graph via [ObserveOutputStream](https://github.com/google/mediapipe/search?q=ObserveOutputStream) . instead of polling, this would call the provided callback function on each output . i don't think it would block, it just shouldn't get called if no output (...i haven't verified this but it may be worth a try)

**Comment by mcclanahoochie** [comment]
this seems related  https://github.com/google/mediapipe/issues/1747#issuecomment-810976877

i don't think there is an easy way for that, the callback was designed to only be called when there are landmarks to process

you can try editing the graphs (and/or calculators, in)
mediapipe/modules/pose_landmark/pose_landmark_by_roi_gpu.pbtxt
mediapipe/modules/pose_landmark/pose_landmark_gpu.pbtxt

in particular look at how the GateCalculator(s) are used. 
unfortunately i don't have a quick solution for you

**Comment by yangcheng** [comment]
thanks, that's very helpful. I'll give a try

**Comment by yangcheng** [comment]
is there a way to add another dummy output that will always be called when the process finish? so I can know the frame process is finished?

**Comment by mcclanahoochie** [comment]
Please open another ticket specific to further questions. These have been unrelated to the original question about NPU. Thanks

**Comment by ralarcong** [comment]
Hello, 

What do I need to do to enable the use of NPU inference through the Python API?

Thank you in advance.
