### ISSUE TITLE
"Error: glTexStorage2D: dimensions out of range" on mobile Chrome 

### ISSUE THREAD

**Issue by syanenko** [google/mediapipe#1436]
Hi,
thank you for the great API you share with us !

My first simple JS app with 'hands' interface works fine on Win7 desktop with Nvidia RTX 2070 under Chrome 87.0 , but I can not figure out why it fails on my mobile LG ThinQ G7.

Both supports WebGL 2.0 (OpenGL ES 3.0 Chromium), please find [logs and webglreports here](https://drive.google.com/file/d/1JZT_Vkswin9Zc9LQCbZA0_nOgu_KnDnw/view?usp=sharing)

Could you please suggest something to resolve this issue ?
Thanks in advance.

Stack trace is following:

```
hands:151 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://crbug.com/954323
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 I1225 17:43:38.933000       1 gl_context_webgl.cc:146] Successfully created a WebGL context with major version 3 and handle 3
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 I1225 17:43:38.958000       1 gl_context.cc:340] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)))
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 W1225 17:43:38.960000       1 gl_context.cc:794] Drishti OpenGL error checking is disabled
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 E1225 17:43:39.959000       1 calculator_graph.cc:775] INTERNAL: CalculatorGraph::Run() failed in Run: 
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 Calculator::Open() for node "handlandmarktrackinggpu__handlandmarkgpu__InferenceCalculator" failed: [GL_INVALID_VALUE]: A numeric argument is out of range.,[GL_INVALID_FRAMEBUFFER_OPERATION]: The framebuffer object is not complete.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:50 [type.googleapis.com/mediapipe.StatusList='\n\xbc\x02\x08\r\x12\xb7\x02\x43\x61lculator::Open() for node \"handlandmarktrackinggpu__handlandmarkgpu__InferenceCalculator\" failed: [GL_INVALID_VALUE]: A numeric argument is out of range.,[GL_INVALID_FRAMEBUFFER_OPERATION]: The framebuffer object is not complete.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:50']
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 F1225 17:43:39.960000       1 solutions_wasm.embind.cc:585] Check failed: ::util::OkStatus() == (graph_->WaitUntilIdle()) (OK vs. INTERNAL: CalculatorGraph::Run() failed in Run: 
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 Calculator::Open() for node "handlandmarktrackinggpu__handlandmarkgpu__InferenceCalculator" failed: [GL_INVALID_VALUE]: A numeric argument is out of range.,[GL_INVALID_FRAMEBUFFER_OPERATION]: The framebuffer object is not complete.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:50 [type.googleapis.com/mediapipe.StatusList='\n\xbc\x02\x08\r\x12\xb7\x02\x43\x61lculator::Open() for node \"handlandmarktrackinggpu__handlandmarkgpu__InferenceCalculator\" failed: [GL_INVALID_VALUE]: A numeric argument is out of range.,[GL_INVALID_FRAMEBUFFER_OPERATION]: The framebuffer object is not complete.: glCreateShader in third_party/tensorflow/lite/delegates/gpu/gl/gl_shader.cc:50']) 
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 *** Check failure stack trace: ***
put_char @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 undefined
abort @ cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9
hands:1 [.WebGL-0xc9b16a00]GL ERROR :GL_INVALID_VALUE : glTexStorage2D: dimensions out of range
hands:1 [.WebGL-0xc9b16a00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:67549)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:67725)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:41039)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:179943)
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10471]:0x49a300
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10466]:0x49a278
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10461]:0x499da0
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10458]:0x499a2a
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10474]:0x49a359
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[515]:0xebe1
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:41070)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:179943)
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10471]:0x49a300
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10466]:0x49a278
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10461]:0x499da0
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10458]:0x499a2a
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[10474]:0x49a359
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[515]:0xebe1
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.wasm:wasm-function[502]:0xd956
    at SolutionWasm$send [as send] (eval at new_ (https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.1/hands_solution_wasm_bin.js:9:160446), <anonymous>:9:1)

```

**Comment by Adolar13** [comment]
I have the same issue on chrome mobile on a samsung galaxy s7.

**Comment by simon-lanf** [comment]
I have this issue too with Chrome Mobile, with FaceMesh.

**Comment by syanenko** [comment]
Hi,
You can try this issue with my app:  [Shaderplay](https://virtualkiln.ru) by selecting "Fireball" from menu.
Hope it will be helpful.

**Comment by mcclanahoochie** [comment]
Unfortunately there is a known issue with mobile browsers at the moment :(

There also seems to be an unrelated issue with your graph when testing on a known working laptop
<img width="922" alt="Screen Shot 2021-02-19 at 1 16 41 PM" src="https://user-images.githubusercontent.com/1004136/108562573-f0872300-72b4-11eb-9fc0-6040cbd85d74.png">

**Comment by simon-lanf** [comment]
I have the same issue, it crashes hard when run on Capacitor, Ionic or Cordova.

**Comment by syanenko** [comment]
At the same time it works fine under WIn7 / Chrome 88.0.4324.182 / NVIDIA GeForce RTX2070 Super /  Driver version 446.14
![image](https://user-images.githubusercontent.com/6688301/108566195-0e856f80-7317-11eb-9527-3184a0211561.png)

**Comment by mcclanahoochie** [comment]
i see, the effects all work for me on chrome desktop. 
i didn't realize that fireball was for your hand and the empty packet was no hand in frame (so i just saw black screen at first).

**Comment by syanenko** [comment]
You are right - everything fine on desktop, but on fails on mobile (I have hands 0.1.1612238212).

At the same time I see new issue with current hands version on desktop: https://mediapipe.dev/demo/hands
hands:96 Uncaught SyntaxError: Unexpected identifier
Chrome: 88.0.4324.182

**Comment by syanenko** [comment]
Previouse issue with hands I reported here: https://github.com/google/mediapipe/issues/1627

**Comment by syanenko** [comment]
Now with Chrome 88.04324 works fine !

**Comment by sgowroji** [comment]
Thanks for sharing the update. We are closing this issue .
