### ISSUE TITLE
HandTrackerGpu failed build 

### ISSUE THREAD

**Issue by manosh7n** [google/mediapipe#1440]
I'm trying to build an .xcodeproject file using tulsi. When I click on GENERATE, I get the following error.

```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//mediapipe/objc:mediapipe_framework_ios' failed; build aborted: Problem getting numpy include path.Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary' failed; build aborted: Problem getting numpy include path.Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fc58ff069f150c81abd10231bb1d9fbff0ba9322e03c9396518db4d054d5f2e6"
DEBUG: Repository rules_cc instantiated at:
  /Users/air/Documents/gesture_recognition/mediapipe/WORKSPACE:33:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_air/035001996e16ac5d58444feb18e29e73/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary' failed; build aborted: Problem getting numpy include path.Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
General failure: Bazel aspects could not be built.
```

It says that I don't have numpy, but I have it installed using `pip install numpy`. There are any solutions to this problem, and then I do not understand why he does not see numpy. macOS 11.1, python 3.9.5, bazel 3.7.2-homebrew

**Comment by pzoltowski** [comment]
I guess you might have another python installed by default on mac that is linked. I have python 3.9.1. installed via homebrew and added the following to my _~/.zshenv_
`export PATH="/usr/local/opt/python@3.9/libexec/bin:$PATH"`

add similar line to your _~/.zshenv or ~/.zshrc_ and reboot. Double check correct python is linked in your terminal with the following commands:

```
patryk@local ~ % python --version
Python 3.9.1
patryk@local ~ % which pip
/usr/local/opt/python@3.9/libexec/bin/pip
patryk@local ~ % python --version
Python 3.9.1
patryk@local ~ % which python
/usr/local/opt/python@3.9/libexec/bin/python
patryk@local ~ % which pip
/usr/local/opt/python@3.9/libexec/bin/pip
patryk@local ~ % pip --version
pip 20.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
patryk@local ~ % python
Python 3.9.1 (default, Dec 17 2020, 03:41:37)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.19.4'
```

**Comment by manosh7n** [comment]
I did everything as you wrote, got the same output when checking the python version and paths. But I still get the same error, I don't understand what the problem might be.

**Comment by manosh7n** [comment]
This helped solve the problem
`/usr/bin/python3 -m pip install numpy`

**Comment by yshuolu** [comment]
`/usr/bin/python3 -m pip install numpy` did not work for me

**Comment by manhnnsolar** [comment]
> /usr/bin/python3 -m pip install numpy

Thank you very much with your resolved

**Comment by manhnnsolar** [comment]
> This helped solve the problem
> `/usr/bin/python3 -m pip install numpy`

Thank you very much with your resolved
