### ISSUE TITLE
problem when using mediapipe into touchdesigner

### ISSUE THREAD

**Issue by orkebel** [google/mediapipe#1515]
HI !
i try to link mediapipe with touchdesigner.
When i try to run this simple code in touchdesigner :
"import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils"

i got this message :

"Traceback (most recent call last):
File "</base_mediapipe/text_template:op('/base_mediapipe/text_template').run()>", line 1
td.Error: File "/base_mediapipe/text_template", line 7
AttributeError: module 'mediapipe' has no attribute 'solutions'
Results of run operation resulted in exception."

i copy paste mediapipe into the directory where i got my .toe
i let mediapipe into the depo where i first install it --> /usr/"myname"/mediapipe
i copy paste mediapipe into the site-packages --> /usr/local/bin/pythonUsers/hugo/Library/Python/3.7/lib/python/site-packages
In Touchdesigner, the section "python 64 bit module path" is complete with this path --> Users/hugo/Library/Python/3.7/lib/python/site-packages

i'm on mac version 11.1 and i'm also a newbie :)
can you light my path ?
Thank you very much !

**Comment by Beep-Boop-Bopa** [comment]
Maybe this one might help: https://github.com/google/mediapipe/issues/1349

**Comment by orkebel** [comment]
Thank you beep-boop-bopa but i try all the solution given on the issue #1349 and that didn't solve my issue. I try to install the library into touchdesigner so i believe this is a new way of creating the same problem :) 
thank you anyway !

**Comment by jiuqiant** [comment]
You don't need to have the mediapipe source code to run it. In fact, it sometimes causes problem when you launch the python interpreter in the mediapipe dir. If you only need to run mediapipe python, my suggestion is deleting the source code dire and just do `pip install mediapipe`.

**Comment by jiuqiant** [comment]
We are closing this issue due to lack of activity.
