### ISSUE TITLE
at com.google.mediapipe.apps.objectdetectioncpu.MainActivity.<clinit>(MainActivity.java:50)

### ISSUE THREAD

**Issue by wxs19920926** [google/mediapipe#162]
10-10 10:55:42.910 5618-5618/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.objectdetectioncpu, PID: 5618
    java.lang.UnsatisfiedLinkError: com.google.devtools.build.android.incrementaldeployment.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.objectdetectioncpu/dex/incremental_classes1.dex"],nativeLibraryDirectories=[/data/user/0/com.google.mediapipe.apps.objectdetectioncpu/lib, /vendor/lib, /system/lib]]] couldn't find "libmediapipe_jni.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.google.mediapipe.apps.objectdetectioncpu.MainActivity.<clinit>(MainActivity.java:50)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1074)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2410)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:166)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5619)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by jiuqiant** [comment]
Please provide your host platform info, device info, Bazel version, Android sdk and ndk version, and Bazel build command to help us understnd your problem. Moreover, please don't file the same issue multiple times without providing more information. Thanks.

**Comment by wxs19920926** [comment]
thanks for your help, Ubuntu version is 16.04.6 LTS, android version is 6.0.1, Build label is 0.29.1,  sdk  version is 29, ndk version is 20.0.5594570,  Bazel build : bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu

**Comment by jiuqiant** [comment]
I am not sure if our demo apps still work with Android 6, which was released in 2015. Have you tested the demo apps on some other devices? Moreover, we also provide some [prebuilt arm64 apk](https://drive.google.com/file/d/1uCjS0y0O0dTDItsMh8x2cf4-l3uHW1vE/view), can you try the apk?

Another possibility is that your device has armeabi-v7a CPUs and android_arm64 setting is not working on your device.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
