### ISSUE TITLE
Adding a proto from mediapipe/util to aar library

### ISSUE THREAD

**Issue by atul109** [google/mediapipe#1624]
On adding box_tracker.proto to mediapipe_aar.bzl the aar is failing to build. Where as there are no issues adding a .proto file from framework/formats.

BUILD file of framework/formats has this format
`mediapipe_proto_library( ..... )`
where as util/tracking like this
`proto_library( ..... )`
Where can I find docs related to this BUILD setup?

`Executing genrule //mediapipe/examples/android/src/java/com/google/mediapipe/apps/mytracking_aar:box_tracker_proto_proto_java_src_generator failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)`

Changes in mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
```    _
     proto_java_src_generator(
        name = "box_tracker_proto",
        proto_src = "mediapipe/util/tracking/box_tracker.proto",
        java_lite_out = "com/google/mediapipe/formats/proto/BoxTrackerProto.java",
        srcs = [
            "//mediapipe/framework/formats:protos_src",
            "//mediapipe/framework/formats/annotation:protos_src",
        ],
    )

      android_library(
         name = name + "_android_lib",
         srcs = [
            ..........
            "com/google/mediapipe/formats/proto/BoxTrackerProto.java",
        ],
```

**Comment by jiuqiant** [comment]
You need to add a filegroup rule into https://github.com/google/mediapipe/blob/master/mediapipe/util/tracking/BUILD to expose the proto src. Here is the filegroup rule for framework/formats: https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/BUILD#L273

**Comment by atul109** [comment]
Added filegroup to util/tracking/BUILD file and modified mediapipe_aar.bzl
```    _proto_java_src_generator(
        name = "box_tracker_proto",
        proto_src = "mediapipe/util/tracking/box_tracker.proto",
        java_lite_out = "com/google/mediapipe/tracking/BoxTrackerProto.java",
        srcs = [
            "//mediapipe/util/tracking:protos_src",
        ],
    )
```
Build is now failing with a different error

`java failed: error executing command external/remotejdk11_macos/bin/java -Xverify:none -XX:+UseParallelOldGC -XX:-CompactStrings '--patch-module=java.compiler=external/remote_java_tools_darwin/java_tools/java_compiler.jar' ... (remaining 118 argument(s) skipped)
`

**Comment by jiuqiant** [comment]
Since box tracker proto depends a chain of other proto files, it's required to compile every proto to make the box tracker proto work. The following is the required code change to have box tracker proto into the AAR package. The AAR package can be successfully built on my end. 

```
diff --git a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
index 5aa4fa2..a9bac94 100644
--- a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
+++ b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
@@ -121,6 +121,27 @@ cat > $(OUTS) <<EOF
         ],
     )
 
+    _proto_java_src_generator(
+        name = "motion_models_proto",
+        proto_src = "mediapipe/util/tracking/motion_models.proto",
+        java_lite_out = "com/google/mediapipe/tracking/MotionModelsProto.java",
+        srcs = ["//mediapipe/util/tracking:protos_src"],
+    )
+
+    _proto_java_src_generator(
+        name = "tracking_proto",
+        proto_src = "mediapipe/util/tracking/tracking.proto",
+        java_lite_out = "com/google/mediapipe/tracking/TrackingProto.java",
+        srcs = ["//mediapipe/util/tracking:protos_src"],
+    )
+
+    _proto_java_src_generator(
+        name = "box_tracker_proto",
+        proto_src = "mediapipe/util/tracking/box_tracker.proto",
+        java_lite_out = "com/google/mediapipe/tracking/BoxTrackerProto.java",
+        srcs = ["//mediapipe/util/tracking:protos_src"],
+    )
+
     android_library(
         name = name + "_android_lib",
         srcs = [
@@ -132,6 +153,9 @@ cat > $(OUTS) <<EOF
             "com/google/mediapipe/formats/proto/DetectionProto.java",
             "com/google/mediapipe/formats/proto/LocationDataProto.java",
             "com/google/mediapipe/formats/annotation/proto/RasterizationProto.java",
+            "com/google/mediapipe/tracking/BoxTrackerProto.java",
+            "com/google/mediapipe/tracking/TrackingProto.java",
+            "com/google/mediapipe/tracking/MotionModelsProto.java",
         ],
         manifest = "AndroidManifest.xml",
         proguard_specs = ["//mediapipe/java/com/google/mediapipe/framework:proguard.pgcfg"],
diff --git a/mediapipe/util/tracking/BUILD b/mediapipe/util/tracking/BUILD
index f1114e8..577538a 100644
--- a/mediapipe/util/tracking/BUILD
+++ b/mediapipe/util/tracking/BUILD
@@ -800,3 +800,9 @@ cc_library(
         "@com_google_absl//absl/container:node_hash_map",
     ],
 )
+
+filegroup(
+    name = "protos_src",
+    srcs = glob(["*.proto"]),
+    visibility = ["//mediapipe:__subpackages__"],
+)
diff --git a/mediapipe/util/tracking/motion_models.proto b/mediapipe/util/tracking/motion_models.proto
index 889cc42..73e9d8f 100644
--- a/mediapipe/util/tracking/motion_models.proto
+++ b/mediapipe/util/tracking/motion_models.proto
@@ -24,6 +24,8 @@
 syntax = "proto2";
 
 package mediapipe;
+option java_package = "com.google.mediapipe.tracking";
+option java_outer_classname = "MotionModelsProto";
 
 // Here x represents a 2D point in the image plane, in the following
 // coordinate system:
diff --git a/mediapipe/util/tracking/tracking.proto b/mediapipe/util/tracking/tracking.proto
index ff00380..a80619f 100644
--- a/mediapipe/util/tracking/tracking.proto
+++ b/mediapipe/util/tracking/tracking.proto
@@ -15,6 +15,8 @@
 syntax = "proto2";
 
 package mediapipe;
+option java_package = "com.google.mediapipe.tracking";
+option java_outer_classname = "TrackingProto";
 
 import "mediapipe/util/tracking/motion_models.proto";
 
```

**Comment by atul109** [comment]
Thank you, I was missing `option java_package` and `option java_outer_classname` within TrackingProto and MotionModelsProto when trying to build with required dependency protos which caused errors. Now with that change its successfully building aar with TimedBoxProtoList available in java.

Also figured out an alternate way to build proto files using this command by refering [this article](https://www.baeldung.com/google-protocol-buffer)
`protoc -I=. --java_out=. motion_models.proto`

**Comment by arijith96** [comment]
Hi @jiuqiant 

thanks for the guidance! I made your changes and tried to build the aar again (a knift aar including TimedBoxProtoList) but it fails with this error 

`/home/ari/testMediapipe/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/BUILD:3:14: Assembling dex files into mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example/_dx/mediapipe_template_matching_dummy_app/classes.dex.zip failed (Exit 1): DexFileMerger failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger --input ... (remaining 4 argument(s) skipped)
`
```

Use --sandbox_debug to see verbose messages from the sandbox
com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$8.updateIndex(DexMerger.java:564)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:275)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:573)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:165)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:197)
	at com.google.devtools.build.android.dexer.DexFileAggregator.merge(DexFileAggregator.java:164)
	at com.google.devtools.build.android.dexer.DexFileAggregator.access$000(DexFileAggregator.java:40)
	at com.google.devtools.build.android.dexer.DexFileAggregator$RunDexMerger.call(DexFileAggregator.java:199)
	at com.google.devtools.build.android.dexer.DexFileAggregator$RunDexMerger.call(DexFileAggregator.java:188)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:258)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at com.google.devtools.build.android.dexer.DexFileAggregator.writeMergedFile(DexFileAggregator.java:138)
	at com.google.devtools.build.android.dexer.DexFileAggregator.rotateDexFile(DexFileAggregator.java:126)
	at com.google.devtools.build.android.dexer.DexFileAggregator.close(DexFileAggregator.java:99)
	at com.google.devtools.build.android.dexer.DexFileMerger.buildMergedDexFiles(DexFileMerger.java:268)
	at com.google.devtools.build.android.dexer.DexFileMerger.main(DexFileMerger.java:205)

Exception in thread "main" com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger$8.updateIndex(DexMerger.java:564)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:275)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:573)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:165)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:197)
	at com.google.devtools.build.android.dexer.DexFileAggregator.merge(DexFileAggregator.java:164)
	at com.google.devtools.build.android.dexer.DexFileAggregator.access$000(DexFileAggregator.java:40)
	at com.google.devtools.build.android.dexer.DexFileAggregator$RunDexMerger.call(DexFileAggregator.java:199)
	at com.google.devtools.build.android.dexer.DexFileAggregator$RunDexMerger.call(DexFileAggregator.java:188)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:258)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at com.google.devtools.build.android.dexer.DexFileAggregator.writeMergedFile(DexFileAggregator.java:138)
	at com.google.devtools.build.android.dexer.DexFileAggregator.rotateDexFile(DexFileAggregator.java:126)
	at com.google.devtools.build.android.dexer.DexFileAggregator.close(DexFileAggregator.java:99)
	at com.google.devtools.build.android.dexer.DexFileMerger.buildMergedDexFiles(DexFileMerger.java:268)
	at com.google.devtools.build.android.dexer.DexFileMerger.main(DexFileMerger.java:205)

Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mediapipe_template_matching.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 14.443s, Critical Path: 10.51s
INFO: 78 processes: 2 internal, 1 linux-sandbox, 75 worker.
FAILED: Build did NOT complete successfully
```

Any suggestion on how to tackle this?

**Comment by jiuqiant** [comment]
Try the following:

diff --git a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
index 0b75ba7..72a788d 100644
--- a/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
+++ b/mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl
@@ -286,6 +286,7 @@
         name = name + "_dummy_app",
         manifest = name + "_generated_AndroidManifest.xml",
         custom_package = "dummy.package.for.so",
+        multidex = "native",
         deps = [android_library],
     )

**Comment by arijith96** [comment]
@jiuqiant 
Yes! The `multidex` argument was missing.

Thanks!

**Comment by ya332** [comment]
I did all of this but for hair_segmentation aar and I am getting the following error:

```
ERROR: /C/Documents/Misc/Dev/custom-mediapipe-fork/mediapipe/examples/android/src/java/com/hairlight/hairsegmentation/apps/aar_example/BUILD:5:14: Executing genrule //mediapipe/examples/android/src/java/com/hairlight/hairsegmentation/apps/aar_example:landmark_proto_proto_java_src_generator failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mv: cannot stat 'bazel-out/k8-opt/bin/com/google/mediapipe/formats/proto/LandmarkProto.java': No such file or directory
```

@jiuqiant Do you know how I can fix this?
