### ISSUE TITLE
build iOS handtracking error on platform Mac

### ISSUE THREAD

**Issue by bugmany** [google/mediapipe#1643]
when I build handtrackinggpu with iOS, always error and error info as below:
build command:
bazel build -c opt --config=ios_arm64  mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
----error log-----
Repository rule http_archive defined at:
/private/var/tmp/_bazel_root/3abcfccc9c0c8021bcc290577585d06c/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /private/var/tmp/_bazel_root/3abcfccc9c0c8021bcc290577585d06c/external/build_bazel_rules_apple/tools/realpath/BUILD:9:14: in _apple_genrule_inner rule @build_bazel_rules_apple//tools/realpath:realpath_genrule: 
Traceback (most recent call last):File "/private/var/tmp/_bazel_root/3abcfccc9c0c8021bcc290577585d06c/external/build_bazel_apple_support/rules/apple_genrule.bzl", line 78, column 28, in _apple_genrule_impl
apple_support.run_shell(File "/private/var/tmp/_bazel_root/3abcfccc9c0c8021bcc290577585d06c/external/build_bazel_apple_support/lib/apple_support.bzl", line 326, column 26, in _run_shell
		ctx.actions.run_shell(**_kwargs_for_apple_platform(ctx, **kwargs))
Error in run_shell: 'command' must be of type string. passing a sequence of strings as 'command' is deprecated. To temporarily disable this check, set --incompatible_run_shell_command_string=false.
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed; build aborted: Analysis of target '@build_bazel_rules_apple//tools/realpath:realpath_genrule' failed

then build failed.

**Comment by bugmany** [comment]
after uninstall bazel 4.0.0, then re-install Bazel 3.7.2.
then re-build Mediapipe pass.
