### ISSUE TITLE
build MediaPipe Hands with C++ on Windows 10 error

### ISSUE THREAD

**Issue by Ruffletuft** [google/mediapipe#1658]
I followed the [install document](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) and the Hello World program works fine.
Here's build command and build result.I has googled but find nothing special.
```
E:\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
DEBUG: C:/users/a/_bazel_a/wsixtlup/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  E:/mediapipe/WORKSPACE:387:13: in <toplevel>
  C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/tensorflow/workspace.bzl:74:20: in tf_workspace
  C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/tensorflow/workspace.bzl:90:27: in tf_repositories
  C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: Error fetching repository: Traceback (most recent call last):
        File "C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/a/_bazel_a/wsixtlup/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Repository command failed

INFO: Elapsed time: 1.484s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 11 targets configured)
```

**Comment by jiuqiant** [comment]
In https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md#installing-on-windows step 9, we mentioned that you need to add `--action_env PYTHON_BIN_PATH="C://path//to//python.exe"`.

**Comment by jiuqiant** [comment]
In https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md#installing-on-windows step 9, we mention that you need to add `--action_env PYTHON_BIN_PATH="C://path//to//python.exe"`. In your bazel command, the python_bin_path part is missing.

**Comment by Ruffletuft** [comment]
> 
> 
> In https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md#installing-on-windows step 9, we mention that you need to add `--action_env PYTHON_BIN_PATH="C://path//to//python.exe"`. In your bazel command, the python_bin_path part is missing.

E:\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://Python//Python37//python.exe  mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
Starting local Bazel server and connecting to it...
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
DEBUG: C:/users/a/_bazel_a/wsixtlup/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 6.432s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action

Is it nothing built?

**Comment by Ruffletuft** [comment]
> 
> 
> In https://github.com/google/mediapipe/blob/master/docs/getting_started/install.md#installing-on-windows step 9, we mention that you need to add `--action_env PYTHON_BIN_PATH="C://path//to//python.exe"`. In your bazel command, the python_bin_path part is missing.

thank you,I followed the build steps but:
```
........
INFO: From ProtoCompile mediapipe/calculators/tensor/tensors_to_classification_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/core/gate_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/util/rect_to_render_data_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tensor/image_to_tensor_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tensor/inference_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tensor/tensors_to_landmarks_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/framework/calculator_profile.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/util/detections_to_rects_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tensor/tensors_to_landmarks_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/util/landmarks_to_render_data_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tflite/ssd_anchors_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tensor/tensors_to_detections_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/core/constant_side_packet_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/util/non_max_suppression_calculator.pb.h:
bazel-out/x64_windows-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/util/non_max_suppression_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
INFO: From ProtoCompile mediapipe/calculators/tensor/image_to_tensor_calculator.pb.h [for host]:
bazel-out/host/bin/external/com_google_protobuf/src: warning: directory does not exist.
ERROR: E:/mediapipe/mediapipe/calculators/tensor/BUILD:267:24: output 'mediapipe/calculators/tensor/tensors_to_landmarks_calculator.pb.h' was not created
ERROR: E:/mediapipe/mediapipe/calculators/tensor/BUILD:267:24: ProtoCompile mediapipe/calculators/tensor/tensors_to_landmarks_calculator.pb.h failed: not all outputs were created or valid
ERROR: E:/mediapipe/mediapipe/calculators/tensor/BUILD:267:24: output 'mediapipe/calculators/tensor/tensors_to_landmarks_calculator.pb.h' was not created
ERROR: E:/mediapipe/mediapipe/calculators/util/BUILD:75:24: output 'mediapipe/calculators/util/non_max_suppression_calculator.pb.h' was not created
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 176.258s, Critical Path: 139.89s
INFO: 1157 processes: 398 internal, 759 local.
FAILED: Build did NOT complete successfully
```
why did those files disappear ?

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
