### ISSUE TITLE
Error on following "Build with Bazel in Android Studio"

### ISSUE THREAD

**Issue by adarmawan117** [google/mediapipe#1710]
I have followed the tutorials of : https://google.github.io/mediapipe/getting_started/android.html
But i faced this error:
**This bazel problem**
.
![image](https://user-images.githubusercontent.com/46953807/110198279-03d4e980-7e84-11eb-8901-ed859ee87149.png)
.
.
.
**When i sync bazel, i faced error :**
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
		python_lib = _get_python_lib(repository_ctx, python_bin)
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
		result = execute(repository_ctx, [python_bin, "-c", cmd])
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Repository command failed
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
		python_lib = _get_python_lib(repository_ctx, python_bin)
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
		result = execute(repository_ctx, [python_bin, "-c", cmd])
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Repository command failed
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
.
.
.
**I tried to search, and found sollution. Sollution is to turn off "app execution aliases"**
![image](https://user-images.githubusercontent.com/46953807/110198435-07b53b80-7e85-11eb-9f99-b03d970846ce.png)
.
.
.
**But, i faced another error:**
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/py/python_configure.bzl", line 208, column 32, in _create_local_python_repository
		python_bin = get_python_bin(repository_ctx)
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 46, column 23, in get_python_bin
		python_bin = which(repository_ctx, "python3")
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 25, in which
		result = execute(repository_ctx, ["C:\\Windows\\System32\\where.exe", program_name])
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: Error fetching repository: Traceback (most recent call last):
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/py/python_configure.bzl", line 208, column 32, in _create_local_python_repository
		python_bin = get_python_bin(repository_ctx)
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 46, column 23, in get_python_bin
		python_bin = which(repository_ctx, "python3")
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 25, in which
		result = execute(repository_ctx, ["C:\\Windows\\System32\\where.exe", program_name])
	File "C:/users/adarm/_bazel_adarm/ghnafdkl/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
		fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
.
.
.
.
**What should i do.?
I tried a variety of ways, but it made more and more errors.**
.

**Comment by sgowroji** [comment]
Hi @adarmawan117 Which solution are you trying for ?

**Comment by adarmawan117** [comment]
https://stackoverflow.com/a/65342590

**Comment by adarmawan117** [comment]
By the way. I have succesfull running desktop hello world and hand tracking example.
But this android example (on android studio), i facef that error

**Comment by adarmawan117** [comment]
By the way, i use windows

**Comment by sgowroji** [comment]
Hi @adarmawan117 , As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.

**Comment by adarmawan117** [comment]
Oke. Because my OS.
I will trying to compile in my linux OS later.

**Comment by sgowroji** [comment]
From your above comment, closing this issue. Thanks !

**Comment by jiuqiant** [comment]
FYI, using MediaPipe in Android Studio with Bazel is deprecated. Please see the new gradle approach in https://github.com/google/mediapipe/blob/master/docs/getting_started/android_solutions.md.
