### ISSUE TITLE
 FaceMesh (js) does not work with non-camera video input?

### ISSUE THREAD

**Issue by mzwtjp** [google/mediapipe#1727]
I am getting these errors when trying to use js version of face_mesh demo.

The same demo works OK and detects and report face landmarks as expected (using PC built-in camera as input).
However, if I feed video data (webm/v9) to video tag's srcObject using MediaSource interface, these errors happen and mediapipe FaceMesh.send() does not seem to be working.

Firstly, I doubted if this is caused by lack of heap memory (I was trying it with 120M bytes video data), but I found this happens even with 25M bytes of video data.

Rather, this is caused by using feeding non-camera data to the video tag (which is the input to FaceMesh)?

Errors from  chrome console.
These errors are repeated a few times, then I see other kinds of errors later.

```
VM161 face_mesh_solution_packed_assets_loader.js:48 Uncaught TypeError: Cannot read property 'https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_packed_assets.data' of undefined
    at XMLHttpRequest.xhr.onprogress (VM155 face_mesh_solution_packed_assets_loader.js:48)
xhr.onprogress @ VM161 face_mesh_solution_packed_assets_loader.js:48
XMLHttpRequest.send (async)
fetchRemotePackage @ VM161 face_mesh_solution_packed_assets_loader.js:76
loadPackage @ VM161 face_mesh_solution_packed_assets_loader.js:86
(anonymous) @ VM161 face_mesh_solution_packed_assets_loader.js:184
(anonymous) @ VM161 face_mesh_solution_packed_assets_loader.js:186
```

then:

```
Uncaught (in promise) TypeError: Cannot read property 'buffer' of undefined
    at Object.write (VM156 face_mesh_solution_wasm_bin.js:9)
    at Object.write (VM156 face_mesh_solution_wasm_bin.js:9)
    at Object.createDataFile (VM156 face_mesh_solution_wasm_bin.js:9)
    at finish (VM156 face_mesh_solution_wasm_bin.js:9)
    at processData (VM156 face_mesh_solution_wasm_bin.js:9)
    at Object.createPreloadedFile [as FS_createPreloadedFile] (VM156 face_mesh_solution_wasm_bin.js:9)
    at DataRequest.finish (VM155 face_mesh_solution_packed_assets_loader.js:127)
    at DataRequest.onload (VM155 face_mesh_solution_packed_assets_loader.js:122)
    at processPackageData (VM155 face_mesh_solution_packed_assets_loader.js:158)
    at runWithFS (VM155 face_mesh_solution_packed_assets_loader.js:169)
write @ VM168 face_mesh_solution_wasm_bin.js:9
write @ VM168 face_mesh_solution_wasm_bin.js:9
createDataFile @ VM168 face_mesh_solution_wasm_bin.js:9
finish @ VM168 face_mesh_solution_wasm_bin.js:9
processData @ VM168 face_mesh_solution_wasm_bin.js:9
createPreloadedFile @ VM168 face_mesh_solution_wasm_bin.js:9
finish @ VM155 face_mesh_solution_packed_assets_loader.js:127
onload @ VM155 face_mesh_solution_packed_assets_loader.js:122
processPackageData @ VM155 face_mesh_solution_packed_assets_loader.js:158
runWithFS @ VM155 face_mesh_solution_packed_assets_loader.js:169
callRuntimeCallbacks @ VM156 face_mesh_solution_wasm_bin.js:9
preRun @ VM156 face_mesh_solution_wasm_bin.js:9
run @ VM156 face_mesh_solution_wasm_bin.js:9
runCaller @ VM156 face_mesh_solution_wasm_bin.js:9
removeRunDependency @ VM156 face_mesh_solution_wasm_bin.js:9
receiveInstance @ VM156 face_mesh_solution_wasm_bin.js:9
receiveInstantiatedSource @ VM156 face_mesh_solution_wasm_bin.js:9
Promise.then (async)
asyncGeneratorStep @ index.js:124
_next @ index.js:124
(anonymous) @ index.js:124
(anonymous) @ index.js:124
```

and:

```
VM176 face_mesh_solution_wasm_bin.js:9 Uncaught (in promise) RuntimeError: abort(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68379)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:68555)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42200)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:23247)
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:23071
    at ja.h (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:30:51)
    at Q (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:10:296)
    at ma.next (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:11:90)
    at k (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:22:318)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:42231)
    at Object.get (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:23247)
    at https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh_solution_wasm_bin.js:9:23071
    at ja.h (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:30:51)
    at Q (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:10:296)
    at ma.next (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:11:90)
    at k (https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js:22:318)
```

**Comment by mzwtjp** [comment]
I can see #1412 describing similar errors.

**Comment by mzwtjp** [comment]
I can see below in camera_utils.js, so it has something to do with mediastream's width / height?

```
function t(a, b)     
        a.video.srcObject = b;
        a.video.onloadedmetadata = function() {
            a.video.play();
            q(a)
        }
}
```

```
var n = {
    facingMode: "user",
    width: 640,
    height: 480
};
```

```
p.prototype.start = function() {
...
    return navigator.mediaDevices.getUserMedia({
        video: {
            facingMode: b.facingMode,
            width: b.width,
            height: b.height
        }
...
};
```

**Comment by mzwtjp** [comment]
though not sure if it is related, "Module.arguments has been replaced with plain arguments_ " error menthoned in below (emscripten issues).

https://github.com/emscripten-core/emscripten/issues/11239

**Comment by mzwtjp** [comment]
For easy repro, I just tried directly specify video file in video tag (previously, I was feeding video data by js code via MediaSource i/f).
Even with this, I am getting similar error.

```
<video class="input_video" width="640px" height="480px" type="video/webm" src="nBs3K0bsxyc.webm"></video>
```

**Comment by tyrmullen** [comment]
It's possible your initial errors might be unrelated-- they seem to be related to loading assets rather than initializing the video stream.  But I will address the non-camera video input here:

Currently camera_utils is set up to specifically use web-cam input, so it will fail if you try to feed it a video stream.  This is a feature which can definitely be added, but is not a high priority, as the camera_utils class itself is quite small and bare-bones.  It should be perfectly fine to feed other video data into MediaPipe, but for now you'll have to set that up without camera_utils as follows:

- Play your source video in an HTMLVideoElement object
- Use requestAnimationFrame() callbacks to poll for new frames
- Determine if a new frame has actually loaded, by caching video frame times (optional, but eliminates unnecessary processing).  For example, something like "if (!videoElement.paused && videoElement.currentTime !== lastVideoTime) {..."
- If a new frame has loaded, then send it into the FaceMesh solution: "faceMesh.send({image: videoElement});"

**Comment by mzwtjp** [comment]
Thank you for your hint.
Looks like I have to wait for the "loadeddata" event so that now it is assured there is a image.
No more crashes and the model is working.

Previously, I was hooking to "updatetime" event, so I was giving video element to faceMesh before was ready, so faceMesh library was crashing.
(In camera input case there is no such delay for image data loading?)

I think I can close this issue.

**Comment by veetechh** [comment]
I am facing same issue on web demo for hand. Can you please tell me how to use loadeddata function?

https://codepen.io/mediapipe/pen/RwGWYJw
