### ISSUE TITLE
FaceMesh Android - Can not generate face_mesh_mobile_gpu.binarypb

### ISSUE THREAD

**Issue by karen-1996** [google/mediapipe#1728]
Hi everyone. I try to build an android application and use Mediapipe to get face landmarks. I found that I must use FaceMesh, and to use it I must generate face_mesh_mobile_gpu.binarypb
I tried everything, but every time get different errors from Bazel...
Could you provide me generated face_mesh_mobile_gpu.binarypb or tell me the correct way to do it?

**Comment by sgowroji** [comment]
Hi @karen-1996 , Could you please elaborate your complete issue with clear steps. What errors are you facing and what did you tried. Thanks !!

**Comment by karen-1996** [comment]
I've cloned Mediapipe's whole repository and install Bazel on my MacBook. After that, I make this
bazel build -c opt mediapipe/graphs/face_detection:face_detection_mobile_gpu_binary_graph
and get error

Starting local Bazel server and connecting to it...
INFO: Repository com_google_absl instantiated at:
  /Users/karennamalyan/Downloads/mediapipe-master/WORKSPACE:17:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_karennamalyan/c82c5edd8ca438b7ff1fb62c2fcec092/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_google_absl':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_karennamalyan/c82c5edd8ca438b7ff1fb62c2fcec092/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_karennamalyan/c82c5edd8ca438b7ff1fb62c2fcec092/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
Analyzing: target //mediapipe/graphs/face_detection:face_detection_mobile_gpu_\
binary_graph (74 packages loaded, 864 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@google_toolbox_for_mac//:GTM_Defines, config=BuildConfigurationValue.Key[c805064e1ae26e9622e7abf6d7d2e3034d6c1e8f490563cc78f993ef6619baf0]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:MPPMetalHelper, config=BuildConfigurationValue.Key[c805064e1ae26e9622e7abf6d7d2e3034d6c1e8f490563cc78f993ef6619baf0]}', 'ConfiguredTargetKey{label=//mediapipe/gpu:MPPGraphGPUData, config=BuildConfigurationValue.Key[c805064e1ae26e9622e7abf6d7d2e3034d6c1e8f490563cc78f993ef6619baf0]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:569)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:263)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:367)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1019)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1063)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:949)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:381)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:194)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more

**Comment by sgowroji** [comment]
Hi @karen-1996 , Could you please recheck the repo downloaded and do a rebuild. I can see the IOException while fetching the repository.

`ERROR: An error occurred during the fetch of repository 'com_google_absl':
Traceback (most recent call last):
File "/private/var/tmp/_bazel_karennamalyan/c82c5edd8ca438b7ff1fb62c2fcec092/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
ERROR: Error fetching repository: Traceback (most recent call last):
File "/private/var/tmp/_bazel_karennamalyan/c82c5edd8ca438b7ff1fb62c2fcec092/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in http_archive_impl
download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
Analyzing: target //mediapipe/graphs/face_detection:face_detection_mobile_gpu
binary_graph (74 packages loaded, 864 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:`

**Comment by karen-1996** [comment]
Hi @sgowroji. What can I do if Bazel can not download and fetch one of the external repositories? Every time I get a similar but different error. Now I get something like this - ERROR: An error occurred during the fetch of repository 'XNNPACK'...
Also, I tried to sync all repos before the build, but when the build started I get RuntimeException )))
So could you please send me just a single generated face_mesh_mobile_gpu.binarypb file. It will be very kind of you ))

**Comment by jiuqiant** [comment]
The issue is that Xcode is not installed on macOS. As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-macos, please install Xcode and also make sure you run xcode-select --install. Then, please run bazel shutdown && bazel clean --expunge to get ride of the cache. Finally, you can retry the build command. Finally, you can retry the build command. Hope this helps.

**Comment by jiuqiant** [comment]
I can build the face detection binary graph and attach it here. But, it's not very useful if you still can't have the mediapipe framework and face detection calculators binaries.

[face_detection_mobile_gpu.binarypb.zip](https://github.com/google/mediapipe/files/6150793/face_detection_mobile_gpu.binarypb.zip)

**Comment by karen-1996** [comment]
Hi @jiuqiant, Thank you for your help. I'll try to install Xcode and try again.
I tried to use this face_detection_mobile_gpu.binarypb.zip, but I think you send me the wrong file because I need face_mesh_mobile_gpu.binarypb, here is the build repo which I need. https://github.com/google/mediapipe/blob/master/mediapipe/graphs/face_mesh/BUILD
Could you send me this one?

Using this face_detection_mobile_gpu.binarypb I get an error

> com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
> No registered object with name: FaceDetectionFrontGpu; Unable to find Calculator "FaceDetectionFrontGpu"
