### ISSUE TITLE
"Read buffer does not match write buffer size" when change object detection model

### ISSUE THREAD

**Issue by IvesHsu** [google/mediapipe#1731]
Hi all,

when I change the model in mediapipe object detection gpu
it shows an exception as below
may I ask how to fix it?
thanks a lot

1. model is downloaded from TensorFlow Hub
https://tfhub.dev/tensorflow/lite-model/efficientdet/lite0/detection/default/1
2. I only modify BUILD file and object_detection_mobile_gpu.pbtxt

2021-03-11 19:21:38.851 13221-13245/? E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 
    Calculator::Process() for node "TfLiteTensorsToDetectionsCalculator" failed: Read buffer does not match write buffer size.
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:360)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:442)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:364)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

**Comment by sgowroji** [comment]
@IvesHsu Please find the similar issue , this may resolve your [issue](https://github.com/google/mediapipe/issues/1235)

**Comment by IvesHsu** [comment]
@sgowroji 
thanks for reply
how to know if a model can use  GPU delegate or not?

**Comment by IvesHsu** [comment]
Hi @fanzhanggoogle ,
do you have any suggestion?
thanks a lot

**Comment by fanzhanggoogle** [comment]
Hi, you can try the [tflite benchmarking tool ](https://www.tensorflow.org/lite/performance/measurement) first to make sure the model can be supported. It'll be difficult to debug in MediaPipe graph by just switching model. There's could multiple reasons why the model isn't working, e.g. ops in the model are supported by the GPU, e.t.c.
