### ISSUE TITLE
Error building Mac desktop hello world, java.io.IOException: Cannot run program "git" in directory, error=2, No such file or directory

### ISSUE THREAD

**Issue by mapmp** [google/mediapipe#175]
I can't get hello world desktop to build on Mac.

Here's the error that pops up a few times:

"/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory

I checked that the first such errored directory exists and is empty.

Here's my full log:
username-macbookpro:mediapipe username$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
>     mediapipe/examples/desktop/hello_world:hello_world
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/command.profile.gz'
INFO: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /Users/username/mediapipe/WORKSPACE:259:1
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory
INFO: Elapsed time: 2.326s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
username-macbookpro:mediapipe username$ bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/command.profile.gz'
INFO: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /Users/username/mediapipe/WORKSPACE:259:1
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(("error running '%s' while worki...)))
error running 'git init /private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple' while working with @build_bazel_rules_apple:
java.io.IOException: Cannot run program "git" (in directory "/private/var/tmp/_bazel_username/69e93b0bda4766b48b4be1ad1574336d/external/build_bazel_rules_apple"): error=2, No such file or directory
INFO: Elapsed time: 3.418s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
username-macbookpro:mediapipe username$

**Comment by jiuqiant** [comment]
This is probably related to your xcode common tools setting. It can be solved by doing the following:
```
$ xcode-select install
$ bazel clean --expunge
$ bazel run --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hello_world:hello_world
```
