### ISSUE TITLE
posetrackingcpu crashed

### ISSUE THREAD

**Issue by yangcheng** [google/mediapipe#1761]
Hi, I am trying to run posetracking using cpu. 

Environment.
 
Android Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 26, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.16

In my BUILD I try to re-use the graph defined 

https://github.com/google/mediapipe/tree/master/mediapipe/graphs/pose_tracking 

```
licenses(["notice"])

package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "libmediapipe_jni.so",
    linkshared = 1,
    linkstatic = 1,
    deps = [
        "//mediapipe/graphs/pose_tracking:pose_tracking_cpu_deps",
        "//mediapipe/java/com/google/mediapipe/framework/jni:mediapipe_framework_jni",
    ],
)

cc_library(
    name = "mediapipe_jni_lib",
    srcs = [":libmediapipe_jni.so"],
    alwayslink = 1,
)

android_binary(
    name = "posetrackingcpu",
    srcs = glob(["*.java"]),
    assets = [
        "//mediapipe/graphs/pose_tracking:pose_tracking_cpu.binarypb",
        "//mediapipe/modules/pose_landmark:pose_landmark_full_body.tflite",
        "//mediapipe/modules/pose_detection:pose_detection.tflite",
    ],
    assets_dir = "",
    manifest = "//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:AndroidManifest.xml",
    manifest_values = {
        "applicationId": "com.google.mediapipe.apps.posetrackingcpu",
        "appName": "Pose Tracking CPU",
        "mainActivity": ".MainActivity",
        "cameraFacingFront": "False",
        "binaryGraphName": "pose_tracking_cpu.binarypb",
        "inputVideoStreamName": "input_video",
        "outputVideoStreamName": "output_video",
        "flipFramesVertically": "True",
        "converterNumBuffers": "2",
    },
    multidex = "native",
    deps = [
        ":mediapipe_jni_lib",
        "//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib",
        "//mediapipe/framework/formats:landmark_java_proto_lite",
        "//mediapipe/java/com/google/mediapipe/framework:android_framework",
        "@com_google_protobuf//:protobuf_javalite",
    ],
)
````
and MainActivity looks extactly the same as posetrackinggpu

```
package com.google.mediapipe.apps.posetrackingcpu;

import android.os.Bundle;
import android.util.Log;

import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmark;
import com.google.mediapipe.formats.proto.LandmarkProto.NormalizedLandmarkList;
import com.google.mediapipe.framework.PacketGetter;
import com.google.protobuf.InvalidProtocolBufferException;

/** Main activity of MediaPipe pose tracking app. */
public class MainActivity extends com.google.mediapipe.apps.basic.MainActivity {
  private static final String TAG = "MainActivity";

  private static final String OUTPUT_LANDMARKS_STREAM_NAME = "pose_landmarks";

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // To show verbose logging, run:
    // adb shell setprop log.tag.MainActivity VERBOSE
    if (Log.isLoggable(TAG, Log.VERBOSE)) {
      processor.addPacketCallback(
          OUTPUT_LANDMARKS_STREAM_NAME,
          (packet) -> {
            Log.v(TAG, "Received pose landmarks packet.");
            try {
              NormalizedLandmarkList poseLandmarks =
                  PacketGetter.getProto(packet, NormalizedLandmarkList.class);
              Log.v(
                  TAG,
                  "[TS:"
                      + packet.getTimestamp()
                      + "] "
                      + getPoseLandmarksDebugString(poseLandmarks));
            } catch (InvalidProtocolBufferException exception) {
              Log.e(TAG, "Failed to get proto.", exception);
            }
          });
    }
  }

  private static String getPoseLandmarksDebugString(NormalizedLandmarkList poseLandmarks) {
    String poseLandmarkStr = "Pose landmarks: " + poseLandmarks.getLandmarkCount() + "\n";
    int landmarkIndex = 0;
    for (NormalizedLandmark landmark : poseLandmarks.getLandmarkList()) {
      poseLandmarkStr +=
          "\tLandmark ["
              + landmarkIndex
              + "]: ("
              + landmark.getX()
              + ", "
              + landmark.getY()
              + ", "
              + landmark.getZ()
              + ")\n";
      ++landmarkIndex;
    }
    return poseLandmarkStr;
  }
}

```

The build was successful, however, I got an error when running the app

```
03-17 17:13:08.315  4899  4926 E native  : E20210317 17:13:08.315152  4926 graph.cc:407] Input stream "output_video" of calculator "egl_surface_sink_output_video" expects packets of type "mediapipe::GpuBuffer" but the connected output stream will contain packets of type "mediapipe::ImageFrame"
03-17 17:13:08.317  4899  4926 D GlThread: Stopping GL thread ExternalTextureConverter
--------- beginning of crash
03-17 17:13:08.317  4899  4926 E AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
03-17 17:13:08.317  4899  4926 E AndroidRuntime: Process: com.google.mediapipe.apps.posetrackingcpu, PID: 4899
03-17 17:13:08.317  4899  4926 E AndroidRuntime: com.google.mediapipe.framework.MediaPipeException: unknown: Input stream "output_video" of calculator "egl_surface_sink_output_video" expects packets of type "mediapipe::GpuBuffer" but the connected output stream will contain packets of type "mediapipe::ImageFrame"
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:537)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:409)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:427)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:364)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
03-17 17:13:08.317  4899  4926 E AndroidRuntime: 	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
03-17 17:13:08.320  3709  4078 W ActivityManager:   Force finishing activity com.google.mediapipe.apps.posetrackingcpu/.MainActivity
```

**Comment by harry240** [comment]
@yangcheng 

I also had this problem.   I suspect the reason for this problem is " The packet created by FrameProcessor is a GpuBuffer ".  

There are two "onNewFrame" functions defined, but only the following one is used.

```
public void onNewFrame(TextureFrame frame) {
Packet imagePacket = null;
long timestamp = frame.getTimestamp();
.
.
.

imagePacket = this.packetCreator.createGpuBuffer(frame);
```

**Comment by yangcheng** [comment]
@harry240 have you found a solution yet?

**Comment by yangcheng** [comment]
I think I found the issue , the example is missing the cpu and gpu conversion nodes. 

```
```

**Comment by harry240** [comment]
> I think I found the issue , the example is missing the cpu and gpu conversion nodes.

@yangcheng     have you fixed this issue?

**Comment by yangcheng** [comment]
yes, but the code is not as clean , I'll make a pr soon

**Comment by yangcheng** [comment]
@harry240 see https://github.com/google/mediapipe/pull/1773

**Comment by sgowroji** [comment]
Closing this issue as we see you already resolved. Thanks!
