### ISSUE TITLE
Android 5.1 compatibility

### ISSUE THREAD

**Issue by rawnsley** [google/mediapipe#178]
I built the hand tracking sample for armeabi-v7a using the following command line:

```
bazel build -c opt --config=android_arm mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu
```

It runs fine on my Android 9.0 devices but throws this error on an Android 5.1 device:
```
E art     : dlopen("/data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm/libmediapipe_jni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmediapipe_jni.so"...
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.google.mediapipe.apps.handtrackinggpu, PID: 2657
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmediapipe_jni.so"...
E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:988)
E AndroidRuntime: 	at com.google.mediapipe.apps.handtrackinggpu.MainActivity.<clinit>(MainActivity.java:50)
```
Perhaps including `-DANDROID_PLATFORM=android-21` in the **cmake** for the native binaries would fix it, but I'm not familiar enough with Bazel to know where to put it.

**Comment by teleger** [comment]
> 我使用以下命令行为armeabi-v7a构建了手部跟踪示例：
> 
> ```
> bazel build -c opt --config=android_arm mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu
> ```
> 
> 它在我的Android 9.0设备上运行良好，但在Android 5.1设备上抛出此错误：
> 
> ```
> E art     : dlopen("/data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm/libmediapipe_jni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmediapipe_jni.so"...
> D AndroidRuntime: Shutting down VM
> E AndroidRuntime: FATAL EXCEPTION: main
> E AndroidRuntime: Process: com.google.mediapipe.apps.handtrackinggpu, PID: 2657
> E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmediapipe_jni.so"...
> E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
> E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:988)
> E AndroidRuntime: 	at com.google.mediapipe.apps.handtrackinggpu.MainActivity.<clinit>(MainActivity.java:50)
> ```
> 
> 也许将本地二进制文件包含`-DANDROID_PLATFORM=android-21`在**cmake**中可以解决该问题，但是我对Bazel不够了解，无法知道将其放在哪里。


21/5000

I have the same problem as you. Have you solved it?

**Comment by jiuqiant** [comment]
You probably need to config android_ndk_repository() differently in the WORKSPACE file.
My WORKSPACE file change is attached below and those MediaPipe **CPU** demos work on a Google Nexus 5 with Android 6 and armeabi-v7a processor. 

```
$ git diff
diff --git a/WORKSPACE b/WORKSPACE
index f568e8e..c5e2445 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -247,6 +247,7 @@ maven_jar(
 # You may run setup_android.sh to install Android SDK and NDK.
 android_ndk_repository(
     name = "androidndk",
+    api_level = 21,
 )
```

However, those MediaPipe GPU demos are not working because of some mediapipe/tflite issues. Also see https://github.com/google/mediapipe/issues/193.

```
 E FrameProcessor: Mediapipe error:
10-29 13:34:51.714 12365 12403 E FrameProcessor: com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors:
10-29 13:34:51.714 12365 12403 E FrameProcessor: Calculator::Open() for node "[TfLiteInferenceCalculator, TfLiteInferenceCalculator with output stream: detection_tensors]" failed: [GL_INVALID_ENUM]: An unacceptable value is specified for an enumerated argument.: glBufferData in external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:245
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:380)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:253)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:261)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:211)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at android.os.Handler.handleCallback(Handler.java:739)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at android.os.Looper.loop(Looper.java:148)
10-29 13:34:51.714 12365 12403 E FrameProcessor: 	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)
```

**Comment by jiuqiant** [comment]
Updated install.md to document how to lower the api_level in https://github.com/google/mediapipe/commit/fce372d1530964cd6f33fe091f006a23f294a883.

**Comment by rawnsley** [comment]
Thanks @jiuqiant that worked for me.

A couple of notes for "future me" when I have this problem again:

  1. The device didn't have a front camera and I needed to change to CameraHelper.CameraFacing.BACK in MainActivity.java (error was "_No supported surface combination is found for camera device_").
  2. An app was using the camera just before the demo launched and it doesn't wait patiently for the camera to become free.

**Comment by billhung** [comment]
Hi, 
 I had this problem today. Particularly, I got the error
"java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libmediapipe_jni.so"..."
  The error only occurs on Android 5.1 (api 22), and it's working totally fine on Android 6/0 (api 23).
 Not sure how to solve the mediapipe/tflite issue @jiuqiant mentioned above.

**Comment by hafiedh** [comment]
W/System: A resource failed to call close. 
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mosibit, PID: 15166
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.example.mosibit.ui.translate.TranslateFragment.<clinit>(TranslateFragment.kt:54)
        at com.example.mosibit.ui.SectionsPagerAdapter.getItem(SectionsPagerAdapter.kt:26)
        at androidx.fragment.app.FragmentPagerAdapter.instantiateItem(FragmentPagerAdapter.java:174)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1224)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:490)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
        at android.view.View.measure(View.java:25466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3397)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2228)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 15166 SIG: 9

**Comment by sgowroji** [comment]
Hi @rawnsley, Could you please raise it as a new issue with complete steps to reproduce the above and all the configuration details. Thanks!

**Comment by rawnsley** [comment]
> Hi @rawnsley, Could you please raise it as a new issue with complete steps to reproduce the above and all the configuration details. Thanks!

Presumably you meant @hafiedh
