### ISSUE TITLE
Buggy on Motorola devices

### ISSUE THREAD

**Issue by atul109** [google/mediapipe#1801]
The build provided in instant tracking page will not work in any Motorola devices, but it can be solved by this fix
https://github.com/google/mediapipe/pull/1799

Even after applying the above fix, Moto G5+ camera preview was lagging and crashes after few seconds
Orientation of 3D is different from rest of devices.

I am unable to provide any crash logs since the device is not with me. Will update this thread if I manage to get crash in any online testing platforms.

**Comment by sgowroji** [comment]
Hi @atul109  Without error logs, We will not able to answer your query. Need logs and Complete device details  to verify. Thanks!

**Comment by atul109** [comment]
Moto G (5S) Plus
Android 8.1.0

`Fatal Exception: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
       at android.graphics.SurfaceTexture.nativeUpdateTexImage(SurfaceTexture.java)
       at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
       at com.google.mediapipe.glutil.ExternalTextureRenderer.render(ExternalTextureRenderer.java:116)
       at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.updateOutputFrame(ExternalTextureConverter.java:448)
       at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:350)
       at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
       at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(:4)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)`

**Comment by jianingwei** [comment]
Can you provide a full bugreport?

**Comment by atul109** [comment]
Logs from MotoG5 attached
[crash_report.txt](https://github.com/google/mediapipe/files/6244953/crash_report.txt)

**Comment by tyrmullen** [comment]
Looking at the crash log, it looks like it's successfully running for a bit, but then running into some errors.  Specifically, it looks like the external texture converter crash is probably caused by the surface errors earlier which might be because the graphics driver is failing to create glFenceSync objects (possibly connected to that "too many open files" error)?  So I'd see if you can limit the number of frames in-flight or the framerate, to see if throttling can help workaround the issue.  Otherwise, I think this would require a deeper dive into the Android graphics stack, so reassigning for follow-ups.

**Comment by atul109** [comment]
The issue was present in a build pulled from master branch, building from Mediapipe 0.8.2 release appears to have solved this. Also reduced camera preview resolution so that these devices are able to smoothly handle this, if resolution is not reduced sometimes there is a significant lag in camera preview which ends up crashing.
