### ISSUE TITLE
when add the android:sharedUserId in the AndroidManifest.xml, install the apk, there is the failed to install handtrackinggpu.apk: Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package com.google.mediapipe.apps.handtrackinggpu tried to change user null]

### ISSUE THREAD

**Issue by wxk2008** [google/mediapipe#1805]
when using this method(https://blog.csdn.net/TAI_BAO/article/details/109116112) to singature, there is another issuse,
java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:115)
	at java.base/java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:355)
	at com.android.signapk.SignApk.readPublicKey(SignApk.java:75)
	at com.android.signapk.SignApk.main(SignApk.java:318)
Caused by: java.io.IOException: Empty input
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:111)
	... 3 more
can you give me some advice,thanks!!

**Comment by sgowroji** [comment]
Hi @wxk2008 Could you please help us by giving more details of the above issue as how it is related to MediaPipe. Thanks!

**Comment by sgowroji** [comment]
Hi @wxk2008, Please provide more details to understand your issue. Thanks !

**Comment by sgowroji** [comment]
As we see lack of activity on this issue, We are closing it. Please feel free to open if the issue still exists. Thanks!
