### ISSUE TITLE
handtrackinggpu runtime error builded with Android Studio

### ISSUE THREAD

**Issue by f00kat** [google/mediapipe#1816]
Hi. I'm trying to run the example (Xiaomi MI9T)
`//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`

And it's works well if I build it from console and load manually with adb

1. `bazel build -c opt --config=android_arm64 --verbose_failures //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu`
2. `adb push -p ~/mediapipe/bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk /data/local/tmp`
3. `adb shell pm install /data/local/tmp/handtrackinggpu.apk`

But when I run installed app builded by AndroidStudio I get this
```2021-03-30 15:37:32.525 701-774/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2021-03-30 15:37:32.525 1644-9519/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2021-03-30 15:37:32.526 700-700/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.google.mediapipe.apps.handtrackinggpu pid = -1
2021-03-30 15:37:32.542 700-743/? E/ANDR-IOP: io prefetch is disabled
2021-03-30 15:37:32.603 23449-23449/? E/handtrackinggp: Not starting debugger since process cannot load the jdwp agent.
2021-03-30 15:37:32.646 23449-23449/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.google.mediapipe.apps.handtrackinggpu-2k-rua0EuU9q3PlIJovA8w==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.mediapipe.apps.handtrackinggpu-2k-rua0EuU9q3PlIJovA8w==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:228)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:733)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5867)
        at android.app.ActivityThread.access$1200(ActivityThread.java:201)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2021-03-30 15:37:33.967 23449-23449/? E/handtrackinggp: Invalid ID 0x00000000.
2021-03-30 15:37:33.971 23449-23449/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.handtrackinggpu, PID: 23449
    java.lang.RuntimeException: Unable to create application com.google.devtools.build.android.incrementaldeployment.StubApplication: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6005)
        at android.app.ActivityThread.access$1200(ActivityThread.java:201)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.monkeyPatchExistingResources(StubApplication.java:320)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.onCreate(StubApplication.java:569)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6000)
        at android.app.ActivityThread.access$1200(ActivityThread.java:201) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6861) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
     Caused by: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.monkeyPatchExistingResources(StubApplication.java:312)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.onCreate(StubApplication.java:569) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6000) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:201) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6861) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
2021-03-30 15:37:33.972 551-551/? E/SELinux: avc:  denied  { find } for service=miui.mqsas.MQSService pid=23449 uid=10275 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:mqs_service:s0 tclass=service_manager permissive=0
2021-03-30 15:37:33.973 23449-23449/? E/MQSEventManagerDelegate: failed to get MQSService.
```

Bazel Project settings
```
directories:
  # read project settings, e.g., .bazelrc
  .
  -mediapipe/objc
  -mediapipe/examples/ios

targets:
  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
  //mediapipe/java/...:all

android_sdk_platform: android-29

sync_flags:
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
  ```

I tried to disable "MIUI Optimization" but it doesn't help (stackoverflow advice)

**Comment by sgowroji** [comment]
Pls go through this https://github.com/google/mediapipe/issues/329

**Comment by f00kat** [comment]
I change the WORKSPACE like file this(this time I installed NDK via AndroidStudio)
```

# You may run setup_android.sh to install Android SDK and NDK.
android_ndk_repository(
    name = "androidndk",
    #path = "/home/user/Android/Sdk/ndk-bundle/android-ndk-r18b",
    path = "/home/user/Android/Sdk/ndk/21.4.7075529",
    api_level = 21,
)

android_sdk_repository(
    name = "androidsdk",
    path = "/home/user/Android/Sdk",
    api_level = 29
)
```

and still getting the same error.

**Comment by eknight7** [comment]
@jiuqiant is more familiar with this type of issue.

**Comment by jiuqiant** [comment]
> @jiuqiant is more familiar with this type of issue.

Unfortunately,  I am not familiar with Android Studio. If the app built by Bazel is running ok, it seems related to Android studio setting, similiar to https://stackoverflow.com/questions/56252142/after-migration-to-androidx-exception-at-start-up-java-lang-classnotfoundexcep.

**Comment by eknight7** [comment]
@f00kat did you get a chance to try out the link from the post above? please share, thanks.

**Comment by sgowroji** [comment]
Hi @f00kat, Can you please respond to the above comments. Thanks!

**Comment by f00kat** [comment]
Sorry, forgot about this.

If I understand "what to do" correctly..

- Added the file `proguard-rules.pro` here `/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu`
```
-keep class androidx.core.app.CoreComponentFactory { *; }
```
- Fix the `BUILD` file (`/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD`)
```
..
    proguard_generate_mapping = True,
    proguard_specs = ["proguard-rules.pro"],
..
```
- Got a lot of errors
```[19 / 24] Trimming binary with Proguard: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu; 1s linux-sandbox
ERROR: /home/user/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:35:15: Trimming binary with Proguard: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed (Exit 1): proguard failed: error executing command bazel-out/host/bin/external/remote_java_tools_linux/proguard -forceprocessing -injars ... (remaining 17 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox proguard failed: error executing command bazel-out/host/bin/external/remote_java_tools_linux/proguard -forceprocessing -injars ... (remaining 17 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Warning: com.google.common.util.concurrent.FuturesGetChecked$GetCheckedTypeValidatorHolder$ClassValueValidator$1: can't find superclass or interface java.lang.ClassValue
Warning: com.google.common.cache.Striped64: can't find referenced class sun.misc.Unsafe
Warning: com.google.common.cache.Striped64: can't find referenced class sun.misc.Unsafe
Warning: com.google.common.cache.Striped64: can't find referenced class sun.misc.Unsafe
...
Warning: com.google.common.hash.LittleEndianByteArray$UnsafeByteArray$1: can't find referenced class sun.misc.Unsafe
ProGuard, version 5.3.3
Reading program jar [/home/user/.cache/bazel/_bazel_user/7c8e9454b28036a640b8e74dd925916d/execroot/mediapipe/bazel-out/arm64-v8a-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_deploy.jar]
Reading library jar [/home/user/Android/Sdk/platforms/android-29/android.jar]
Note: androidx.coordinatorlayout.widget.CoordinatorLayout calls 'Class.getAnnotation'
Note: androidx.lifecycle.ClassesInfoCache calls 'Method.getAnnotation'
Note: androidx.viewpager.widget.ViewPager calls 'Class.getAnnotation'
Warning: com.google.common.hash.LittleEndianByteArray$UnsafeByteArray$1: can't find referenced class sun.misc.Unsafe
Note: com.google.common.eventbus.Subscriber calls 'Method.getAnnotation'
Warning: com.google.common.hash.LittleEndianByteArray$UnsafeByteArray$2: can't find referenced class sun.misc.Unsafe
...
Note: com.google.protobuf.UnsafeUtil accesses a method 'objectFieldOffset(java.lang.reflect.Field)' dynamically
      Maybe this is program method 'com.google.protobuf.UnsafeUtil { long objectFieldOffset(java.lang.reflect.Field); }'
      Maybe this is program method 'com.google.protobuf.UnsafeUtil$MemoryAccessor { long objectFieldOffset(java.lang.reflect.Field); }'
Note: there were 5 classes trying to access annotations using reflection.
      You should consider keeping the annotation attributes
      (using '-keepattributes *Annotation*').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 25 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 5 classes trying to access enclosing classes using reflection.
      You should consider keeping the inner classes attributes
      (using '-keepattributes InnerClasses').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 2 classes trying to access enclosing methods using reflection.
      You should consider keeping the enclosing method attributes
      (using '-keepattributes InnerClasses,EnclosingMethod').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 27 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 50 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.466s, Critical Path: 3.18s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully

```
- Edit the file proguard-rules.pro
```
-keep class androidx.core.app.CoreComponentFactory { *; }
-keepattributes *Annotation*
-keepattributes Signature
```
- Still getting some errors
```      Maybe this is library method 'android.webkit.WebIconDatabase { android.webkit.WebIconDatabase getInstance(); }'
      Maybe this is library method 'android.webkit.WebStorage { android.webkit.WebStorage getInstance(); }'
      Maybe this is library method 'java.text.Collator { java.text.Collator getInstance(); }'
      Maybe this is library method 'java.text.DateFormat { java.text.DateFormat getInstance(); }'
      Maybe this is library method 'java.text.DateFormatSymbols { java.text.DateFormatSymbols getInstance(); }'
      Maybe this is library method 'java.text.DecimalFormatSymbols { java.text.DecimalFormatSymbols getInstance(); }'
      Maybe this is library method 'java.text.NumberFormat { java.text.NumberFormat getInstance(); }'
      Maybe this is library method 'java.util.Calendar { java.util.Calendar getInstance(); }'
Note: com.google.protobuf.UnsafeUtil accesses a method 'objectFieldOffset(java.lang.reflect.Field)' dynamically
      Maybe this is program method 'com.google.protobuf.UnsafeUtil { long objectFieldOffset(java.lang.reflect.Field); }'
      Maybe this is program method 'com.google.protobuf.UnsafeUtil$MemoryAccessor { long objectFieldOffset(java.lang.reflect.Field); }'
Note: com.google.protobuf.UnsafeUtil accesses a method 'arrayBaseOffset(java.lang.Class)' dynamically
      Maybe this is program method 'com.google.protobuf.UnsafeUtil { int arrayBaseOffset(java.lang.Class); }'
      Maybe this is program method 'com.google.protobuf.UnsafeUtil$MemoryAccessor { int arrayBaseOffset(java.lang.Class); }'
Note: com.google.protobuf.UnsafeUtil accesses a method 'arrayIndexScale(java.lang.Class)' dynamically
      Maybe this is program method 'com.google.protobuf.UnsafeUtil { int arrayIndexScale(java.lang.Class); }'
      Maybe this is program method 'com.google.protobuf.UnsafeUtil$MemoryAccessor { int arrayIndexScale(java.lang.Class); }'
Note: com.google.protobuf.UnsafeUtil accesses a method 'objectFieldOffset(java.lang.reflect.Field)' dynamically
      Maybe this is program method 'com.google.protobuf.UnsafeUtil { long objectFieldOffset(java.lang.reflect.Field); }'
      Maybe this is program method 'com.google.protobuf.UnsafeUtil$MemoryAccessor { long objectFieldOffset(java.lang.reflect.Field); }'
Note: there were 27 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 50 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.065s, Critical Path: 2.79s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully```

**Comment by jiuqiant** [comment]
Using MediaPipe in Android Studio with Bazel is deprecated. Please see the new gradle approach in https://github.com/google/mediapipe/blob/master/docs/getting_started/android_solutions.md.
