### ISSUE TITLE
Posetracking android error on api25 ARM Cortex-A17

### ISSUE THREAD

**Issue by danj96dev** [google/mediapipe#1825]
`2021-03-31 10:40:44.929 2095-2095/com.google.mediapipe.apps.posetrackinggpu W/System: ClassLoader referenced unknown path: /data/app/com.google.mediapipe.apps.posetrackinggpu-1/lib/arm
2021-03-31 10:40:44.990 2095-2095/com.google.mediapipe.apps.posetrackinggpu V/StubApplication: StubApplication created. Android package is com.google.mediapipe.apps.posetrackinggpu, real application class is android.app.Application.
2021-03-31 10:40:44.991 2095-2095/com.google.mediapipe.apps.posetrackinggpu V/StubApplication: Found external resources at /data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.posetrackinggpu/resources.ap_
2021-03-31 10:40:44.995 2095-2095/com.google.mediapipe.apps.posetrackinggpu V/IncrementalClassLoader: Incremental dex path is /data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.posetrackinggpu/dex/incremental_classes1.dex
2021-03-31 10:40:44.995 2095-2095/com.google.mediapipe.apps.posetrackinggpu V/IncrementalClassLoader: Native lib dir is /data/user/0/com.google.mediapipe.apps.posetrackinggpu/lib
2021-03-31 10:40:51.833 2095-2095/com.google.mediapipe.apps.posetrackinggpu W/System: ClassLoader referenced unknown path: /data/user/0/com.google.mediapipe.apps.posetrackinggpu/lib
2021-03-31 10:40:51.834 2095-2095/com.google.mediapipe.apps.posetrackinggpu V/INCREMENTAL: disableContentProviders
2021-03-31 10:40:51.839 2095-2095/com.google.mediapipe.apps.posetrackinggpu V/INCREMENTAL: enableContentProviders
2021-03-31 10:40:51.854 2095-2095/com.google.mediapipe.apps.posetrackinggpu D/AndroidRuntime: Shutting down VM
2021-03-31 10:40:51.855 2095-2095/com.google.mediapipe.apps.posetrackinggpu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.posetrackinggpu, PID: 2095
    java.lang.UnsatisfiedLinkError: com.google.devtools.build.android.incrementaldeployment.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/local/tmp/incrementaldeployment/com.google.mediapipe.apps.posetrackinggpu/dex/incremental_classes1.dex"],nativeLibraryDirectories=[/data/user/0/com.google.mediapipe.apps.posetrackinggpu/lib, /system/lib, /vendor/lib]]] couldn't find "libmediapipe_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2563)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)`

Are there any more settings I need to specify in workplace or BUILD to get the app to run, it works fine on some other devices but I'm targeting a rockchip 3288

**Comment by sgowroji** [comment]
Hi @danj96dev This helped for face detection. Can you please try and let us know https://github.com/google/mediapipe/issues/205#issuecomment-564660099

**Comment by sgowroji** [comment]
Hi @danj96dev Did you get a chance to go through the above comment. Thanks!

**Comment by danj96dev** [comment]
Yes but switching to arm32 build was what ended up working for me

**Comment by sgowroji** [comment]
Seems you are unblocked we are closing this issue. Thanks.
