### ISSUE TITLE
Portrait Segmentation Runtime Error (when building apk with terminal and android studio)

### ISSUE THREAD

**Issue by yogeshsangtani** [google/mediapipe#1836]
**Description of the problem:**
Getting the same run time error when building apk from both terminal and android studio using bazel.

Configurations:
OS - Ubuntu 18.04 
Android Studio - 4.1.3 
Android API Level / SDK Platform and Build Tools - 29
Android NDK - 19
Bazel - 3.7.2

```
Error: /home/yogesh/Desktop/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/portraitsegmentationgpu/BUILD:35:15: Merging manifest for //mediapipe/examples/android/src/java/com/google/mediapipe/apps/portraitsegmentationgpu:portraitsegmentationgpu failed (Exit 1): ResourceProcessorBusyBox failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_MANIFEST -- --manifest ... (remaining 11 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox ResourceProcessorBusyBox failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_MANIFEST -- --manifest ... (remaining 11 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Error: [//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib] /tmp/manifest_merge_tmp5766761173616067927/bazel-out/android-arm64-v8a-opt/bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/basic_lib_processed_manifest/AndroidManifest.xml:24:55-93 Error:
	Attribute meta-data#converterNumBuffers@value at [//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:basic_lib] AndroidManifest.xml:24:55-93 requires a placeholder substitution but no value for <converterNumBuffers> is provided.
Error: /home/yogesh/.cache/bazel/_bazel_yogesh/098c900991236ccb28db44b0cb0bf1d5/sandbox/linux-sandbox/3467/execroot/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/AndroidManifest.xml:35:53-91 Error:
	Attribute meta-data#converterNumBuffers@value at AndroidManifest.xml:35:53-91 requires a placeholder substitution but no value for <converterNumBuffers> is provided.
Error: /home/yogesh/.cache/bazel/_bazel_yogesh/098c900991236ccb28db44b0cb0bf1d5/sandbox/linux-sandbox/3467/execroot/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/AndroidManifest.xml Error:
	Validation failed, exiting
Apr 03, 2021 1:44:23 PM com.google.devtools.build.android.ManifestMergerAction main
SEVERE: Error during merging manifests
com.google.devtools.build.android.AndroidManifestProcessor$ManifestProcessingException: Manifest merger failed with multiple errors, see logs
	at com.google.devtools.build.android.AndroidManifestProcessor.mergeManifest(AndroidManifestProcessor.java:186)
	at com.google.devtools.build.android.ManifestMergerAction.main(ManifestMergerAction.java:217)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$5.call(ResourceProcessorBusyBox.java:93)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:233)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)

Warning: 
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
Warning: 
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/portraitsegmentationgpu:portraitsegmentationgpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3809.090s, Critical Path: 2061.50s
INFO: 3605 processes: 200 internal, 3361 linux-sandbox, 44 worker.
FAILED: Build did NOT complete successfully

```

**Comment by jiuqiant** [comment]
It seems that you build your own apk portraitsegmentationgpu and the error is "Attribute meta-data#converterNumBuffers@value at AndroidManifest.xml:35:53-91 requires a placeholder substitution but no value for <converterNumBuffers> is provided."
Please follow  https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu/BUILD#L45 to provide converterNumBuffers and the other manifest values.

**Comment by yogeshsangtani** [comment]
Thanks for the support, The apk build is successful.

**Comment by kunalchamoli** [comment]
@yogeshsangtani  what value of converted _converterNumBuffers_ you used ?
