### ISSUE TITLE
how to switch cameras on Android?

### ISSUE THREAD

**Issue by hollyhook** [google/mediapipe#1842]
I'm using CameraXPreviewHandler on Android and it works fine to start the camera, both front or back are working as expected and I can receive pose data just fine. My code is based on the Android Example. Now want to allow the user to switch to the other camera. This is how I'm trying to do it:
``` kotlin
Log.i(TAG, "close " + (if (takeFrontCamera) "front" else "back") + " camera")
previewDisplayView?.visibility = View.GONE

try {
     previewFrameTexture?.release()
     converter?.close()
} catch (e: Exception) {
    e.printStackTrace()
}
takeFrontCamera = !takeFrontCamera

// open again the other cam ---------------------------------
Log.i(TAG, "open " + (if (takeFrontCamera) "front" else "back") + " camera")

converter = ExternalTextureConverter(eglManager?.context)
converter!!.setFlipY(FLIP_FRAMES_VERTICALLY)
converter!!.setConsumer(processor)
cameraHelper = CameraXPreviewHelper()
cameraHelper!!.setOnCameraStartedListener { surfaceTexture: SurfaceTexture? ->
    onCameraStarted(surfaceTexture!!)
}
val cameraFacing = if (takeFrontCamera) CameraFacing.FRONT else CameraFacing.BACK
cameraHelper!!.startCamera(
                    activity,
                    cameraFacing,
                    null,
                    cameraTargetResolution()
                )
```

it works like in 3 of 4 attempts, but else it crashes with this logcat:

```
2021-04-04 19:48:34.593 18926-18926/com.hollyhook.posehook I/PoseHookActivity: close back camera
2021-04-04 19:48:34.593 18926-18926/com.hollyhook.posehook D/SurfaceControl: hide : mNativeObject = 529859134384 - sc.mNativeObject = 529322728624 - Surface(name=SurfaceView - com.hollyhook.posehook/com.hollyhook.posehook.MainActivity@660997b@3)/@0x7b137ba
2021-04-04 19:48:34.593 18926-18926/com.hollyhook.posehook D/SurfaceControl: nativeSetFlags Done : Surface(name=SurfaceView - com.hollyhook.posehook/com.hollyhook.posehook.MainActivity@660997b@3)/@0x7b137ba
2021-04-04 19:48:34.594 18926-18926/com.hollyhook.posehook I/SurfaceView: surfaceDestroyed callback.size 1 #3 android.view.SurfaceView{660997b G.E...... ......I. 0,38-720,758 #7f080191 app:id/surfaceView}
2021-04-04 19:48:34.594 18926-18926/com.hollyhook.posehook V/PoseHookActivity: SurfaceHolder.Callback: surfaceDestroyed
2021-04-04 19:48:34.616 18926-19585/com.hollyhook.posehook W/libEGL: EGLNativeWindowType 0x7c5e49ae30 disconnect failed
2021-04-04 19:48:34.622 18926-19788/com.hollyhook.posehook E/lyhook.posehoo: [SurfaceTexture-1-18926-3] updateTexImage: SurfaceTexture is abandoned!
2021-04-04 19:48:34.626 18926-19788/com.hollyhook.posehook D/GlThread: Stopping GL thread ExternalTextureConverter
    
    --------- beginning of crash
2021-04-04 19:48:34.626 18926-19788/com.hollyhook.posehook E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.hollyhook.posehook, PID: 18926
    java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
        at com.google.mediapipe.glutil.ExternalTextureRenderer.render(ExternalTextureRenderer.java:116)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.updateOutputFrame(ExternalTextureConverter.java:448)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:350)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
2021-04-04 19:48:34.634 18926-19556/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) dequeueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.651 18926-19556/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.684 18926-19556/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.727 18926-19557/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.751 18926-19557/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.783 18926-19728/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.817 18926-19728/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.850 18926-19557/com.hollyhook.posehook E/BufferQueueProducer: [SurfaceTexture-1-18926-3](id:49ee00000003,api:4,p:752,c:18926) queueBuffer: BufferQueue has been abandoned
2021-04-04 19:48:34.852 18926-19728/com.hollyhook.posehook I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.hollyhook.posehook API Level 2
2021-04-04 19:48:34.853 18926-19594/com.hollyhook.posehook D/CaptureSession: CameraCaptureSession.onReady() OPENED
2021-04-04 19:48:39.731 18926-19553/com.hollyhook.posehook I/BpBinder: onLastStrongRef automatically unlinking death recipients: <uncached descriptor>

```

what would be the right way to switch the cameras? My phone is Samsung S10, Android 11

Edit: attached video:

https://user-images.githubusercontent.com/9899825/120538936-5d977200-c3e7-11eb-86a4-43805d91d4bb.mp4

**Comment by shadow111** [comment]
Hello @hollyhook  i'm working on the same things can you share your MainActicity as well as the layout please, i will review it with you

**Comment by hollyhook** [comment]
Hello Shadow, the app is open source, you find the code at https://bitbucket.org/constanze/posehook/

- [MainActivity](https://bitbucket.org/constanze/posehook/src/master/app/src/main/java/com/hollyhook/posehook/MainActivity.kt)
- [layouts](https://bitbucket.org/constanze/posehook/src/master/app/src/main/res/layout/) 
- in playstore, if you sign up as beta tester: https://play.google.com/store/apps/details?id=com.hollyhook.posehook

Any hint how to fix it would be appreciated.

**Comment by shadow111** [comment]
okay perfect i'm reviewing that now.
One other thing and it maybe out of scope, are you using mediaPipe tflite models?

**Comment by hollyhook** [comment]
Hi @ivan-grishchenko @rmothukuru any chance you could look into this? 
In addition to the above mentioned crash, I noticed the following issue: If the switch to the other camera sucessfully worked, the model has a tendency to see ghosts at the location where a person was previously detected with the other camera (before the switch)
Would be great if you could consider this in your solution. Thanks a lot.

**Comment by sgowroji** [comment]
Hi @hollyhook, its more an android implementation of switching the camera. I can share you the one https://stackoverflow.com/questions/27946040/switch-to-front-camera-and-back-camera-android-surfaceview/27946300 .

**Comment by hollyhook** [comment]
Hello and thanks for the link to stackoverflow.
I'm using CameraXPreviewHelper, which hides the camera obejct. Please explain how I can implement the proposed SO solution:

quoting SO:
```
mCamera.stopPreview();
mCamera.release();
if(currentCameraId == Camera.CameraInfo.CAMERA_FACING_BACK){
            currentCameraId = Camera.CameraInfo.CAMERA_FACING_FRONT;
}
else {
            currentCameraId = Camera.CameraInfo.CAMERA_FACING_BACK;
}
mCamera = Camera.open(currentCameraId);

```

I don't see how that fits together with my current approach which from the example app, which is 
````
                    cameraHelper!!.startCamera(
                            activity,
                            cameraFacing, // front or back
                            null,
                            cameraTargetResolution()
                    )
````

Do you propose to remove cameraXHelper altogether?

Also please address the question about the ghost image, see [comment above ](https://github.com/google/mediapipe/issues/1842#issuecomment-836973217)

thanks in advance

**Comment by eknight7** [comment]
Hi @hollyhook, there is an enum to select `FRONT` facing v/s `BACK` facing camera: https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/CameraHelper.java#L36-L39, and you can change that here for example: https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L176-L179

**Comment by hollyhook** [comment]
Thank you @eknight7, I'm aware of the enum. Did you have a chance to read my issue description?

**Comment by sgowroji** [comment]
Hi @hollyhook, W.r.t this [`the model has a tendency to see ghosts at the location where a person was previously detected with the other camera (before the switch)`](https://github.com/google/mediapipe/issues/1842#issuecomment-836973217) can you provide any video reference to understand it much better.

**Comment by hollyhook** [comment]
> 
> 
> Hi @hollyhook, W.r.t this [`the model has a tendency to see ghosts at the location where a person was previously detected with the other camera (before the switch)`](https://github.com/google/mediapipe/issues/1842#issuecomment-836973217) can you provide any video reference to understand it much better.

I attached the video to demonstrate the effect. This is what I recorded:
 
-  0...12s shows my carpet using the back camera. Nothing to detect here, which is ok
- switch to the front camera, showing my face (blurred for privacy)
- face quickly gets detected
- 17s: switching again to back camera 
- -> problem: some "ghost" detected in the carpet

I assume using a correct method to switch the camera could fix easily it. I want to point out that this is not a big issue, I'm much more concerned with the crash.

**Comment by eknight7** [comment]
> Thank you @eknight7, I'm aware of the enum. Did you have a chance to read my issue description?


> Hello and thanks for the link to stackoverflow.
> I'm using CameraXPreviewHelper, which hides the camera obejct. Please explain how I can implement the proposed SO solution:
> 
> quoting SO:
> 
> ```
> mCamera.stopPreview();
> mCamera.release();
> if(currentCameraId == Camera.CameraInfo.CAMERA_FACING_BACK){
>             currentCameraId = Camera.CameraInfo.CAMERA_FACING_FRONT;
> }
> else {
>             currentCameraId = Camera.CameraInfo.CAMERA_FACING_BACK;
> }
> mCamera = Camera.open(currentCameraId);
> ```
> 
> I don't see how that fits together with my current approach which from the example app, which is
> 
> ```
>                     cameraHelper!!.startCamera(
>                             activity,
>                             cameraFacing, // front or back
>                             null,
>                             cameraTargetResolution()
>                     )
> ```
> 
 
What I see is that you want to switch between Front and back facing camera, as suggested in the [comment above](https://github.com/google/mediapipe/issues/1842#issuecomment-849098055) you can do this via the enum. 

So when you press the switch camera button, you need to call `cameraHelper.startCamera(...<enum_for_front_or_back_cameraFacing> ...)`

Can you perhaps rephrase if I am misunderstanding your question? Thanks!

**Comment by hollyhook** [comment]
Hello @eknight7. Yes, this is how I do it in my app, but unfortunately it sometimes crashes. If you would kindly check out my post at the begining of this thread, you will find the log of the crash.

**Comment by ForLovelj** [comment]
@hollyhook This is my code for switching the camera, I hope it helps you.
```
class CameraXHelper(context: Context) : LifecycleObserver {

    companion object{
        private const val RATIO_4_3_VALUE = 4.0 / 3.0
        private const val RATIO_16_9_VALUE = 16.0 / 9.0
        private const val TAG  = "CameraXHelper"

    }

    private var lensFacing = CameraSelector.LENS_FACING_FRONT
    private val appContext = context.applicationContext
    private var mLifecycle: Lifecycle? = null
    private var mLifecycleOwner: LifecycleOwner? = null
    private val defalutSize = Size(1280, 720)
    private var expectSize: Size = defalutSize
    // Target frame and view resolution size in landscape.
    private var frameSize: Size? = null
    // Rotation of the camera-preview frames in degrees.
    private var frameRotation = 0
    private var  ratio = -1
    private lateinit var listener: (surfaceTexture: SurfaceTexture)->Unit
    private var cameraProvider: ProcessCameraProvider? = null
    private var preview: Preview? = null
    private var camera: Camera? = null
    private val renderExecutor by lazy {
        SingleThreadHandlerExecutor("RenderThread", 0)
    }
    private val eglManager by lazy { EglManager(null) }

    fun lifecycle(owner: LifecycleOwner?): CameraXHelper {
        if (owner == null) {
            clearLifecycleObserver()
        } else {
            clearLifecycleObserver()
            mLifecycleOwner = owner
            mLifecycle = owner.lifecycle
            mLifecycle!!.addObserver(this)
        }
        return this
    }

    private fun clearLifecycleObserver() {
        if (mLifecycle != null) {
            mLifecycle!!.removeObserver(this)
            mLifecycle = null
        }
    }

    fun setFace(face: Int): CameraXHelper {
        lensFacing = face
        return this
    }

    fun setTargetSize(size: Size): CameraXHelper {
        expectSize = size
        return this
    }

    /**
     *  [androidx.camera.core.ImageAnalysisConfig] requires enum value of
     *  [androidx.camera.core.AspectRatio]. Currently it has values of 4:3 & 16:9.
     *
     *  Detecting the most suitable ratio for dimensions provided in @params by counting absolute
     *  of preview ratio to one of the provided values.
     *
     *  @param width - preview width
     *  @param height - preview height
     *  @return suitable aspect ratio
     */
    fun aspectRatio(width: Int, height: Int): CameraXHelper {
        val previewRatio = max(width, height).toDouble() / min(width, height)
        ratio = if (abs(previewRatio - RATIO_4_3_VALUE) <= abs(previewRatio - RATIO_16_9_VALUE)) {
            AspectRatio.RATIO_4_3
        } else {
            AspectRatio.RATIO_16_9
        }
        return this
    }

    fun onCameraStart(listener: (surfaceTexture: SurfaceTexture)->Unit): CameraXHelper {
        this.listener = listener
        return this
    }

    fun switchCamera() {
        lensFacing = if (CameraSelector.LENS_FACING_FRONT == lensFacing) {
            CameraSelector.LENS_FACING_BACK
        } else {
            CameraSelector.LENS_FACING_FRONT
        }
        bindCameraUseCases()
    }

    fun startCamera() {
        val cameraProviderFuture = ProcessCameraProvider.getInstance(appContext)
        cameraProviderFuture.addListener(Runnable {

            // CameraProvider
            cameraProvider = cameraProviderFuture.get()

            // Select lensFacing depending on the available cameras
            lensFacing = when {
                hasBackCamera() && lensFacing == CameraSelector.LENS_FACING_BACK -> CameraSelector.LENS_FACING_BACK
                hasFrontCamera() -> CameraSelector.LENS_FACING_FRONT
                else -> throw IllegalStateException("Back and front camera are unavailable")
            }

            // Build and bind the camera use cases
            bindCameraUseCases()
        }, ContextCompat.getMainExecutor(appContext))
    }

    /** Declare and bind preview, capture and analysis use cases */
//    @SuppressLint("WrongConstant")
    @SuppressLint("WrongConstant")
    private fun bindCameraUseCases() {
        renderExecutor.shutdown()
        renderExecutor.start()
        // CameraProvider
        val cameraProvider = cameraProvider
            ?: throw IllegalStateException("Camera initialization failed.")

        // CameraSelector
        val cameraSelector = CameraSelector.Builder().requireLensFacing(lensFacing).build()
        // According to CameraX documentation
        // (https://developer.android.com/training/camerax/configuration#specify-resolution):
        // "Express the resolution Size in the coordinate frame after rotating the supported sizes by
        // the target rotation."
        // Since we only support portrait orientation, we unconditionally transpose width and height.
        val rotatedSize = Size(expectSize.height, expectSize.width)

        // Preview
        preview = Preview.Builder()
            .also {
                if (ratio != -1) {
                    //如果指定了比例将不再使用指定分辨率
                    // We request aspect ratio but no resolution
                    it.setTargetAspectRatio(ratio)
                } else {
                    it.setTargetResolution(expectSize)
                }
            }
            // Set initial target rotation
//            .setTargetRotation(rotation)
            .build()

        // Must unbind the use-cases before rebinding them
        cameraProvider.unbindAll()

        try {
            // A variable number of use-cases can be passed here -
            // camera provides access to CameraControl & CameraInfo
            camera = cameraProvider.bindToLifecycle(
                mLifecycleOwner!!, cameraSelector, preview)

            // Attach the viewfinder's surface provider to preview use case
            preview?.setSurfaceProvider(renderExecutor, Preview.SurfaceProvider {request ->
                val resolution = request.resolution
                Log.d(
                    "CameraXHelper",
                    String.format(
                        "Received surface request for resolution %dx%d",
                        resolution.width,
                        resolution.height
                    )
                )
                val previewFrameTexture = createSurfaceTexture()
                previewFrameTexture.setDefaultBufferSize(
                    resolution.width,
                    resolution.height
                )
                previewFrameTexture.setOnFrameAvailableListener(
                    { frameTexture: SurfaceTexture ->
                        if (frameTexture === previewFrameTexture) {
                            this.onInitialFrameReceived(appContext, frameTexture)
                        }
                    }, renderExecutor.handler!!
                )
                val surface =
                    Surface(previewFrameTexture)
                Log.d(TAG, "Providing surface")
                request.provideSurface(surface, renderExecutor,
                    Consumer { result: SurfaceRequest.Result ->
                        Log.d(
                            "CameraXHelper",
                            "Surface request result: $result"
                        )
                        previewFrameTexture.release()
                        surface.release()
                    }
                )

            })
        } catch (exc: Exception) {
            Log.e(TAG, "Use case binding failed", exc)
        }
    }

    /** Returns true if the device has an available back camera. False otherwise */
    private fun hasBackCamera(): Boolean {
        return cameraProvider?.hasCamera(CameraSelector.DEFAULT_BACK_CAMERA) ?: false
    }

    /** Returns true if the device has an available front camera. False otherwise */
    private fun hasFrontCamera(): Boolean {
        return cameraProvider?.hasCamera(CameraSelector.DEFAULT_FRONT_CAMERA) ?: false
    }

    @SuppressLint("RestrictedApi")
    private fun onInitialFrameReceived(
        context: Context,
        previewFrameTexture: SurfaceTexture
    ) {
        // This method is called by the onFrameAvailableListener we install when opening the camera
        // session, the first time we receive a frame. In this method, we remove our callback,
        // acknowledge the frame (via updateTextImage()), detach the texture from the GL context we
        // created earlier (so that the MediaPipe pipeline can attach it), and perform some other
        // one-time initialization based on the newly opened camera device. Finally, we indicate the
        // camera session is ready via the onCameraStartedListener.
        // Remove our callback.
        previewFrameTexture.setOnFrameAvailableListener(null)

        // Update texture image so we don't stall callbacks.
        previewFrameTexture.updateTexImage()

        // Detach the SurfaceTexture from the GL context we created earlier so that the MediaPipe
        // pipeline can attach it.
        previewFrameTexture.detachFromGLContext()
        if (preview!!.attachedSurfaceResolution!! != frameSize) {
            frameSize  = preview!!.attachedSurfaceResolution

            frameRotation = camera!!.cameraInfo.sensorRotationDegrees;
            if (frameSize!!.width == 0 || frameSize!!.height == 0) {
                // Invalid frame size. Wait for valid input dimensions before updating
                // display size.
                Log.d(TAG, "Invalid frameSize.");
                return
            }
        }
        Log.d(
            TAG,
            String.format(
                "frameSize %dx%d",
                frameSize?.width,
                frameSize?.height
            )
        )

        ContextCompat.getMainExecutor(context)
            .execute { listener.invoke(previewFrameTexture) }
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
    fun release() {
        clearLifecycleObserver()
        eglManager.release()
        renderExecutor.shutdown()
    }

    fun computeDisplaySizeFromViewSize(viewSize: Size): Size {
        // Camera target size is computed already, so just return the capture frame size.
        return frameSize ?: expectSize
    }

    fun isCameraRotated(): Boolean {
        return frameRotation % 180 == 90
    }

    private fun createSurfaceTexture(): SurfaceTexture {
        val tempEglSurface =
            eglManager.createOffscreenSurface(1, 1)
        eglManager.makeCurrent(tempEglSurface, tempEglSurface)
        val textures = IntArray(1)
        GLES20.glGenTextures(1, textures, 0)
        return SurfaceTexture(textures[0])
    }

    /**
     * Provides an Executor that wraps a single-threaded Handler.
     *
     * <p>All operations involving the surface texture should happen in a single thread, and that
     * thread should not be the main thread.
     *
     * <p>The surface provider callbacks require an Executor, and the onFrameAvailable callback
     * requires a Handler. We want everything to run on the same thread, so we need an Executor that
     * is also a Handler.
     */
    private class SingleThreadHandlerExecutor internal constructor(
        threadName: String?,
        priority: Int
    ) :
        Executor {
        private var handlerThread: HandlerThread? = null
        var handler: Handler? = null

        override fun execute(command: Runnable) {
            if(handler == null)return
            if (!handler!!.post(command)) {
                throw RejectedExecutionException(handlerThread?.name + " is shutting down.")
            }
        }

        fun shutdown() {
            handlerThread?.quitSafely()
            try {
                handlerThread?.join()
                handlerThread = null
                handler = null
            } catch (e: InterruptedException) {
                e.printStackTrace()
            }
        }

        fun start() {
            handlerThread = HandlerThread("RenderThread", 0)
            handlerThread!!.start()
            handler = Handler(handlerThread!!.looper)
        }
    }
}
```
like:
```
cameraHelper = CameraXHelper(this)
            .lifecycle(this)
            .setFace(CameraSelector.LENS_FACING_FRONT)
            .setTargetSize(cameraTargetResolution())
//            .aspectRatio(4,3)
            .onCameraStart {
                onCameraStarted(it)
            }
        cameraHelper?.startCamera()
//You can call cameraHelper?.switchCamera()
```

**Comment by hollyhook** [comment]
Thank you so much @ForLovelj! will give it a try.

**Comment by eknight7** [comment]
> Hello @eknight7. Yes, this is how I do it in my app, but unfortunately it sometimes crashes. If you would kindly check out my post at the begining of this thread, you will find the log of the crash.

Hi! Thank you for explaining. I looked at the exception and the code again. One thing I wanted to suggest trying is to switch the order of closing the `ExternalTextureConverter` object and releasing the `previewFrameTexture`:

```
try {
     // 1. Close converter first so that it stops grabbing frames and trying to update the output SurfaceTexture.
     converter?.close() 
     // 2. Release the previewFrameTexture after the converter has closed safely.
     previewFrameTexture?.release()
} catch (e: Exception) {
    e.printStackTrace()
}
```

From this line

> 2021-04-04 19:48:34.622 18926-19788/com.hollyhook.posehook E/lyhook.posehoo: [SurfaceTexture-1-18926-3] updateTexImage: SurfaceTexture is abandoned!

It seems that the `ExternalTextureConverter` is still trying to update a `SurfaceTexture` object after `previewFrameTexture?.release()`. So close the `converter` object first.
