### ISSUE TITLE
Sometimes after "Starting GL thread ExternalTextureConverter" it never follws up with "Create output texture" on Android

### ISSUE THREAD

**Issue by shabazkhundmiri** [google/mediapipe#1859]
I have an issue where 30-40% of the time the "Created output texture" never occurs in the logs and will not initialize TensorFlow Lite to gather input. In my case I'm using this for iris tracking. I'm not sure if there is any interruption of the thread but from the looks of the logs it seems

 ` D/ExternalTextureConv: Created output texture: 2 width: 720 height: 1280` 
 ` I/tflite: Initialized TensorFlow Lite runtime.`

and additional output never occurs. 

Thank you for any help.

**Comment by sgowroji** [comment]
Hi @shabazkhundmiri, Could you please explain your usecase with complete details like Error details, solution, code snippet or repo and steps followed.  Thanks!

**Comment by shabazkhundmiri** [comment]
This is a relevant snippet of where the converter object is initialized in the OnResume function and the startCamera() function is called to start the camera after checking that permission is granted.

```override fun onResume() {
  converter = ExternalTextureConverter(eglManager!!.context)
            converter!!.setFlipY(FLIP_FRAMES_VERTICALLY)
            converter!!.setConsumer(processor)
            if (PermissionHelper.cameraPermissionsGranted(this)) {
                Log.d(TAG, "start camera");
                startCamera()
            }
}

private fun startCamera() {
        cameraHelper = CameraXPreviewHelper()
        cameraHelper!!.setOnCameraStartedListener { surfaceTexture: SurfaceTexture? ->
            previewFrameTexture = surfaceTexture
            val focalLength = cameraHelper!!.focalLengthPixels
            if (focalLength != Float.MIN_VALUE) {
                val focalLengthSidePacket = processor!!.packetCreator.createFloat32(focalLength)
                val inputSidePackets: MutableMap<String, Packet> = HashMap()
                inputSidePackets[FOCAL_LENGTH_STREAM_NAME] = focalLengthSidePacket
                processor!!.setInputSidePackets(inputSidePackets)
            }
            previewDisplayView!!.visibility = View.VISIBLE
        }
        cameraHelper!!.startCamera(this, CAMERA_FACING,  /*surfaceTexture=*/null)
    }
```

Below is the logs of the expected output when it does successfully work and starts detecting through the camera. When it doesn't work, this log output below is not present and the app never starts detecting through the camera. Other than that the logs seem identical. The app does not crash or show any relevant error when the camera doesn't start detecting. I have been combing through comparing the logs between when the camera detects and doesn't detect but the only difference seems to be lack of the log output below where output textures are created and the tflite files are successfully loaded. 

```
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 2 width: 720 height: 1280
com.example.mediapipe.iris I/native: I20210408 23:37:59.986203 16976 graph.cc:411] Start running the graph, waiting for inputs.
com.example.mediapipe.iris I/native: I20210408 23:37:59.986452 16976 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
com.example.mediapipe.iris I/native: I20210408 23:37:59.987490 17061 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 V@0490.0 (GIT@4783c89, I46ff5fc46f, 1606807783) (Date:11/30/20))
com.example.mediapipe.iris I/native: I20210408 23:38:00.000830 16974 resource_util_android.cc:54] Successfully loaded: face_detection_front.tflite
com.example.mediapipe.iris I/tflite: Initialized TensorFlow Lite runtime.
com.example.mediapipe.iris I/tflite: Created TensorFlow Lite delegate for GPU.
com.example.mediapipe.iris E/tflite: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    164 operations will run on the GPU, and the remaining 0 operations will run on the CPU.
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 4 width: 720 height: 1280
com.example.mediapipe.iris I/native: I20210408 23:38:00.306030 17060 jni_util.cc:41] GetEnv: not attached
com.example.mediapipe.iris D/H: checkAllPermissions
com.example.mediapipe.iris D/H: hasUsageStatsPermission: true
com.example.mediapipe.iris I/native: I20210408 23:38:00.745271 16974 resource_util_android.cc:54] Successfully loaded: face_landmark.tflite
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 129 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 136 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 144 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 149 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 162 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 173 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 179 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 184 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 191 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 210 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 226 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 245 width: 720 height: 1280
com.example.mediapipe.iris I/native: I20210408 23:38:01.419572 16974 resource_util_android.cc:54] Successfully loaded: iris_landmark.tflite
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 246 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 246 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 246 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 246 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 246 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 246 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 252 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 286 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 291 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 325 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 330 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 369 width: 720 height: 1280
com.example.mediapipe.iris D/H: deleteUserContent main 0
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 412 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 426 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 462 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 475 width: 720 height: 1280
com.example.mediapipe.iris I/native: I20210408 23:38:01.991688 16974 resource_util_android.cc:54] Successfully loaded: iris_landmark.tflite
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 476 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 476 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 595 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 703 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 705 width: 720 height: 1280
com.example.mediapipe.iris D/ExternalTextureConv: Created output texture: 707 width: 720 height: 1280
com.example.mediapipe.iris V/MainActivity: right depth in cm is: 136.09496
com.example.mediapipe.iris V/MainActivity: left depth in cm is: 43.320686
```

Any help would be appreciated. Please let me know if I can provide anything more to get a better idea of the issue. Thank You!

**Comment by stilva** [comment]
@shabazkhundmiri I've also had this issue for the longest time. [This ](https://github.com/google/mediapipe/issues/1508#issuecomment-812390364)fixed it for me.

Basically just add `surfaceTexture.updateTexImage();` in [`ExternalTextureConverter.java`](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/ExternalTextureConverter.java#L285):

```java
public void setSurfaceTextureAndAttachToGLContext(SurfaceTexture texture, int width, int height) {
    setSurfaceTexture(texture, width, height);
    int[] textures = new int[1];
    GLES20.glGenTextures(1, textures, 0);
    surfaceTexture.attachToGLContext(textures[0]);
    surfaceTexture.updateTexImage();
}
```

**Comment by sgowroji** [comment]
We are glad to know you issue is resolved. Closing this issue . Thanks!

**Comment by shabazkhundmiri** [comment]
> @shabazkhundmiri I've also had this issue for the longest time. [This ](https://github.com/google/mediapipe/issues/1508#issuecomment-812390364)fixed it for me.
> 
> Basically just add `surfaceTexture.updateTexImage();` in [`ExternalTextureConverter.java`](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/ExternalTextureConverter.java#L285):
> 
> ```java
> public void setSurfaceTextureAndAttachToGLContext(SurfaceTexture texture, int width, int height) {
>     setSurfaceTexture(texture, width, height);
>     int[] textures = new int[1];
>     GLES20.glGenTextures(1, textures, 0);
>     surfaceTexture.attachToGLContext(textures[0]);
>     surfaceTexture.updateTexImage();
> }
> ```

Thank you so much @stilva ! This helped get it running 100% of the time. 

Unfortunately I'm now running into an issue where when the app is paused, it crashes. It seems as though surfaceTexture is not being released/detached properly.

This is in my current onPause() function:

super.onPause()

            processor!!.close()
            try {
                previewFrameTexture!!.release()

                if (converter != null) converter!!.close()
            } catch (e: java.lang.Exception) {
                e.printStackTrace()
            }

**Comment by shabazkhundmiri** [comment]
> @shabazkhundmiri I've also had this issue for the longest time. [This ](https://github.com/google/mediapipe/issues/1508#issuecomment-812390364)fixed it for me.
> 
> Basically just add `surfaceTexture.updateTexImage();` in [`ExternalTextureConverter.java`](https://github.com/google/mediapipe/blob/master/mediapipe/java/com/google/mediapipe/components/ExternalTextureConverter.java#L285):
> 
> ```java
> public void setSurfaceTextureAndAttachToGLContext(SurfaceTexture texture, int width, int height) {
>     setSurfaceTexture(texture, width, height);
>     int[] textures = new int[1];
>     GLES20.glGenTextures(1, textures, 0);
>     surfaceTexture.attachToGLContext(textures[0]);
>     surfaceTexture.updateTexImage();
> }
> ```

Thank you so much @stilva ! This helped get it running 100% of the time. 

Unfortunately I'm now running into an issue where when the app is paused, it crashes. It seems as though surfaceTexture is not being released/detached properly.

This is in my current onPause() function:

      override fun onPause() {
            super.onPause()

            processor!!.close()
            try {
                previewFrameTexture!!.release()

                if (converter != null) converter!!.close()
            } catch (e: java.lang.Exception) {
                e.printStackTrace()
            }
       }

This is the the relevant log:

       
```
I/native: I20210505 10:37:47.091229 13058 graph.cc:535] Close all input streams.
I/native: I20210505 10:37:47.131820 13229 jni_util.cc:86] Exiting thread. Detach thread.
I/native: I20210505 10:37:47.131821 13224 jni_util.cc:86] Exiting thread. Detach thread.
I/native: I20210505 10:37:47.135502 13225 jni_util.cc:86] Exiting thread. Detach thread.
I/native: I20210505 10:37:47.136014 13228 jni_util.cc:86] Exiting thread. Detach thread.
I/native: I20210505 10:37:47.136055 13226 jni_util.cc:86] Exiting thread. Detach thread.
I/native: I20210505 10:37:47.136173 13222 jni_util.cc:86] Exiting thread. Detach thread.
I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
I/native: I20210505 10:37:47.136039 13223 jni_util.cc:86] Exiting thread. Detach thread.
D/SurfaceUtils: disconnecting from surface 0x70a73c75c0, reason disconnectFromSurface
I/native: I20210505 10:37:47.137293 13227 jni_util.cc:86] Exiting thread. Detach thread.
E/BufferQueueProducer: [MediaCodec.release](id:330200000002,api:0,p:-1,c:13058) detachBuffer: BufferQueue has no connected producer
W/A: Queue length for executor EventBus is now 11. Perhaps some tasks are too long, or the pool is too small.
W/NgaMessageHandler: Invalid action "screen_state" for state:
      NGA is Assistant = true
      SysUI is NGA UI = true
E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: failed precondition: Graph must be running.
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:379)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:442)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:365)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:310)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
I/AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
E/BufferQueueProducer: [SurfaceTexture-1-13058-0](id:330200000000,api:4,p:1132,c:13058) queueBuffer: BufferQueue has been abandoned
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/Camera3-OutputStream: returnBufferCheckedLocked: Stream 0: Error queueing buffer to native window: No such device (-19)
E/BufferQueueProducer: [SurfaceTexture-1-13058-0](id:330200000000,api:4,p:1132,c:13058) dequeueBuffer: BufferQueue has been abandoned
E/Camera3-OutputStream: getBufferLockedCommon: Stream 0: Can't dequeue next output buffer: No such device (-19)
W/GCH_CameraDeviceSession: RequestStreamBuffers: Requesting stream buffer failed. (buffer_returns has 1 entries)
I/GCH_CameraDeviceSession: RequestStreamBuffers: stream -1, buffer request error 3
I/StreamBufferCacheManager: AllocateDummyBufferLocked: [sbc] Dummy buffer allocated: strm 0 buffer 0xb400007b668273c0
W/StreamBufferCacheManager: Refill: Failed to acquire buffer for stream 0, error 3
W/StreamBufferCacheManager: Refill: Stream 0 is disconnected or unknown error observed.This stream is marked as inactive.
I/StreamBufferCacheManager: Refill: Stream 0 begin to use dummy buffer.
I/GCH_CameraDeviceSession: RequestBuffersFromStreamBufferCacheManager: [sbc] Dummy buffer returned for stream: 0, frame: 126
I/StreamBufferCacheManager: Refill: Already notified for flushing or stream already deactived.
I/GCH_CameraDeviceSession: NotifyErrorMessage: [sbc] Request 126 with stream (0), return error code (4)
I/GCH_CameraDeviceSession: NotifyBufferError: [sbc] Return Buffer Error Status for frame 126 stream 0
I/StreamBufferCacheManager: Refill: Already notified for flushing or stream already deactived.
I/GCH_CameraDeviceSession: RequestBuffersFromStreamBufferCacheManager: [sbc] Dummy buffer returned for stream: 0, frame: 127
I/GCH_CameraDeviceSession: NotifyErrorMessage: [sbc] Request 127 with stream (0), return error code (4)
I/GCH_CameraDeviceSession: NotifyBufferError: [sbc] Return Buffer Error Status for frame 127 stream 0
D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
I/ProximityAuth: [FeatureEnabledController] Updating previously enabled features ([]) and with enabled features synced from Cryptauth ([]) [CONTEXT service_id=108 ]
D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
I/GCH_CameraDeviceSession: RequestBuffersFromStreamBufferCacheManager: [sbc] Dummy buffer returned for stream: 0, frame: 128
I/StreamBufferCacheManager: Refill: Already notified for flushing or stream already deactived.
I/GCH_CameraDeviceSession: NotifyErrorMessage: [sbc] Request 128 with stream (0), return error code (4)
I/GCH_CameraDeviceSession: NotifyBufferError: [sbc] Return Buffer Error Status for frame 128 stream 0
E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
I/native: I20210505 10:37:47.298754 13134 jni_util.cc:86] Exiting thread. Detach thread.
I/GCH_CameraDeviceSession: RequestBuffersFromStreamBufferCacheManager: [sbc] Dummy buffer returned for stream: 0, frame: 129
I/StreamBufferCacheManager: Refill: Already notified for flushing or stream already deactived.
I/GCH_CameraDeviceSession: NotifyErrorMessage: [sbc] Request 129 with stream (0), return error code (4)
I/GCH_CameraDeviceSession: NotifyBufferError: [sbc] Return Buffer Error Status for frame 129 stream 0
E/chromium: [0505/103747.348586:ERROR:elf_dynamic_array_reader.h(61)] tag not found
I/StreamBufferCacheManager: Refill: Already notified for flushing or stream already deactived.
I/GCH_CameraDeviceSession: RequestBuffersFromStreamBufferCacheManager: [sbc] Dummy buffer returned for stream: 0, frame: 130
I/GCH_CameraDeviceSession: NotifyErrorMessage: [sbc] Request 130 with stream (0), return error code (4)
I/GCH_CameraDeviceSession: NotifyBufferError: [sbc] Return Buffer Error Status for frame 130 stream 0
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1a0 in tid 13137 (ExternalTexture), pid 13058
I/GCH_CameraDeviceSession: RequestBuffersFromStreamBufferCacheManager: [sbc] Dummy buffer returned for stream: 0, frame: 131
I/StreamBufferCacheManager: Refill: Already notified for flushing or stream already deactived.
I/GCH_CameraDeviceSession: UpdatePendingRequest: [sbc] All inflight requests/streams cleared. Notified SBC for flushing.
I/GCH_CameraDeviceSession: NotifyErrorMessage: [sbc] Request 131 with stream (0), return error code (4)
I/GCH_CameraDeviceSession: NotifyBufferError: [sbc] Return Buffer Error Status for frame 131 stream 0
D/CaptureSession: CameraCaptureSession.onReady() OPENED
I/MagicTether: [AutoDisconnectIntentOperation] Canceling task. [CONTEXT service_id=276 ]
I/MagicTether: [AutoDisconnectIntentOperation] Canceling task. [CONTEXT service_id=276 ]
I/crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
I/tombstoned: received crash request for pid 13137
I/crash_dump64: performing dump of process 13058 (target tid = 13137)
A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: 'google/redfin/redfin:11/RQ2A.210505.003/7255357:user/release-keys'
A/DEBUG: Revision: 'DVT1.0'
A/DEBUG: ABI: 'arm64'
A/DEBUG: Timestamp: 2021-05-05 10:37:47-0700
A/DEBUG: pid: 13058, tid: 13137, name: ExternalTexture  >>> com.medipipe.example <<<
A/DEBUG: uid: 10283
A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1a0
A/DEBUG: Cause: null pointer dereference
A/DEBUG:     x0  0000000000000000  x1  0000006e9ba58364  x2  0000000000000000  x3  0000000000000003
A/DEBUG:     x4  00000000000002d0  x5  0000000000000500  x6  0000006e9ba58368  x7  0000006e9ba59fb8
A/DEBUG:     x8  1f9faf34c2bbf449  x9  1f9faf34c2bbf449  x10 0000000000430000  x11 0000006e9ba56fa8
A/DEBUG:     x12 0000006e9ba58368  x13 0000006e9ba58358  x14 0000000000000001  x15 00000000ebad6a89
A/DEBUG:     x16 0000006eb64433b8  x17 0000006eb598f7c0  x18 0000006e9b1b6000  x19 0000000000000000
A/DEBUG:     x20 0000000000000500  x21 00000000000002d0  x22 0000000000000003  x23 00000070973cce38
A/DEBUG:     x24 0000006e9ba58364  x25 0000006fe73f7910  x26 0000006e9ba58368  x27 0000006e9ba5a000
A/DEBUG:     x28 0000006e9ba58370  x29 0000006e9ba58340
A/DEBUG:     lr  0000006eb599a1a0  sp  0000006e9ba58230  pc  0000006eb598f7c0  pst 0000000060000000
```

I've been trying out small tweaks but to no avail. I would really appreciate any help on the matter. Thank you!

**Comment by sgowroji** [comment]
Hi @shabazkhundmiri, You can raise it as a new issue if that is not relavant to the above one.

**Comment by shabazkhundmiri** [comment]
Hey @sgowroji, I think it may be related to the solution of the last issue since it popped up directly afterwards.

**Comment by mcclanahoochie** [comment]
Hi, Are you using a custom MainActivity.java? If so, can you compare your override functions to how they are implemented here https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java ?

You can also try increasing the [NUM_BUFFERS](https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/MainActivity.java#L55) for the external tex converter, to 3 or 4.

**Comment by sgowroji** [comment]
Hi @shabazkhundmiri,  Did you get a chance to go through the above [comment](https://github.com/google/mediapipe/issues/1859#issuecomment-854932725). Thanks!

**Comment by shabazkhundmiri** [comment]
Thank you for your reply @mcclanahoochie .

Changing the NUM_BUFFERS didn't help but when I compared the my code to the link you mentioned I decided to revise the onPause() function to only close the ExternalTextureConverter like this:
```
 override fun onPause() {
        try {
            if (converter != null) 
               //close ExternalTextureConverter
               converter!!.close()
        } catch (e: java.lang.Exception) {
            e.printStackTrace()
        }
   }
```
This lead to a more understandable error that now showed that the `converter` was trying to open as a new instance when the app was coming back to the foreground. So then I added an IF statement to my onResume() function to check if an instance is already running:

```
if (converter == null) {
            converter = ExternalTextureConverter(eglManager!!.context, 2)
            converter!!.setFlipY(FLIP_FRAMES_VERTICALLY)
            converter!!.setConsumer(processor)
            if (PermissionHelper.cameraPermissionsGranted(this)) {
                Log.d(TAG, "start camera");
                startCamera()
            }
        }
```

Now the app is allowed to pause and resume correctly. Thank you for the help!
