### ISSUE TITLE
Error when trying to build for ios 

### ISSUE THREAD

**Issue by lvkleist** [google/mediapipe#187]
while following this tutorial:
https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md

I tried to build the Hand Tracking App for ios using the command 
bazel build --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
And I get the following error:
ERROR: /Users/jm/Desktop/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:43:1: in ios_application rule //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp: 
Traceback (most recent call last):
	File "/Users/jm/Desktop/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD", line 43
		ios_application(name = 'HandTrackingGpuApp')
	File "/private/var/tmp/_bazel_jm/a96ea57bedade54fb24cd40c294df00f/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 160, in _ios_application_impl
		run_support.register_simulator_executable(<2 more arguments>)
	File "/private/var/tmp/_bazel_jm/a96ea57bedade54fb24cd40c294df00f/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 28, in run_support.register_simulator_executable
		ctx.actions.expand_template(<4 more arguments>)
	File "/private/var/tmp/_bazel_jm/a96ea57bedade54fb24cd40c294df00f/external/build_bazel_rules_apple/apple/internal/run_support.bzl", line 36, in ctx.actions.expand_template
		shell.quote(<1 more arguments>)
	File "/private/var/tmp/_bazel_jm/a96ea57bedade54fb24cd40c294df00f/external/bazel_skylib/lib/shell.bzl", line 49, in shell.quote
		s.replace("'", "'\\''")
type 'NoneType' has no method replace()
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed; build aborted: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed; build aborted

Would appreciate any help :)

**Comment by jiuqiant** [comment]
It's because of the latest Bazel version. It seems like MediaPipe has some problem with Bazel 1.0.0+ on macOS.
Please downgrade to Bazel 0.29.1 if possible. You need to do 
```
$ brew uninstall bazel
$ BAZEL_VERSION="0.29.1"  &&  wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh  
$ chmod +x bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh   
$ sudo ./bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh
```

**Comment by johniao** [comment]
I just encounter the same error, and solved it with 
"
brew uninstall bazel
brew install https://raw.githu...
brew link bazel
"
which @jiuqiant mentioned above!!!
Thank you both!!!
