### ISSUE TITLE
converting objectron to kotlin

### ISSUE THREAD

**Issue by tilenpinta** [google/mediapipe#1977]
I want to make object detection in kotlin and im getting this error -> `A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22148 (mediapipe_gl_ru), pid 18790 (mple.pipetest3d)`

When I run the app, then I get to access camera and when I click to access it. App crash and get that error.

And there is whole log ->

05/04 10:15:36: Launching 'app' on Physical Device.
Install successfully finished in 3 s 168 ms.
$ adb shell am start -n "com.example.pipetest3d/com.example.pipetest3d.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 18790 on device 'oneplus-hd1903-7f031316'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/mple.pipetest3: Late-enabling -Xcheck:jni
I/mple.pipetest3: Unquickening 21 vdex files!
E/mple.pipetest3: Unknown bits set in runtime_flags: 0x800000
I/100: Open /data/app/~~HgEgz8VtgWzoZB97aU_cCA==/com.example.pipetest3d-nz-GJO6SIeyqvd4YIYwU7A==/base.apk took:167ms
I/Perf: Connecting to perf service.
I/mple.pipetest3: [GL_OOM] ClampGrowthLimit 536870912
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
E/Config:Grabber:OnePlusFontConfig: Index 0 requested, with a size of 0
E/mple.pipetest3: [frame_perf] perfboost open tb_ctl file failed, isApp[1], errno=No such file or directory
E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
W/mple.pipetest3: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/mple.pipetest3: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/native: I20210504 10:15:41.963449 18790 asset_manager_util.cc:59] Created global reference to asset manager.
I/AdrenoGLES-0: QUALCOMM build                   : 559e78c, Ib9d997268a
    Build Date                       : 10/13/20
    OpenGL ES Shader Compiler Version: EV031.32.02.02
    Local Branch                     : mybrancheb0d76cb-f27a-f1ff-9cdc-1458d0b52ae8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
    Build Config                     : S P 10.0.7 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
I/native: I20210504 10:15:41.990247 18790 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I20210504 10:15:41.995401 22148 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 V@0502.0 (GIT@559e78c, Ib9d997268a, 1602617665) (Date:10/13/20))
I/native: I20210504 10:15:42.004722 18790 asset_manager_util.cc:59] Created global reference to asset manager.
D/PermissionHelper: checkAndRequestCameraPermissions
D/GlThread: Starting GL thread ExternalTextureConverter
D/ViewRootImpl: support adaptive color gamut feature!
V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
D/OpScreenModeManager: setRefreshRate view android.view.SurfaceView{c9bd7ab G.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
D/OpScreenModeManager: create mRatio 1.2
D/GlThread: Stopping GL thread ExternalTextureConverter
I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
D/PermissionHelper: onRequestPermissionsResult
    android.permission.CAMERA permission granted.
D/GlThread: Starting GL thread ExternalTextureConverter
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@9d91c77[MainActivity]
I/CameraManagerGlobal: Connecting to camera service
D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=true inTouchMode=true
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/chatty: uid=10423(com.example.pipetest3d) CameraX-core_ca identical 1 line
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 3
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 4
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 5
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/CameraRepository: Added camera: 0
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
D/CameraRepository: Added camera: 1
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
D/UseCaseAttachState: Active and attached use case: [] for camera: 0
D/UseCaseAttachState: Active and attached use case: [] for camera: 1
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/DeferrableSurface: Surface created[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@4b943ae}
D/CameraXPreviewHelper: Received surface request for resolution 1280x720
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
D/CameraXPreviewHelper: Providing surface
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Use case Preview:androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b1 ACTIVE
D/UseCaseAttachState: Active and attached use case: [] for camera: 1
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Use cases [Preview:androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b1] now ATTACHED
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b158622509] for camera: 1
    Active and attached use case: [androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b158622509] for camera: 1
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Resetting Capture Session
    {Camera@d2ab95a[id=1]} Releasing session in state INITIALIZED
D/CameraStateRegistry: tryOpenCamera(Camera@d2ab95a[id=1]) [Available Cameras: 1, Already Open: false (Previous state: null)] --> SUCCESS
D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@d2ab95a[id=1]                         OPENING               
    Camera@5c8864e[id=0]                         UNKNOWN               
    -------------------------------------------------------------------
    Open count: 1 (Max allowed: 1)
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Transitioning camera internal state: INITIALIZED --> OPENING
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Opening camera.
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b158622509] for camera: 1
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Use case Preview:androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b1 ACTIVE
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b158622509] for camera: 1
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} CameraDevice.onOpened()
D/Camera2CameraImpl: {Camera@d2ab95a[id=1]} Transitioning camera internal state: OPENING --> OPENED
D/CameraStateRegistry: Recalculating open cameras:
    Camera                                       State                 
    -------------------------------------------------------------------
    Camera@d2ab95a[id=1]                         OPEN                  
    Camera@5c8864e[id=0]                         UNKNOWN               
    -------------------------------------------------------------------
    Open count: 1 (Max allowed: 1)
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b158622509] for camera: 1
D/UseCaseAttachState: Active and attached use case: [androidx.camera.core.Preview-e1c21972-27fd-4de2-ab75-48e3799dc4b158622509] for camera: 1
D/SyncCaptureSessionBase: [androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl@8baf655] getSurface...done
D/DeferrableSurface: New surface in use[total_surfaces=1, used_surfaces=1](androidx.camera.core.SurfaceRequest$2@4b943ae}
D/DeferrableSurface: use count+1, useCount=1 androidx.camera.core.SurfaceRequest$2@4b943ae
D/CaptureSession: Opening capture session.
D/CaptureSession: Attempting to send capture request onConfigured
D/CaptureSession: Issuing request for session.
D/CaptureSession: CameraCaptureSession.onConfigured() mState=OPENED
D/CaptureSession: CameraCaptureSession.onReady() OPENED
D/CameraOrientationUtil: getRelativeImageRotation: destRotationDegrees=0, sourceRotationDegrees=270, isOppositeFacing=false, result=270
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/OpScreenModeManager: setRefreshRate parent android.widget.FrameLayout{9f43136 V.E...... ......ID 0,0-1080,2117 #7f08011f app:id/preview_display_layout} parent width 1080 parent height 2117 mRatio 1.2
    setRefreshRate view android.view.SurfaceView{c9bd7ab V.E...... ......ID 0,0-1080,2117} viewRate 1 width 1080 height 2117
    setRefreshRate token android.os.BinderProxy@501ed42 rate 1 mCurrentRate 0 tmpRate:2
D/OpScreenModeManager: updateScenario fullScreen 1
D/OpScreenModeManager: setRefreshRate parent android.widget.FrameLayout{9f43136 V.E...... ........ 0,0-1080,2117 #7f08011f app:id/preview_display_layout} parent width 1080 parent height 2117 mRatio 1.2
    setRefreshRate view android.view.SurfaceView{c9bd7ab V.E...... ........ 0,0-1080,2117} viewRate 1 width 1080 height 2117
D/ExternalTextureConv: Created output texture: 2 width: 1280 height: 720
I/native: I20210504 10:15:48.512840 22262 graph.cc:475] Start running the graph, waiting for inputs.
    I20210504 10:15:48.512987 22262 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I20210504 10:15:48.514575 22300 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 V@0502.0 (GIT@559e78c, Ib9d997268a, 1602617665) (Date:10/13/20))
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22148 (mediapipe_gl_ru), pid 18790 (mple.pipetest3d)
D/ExternalTextureConv: Created output texture: 3 width: 1280 height: 720
I/native: I20210504 10:15:48.549842 22294 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.562898 22296 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.610980 22299 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.631660 22298 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.664021 22295 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.697582 22293 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.730330 22292 jni_util.cc:41] GetEnv: not attached
I/native: I20210504 10:15:48.763667 22297 jni_util.cc:41] GetEnv: not attached

My build gradle ->
    
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    // MediaPipe deps
    implementation 'com.google.flogger:flogger:0.3.1'
    implementation 'com.google.flogger:flogger-system-backend:0.3.1'
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'com.google.protobuf:protobuf-java:3.11.4'

    // CameraX core library
    def camerax_version = "1.1.0-alpha04"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"

here is a pic of libraries I have in and other stuff
![image](https://user-images.githubusercontent.com/61638005/116978143-9dbde480-acc3-11eb-946a-e2eefd3a85e4.png)

EDITED*

One guy have code in kotlin but for hand tracking. I want to have Objectron.
And he have for cameraX in build.gradle(:app)

    // CameraX core library
    def camerax_version = "1.0.0-alpha06"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"

If I add the same I got error -> 
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/camera/lifecycle/ProcessCameraProvider;`
        at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:160)
        at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:130)
        at com.example.pipetest3d.MainActivity.startCamera(MainActivity.kt:159)
        ...
            `Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.camera.lifecycle.ProcessCameraProvider" on path: DexPathList[[zip file "/data/app/~~aE9QmtPzWhgAiLmC7iTp3w==/com.example.pipetest3d-8aMjgllslw7ZdUtV59QuRA==/base.apk"],nativeLibraryDirectories=[/data/app/~~aE9QmtPzWhgAiLmC7iTp3w==/com.example.pipetest3d-8aMjgllslw7ZdUtV59QuRA==/lib/arm64, /data/app/~~aE9QmtPzWhgAiLmC7iTp3w==/com.example.pipetest3d-8aMjgllslw7ZdUtV59QuRA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]`
       ...
And at line 159 I have ->
![image](https://user-images.githubusercontent.com/61638005/116986127-b4693900-accd-11eb-8141-64d733172305.png)

**Comment by sgowroji** [comment]
Hi @tilenpinta, Take a look at this issue https://github.com/google/mediapipe/issues/1237.

**Comment by tilenpinta** [comment]
> I'm having the same issue and downgrading to 1.0.0-alpha06 does not help, any ideas how to solve this?
> 
> Ok, was able to get further by upgrading to 1.1.0-alpha03 and adding
> implementation "androidx.camera:camera-lifecycle:$camerax_version"

I tried this and get error
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 20512 (mediapipe_gl_ru), pid 13024 (mple.pipetest3d)`

At the moment I have 1.1.0-alpha04 which is newer and still get the same error.

**Comment by tilenpinta** [comment]
I downgraded google/mediapipe to => `parent 8f69af9 commit cccf6244d3fc4afc53082a397e764a8560eec96e` and build new mp_object_detection_3d_aar.aar file for objectron.
And I think I'm past that error. But now I have new error...

`W/native: W20210505 00:14:06.753552 28415 motion_analysis_calculator.cc:337] No input video header found. Downstream calculators expecting video headers are likely to fail.`

`A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28364 (mediapipe_gl_ru), pid 18645 (mple.pipetest3d)`

Here is the whole log =>

05/05 00:13:58: Launching 'app' on Physical Device.
Install successfully finished in 4 s 586 ms.
$ adb shell am start -n "com.example.pipetest3d/com.example.pipetest3d.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 18645 on device 'oneplus-hd1903-7f031316'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/100: Open /data/app/~~UlUvJd51g8J-JlgMR3tIRQ==/com.example.pipetest3d-1xcYzh-HKPdx1rIzJtpwaA==/base.apk took:150ms
I/Perf: Connecting to perf service.
I/mple.pipetest3: [GL_OOM] ClampGrowthLimit 536870912
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/Camera2Initializer: CameraX initializing with Camera2 ...
I/CameraManagerGlobal: Connecting to camera service
W/mple.pipetest3d: type=1400 audit(0.0:11212): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
I/chatty: uid=10423(com.example.pipetest3d) identical 1 line
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 3
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 4
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/CameraManagerGlobal: [soar.cts] ignore the status update of camera: 5
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/CameraRepository: Added camera: 0
D/CameraRepository: Added camera: 1
D/UseCaseAttachState: Active and online use case: [] for camera: 0
D/UseCaseAttachState: Active and online use case: [] for camera: 1
E/Config:Grabber:OnePlusFontConfig: Index 0 requested, with a size of 0
E/mple.pipetest3: [frame_perf] perfboost open tb_ctl file failed, isApp[1], errno=No such file or directory
E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
W/mple.pipetest3: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/mple.pipetest3: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/native: I20210505 00:14:04.225211 18645 asset_manager_util.cc:59] Created global reference to asset manager.
I/AdrenoGLES-0: QUALCOMM build                   : 559e78c, Ib9d997268a
    Build Date                       : 10/13/20
    OpenGL ES Shader Compiler Version: EV031.32.02.02
    Local Branch                     : mybrancheb0d76cb-f27a-f1ff-9cdc-1458d0b52ae8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
    Build Config                     : S P 10.0.7 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
I/native: I20210505 00:14:04.245719 18645 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I20210505 00:14:04.248859 28364 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 V@0502.0 (GIT@559e78c, Ib9d997268a, 1602617665) (Date:10/13/20))
I/native: I20210505 00:14:04.256713 18645 asset_manager_util.cc:59] Created global reference to asset manager.
D/PermissionHelper: checkAndRequestCameraPermissions
D/GlThread: Starting GL thread ExternalTextureConverter
D/ViewRootImpl: support adaptive color gamut feature!
V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
D/OpScreenModeManager: setRefreshRate view android.view.SurfaceView{e3c799e G.E...... ......I. 0,0-0,0} viewRate 0 width 0 height 0
D/OpScreenModeManager: create mRatio 1.2
D/GlThread: Stopping GL thread ExternalTextureConverter
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@a56594d[MainActivity]
D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=true inTouchMode=true
D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=false inTouchMode=true
W/Binder:18645_3: type=1400 audit(0.0:11222): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/PermissionHelper: onRequestPermissionsResult
    android.permission.CAMERA permission granted.
D/GlThread: Starting GL thread ExternalTextureConverter
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/mple.pipetest3d: type=1400 audit(0.0:11223): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/mple.pipetest3d: type=1400 audit(0.0:11224): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_FULL
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/mple.pipetest3d: type=1400 audit(0.0:11225): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/mple.pipetest3d: type=1400 audit(0.0:11226): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/mple.pipetest3d: type=1400 audit(0.0:11227): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
W/mple.pipetest3d: type=1400 audit(0.0:11228): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
D/Camera: Use cases [Preview:androidx.camera.core.Preview-9ca41d72-d52a-4870-adbb-d88d42f97b33] ONLINE for camera 1
D/UseCaseAttachState: Active and online use case: [] for camera: 1
D/Camera: Resetting Capture Session
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@a56594d[MainActivity]
D/Camera: releasing session in state INITIALIZED
D/Camera: Transitioning camera internal state: INITIALIZED --> OPENING
    Opening camera: 1
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-9ca41d72-d52a-4870-adbb-d88d42f97b33] for camera: 1
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/ViewRootImpl[MainActivity]: windowFocusChanged hasFocus=true inTouchMode=true
W/CameraX-: type=1400 audit(0.0:11229): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
W/mple.pipetest3d: type=1400 audit(0.0:11230): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=18984 scontext=u:r:untrusted_app:s0:c167,c257,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.example.pipetest3d
E/libc: Access denied finding property "vendor.camera.aux.packagelist"
D/OpScreenModeManager: setRefreshRate parent android.widget.FrameLayout{b4e9398 V.E...... ......ID 0,0-1080,2117 #7f08011f app:id/preview_display_layout} parent width 1080 parent height 2117 mRatio 1.2
    setRefreshRate view android.view.SurfaceView{e3c799e V.E...... ......ID 0,0-1080,2117} viewRate 1 width 1080 height 2117
    setRefreshRate token android.os.BinderProxy@95e76c1 rate 1 mCurrentRate 0 tmpRate:2
D/OpScreenModeManager: updateScenario fullScreen 1
D/Camera: Use case Preview:androidx.camera.core.Preview-9ca41d72-d52a-4870-adbb-d88d42f97b33 ACTIVE for camera 1
D/UseCaseAttachState: Active and online use case: [androidx.camera.core.Preview-9ca41d72-d52a-4870-adbb-d88d42f97b33] for camera: 1
D/Camera: CameraDevice.onOpened(): 1
D/Camera: Transitioning camera internal state: OPENING --> OPENED
D/UseCaseAttachState: All use case: [androidx.camera.core.Preview-9ca41d72-d52a-4870-adbb-d88d42f97b33] for camera: 1
D/OpScreenModeManager: setRefreshRate parent android.widget.FrameLayout{b4e9398 V.E...... ........ 0,0-1080,2117 #7f08011f app:id/preview_display_layout} parent width 1080 parent height 2117 mRatio 1.2
D/OpScreenModeManager: setRefreshRate view android.view.SurfaceView{e3c799e V.E...... ........ 0,0-1080,2117} viewRate 1 width 1080 height 2117
D/CaptureSession: Opening capture session.
D/CaptureSession: Attempting to send capture request onConfigured
    Issuing request for session.
D/CaptureSession: CameraCaptureSession.onConfigured() mState=OPENED
    CameraCaptureSession.onReady() OPENED
D/ExternalTextureConv: Created output texture: 2 width: 1080 height: 1080
I/native: I20210505 00:14:06.749358 28390 graph.cc:411] Start running the graph, waiting for inputs.
    I20210505 00:14:06.749524 28390 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I20210505 00:14:06.750743 28422 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 V@0502.0 (GIT@559e78c, Ib9d997268a, 1602617665) (Date:10/13/20))
I/native: I20210505 00:14:06.750871 28390 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I20210505 00:14:06.751957 28423 gl_context.cc:324] GL version: 3.2 (OpenGL ES 3.2 V@0502.0 (GIT@559e78c, Ib9d997268a, 1602617665) (Date:10/13/20))
W/native: W20210505 00:14:06.753552 28415 motion_analysis_calculator.cc:337] No input video header found. Downstream calculators expecting video headers are likely to fail.
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 28364 (mediapipe_gl_ru), pid 18645 (mple.pipetest3d)
D/ExternalTextureConv: Created output texture: 3 width: 1080 height: 1080
D/ExternalTextureConv: Created output texture: 4 width: 1080 height: 1080
D/ExternalTextureConv: Created output texture: 5 width: 1080 height: 1080
D/ExternalTextureConv: Created output texture: 6 width: 1080 height: 1080
D/ExternalTextureConv: Created output texture: 7 width: 1080 height: 1080
D/ExternalTextureConv: Created output texture: 8 width: 1080 height: 1080
D/ExternalTextureConv: Created output texture: 9 width: 1080 height: 1080

**Comment by jiuqiant** [comment]
Please assign this to the objectron owners. Thanks!

**Comment by jianingwei** [comment]
Is this specific to Objectron or is more generic? The error seems to be camera related.

**Comment by tilenpinta** [comment]
I think is Objectron related because this project is working: https://github.com/machidyo/MediaPipeHandTracking

**Comment by tilenpinta** [comment]
>  override fun surfaceChanged(

I think in previus comment that function is wrong. And it have to be something like that:
![image](https://user-images.githubusercontent.com/61638005/117985059-ac963e00-b338-11eb-9dc0-81281b2a205e.png)

But then I get error:
`A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 26810 (mediapipe_gl_ru), pid 23662 (e.pipetest3dv11)`

And if I change aar library to hand tracking and have this assets:
![image](https://user-images.githubusercontent.com/61638005/117985447-fed75f00-b338-11eb-8762-111d1ee58c38.png)

Then in build.gradle (app) set `def camerax_version = "1.0.0-alpha06"` from `def camerax_version = "1.1.0-alpha04"` and delete `camera-lifecycle` because alpha06 doesn't support it and if I try to run my app at alpha06 version I get error 
![image](https://user-images.githubusercontent.com/61638005/117986223-b3718080-b339-11eb-8545-7b9af7fa7309.png)

And in MainActivity.kt only change from 
`private val BINARY_GRAPH_NAME = "mobile_gpu_binary_graph.binarypb"` to 
`private val BINARY_GRAPH_NAME = "multihandtrackinggpu.binarypb"` hand tracking works.

So error should be in assets files. And all files I build and copy didn't change a thing. But maybe I missed out some files.

**Comment by atul109** [comment]
Objectron APK build from mediapipe 0.8.2 crashes with the above mentioned error `mediapipe_gl_ru `
where as 0.7.10 builds and runs without error, except the video is very zoomed in.
Somewhere in between 0.7.10 and 0.8.2 it is broken.

**Comment by jianingwei** [comment]
Can you verify the device where you find this crash (one-plus / huawei)? And is it crashing all the time?

**Comment by sgowroji** [comment]
Hi @tilenpinta, Could you please respond to the above [comment](https://github.com/google/mediapipe/issues/1977#issuecomment-856108111). Thanks!

**Comment by sgowroji** [comment]
Hi @tilenpinta, Did you get a chance to go through my above comment. Thanks!

**Comment by sgowroji** [comment]
We are closing this issue due to lack of activity.
