### ISSUE TITLE
Loading of posemodel stopped today - No EM_ASM constant found at address

### ISSUE THREAD

**Issue by larserikfinholt** [google/mediapipe#1993]
Today our app stopped working, it is an app that predicts coffee based on your face: https://www.kafferobot.no/app/

**Update:** 
This workaround https://github.com/google/mediapipe/issues/1989 also works for us:

![image](https://user-images.githubusercontent.com/1328417/117424386-05716b00-af22-11eb-94b3-61b5c374162d.png)

I assume this is a permanent change? So that we may keep this in our app?
**..end update..**

Error:
```
_app-a34486946e921ded2648.js:1 RuntimeError: abort(No EM_ASM constant found at address 553152) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:64180)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:64432)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:37792)
    at _emscripten_asm_const_int (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:177754)
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6985]:0x36c3e9
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6984]:0x36c1e3
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6983]:0x36c025
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6451]:0x33e4ed
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6199]:0x32f2a3
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6196]:0x32d9ed
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[6194]:0x32d580
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[256]:0xc900
    at https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.wasm:wasm-function[194]:0xaa1c
    at SolutionWasm$send [as send] (eval at new_ (https://cdn.jsdelivr.net/npm/@mediapipe/pose/pose_solution_wasm_bin.js:9:157521), <anonymous>:9:1)
    at h.h (https://www.kafferobot.no/app/_next/static/chunks/71247caf95475e3ea7f9a0f8a30beb258b23d005.bb30ca556f2d556c016e.js:1:473147)
```

Before that error, theres a lot of warnings:

![image](https://user-images.githubusercontent.com/1328417/117406864-fb457180-af0d-11eb-91ee-7a0fafae8630.png)

We're using  "@mediapipe/pose": "^0.2.1614787780" and also tried with todays version with no luck.

**Comment by sgowroji** [comment]
Hi @larserikfinholt, To prevent breaking changes from affecting your work, restrict your request to a <minor> number.  Please go through our [documentation](https://google.github.io/mediapipe/getting_started/javascript) to understand the implementation much better. Thanks!
