### ISSUE TITLE
add opencv_contrib module , How can I do it

### ISSUE THREAD

**Issue by zhaoqilong3031** [google/mediapipe#2024]

**Comment by rmothukuru** [comment]
@zhaoqilong3031,
Can you please elaborate your point? Please provide the reproducible code and the screenshots, if possible. Thanks!

**Comment by zhaoqilong3031** [comment]
@rmothukuru 
 Add the MCC(opencv_contrib) module, AAR can compile, but Android can't run


CODE
```
#include <opencv2/mcc.hpp>
.
.
.
 ::mediapipe::Status RepairColorCalculator::Process(CalculatorContext* cc) {
        LOG(INFO) << "ggg" << " mcccccccccc" ;
        
    if (cc->Inputs().Tag(kImageFrameTag).IsEmpty()) {
      return absl::OkStatus();
    }
    const auto& input_img = cc->Inputs().Tag(kImageFrameTag).Get<ImageFrame>();
    cv::Mat input_mat = formats::MatView(&input_img);
    cv::mcc::CCheckerDetector::create();

```
android error
```
2021-05-13 17:49:23.568 11835-11835/com.example.face E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.face, PID: 11835
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv3mcc16CCheckerDetector6createEv" referenced by "/data/app/com.example.face-HOF9clP71Ds4XKBhsmnBsw==/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.example.face.BaseActivity.<clinit>(BaseActivity.java:66)
        at java.lang.Class.newInstance(Native Method)
```

**Comment by jiuqiant** [comment]
MediaPipe uses the official prebuilt opencv android sdk (https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip) at https://github.com/google/mediapipe/blob/master/WORKSPACE#L225.

For having opencv-contrib, you probably need to build an opencv android sdk with opencv_contrib locally and replace the mediapipe android_opencv rule with something like the following:

```
new_local_repository(
    name = "android_opencv",
    build_file = "@//third_party:opencv_android.BUILD",
    path = "/path/to/your/local/opencv/android/sdk/with/opencv/contrib",
}
```

**Comment by zhaoqilong3031** [comment]
@jiuqiant 
I changed http_archive ，”opencv-4.5.2-android-sdk.zip“  Including the MCC


```
http_archive(
    name = "android_opencv",
    build_file = "@//third_party:opencv_android.BUILD",
    strip_prefix = "OpenCV-android-sdk",
    type = "zip",
    #url = "https://github.com/opencv/opencv/releases/download/4.5.2/opencv-4.5.2-android-sdk.zip",
    url = "https://my-repository.com/opencv-4.5.2-android-sdk.zip",
)
```

**Comment by jiuqiant** [comment]
Thanks for providing your solution!
