### ISSUE TITLE
FileNotFoundError: The path does not exist (solution_base.py, solutions\holistic.py)

### ISSUE THREAD

**Issue by Danil-e** [google/mediapipe#2050]
I can't execute the sample code.
Only the camera reacts - a connection is made (the indicator lights up), after which an exception is made.

```
_with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
  File "...\site-packages\mediapipe\python\solutions\holistic.py", line 121, in __init__
    'face_landmark'
  File "...\site-packages\mediapipe\python\solution_base.py", line 230, in __init__
    binary_graph_path=os.path.join(root_path, binary_graph_path))
FileNotFoundError: The path does not exist_
```

_File "...\site-packages\mediapipe\python\solutions\holistic.py", line 121, in __init___
_https://github.com/google/mediapipe/blob/ae05ad04b3ae43d475ccb2868e23f1418fea8746/mediapipe/python/solutions/holistic.py#L120_

```

import mediapipe as mp
import cv2

import cv2

print('Hi')
#cam = cv2.VideoCapture(0)
#cam = cv2.VideoCapture(0, cv2.cap_dshow)


mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic


mp_drawing.DrawingSpec(color=(0,0,255), thickness=2, circle_radius=2)
mp_drawing.draw_landmarks


#cap = cv2.VideoCapture(0)
#camera = cv2.VideoCapture(camera_port, cv2.CAP_DSHOW)
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW)


# Initiate holistic model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    while cap.isOpened():
        ret, frame = cap.read()
        
        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        # Make Detections
        results = holistic.process(image)
        # print(results.face_landmarks)
        
        # face_landmarks, pose_landmarks, left_hand_landmarks, right_hand_landmarks
        
        # Recolor image back to BGR for rendering
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        # 1. Draw face landmarks
        mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACE_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1),
                                 mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                                 )
        
        # 2. Right hand
        mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                                 )

        # 3. Left Hand
        mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                                 )

        # 4. Pose Detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                                 )
                        
        cv2.imshow('Raw Webcam Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()
```

**Comment by Danil-e** [comment]
Hi
Traceback (most recent call last):
  File "a.py", line 25, in <module>
    with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
  File "site-packages\mediapipe\python\solutions\holistic.py", line 105, in __init__
    'face_landmarks'
  File "site-packages\mediapipe\python\solution_base.py", line 221, in __init__
    binary_graph_path=os.path.join(root_path, binary_graph_path))
FileNotFoundError: The path does not exist.

**Comment by Danil-e** [comment]
Still not working...

**Comment by Danil-e** [comment]
Still not working...

**Comment by Danil-e** [comment]
No matter how he tried to get out of the impasse, the problem is not being solved in any way. In fact, the mediapipe package does not even start, since the program immediately crashes with an error. **It is still complicated by the fact that no similar problems and solutions have been found for others.**

**Comment by Clearwithme** [comment]
ı also have the same problem but still couldnt find the solution.

**Comment by sgowroji** [comment]
Hi @Danil-e, Did you try this [code](https://google.github.io/mediapipe/solutions/holistic.html#python-solution-api) for Holistic solution. And Could you please explain  your use case from above code.

**Comment by alibolun** [comment]
how to save it?I also ran into this problem.
