### ISSUE TITLE
SSLCertifiactionVerfication error while running below python samples in mediapipe

### ISSUE THREAD

**Issue by bhargav-sudo** [google/mediapipe#2108]
Hi,

I am facing issue when I am working on [pose](https://google.github.io/mediapipe/solutions/pose) , [holistic](https://google.github.io/mediapipe/solutions/holistic) and [objectron](https://google.github.io/mediapipe/solutions/objectron) 
**python samples.**

**Error facing :** 

Downloading model to /mediapipepythonexamples/mp_env1/lib/python3.7/site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite
Traceback (most recent call last):
  File "/usr/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mppose.py", line 10, in <module>
    min_detection_confidence=0.5) as pose:
  File "/mediapipepythonexamples/mp_env1/lib/python3.7/site-packages/mediapipe/python/solutions/pose.py", line 170, in __init__
    _download_oss_pose_landmark_model(model_complexity)
  File "/mediapipepythonexamples/mp_env1/lib/python3.7/site-packages/mediapipe/python/solutions/pose.py", line 133, in _download_oss_pose_landmark_model
    'mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite')
  File "/mediapipepythonexamples/mp_env1/lib/python3.7/site-packages/mediapipe/python/solutions/download_utils.py", line 32, in download_oss_model
    with urllib.request.urlopen(model_url) as response, open(model_abspath,
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>

Note : I am facing similar error for all the above examples that i mentioned.
I am getting output sucessfully to facedetection , facemesh and hands.

Python version : 3.7.10
OS : linux 18.04

I want to solve this issue.

Thanks,
Bhargav.K.

**Comment by bhargav-sudo** [comment]
I solved it by my self.
So I closed this issue..

Thanks,

**Comment by sgowroji** [comment]
Hi @bhargav-sudo, Thank you for letting us know your issue status. I appreciate if you contribute your solution to the community, Which will be helpful for other similar issue reporters.

**Comment by bhargav-sudo** [comment]
Yeah sure..

**Comment by bhargav-sudo** [comment]
Hi ,

We can solve the above error in 2 ways. First solution by clearing SSL certificate error and the other solution by commenting something which is not necessary.So , I choose the second option which is better for me to solve. 

**File "/mediapipepythonexamples/mp_env1/lib/python3.7/site-packages/mediapipe/python/solutions/pose.py", line 170, in init
_download_oss_pose_landmark_model(model_complexity)**

We are getting the error from above line..
If you follow the code in pose.py.
There is a function called "**_download_oss_pose_landmark_model**" (IN lINE NUM : 125)

It states that it **Downloads the pose landmark lite/heavy model from the MediaPipe Github repo if it doesn't exist in the package.**. 

So I already got that from repo. I don't need that. By commenting **line num 170** in pose.py file..

It will definetly work.

Thanks,

**Comment by sgowroji** [comment]
Try this also resolves the above issue https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

**Comment by bhargav-sudo** [comment]
@sgowroji I am using ubuntu.Not mac.
