### ISSUE TITLE
Switching from camera to video

### ISSUE THREAD

**Issue by congnguyenthe** [google/mediapipe#2151]
Hi,
I am trying to switch between using camera to local video on the pose tracking demo using AAR for Android. I have checked the issue #597 and related issues. However, I am having problems with closing the surface texture of the cameraxhelper. I have tried release the previewFrameTexture like but no luck:
```
try{
            previewFrameTexture.release();
            if(converter!=null)
                converter.close();
        }
        catch (Exception e){
            e.printStackTrace();
        }
```
It seems that there is a callback function for camera helper which wasn't clean properly but I don't know how to do it. Could any one suggest how to fix this problem?
Here is the exception log:
```
2021-06-10 00:43:48.110 16060-18467/com.example.robocoach D/DeferrableSurface: use count-1,  useCount=0 closed=false androidx.camera.core.SurfaceRequest$2@1a4c0cf
2021-06-10 00:43:48.111 16060-18467/com.example.robocoach D/DeferrableSurface: Surface no longer in use[total_surfaces=1, used_surfaces=0](androidx.camera.core.SurfaceRequest$2@1a4c0cf}
2021-06-10 00:43:48.116 16060-18467/com.example.robocoach E/SequentialExecutor: Exception while executing runnable CallbackListener,androidx.camera.camera2.internal.Camera2CameraImpl$2@4cec214
    java.lang.RuntimeException: java.lang.IllegalArgumentException: Surface was abandoned
        at androidx.camera.camera2.internal.Camera2CameraImpl$2.onFailure(Camera2CameraImpl.java:976)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:338)
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:229)
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:171)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Surface was abandoned
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:86)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:298)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:146)
        at androidx.camera.camera2.internal.compat.params.OutputConfigurationCompatApi28Impl.<init>(OutputConfigurationCompatApi28Impl.java:34)
        at androidx.camera.camera2.internal.compat.params.OutputConfigurationCompat.<init>(OutputConfigurationCompat.java:51)
        at androidx.camera.camera2.internal.CaptureSession.openCaptureSession(CaptureSession.java:317)
        at androidx.camera.camera2.internal.CaptureSession.lambda$open$0$CaptureSession(CaptureSession.java:209)
        at androidx.camera.camera2.internal.-$$Lambda$CaptureSession$kcuINqjMRDURH344KF0kxyqhnbw.apply(Unknown Source:8)
        at androidx.camera.core.impl.utils.futures.ChainingListenableFuture.run(ChainingListenableFuture.java:201)
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:229) 
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:171) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
        at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:73)
        at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:631)
        at android.hardware.camera2.utils.SurfaceUtils.getSurfaceSize(SurfaceUtils.java:84)
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:298) 
        at android.hardware.camera2.params.OutputConfiguration.<init>(OutputConfiguration.java:146) 
        at androidx.camera.camera2.internal.compat.params.OutputConfigurationCompatApi28Impl.<init>(OutputConfigurationCompatApi28Impl.java:34) 
        at androidx.camera.camera2.internal.compat.params.OutputConfigurationCompat.<init>(OutputConfigurationCompat.java:51) 
        at androidx.camera.camera2.internal.CaptureSession.openCaptureSession(CaptureSession.java:317) 
        at androidx.camera.camera2.internal.CaptureSession.lambda$open$0$CaptureSession(CaptureSession.java:209) 
        at androidx.camera.camera2.internal.-$$Lambda$CaptureSession$kcuINqjMRDURH344KF0kxyqhnbw.apply(Unknown Source:8) 
        at androidx.camera.core.impl.utils.futures.ChainingListenableFuture.run(ChainingListenableFuture.java:201) 
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:229) 
        at androidx.camera.core.impl.utils.executor.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:171) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by sgowroji** [comment]
Hi @congnguyenthe, Could you please provide your updated code changes in MainActivity. java of your android code repo.

**Comment by congnguyenthe** [comment]
Hi @sgowroji ,

Thanks for your response. Luckily I has found one working example for this issue:
https://github.com/afsaredrisy/MediapipeSegmentationGradle

I think it needs more tasks to be done than just changes the texture of the converter. I can follow above repo and let me close this issue.

Thanks again.
