### ISSUE TITLE
Android Hand Tracking example fails with: "dlopen failed: cannot locate symbol 'aligned_alloc'"

### ISSUE THREAD

**Issue by geckogecko** [google/mediapipe#2202]
I followed the Getting Started: [Installation](https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu) and [Hello World! on Android ](https://google.github.io/mediapipe/getting_started/hello_world_android.html#hello-world-on-android). But the Hand Tracking app crashes on my Huawei phone with: 

```
06-22 23:10:37.567 16744 16744 E AndroidRuntime: Process: com.google.mediapipe.apps.handtrackinggpu, PID: 16744
06-22 23:10:37.567 16744 16744 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "aligned_alloc" referenced by "/data/app/com.google.mediapipe.apps.handtrackinggpu-1/lib/arm64/libmediapipe_jni.so"...
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:994)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1533)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at com.google.mediapipe.apps.basic.MainActivity.<clinit>(MainActivity.java:59)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6517)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
06-22 23:10:37.567 16744 16744 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
06-22 23:10:37.702 16744 16744 I Process : Sending signal. PID: 16744 SIG: 9
```

**Other info**
- Ubuntu 19.10
- HUAWEI P9 (EVA-L09) with Android 7.0

**Comment by sgowroji** [comment]
Hi @geckogecko, Could you please try this https://github.com/google/mediapipe/issues/1224#issuecomment-745190852

**Comment by geckogecko** [comment]
Thank you that fixed it
