### ISSUE TITLE
IOS framework was built successfully, but no framework was found

### ISSUE THREAD

**Issue by ljmkimqx** [google/mediapipe#2224]
Hello, I successfully built the IOS framework (MacBook) with mediapipe half a year ago. 

Now I want to use the latest mediapipe to build the IOS framework, and the construction process is successful. 

But I can't find the framework file in the path "bazel bin / mediapipe / examples / IOS / handtrackinggpu", only ".a" file, such as "libhandtrackinggpuapplibrary.a".  

What's the problem? How can I get the framework.

The build file in the handtrackinggpu folder is as follows:
```
load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_framework",
)
load(
    "//mediapipe/examples/ios:bundle_id.bzl",
    "BUNDLE_ID_PREFIX",
    "example_provisioning",
)


licenses(["notice"])

MIN_IOS_VERSION = "10.0"

alias(
    name = "handtrackinggpu",
    actual = "HandTrackingGpuApp",
)

ios_framework(
    name = "HandTrackingGpuApp",
    bundle_id = "xxx.xxx.xxx.xxx",             （Hide information）
    families = [
        "iphone",
        "ipad",
    ],

    hdrs = [
        "HandTracker.h",
        "ManyOtherHandClass.h",
    ],

    infoplists = ["Info.plist"],
    minimum_os_version = MIN_IOS_VERSION,
    provisioning_profile = example_provisioning(),
    deps = [
        ":HandTrackingGpuAppLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)

#copts = ["-std=c++17"],

objc_library(
    name = "HandTrackingGpuAppLibrary",
    srcs = [
        "ManyOtherHandClass.m",
	"HandTracker.mm",
    ],
    hdrs = [
	"HandTracker.h",
        "ManyOtherHandClass.h",
    ],
    
    data = [
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu.binarypb",
        "//mediapipe/modules/hand_landmark:hand_landmark.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection.tflite",


        "//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu.binarypb",
        "//mediapipe/modules/face_detection:face_detection_short_range.tflite",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",
        "//mediapipe/modules/holistic_landmark:hand_recrop.tflite",
        "//mediapipe/modules/pose_detection:pose_detection.tflite",
        "//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",

    ],
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
        "UIKit",
    ],
    deps = [
       "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
            "//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps",
        ],
    }),
)
```

**Comment by sgowroji** [comment]
Hi @ljmkimqx, Did you try the above with latest release of IOS. If you still see the same error. Please provide the complete  steps to reproduce the above issue. Thanks!

**Comment by ljmkimqx** [comment]
This problem disappeared. I suspect it's because MAC installed two xcodes (11.6 and 12.5), so I deleted the Xcode of 11.6. Then the problem disappeared.

But if I download mediapipe again and build it with the following command, I will report an error.

```

bazel build -c opt --config=ios_ arm64 mediapipe/examples/ios/handtr ackinggpu:HandTrackingGpuAppLibrary

```

Error:

```
ERROR: /private/var/tmp/_bazel_ljm/db4283ef7dc11dcc5f964f68d2d19029/external/local_config_cc/BUILD:86:24: in cc_toolchain_config rule @local_config_cc//:darwin_x86_64: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ljm/db4283ef7dc11dcc5f964f68d2d19029/external/local_config_cc/cc_toolchain_config.bzl", line 2083, column 65, in _impl
		flags = _deterministic_libtool_flags(ctx) + [
	File "/private/var/tmp/_bazel_ljm/db4283ef7dc11dcc5f964f68d2d19029/external/local_config_cc/cc_toolchain_config.bzl", line 53, column 38, in _deterministic_libtool_flags
		if _can_use_deterministic_libtool(ctx):
	File "/private/var/tmp/_bazel_ljm/db4283ef7dc11dcc5f964f68d2d19029/external/local_config_cc/cc_toolchain_config.bzl", line 45, column 25, in _can_use_deterministic_libtool
		if _compare_versions(xcode_version, _SUPPORTS_DETERMINISTIC_MODE) >= 0:
	File "/private/var/tmp/_bazel_ljm/db4283ef7dc11dcc5f964f68d2d19029/external/local_config_cc/cc_toolchain_config.bzl", line 38, column 15, in _compare_versions
		return dv1.compare_to(apple_common.dotted_version(v2))
Error: 'NoneType' value has no field or method 'compare_to'
ERROR: While resolving configuration keys for @com_google_absl//absl/strings:strings: Analysis of target '@local_config_cc//:darwin_x86_64' failed
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary' failed; build aborted: Analysis of target '@local_config_cc//:darwin_x86_64' failed

```
I suspect it's the bazel version.

My version information is as follows:
```
Build label: 3.7.2
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 17:02:20 2020 (1608224540)
Build timestamp: 1608224540
Build timestamp as int: 1608224540

Mac OS: 11.4 Big sur

xcode: 12.5
```
Is there any solution?

**Comment by ljmkimqx** [comment]
I download mediapipe again and run the command
(I think I just need the framework, I don't need to configure IOS certificate)
```
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary
```

The results are as follows
```
INFO: From Executing genrule //mediapipe/modules/palm_detection:palm_detection_gpu_graph:
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 60:5: text format contains deprecated field "use_gpu"
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary up-to-date:
  bazel-bin/mediapipe/examples/ios/handtrackinggpu/libHandTrackingGpuAppLibrary.a
INFO: Elapsed time: 730.408s, Critical Path: 392.83s
INFO: 3079 processes: 311 internal, 2768 darwin-sandbox.
INFO: Build completed successfully, 3079 total actions
```
After compiling, there are only these files on the path "bazel bin / mediapipe / examples / IOS / handtrackinggpu":
```
_objs（folder）
HandTrackingGpuAppLibrary-archive.objlist
libHandTrackingGpuAppLibrary.a
```
This is the complete operation process.

Did I make a mistake? I forgot a little.

My environment:
```
Mac Os:  11.4  big sur
Xcode:    12.5
Bazel:      3.7.2

```

**Comment by ljmkimqx** [comment]
Hello, I can generate the framework now. （There are many contents below, but there should be only one practical problem）

But now I find a strange and important problem for me.

If I add one of these two sentences to the code, the compilation of the framework will fail

```
(1) mediapipe::MakePacket<int>(kNumHands);
(2) packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();
```
If I add code:   mediapipe::MakePacket<int>(kNumHands);
The error is:
```
ERROR: /Users/ljm/Downloads/mediapipe-master/mediapipe/examples/ios/handtrackinggpu/BUILD:35:14: Linking of rule '//mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework.__internal__.apple_binary' failed (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 400 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 400 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture arm64:
  "absl::lts_2020_09_23::InvalidArgumentError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::StatusOr<std::__1::vector<google::protobuf::MessageLite const*, std::__1::allocator<google::protobuf::MessageLite const*> > > mediapipe::packet_internal::ConvertToVectorOfProtoMessageLitePtrs<int>(int const*, std::__1::integral_constant<bool, false>) in libHandTrackingGpuAppLibrary.a(HandTracker.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.127s, Critical Path: 5.87s
INFO: 4 processes: 2 internal, 2 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

If I add code:   packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>()
The error is:  
```
ERROR: /Users/ljm/Downloads/mediapipe-master/mediapipe/examples/ios/handtrackinggpu/BUILD:35:14: Linking of rule '//mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework.__internal__.apple_binary' failed (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 400 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-stdlib=libc++' '-std=gnu++11' -arch arm64 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -framework OpenGLES -framework CoreVideo -framework ... (remaining 400 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture arm64:
  "absl::lts_2020_09_23::InternalError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<std::__1::vector<mediapipe::NormalizedLandmarkList, std::__1::allocator<mediapipe::NormalizedLandmarkList> > >() const in libHandTrackingGpuAppLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::strings_internal::CatPieces(std::initializer_list<absl::lts_2020_09_23::string_view>)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<std::__1::vector<mediapipe::NormalizedLandmarkList, std::__1::allocator<mediapipe::NormalizedLandmarkList> > >() const in libHandTrackingGpuAppLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::InvalidArgumentError(absl::lts_2020_09_23::string_view)", referenced from:
      absl::lts_2020_09_23::Status mediapipe::Packet::ValidateAsType<std::__1::vector<mediapipe::NormalizedLandmarkList, std::__1::allocator<mediapipe::NormalizedLandmarkList> > >() const in libHandTrackingGpuAppLibrary.a(HandTracker.o)
  "absl::lts_2020_09_23::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, absl::lts_2020_09_23::string_view)", referenced from:
      std::__1::vector<mediapipe::NormalizedLandmarkList, std::__1::allocator<mediapipe::NormalizedLandmarkList> > const& mediapipe::Packet::Get<std::__1::vector<mediapipe::NormalizedLandmarkList, std::__1::allocator<mediapipe::NormalizedLandmarkList> > >() const in libHandTrackingGpuAppLibrary.a(HandTracker.o)
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
Target //mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.017s, Critical Path: 5.76s
INFO: 4 processes: 2 internal, 2 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

If I don't add these two sentences of code, the result is successful compilation, as shown below:

```
INFO: Analyzed target //mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework up-to-date:
  bazel-bin/mediapipe/examples/ios/handtrackinggpu/Mediapipe_Framework.zip
  bazel-bin/mediapipe/examples/ios/handtrackinggpu/Mediapipe_Framework.framework.dSYM/Contents/Resources/DWARF/Mediapipe_Framework_arm64
  bazel-bin/mediapipe/examples/ios/handtrackinggpu/Mediapipe_Framework.framework.dSYM/Contents/Info.plist
INFO: Elapsed time: 29.670s, Critical Path: 29.42s
INFO: 9 processes: 2 internal, 4 darwin-sandbox, 3 local.
INFO: Build completed successfully, 9 total actions
```

I can't find the problem.

My configuration environment is as follows：

mediapipe/example/ios/handtrackinggpu  Build：
```
load(
    "@build_bazel_rules_apple//apple:ios.bzl",
    "ios_framework",
)
load(
    "//mediapipe/examples/ios:bundle_id.bzl",
    "BUNDLE_ID_PREFIX",
    "example_provisioning",
)


licenses(["notice"])

MIN_IOS_VERSION = "10.0"

alias(
    name = "mediapipe_Framework",
    actual = "Mediapipe_Framework",
)

ios_framework(
    name = "Mediapipe_Framework",
    bundle_id = "com.jixtech.acplay.multiHandTrack",
    families = [
        "iphone",
        "ipad",
    ],

    hdrs = [
        "HandTracker.h",
        "ManyOtherHandClass.h",
    ],
    
    infoplists = ["Info.plist"],
    minimum_os_version = MIN_IOS_VERSION,
    provisioning_profile = example_provisioning(),
    deps = [
        ":HandTrackingGpuAppLibrary",
        "@ios_opencv//:OpencvFramework",
    ],
)

#copts = ["-std=c++17"],

objc_library(
    name = "HandTrackingGpuAppLibrary",
    srcs = [
        "ManyOtherHandClass.m",
	"HandTracker.mm",
    ],
    hdrs = [
	"HandTracker.h",
        "ManyOtherHandClass.h",
    ],
    data = [
        "//mediapipe/graphs/hand_tracking:hand_tracking_mobile_gpu.binarypb",
        "//mediapipe/modules/hand_landmark:hand_landmark.tflite",
        "//mediapipe/modules/hand_landmark:handedness.txt",
        "//mediapipe/modules/palm_detection:palm_detection.tflite",


        "//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu.binarypb",
        "//mediapipe/modules/face_detection:face_detection_short_range.tflite",
        "//mediapipe/modules/face_landmark:face_landmark.tflite",
        "//mediapipe/modules/holistic_landmark:hand_recrop.tflite",
        "//mediapipe/modules/pose_detection:pose_detection.tflite",
        "//mediapipe/modules/pose_landmark:pose_landmark_full.tflite",

    ],
    sdk_frameworks = [
        "AVFoundation",
        "CoreGraphics",
        "CoreMedia",
	"CoreVideo",
        "UIKit",
    ],
    #copts = ["-std=c++17"],
    deps = [
       "//mediapipe/objc:mediapipe_framework_ios",
        "//mediapipe/objc:mediapipe_input_sources_ios",
        "//mediapipe/objc:mediapipe_layer_renderer",
    ] + select({
        "//mediapipe:ios_i386": [],
        "//mediapipe:ios_x86_64": [],
        "//conditions:default": [
            "//mediapipe/graphs/hand_tracking:mobile_calculators",
            "//mediapipe/framework/formats:landmark_cc_proto",
            "//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps",
        ],
    }),
)
```

HandTracker.mm
```
#import "HandTracker.h"
#import "mediapipe/objc/MPPCameraInputSource.h"
#import "mediapipe/objc/MPPGraph.h"
#import "mediapipe/objc/MPPLayerRenderer.h"
#import "mediapipe/objc/MPPPlayerInputSource.h"
#import "mediapipe/objc/MPPTimestampConverter.h"

#include "mediapipe/framework/formats/landmark.pb.h"


static NSString* const kGraphName = @"hand_tracking_mobile_gpu";

static const char* kInputStream = "input_video";
static const char* kOutputStream = "output_video";
//static const char* kVideoQueueLabel = "com.google.mediapipe.handTracker.videoQueue";
static const char* kLandmarksOutputStream = "hand_landmarks";
static const char* kNumHandsInputSidePacket = "num_hands";
static const int kNumHands = 2;

@interface HandTracker()

@property(nonatomic) MPPGraph* mediapipeGraph;

// Helps to convert timestamp.
@property(nonatomic) MPPTimestampConverter* timestampConverter;

@end

@implementation HandTracker

- (instancetype)init
{
    self = [super init];
    if (self) {
        self.timestampConverter = [[MPPTimestampConverter alloc] init];

        dispatch_queue_attr_t qosAttribute = dispatch_queue_attr_make_with_qos_class(
            DISPATCH_QUEUE_SERIAL, QOS_CLASS_USER_INTERACTIVE, /*relative_priority=*/0);
//        _videoQueue = dispatch_queue_create(kVideoQueueLabel, qosAttribute);

        self.mediapipeGraph = [[self class] loadGraphFromResource:kGraphName];
        self.mediapipeGraph.delegate = self;


        [self.mediapipeGraph addFrameOutputStream:kOutputStream
                                 outputPacketType:MPPPacketTypePixelBuffer];
        
//        const mediapipe::Packet aa; // add this can
//        mediapipe::MakePacket<int>(kNumHands); // 🍎 ####### error
        
//        [self.mediapipeGraph setSidePacket:(mediapipe::MakePacket<int>(kNumHands))
//                                     named:kNumHandsInputSidePacket];
        
        
        [self.mediapipeGraph addFrameOutputStream:kLandmarksOutputStream
                                 outputPacketType:MPPPacketTypeRaw];
        
    }
    return self;
}

+ (MPPGraph*)loadGraphFromResource:(NSString*)resource {
  // Load the graph config resource.
  NSError* configLoadError = nil;
  NSBundle* bundle = [NSBundle bundleForClass:[self class]];
  if (!resource || resource.length == 0) {
    return nil;
  }
  NSURL* graphURL = [bundle URLForResource:resource withExtension:@"binarypb"];
  NSData* data = [NSData dataWithContentsOfURL:graphURL options:0 error:&configLoadError];
  if (!data) {
    NSLog(@"Failed to load MediaPipe graph config: %@", configLoadError);
    return nil;
  }

  // Parse the graph config resource into mediapipe::CalculatorGraphConfig proto object.
  mediapipe::CalculatorGraphConfig config;
  config.ParseFromArray(data.bytes, data.length);

  // Create MediaPipe graph with mediapipe::CalculatorGraphConfig proto object.
  MPPGraph* newGraph = [[MPPGraph alloc] initWithGraphConfig:config];
  return newGraph;
}



#pragma mark - MPPInputSourceDelegate methods
- (void)processVideoFrame:(CVPixelBufferRef)imageBuffer timestamp:(CMTime)timestamp{

  [self.mediapipeGraph sendPixelBuffer:imageBuffer
                            intoStream:kInputStream
                            packetType:MPPPacketTypePixelBuffer
                             timestamp:[self.timestampConverter timestampForMediaTime:timestamp]];
}

#pragma mark - MPPGraphDelegate methods

- (void)mediapipeGraph:(MPPGraph*)graph
    didOutputPixelBuffer:(CVPixelBufferRef)pixelBuffer
              fromStream:(const std::string&)streamName {
  if (streamName == kOutputStream) {
    // Display the captured image on the screen.
      CVPixelBufferRetain(pixelBuffer);
      [_delegate handTracker:self didOutputPixelBuffer: pixelBuffer];
      CVPixelBufferRelease(pixelBuffer);
  }
}



#pragma mark - MPPGraphDelegate methods

// Receives a raw packet from the MediaPipe graph. Invoked on a MediaPipe worker thread.
- (void)mediapipeGraph:(MPPGraph*)graph
     didOutputPacket:(const ::mediapipe::Packet&)packet
          fromStream:(const std::string&)streamName {
    if (streamName == kLandmarksOutputStream) {
        
        if (packet.IsEmpty()) { return; }
//        const ::mediapipe::NormalizedLandmarkList aa;
//        const std::vector<::mediapipe::NormalizedLandmarkList> aa;
        
//        packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();  // 🍎 ####### error
  }
}


@end
```

In "objc_library" configuration, I annotated "copts = ["-std=c++17"]", because the following error will be reported after adding it:
```
ERROR: /Users/ljm/Downloads/mediapipe-master/mediapipe/examples/ios/handtrackinggpu/BUILD:59:13: C++ compilation of rule '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuAppLibrary' failed (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang -arch arm64 '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' ... (remaining 194 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang -arch arm64 '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' ... (remaining 194 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
error: invalid argument '-std=c++17' not allowed with 'Objective-C'
Target //mediapipe/examples/ios/handtrackinggpu:Mediapipe_Framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.134s, Critical Path: 0.77s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
```

I spent a lot of time looking for problems, because it was only one step away from success. But I can't find the problem. I hope I can get help. Thank you @sgowroji

**Comment by ljmkimqx** [comment]
I found the same error reporting problem #2147

**Comment by mohammedbalegh** [comment]
adding libc++ framework in target -> general -> frameworks, and in target -> build phases -> link binary with libraries .
fixed it for me.

**Comment by ljmkimqx** [comment]
I haven't solved it yet

**Comment by ozgurshn** [comment]
Adding  copts = ["-std=c++17"]  to the obj_library solved this problem in my case.

**Comment by sgowroji** [comment]
Hi @ljmkimqx, Could you please try the above https://github.com/google/mediapipe/issues/2224#issuecomment-877145750

**Comment by ljmkimqx** [comment]
I finally found the problem. Add   copts = ["-std=c++17"]    and    visibility = ["//mediapipe:__subpackages__"]      to objc_library. I lack to add      visibility = ["//mediapipe:__subpackages__"].
