### ISSUE TITLE
Pose Tracking (GPU) and Holistic Tracking (GPU) crash on Linux

### ISSUE THREAD

**Issue by homuler** [google/mediapipe#2251]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Arch Linux (version 5.12.13-arch1-2 (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1))
- Programming Language and version ( e.g. C++, Python, Java): C++ (gcc (Arch Linux 10.2.0-3) 10.2.0
, g++ (Arch Linux 10.2.0-3) 10.2.0)
- [MediaPipe version](https://github.com/google/mediapipe/releases): v0.8.6
- Bazel version (if compiling from source): 3.7.2 (downloaded)
- Solution ( e.g. FaceMesh, Pose, Holistic ): Pose, Holistic

**Describe the current behavior:**
Pose Tracking (GPU) and Holistic Tracking (GPU) examples crash.

**Describe the expected behavior:**
Pose Tracking (GPU) and Holistic Tracking (GPU) examples work on Linux.

**Standalone code to reproduce the issue:**
Build with the below command
```sh
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 //mediapipe/examples/desktop/pose_tracking:pose_tracking_gpu
```

and run
```sh
GLOG_logtostderr=1 ./bazel-bin/mediapipe/examples/desktop/pose_tracking/pose_tracking_gpu --calculator_graph_config_file=mediapipe/graphs/pose_tracking/pose_tracking_gpu.pbtxt
```

**Other info / Complete Logs :**
```txt
I20210704 19:24:31.353058 139303 demo_run_graph_main_gpu.cc:52] Get calculator graph config contents: # Tracks and renders pose + hands + face landmarks.

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

# GPU image with rendered results. (GpuBuffer)
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
      max_in_queue: 1
      # Timeout is disabled (set to 0) as first frame processing can take more
      # than 1 second.
      in_flight_timeout: 0
    }
  }
}

node {
  calculator: "HolisticLandmarkGpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "POSE_LANDMARKS:pose_landmarks"
  output_stream: "POSE_ROI:pose_roi"
  output_stream: "POSE_DETECTION:pose_detection"
  output_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  output_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
}

# Gets image size.
node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "SIZE:image_size"
}

# Converts pose, hands and face landmarks to a render data vector.
node {
  calculator: "HolisticTrackingToRenderData"
  input_stream: "IMAGE_SIZE:image_size"
  input_stream: "POSE_LANDMARKS:pose_landmarks"
  input_stream: "POSE_ROI:pose_roi"
  input_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  input_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
  input_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "RENDER_DATA_VECTOR:render_data_vector"
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "VECTOR:render_data_vector"
  output_stream: "IMAGE_GPU:output_video"
}
I20210704 19:24:31.353782 139303 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20210704 19:24:31.364363 139303 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20210704 19:24:31.371229 139303 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210704 19:24:31.405195 139328 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 465.31)
I20210704 19:24:31.405292 139303 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
[ WARN:0] OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
I20210704 19:24:35.707214 139303 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20210704 19:24:35.711666 139303 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
I20210704 19:24:35.800426 139328 tflite_gpu_runner.cc:142] OpenCL backend is used.
fish: Job 1, 'GLOG_logtostderr=1 ./bazel-bin/…' terminated by signal SIGSEGV (Address boundary error)
```

backtraces (rebuilt with `--compilation_mode=dbg`)
```txt
#0  0x000055a5636af4cd in tflite::gpu::TFLiteGPURunner::Build() (this=0x7fe9640b4060) at mediapipe/util/tflite/tflite_gpu_runner.cc:155
#1  0x000055a56341209b in mediapipe::api2::InferenceCalculatorGlImpl::InitTFLiteGPURunner(mediapipe::CalculatorContext*) (this=0x55a56478bf10, cc=0x55a564929130)
    at mediapipe/calculators/tensor/inference_calculator_gl.cc:287
#2  0x000055a563410369 in operator()() const (__closure=0x7fe9640ab608) at mediapipe/calculators/tensor/inference_calculator_gl.cc:118
#3  0x000055a56341401c in std::__invoke_impl<absl::lts_2020_09_23::Status, mediapipe::api2::InferenceCalculatorGlImpl::Open(mediapipe::CalculatorContext*)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:60
#4  0x000055a563413972 in std::__invoke_r<absl::lts_2020_09_23::Status, mediapipe::api2::InferenceCalculatorGlImpl::Open(mediapipe::CalculatorContext*)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:115
#5  0x000055a563413454 in std::_Function_handler<absl::lts_2020_09_23::Status(), mediapipe::api2::InferenceCalculatorGlImpl::Open(mediapipe::CalculatorContext*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:292
#6  0x000055a5638167a3 in std::function<absl::lts_2020_09_23::Status ()>::operator()() const (this=0x7fe9640ab608)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:622
#7  0x000055a5639e56c0 in operator()() const (__closure=0x7fe9640ab600) at mediapipe/gpu/gl_context.cc:403
#8  0x000055a5639e96a4 in std::__invoke_impl<absl::lts_2020_09_23::Status, mediapipe::GlContext::Run(mediapipe::GlStatusFunction, int, mediapipe::Timestamp)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:60
#9  0x000055a5639e8c0c in std::__invoke_r<absl::lts_2020_09_23::Status, mediapipe::GlContext::Run(mediapipe::GlStatusFunction, int, mediapipe::Timestamp)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:115
#10 0x000055a5639e812a in std::_Function_handler<absl::lts_2020_09_23::Status(), mediapipe::GlContext::Run(mediapipe::GlStatusFunction, int, mediapipe::Timestamp)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:292
#11 0x000055a5638167a3 in std::function<absl::lts_2020_09_23::Status ()>::operator()() const (this=0x7fe9a17f9510)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:622
#12 0x000055a5639e4066 in mediapipe::GlContext::DedicatedThread::Run(std::function<absl::lts_2020_09_23::Status ()>) (this=0x55a5646c41f0, gl_func=...)
    at mediapipe/gpu/gl_context.cc:147
#13 0x000055a5639e5868 in mediapipe::GlContext::Run(std::function<absl::lts_2020_09_23::Status ()>, int, mediapipe::Timestamp)
    (this=0x55a56467ac10, gl_func=..., node_id=10, input_timestamp=...) at mediapipe/gpu/gl_context.cc:406
#14 0x000055a56391e565 in mediapipe::GlCalculatorHelperImpl::RunInGlContext(std::function<absl::lts_2020_09_23::Status ()>, mediapipe::CalculatorContext*)
    (this=0x7fe9640ab5d0, gl_func=..., calculator_context=0x55a564929130) at mediapipe/gpu/gl_calculator_helper_impl_common.cc:61
#15 0x000055a56391b47b in mediapipe::GlCalculatorHelper::RunInGlContext(std::function<absl::lts_2020_09_23::Status ()>) (this=0x55a56478bf68, gl_func=...)
    at mediapipe/gpu/gl_calculator_helper.cc:100
#16 0x000055a5634106b3 in mediapipe::api2::InferenceCalculatorGlImpl::Open(mediapipe::CalculatorContext*) (this=0x55a56478bf10, cc=0x55a564929130)
    at mediapipe/calculators/tensor/inference_calculator_gl.cc:118
#17 0x000055a5639bd07b in mediapipe::CalculatorNode::OpenNode() (this=0x55a564634850) at mediapipe/framework/calculator_node.cc:501
#18 0x000055a56399fa04 in mediapipe::internal::SchedulerQueue::OpenCalculatorNode(mediapipe::CalculatorNode*) (this=0x55a5647f0f30, node=0x55a564634850)
    at mediapipe/framework/scheduler_queue.cc:287
#19 0x000055a56399ed13 in mediapipe::internal::SchedulerQueue::RunNextTask() (this=0x55a5647f0f30) at mediapipe/framework/scheduler_queue.cc:215
#20 0x000055a56399d8b5 in mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}::operator()() const (__closure=0x55a564739f58)
    at ./mediapipe/framework/executor.h:60
#21 0x000055a56399dcb4 in std::__invoke_impl<void, mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}&>(std::__invoke_other, mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}&) (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:60
#22 0x000055a56399dba4 in std::__invoke_r<void, mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}&>(mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}&) (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:110
#23 0x000055a56399da96 in std::_Function_handler<void (), mediapipe::Executor::AddTask(mediapipe::TaskQueue*)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
    (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:291
#24 0x000055a56368fe40 in std::function<void ()>::operator()() const (this=0x55a564739f58) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:622
--Type <RET> for more, q to quit, c to continue without paging--
#25 0x000055a5639e59e3 in operator()() const (__closure=0x55a564739f40) at mediapipe/gpu/gl_context.cc:419
#26 0x000055a5639e97ea in std::__invoke_impl<void, mediapipe::GlContext::RunWithoutWaiting(mediapipe::GlVoidFunction)::<lambda()>&>(std::__invoke_other, struct {...} &)
    (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:60
#27 0x000055a5639e8daf in std::__invoke_r<void, mediapipe::GlContext::RunWithoutWaiting(mediapipe::GlVoidFunction)::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/invoke.h:110
#28 0x000055a5639e8219 in std::_Function_handler<void(), mediapipe::GlContext::RunWithoutWaiting(mediapipe::GlVoidFunction)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:291
#29 0x000055a56368fe40 in std::function<void ()>::operator()() const (this=0x7fe9a17f9b20) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/bits/std_function.h:622
#30 0x000055a5639e3ea0 in mediapipe::GlContext::DedicatedThread::ThreadBody() (this=0x55a5646c41f0) at mediapipe/gpu/gl_context.cc:134
#31 0x000055a5639e3e32 in mediapipe::GlContext::DedicatedThread::ThreadBody(void*) (instance=0x55a5646c41f0) at mediapipe/gpu/gl_context.cc:109
#32 0x00007fe9e18e7259 in start_thread () at /usr/lib/libpthread.so.0
#33 0x00007fe9e17c75e3 in clone () at /usr/lib/libc.so.6
```

If `InferenceCalculatorGl` is configured to use advanced gpu api (i.e. `delegate: { gpu { use_advanced_gpu_api: true } }`), `TFLiteGPURunner` will be built.
https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/calculators/tensor/inference_calculator_gl.cc#L120

`TFLiteGPURunner` tries to build OpenCL first and this will always success because `InitializeOpenCL` simply returns `mediapipe::OkStatus()` on machines other than Android devices.
https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/util/tflite/tflite_gpu_runner.cc#L139-L140

However, `InferenceBuilder` is not initialized actually, so the program will crash at the below line (`builder` points to null pointer).
https://github.com/google/mediapipe/blob/374f5e2e7e818bde5289fb3cffa616705cec6f73/mediapipe/util/tflite/tflite_gpu_runner.cc#L155

`PoseDetectionGpu` is configured to use advanced gpu api, so calculators that use `PoseDetectionGpu` internally does not work on Linux now.

**Comment by willstott101** [comment]
I've come across this on Ubuntu 18, the suggested patch at https://github.com/google/mediapipe/issues/2170#issuecomment-877734150 allowed me to build and use pose tracking gpu example

**Comment by LKay42** [comment]
I'm running into the exact same problem on Ubuntu 21.04. The suggested one line patch from #2170 fixed it for me as well. Please  consider including the patch in the next version.

**Comment by mcclanahoochie** [comment]
https://github.com/google/mediapipe/pull/2463 has been merged upstream, thanks
