### ISSUE TITLE
don't run example "mediapipe_multi_hands_tracking_aar_example" with file build arr in a tutorial "android_archive_library"

### ISSUE THREAD

**Issue by thaiph99** [google/mediapipe#2255]
**System information**
- OS : Ubuntu 20.04 LTS
- Compiler version : g++ 9.3
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.6
- Bazel version: 3.7.2
- Android SDK and NDK versions: SDK 29, NDK 20
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) : ediapipe_face_detection.aar

**Describe the problem**:
- I can run an app with origin example project but I run with file build AAR (mediapipe 0.8.6)  this app was crashed
- Follow step by [tutorial](https://google.github.io/mediapipe/getting_started/android_archive_library.html) to build aar and binarypb
- Move a file aar, binarypb, tflite into [project example](https://github.com/jiuqiant/mediapipe_face_detection_aar_example)
- run the project on the device !!!
- And crashed :'(

**Complete Logs:**
2021-07-05 15:23:35.814 2611-2611/? I/acedetectionap: Late-enabling -Xcheck:jni
2021-07-05 15:23:35.849 2611-2611/? E/acedetectionap: Unknown bits set in runtime_flags: 0x8000
2021-07-05 15:23:35.867 2611-2611/? D/ActivityThread: setConscryptValidator
2021-07-05 15:23:35.867 2611-2611/? D/ActivityThread: setConscryptValidator - put
2021-07-05 15:23:36.455 2611-2611/com.example.myfacedetectionapp D/AndroidRuntime: Shutting down VM
2021-07-05 15:23:36.458 2611-2611/com.example.myfacedetectionapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myfacedetectionapp, PID: 2611
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.myfacedetectionapp-MCt9M-VGw6ldr1fUeEi9ZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myfacedetectionapp-MCt9M-VGw6ldr1fUeEi9ZQ==/lib/arm, /system/lib]]] couldn't find "libmediapipe_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.example.myfacedetectionapp.MainActivity.<clinit>(MainActivity.java:54)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3436)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by sgowroji** [comment]
Hi @thaiph99, Above [AAR](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/libs/mp_multi_hand_aar.aar) only has files for android arm64 v8a. It doesn’t support android armeabi v7a. Please verify before running on supported device.

**Comment by thaiph99** [comment]
> Hi @thaiph99, Above [AAR](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/blob/master/app/libs/mp_multi_hand_aar.aar) only has files for android arm64 v8a. It doesn’t support android armeabi v7a. Please verify before running on supported device.

Thank you, I will check and test again.

**Comment by sgowroji** [comment]
@thaiph99 Reach us back on the same ticket, if you have any further relevant queries. We are closing this issue now.
