### ISSUE TITLE
Fail when build Hello World, please help!

### ISSUE THREAD

**Issue by camvinh** [google/mediapipe#2279]
There is error message, I want to build it on Windows

ERROR: Traceback (most recent call last):
        File "C:/users/jinrong/_bazel_jinrong/z6v6dmmp/external/build_bazel_rules_apple/apple/internal/testing/ios_rules.bzl", line 63, column 71, in <toplevel>
                _ios_internal_ui_test_bundle = rule_factory.create_apple_bundling_rule(
        File "C:/users/jinrong/_bazel_jinrong/z6v6dmmp/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 955, column 55, in _create_apple_bundling_rule
                rule_attrs.append(_common_binary_linking_attrs(rule_descriptor))
        File "C:/users/jinrong/_bazel_jinrong/z6v6dmmp/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl", line 233, column 21, in _common_binary_linking_attrs
                apple_common.objc_proto_aspect,
Error: 'apple_common' value has no field or method 'objc_proto_aspect'
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: error loading package 'mediapipe/gpu': at C:/users/jinrong/_bazel_jinrong/z6v6dmmp/external/build_bazel_rules_apple/apple/ios.bzl:22:5: initialization of module 'apple/internal/testing/ios_rules.bzl' failed
INFO: Elapsed time: 4.590s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (47 packages loaded, 200 targets configured)
    currently loading: mediapipe/gpu
    Fetching @com_google_absl; fetching
    Fetching ...e_absl; Extracting C:/users/jinrong/_bazel_jinrong/z6v6dmmp/external/com_google_absl/temp2567789691540\
78119/20200923.tar.gz

**Comment by sgowroji** [comment]
Please try this https://github.com/google/mediapipe/issues/2065#issuecomment-847188247

**Comment by sgowroji** [comment]
Hi @camvinh, Could you please try this `bazel clean --expunge` and rerun the above would resolve your error. Thanks!
