### ISSUE TITLE
Generate signed apk with minifyEnabled (Proguard, R8) carshes in android studio

### ISSUE THREAD

**Issue by jaywalk1414** [google/mediapipe#2283]
I'm trying to generate signed apk (release type) with Gradle. The project uses an AAR library that in debug build works absolutely fine. Generally it is a customized Face Effect of MediaPipe that gets inputs from android-Java and in processor.setOnWillAddFrameListener send it with help of packets to the graphs(ex. to changing colors suddenly). 

my proguard-rules.pro is:
`-keep class com.google.mediapipe.components.* {*;}
-keep class com.google.mediapipe.framework.* {*;}
-keep class com.google.mediapipe.glutil.* {*;}
-keep class com.google.mediapipe.proto.* {*;}
-keep class com.google.mediapipe.formats.proto.* {*;}
-keep class com.google.mediapipe.formats.annotation.proto.* {*;}
-keep class com.google.common.flogger.* {*;}
-keep class android.view.SurfaceHolder {*;}
-keep class android.view.SurfaceView {*;}

-keep public interface com.google.mediapipe.framework.* {
  public *;
}

-keep public class com.google.mediapipe.framework.Packet {
  public static *** create(***);
  public long getNativeHandle();
  public void release();
}

-keep public class com.google.mediapipe.framework.PacketCreator {
  *** releaseWithSyncToken(...);
}

-keep public class com.google.mediapipe.framework.MediaPipeException {
  <init>(int, byte[]);
}

-keep class com.google.mediapipe.framework.ProtoUtil$SerializedMessage { *; }`

and my logcat is:
`2021-07-13 12:07:44.620 13072-13072/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.azimuth.negar.acebina, PID: 13072
    java.lang.ExceptionInInitializerError
        at com.google.mediapipe.components.FrameProcessor.initializeGraphAndPacketCreator(FrameProcessor.java:1)
        at com.google.mediapipe.components.FrameProcessor.<init>(FrameProcessor.java:6)
        at org.azimuth.negar.acebina.ui.mediaPipe.MpActivity.onCreate(MpActivity.java:18)
        at org.azimuth.negar.acebina.ui.mediaPipe.MpExtendedActivity.onCreate(MpExtendedActivity.java:1)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: no caller found on the stack for: com.google.common.flogger.FluentLogger
        at com.google.common.flogger.FluentLogger.forEnclosingClass(FluentLogger.java:10)
        at com.google.mediapipe.framework.Graph.<clinit>(Graph.java:1)
        at com.google.mediapipe.components.FrameProcessor.initializeGraphAndPacketCreator(FrameProcessor.java:1) 
        at com.google.mediapipe.components.FrameProcessor.<init>(FrameProcessor.java:6) 
        at org.azimuth.negar.acebina.ui.mediaPipe.MpActivity.onCreate(MpActivity.java:18) 
        at org.azimuth.negar.acebina.ui.mediaPipe.MpExtendedActivity.onCreate(MpExtendedActivity.java:1) 
        at android.app.Activity.performCreate(Activity.java:8198) 
        at android.app.Activity.performCreate(Activity.java:8182) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8506) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) `

P.s: I tried one more thing that if I put the line below in my proguard-rules.pro, it is working fine but that is not what I am exactly looking for it. I wish my whole app be protected by obfuscating.
`-keep class * {*;}`

**Comment by AzureRain1** [comment]
The crash comes from FluentLogger which is a Google looger module. My workaround is just to remove those and use the Android syste logging instead.

**Comment by sgowroji** [comment]
Hi  @jaywalk1414, could you please provide your code changes to understand the issue much better. Thanks!

**Comment by jaywalk1414** [comment]
Hello @sgowroji, Which part do you mean exactly?

**Comment by jaywalk1414** [comment]
@AzureRain1 thanks!!! The problem is solved.

**Comment by sgowroji** [comment]
Hi @jaywalk1414, I was expecting some changes in your Proguard file. Glad to know you resolved. Could you please post the solution, That will help the community if the encounter similar problem.

**Comment by AzureRain1** [comment]
@sgowroji I assume he used my workaround, but what I described is a workaround not a solution. This should be properly fixed on Google side. Let me know if you need more information.

**Comment by brucechou1983** [comment]
@sgowroji I met the same problem yesterday and solved the issue by @AzureRain1 's workaround. But I didn't find a way to solve it by modifying the proguard file.

**Comment by tri-bao** [comment]
The same problem happened to me. After much tries, the following Proguard rule seems to work for me

```
-keep class * extends com.google.common.flogger.backend.Platform$LogCallerFinder
```

**Comment by emad-eldeen** [comment]
> The same problem happened to me. After much tries, the following Proguard rule seems to work for me
> 
> ```
> -keep class * extends com.google.common.flogger.backend.Platform$LogCallerFinder
> ```

For me, this worked:
`-keep class * extends com.google.common.flogger.** {*;}`
