### ISSUE TITLE
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid

### ISSUE THREAD

**Issue by edib** [google/mediapipe#2306]
Ubuntu 20.04 
Mediapipe 0.8.6
python 3.8 
The following code was running in my computer a week ago:

```
import cv2
import mediapipe as mp
import time

mpDraw = mp.solutions.drawing_utils
mpPose = mp.solutions.pose
pose = mpPose.Pose()

cap = cv2.VideoCapture(1)
pTime = 0
while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(imgRGB)
    # print(results.pose_landmarks)
    if results.pose_landmarks:
        mpDraw.draw_landmarks(img, results.pose_landmarks, mpPose.POSE_CONNECTIONS)
        for id, lm in enumerate(results.pose_landmarks.landmark):
            h, w, c = img.shape
            print(id, lm)
            cx, cy = int(lm.x * w), int(lm.y * h)
            cv2.circle(img, (cx, cy), 5, (255, 0, 0), cv2.FILLED)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (70, 50), cv2.FONT_HERSHEY_PLAIN, 3,
                (255, 0, 0), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)

```
Last week this code is working. But now, produces below error:

```
Traceback (most recent call last):
  File "Basics.py", line 7, in <module>
    pose = mpPose.Pose()
  File "/home/user/.local/lib/python3.8/site-packages/mediapipe/python/solutions/pose.py", line 171, in __init__
    super().__init__(
  File "/home/user/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 229, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:posedetectioncpu__Inferencecalculator__posedetectioncpu__input_tensors" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").`

```
I have reinstall the mediapipe in systemwide, the results have not changed. 
I also have tried it in jupyter notebook. The error is produced when I run below codes 
```
pose = mpPose.Pose() 

```

**Comment by sgowroji** [comment]
Hi @edib, How are you passing the image?   Try checking [this](https://google.github.io/mediapipe/solutions/pose#python-solution-api)
