### ISSUE TITLE
Multiprocessing bug - FaceMesh works for a while, but then hangs / gives error

### ISSUE THREAD

**Issue by sradc** [google/mediapipe#2323]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): yes, but not much
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: n/a
- Programming Language and version ( e.g. C++, Python, Java): Python 3.8.10
- [MediaPipe version](https://github.com/google/mediapipe/releases): MediaPipe 0.8.6
- Bazel version (if compiling from source): n/a
- Solution ( e.g. FaceMesh, Pose, Holistic ): FaceMesh
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): n/a
- Xcode & Tulsi version (if issue is related to building for iOS): n/a

**Describe the current behavior:**

FaceMesh works well at first with multiple workers, but eventually some of the workers hang, and an error is printed.

**Describe the expected behavior:**

FaceMesh continues to work well without hanging. Get a speed up of >10x from multiprocessing, it's unfortunate that it mostly works, but not quite.

**Standalone code to reproduce the issue:**

```python
import mediapipe as mp
from multiprocessing import Pool, cpu_count
import numpy as np


N = 100_000  
# Number of "images" each process will run for.
# Pick a large number, so it runs until the crash.


def process_landmarks(id):
    with mp.solutions.face_mesh.FaceMesh(
        static_image_mode=True, max_num_faces=1, min_detection_confidence=0.75
    ) as face_mesh:
        fake_image = np.random.randint(0, 255, [500, 500, 3], np.uint8)
        for i in range(N):
            landmarks = face_mesh.process(fake_image)
            print(f"Process {id}: Completed {i} images, {100 * i / N:.5}%")
        print(f"Process {id}: finished.")


def main():
    num_workers = cpu_count()  # 12 for me
    assert num_workers > 1, "Need more than 1 worker to reproduce the bug (I think)"
    pool = Pool(processes=num_workers)
    pool.map(process_landmarks, [i for i in range(num_workers)])


if __name__ == "__main__":
    main()
```

```shell
$ time python multiprocessing_mediapipe.py > output.txt
```

**Other info / Complete Logs :**

```
INFO: INFO: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
terminate called after throwing an instance of 'std::runtime_error'
  what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance!
terminate called after throwing an instance of 'std::runtime_error'
  what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance!
```

Then I inputted `^C`:

```
^CProcess ForkPoolWorker-19:
Process ForkPoolWorker-18:
Process ForkPoolWorker-13:
Process ForkPoolWorker-15:
Process ForkPoolWorker-16:
Process ForkPoolWorker-17:
Process ForkPoolWorker-14:
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "multiprocessing_mediapipe.py", line 28, in <module>
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
    main()
  File "multiprocessing_mediapipe.py", line 24, in main
    pool.map(process_landmarks, [i for i in range(num_workers)])
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 762, in wait
Process ForkPoolWorker-10:
Process ForkPoolWorker-3:
Process ForkPoolWorker-5:
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "multiprocessing_mediapipe.py", line 15, in process_landmarks
    landmarks = face_mesh.process(fake_image)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 238, in process
    return super().process(input_data={'image': image})
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 318, in process
    self._graph.wait_until_idle()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "multiprocessing_mediapipe.py", line 15, in process_landmarks
    landmarks = face_mesh.process(fake_image)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 238, in process
    return super().process(input_data={'image': image})
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 318, in process
    self._graph.wait_until_idle()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "multiprocessing_mediapipe.py", line 15, in process_landmarks
    landmarks = face_mesh.process(fake_image)
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 238, in process
    return super().process(input_data={'image': image})
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 318, in process
    self._graph.wait_until_idle()
KeyboardInterrupt
Process ForkPoolWorker-9:
    self._event.wait(timeout)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/threading.py", line 302, in wait
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "multiprocessing_mediapipe.py", line 15, in process_landmarks
    landmarks = face_mesh.process(fake_image)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 238, in process
    return super().process(input_data={'image': image})
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 318, in process
    self._graph.wait_until_idle()
KeyboardInterrupt
Process ForkPoolWorker-12:
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "multiprocessing_mediapipe.py", line 15, in process_landmarks
    landmarks = face_mesh.process(fake_image)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 238, in process
    return super().process(input_data={'image': image})
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 307, in process
    self._graph.add_packet_to_input_stream(
KeyboardInterrupt
    waiter.acquire()
KeyboardInterrupt
^CProcess ForkPoolWorker-24:
Process ForkPoolWorker-26:
Process ForkPoolWorker-20:
Process ForkPoolWorker-25:
Process ForkPoolWorker-22:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
Process ForkPoolWorker-21:
    finalizer()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 692, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 672, in _help_stuff_finish
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
    inqueue._rlock.acquire()
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/home/sid/miniconda3/envs/mediapipe/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
```

**Comment by sradc** [comment]
Update:

I can reliably reproduce this on the Ubuntu machine, when I use the Python environment I've been using. 

But:
- I haven't yet reproduced this on a Colab instance (2 workers, same code as above)
- Haven't reproduced on an M1 Mac (under Rosetta 2 x86 emulation, same code as above)
- Using a different Python environment on the Ubuntu machine (installed a new miniforge env and mediapipe)

**Comment by JayCarraway** [comment]
+1
similar problem for me

**Comment by martinkoenig** [comment]
Also similar problem for me. Mediapipe Hands freezes randomly if used with multiprocessing. 
For some reason it pretty much never raises an error, mp.Hands just dies silently. Finally I got this traceback today.


```
Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f27e8cb4ac8>
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Fatal Python error: GC object already tracked
Thread 0x00007f271bbdd700 (most recent call first):
File "/usr/lib/python3.6/threading.py", line 295 in wait
File "/usr/lib/python3.6/multiprocessing/queues.py", line 222 in _feed
File "/usr/lib/python3.6/threading.py", line 864 in run
File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
Thread 0x00007f2730aae700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 295 in wait
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 222 in _feed
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
Thread 0x00007f274cff9700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 295 in wait
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 222 in _feed
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
Thread 0x00007f274d7fa700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 295 in wait
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 222 in _feed
  File "/usr/lib/python3.6/threading.py", line 864 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
Thread 0x00007f2823481700 (most recent call first):
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/pydevd.py", line 172 in _on_run
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 218 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 795 in __call__
Thread 0x00007f2822c80700 (most recent call first):
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_breakpoints.py", line 181 in _fallback_excepthook
Thread 0x00007f282247f700 (most recent call first):
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 292 in _on_run
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 218 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 795 in __call__
Thread 0x00007f27b2017700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 299 in wait
  File "/usr/lib/python3.6/queue.py", line 173 in get
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 367 in _on_run
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 218 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap
  File "/snap/pycharm-professional/252/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 795 in __call__
Current thread 0x00007f2828bac700 (most recent call first):
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  File "<string>", line 5 in SolutionOutputs
  ...
```

**Comment by sradc** [comment]
Thank you, @jiuqiant, it works for me too now.

**Comment by matanster** [comment]
Just a tuning comment to anyone which it may help, and thanks @sradc for the great example code.

Observing core utilization while this code is running, clearly suggests that mediapipe's C core is (already) using threads for concurrent operation for you. Spinning up only ~2 workers you can observe that all of your cores turn from idle to much more utilized, evenly, and consistently. 

So by mapping a workload like this to all logical cores, or even to a much smaller subset of your logical cores, you may equally be reducing throughput because the process workers' mediapipe spawned _threads_ are competing with among them over cpu time as their aggregate number exceeds your cpu throughput. Even though they may all be experiencing great cache performance as they are all doing the same thing, depending on the wat that your hardware cache architecture interacts with the structure and memory size of the underlying mediapie C code. 

This implies that you can likely get better throughput by judiciously scaling your python multiprocessing `map` to only a number of processes saturating your overall cpu time, while generating less heat. Using all logical cores may just totally overwhelm the throughput as above suggested, depending on your particular hardware component characteristics of course.

Since one process worker performing tight-loop mediapipe inference (as in this code example) still keeps much of your cpu core time idle waiting for memory, or doing IO for input arguments and return values back to python or anything else, then amping throughput by gradually increasing the number of processes until getting around 100% utilization does make sense, if you are looking at repeatedly performing inference at scale on a given machine. 

&ast; initially tested with a mediapipe version closer to the one used in this old issue than to the recent new api, but using the exact code from the top of this issue, reducing the number of processes on the pool by half makes N=10000 run twice as fast on my machine, and you can easily tune the number of processes on the pool on your own ― manually or even automatically.

Hope this helps.
