### ISSUE TITLE
An error occurred during the fetch of repository 'local_execution_config_python'

### ISSUE THREAD

**Issue by sonhaaa** [google/mediapipe#2351]
<em>I tried to run bazel command to build posetrackinggpu, but got and error.</em>

**System information**
- OS Platform and Distribution: Windows 10
- Programming Language and version: Java
- Bazel version: 5.0.0-pre.20210720.2
- Android SDK and NDK versions (if android): 
- SDK Platforms: Android API 31
- Android SDK Build-Tools: 31
- NDK version: 21.4.7075529

**Describe the problem**:
I tried to fixed by [Missing Python binary path](https://google.github.io/mediapipe/getting_started/troubleshooting.html#missing-python-binary-path) but it had the same output. I realized that it got error in line 209 in stead of 208 as the post mentioned.

**bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu**

**Complete Logs:**
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: D:/mediapipe/WORKSPACE:401:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
                result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
                bash_bin_path = which(repository_ctx, "bash")
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/remote_config/common.bzl", line 27, column 22, in which
                out = execute(
        File "C:/users/admin/_bazel_admin/hr7sucjp/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
INFO: Could not find files for the given pattern(s).
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/posetrackinggpu:posetrackinggpu' failed; build aborted: Repository command failed
INFO: Could not find files for the given pattern(s).
INFO: Elapsed time: 28.650s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (35 packages loaded, 12 targets configured)

**Comment by sgowroji** [comment]
As we mentioned in https://google.github.io/mediapipe/getting_started/install#installing-on-windows, MediaPipe doesn't support building its Android apps on native Windows because of the limited bazel support for Android on native Windows. Please try WSL instead. You can find the instructions at https://google.github.io/mediapipe/getting_started/install#installing-on-windows-subsystem-for-linux-wsl.
