### ISSUE TITLE
from mediapipe.python._framework_bindings import resource_util ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found.

### ISSUE THREAD

**Issue by Terence-I** [google/mediapipe#2385]
I installed mediapipe by using 'pip install mediapipe' in anaconda prompt and the installation was successful, but when I try to import it, I get the error mentioned above in this issue's title. I am using windows 10 and python 3.6, although I was getting the same error when I tried using python 3.8 too. I have tried multiple fixes I found online, like installing Microsoft visual studio, installing mvc-runtime using pip and uninstalling and reinstalling mediapipe again but none of these suggestions worked. If anyone has any suggestions on how I can fix it this, I would greatly appreciate it. Thank you!

This is the full traceback:

>>> import mediapipe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user_name\Anaconda3\envs\test\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "C:\Users\user_name\Anaconda3\envs\test\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed while importing _framework_bindings: The specified module could not be found.

**Comment by sgowroji** [comment]
Hi @Terence-I, Can you check this issue which is having similar scenario https://github.com/google/mediapipe/issues/1405#issuecomment-813798885

**Comment by Swapnilsable20** [comment]
@sgowroji 
Same error as @Terence-I 
Help

**Comment by Swapnilsable20** [comment]
@Terence-I 
Did u solve ur error.. 
If yes.. 
Pls tell me.. 
I am in the same trouble too
