### ISSUE TITLE
init FaceMesh error

### ISSUE THREAD

**Issue by zhoujingheng** [google/mediapipe#2393]
init code:
```
FaceMeshOptions faceMeshOptions = FaceMeshOptions.builder()
                .setMode(FaceMeshOptions.STREAMING_MODE)
                .build();
        faceMesh = new FaceMesh(mActivity, faceMeshOptions);
        faceMesh.setResultListener(new ResultListener<FaceMeshResult>() {
            @Override
            public void run(FaceMeshResult result) {

            }
        });
        faceMesh.setErrorListener(new ErrorListener() {
            @Override
            public void onError(String message, RuntimeException e) {
                System.out.println("message:" + e.getMessage());

            }
        });
```

error:
```
2021-08-09 11:40:17.978 22023-22023/com.cgfay.caincamerademo E/libEGL: validate_display:87 error 3008 (EGL_BAD_DISPLAY)
2021-08-09 11:40:17.984 22023-22023/com.cgfay.caincamerademo E/native: E20210809 11:40:17.984248 22023 graph.cc:470] ; Input Stream "image" for node with sorted index 33 does not have a corresponding output stream.
2021-08-09 11:40:17.986 22023-22023/com.cgfay.caincamerademo E/SolutionBase: Error occurs when starting the MediaPipe solution graph. 
    com.google.mediapipe.framework.MediaPipeException: unknown: ; Input Stream "image" for node with sorted index 33 does not have a corresponding output stream.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:116)
        at com.google.mediapipe.solutions.facemesh.FaceMesh.<init>(FaceMesh.java:92)
        at com.cgfay.camera.presenter.CameraPreviewPresenter.onAttach(CameraPreviewPresenter.java:214)
        at com.cgfay.camera.fragment.CameraPreviewFragment.onAttach(CameraPreviewFragment.java:166)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2672)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:253)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1168)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1987)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2621)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2569)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by ljmkimqx** [comment]
input stream 你是不是写成了'image'，这个一般都是写‘input_video’

**Comment by zhoujingheng** [comment]
> input stream 你是不是写成了'image'，这个一般都是写‘input_video’

官方代码：
```
public class FaceMesh extends ImageSolutionBase {
    private static final String TAG = "FaceMesh";

    private static final String NUM_FACES = "num_faces";
    private static final String GPU_GRAPH_NAME = "face_landmark_front_gpu_image.binarypb";
    private static final String CPU_GRAPH_NAME = "face_landmark_front_cpu_image.binarypb";
    private static final String IMAGE_INPUT_STREAM = "image";
    private static final ImmutableList<String> OUTPUT_STREAMS =
            ImmutableList.of("multi_face_landmarks", "image");
    private static final int LANDMARKS_INDEX = 0;
    private static final int INPUT_IMAGE_INDEX = 1;
    private final OutputHandler<FaceMeshResult> graphOutputHandler;
```

把imgae改成‘input_video’，也报错了

```
public class FaceMesh extends ImageSolutionBase {
    private static final String TAG = "FaceMesh";

    private static final String NUM_FACES = "num_faces";
    private static final String GPU_GRAPH_NAME = "face_landmark_front_gpu_image.binarypb";
    private static final String CPU_GRAPH_NAME = "face_landmark_front_cpu_image.binarypb";
    private static final String IMAGE_INPUT_STREAM = "input_video";
    private static final ImmutableList<String> OUTPUT_STREAMS =
            ImmutableList.of("multi_face_landmarks", "input_video");
    private static final int LANDMARKS_INDEX = 0;
    private static final int INPUT_IMAGE_INDEX = 1;
    private final OutputHandler<FaceMeshResult> graphOutputHandler;
```

error：
`invalid argument: Graph has errors:`

我传给facemesh的参数是camerax回调回来，转为bitmap
```
@Override
    public void onPreviewFrame(ImageProxy imageProxy) {
        faceMesh.send(toBitmap(imageProxy.getImage()), imageProxy.getImageInfo().getTimestamp());
        imageProxy.close();
    }
```

**Comment by sgowroji** [comment]
Hi @zhoujingheng, This can guide you well https://github.com/google/mediapipe/issues/1859#issuecomment-854932725

**Comment by zhoujingheng** [comment]
Hi @sgowroji did not solve my problem，can you give me sample about solution FaceMesh with android

**Comment by sgowroji** [comment]
Duplicate https://github.com/google/mediapipe/issues/2403#issuecomment-897326635

**Comment by sgowroji** [comment]
Closing this issue w.r.t this #2403 (comment). Please reach us if you still have any queries regarding the above.
