### ISSUE TITLE
FaceMesh cannot run on Samsung SM-G5528

### ISSUE THREAD

**Issue by chenkecheng** [google/mediapipe#2424]
com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Open() for node "singlefacegeometryfromlandmarksgpu__facelandmarkfrontgpu__facedetectionshortrangegpu__inferencecalculator__singlefacegeometryfromlandmarksgpu__facelandmarkfrontgpu__facedetectionshortrangegpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:364)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

**Comment by sgowroji** [comment]
Hi @chenkecheng, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by chenkecheng** [comment]
@sgowroji This problem occurs every time on Samsung SM-G5528 model. Build facemeshgpu.apk by android_arm, then install to Samsung SM-G5528. Run facemeshgpu, then the problem happened.
Android version:8.1.0
SOC: Snapdragon 625

**Comment by chenkecheng** [comment]
@sgowroji Do you have any idea on this exception?

**Comment by sgowroji** [comment]
Hi @chenkecheng, Did you add any code changes in java or graph?

**Comment by chenkecheng** [comment]
@sgowroji Didn't change anything.

**Comment by sgowroji** [comment]
Hi @chenkecheng, We have recently released the gradle solutions for facemesh and hands [here](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/solutions). and [documentation](https://google.github.io/mediapipe/getting_started/android_solutions.html).

**Comment by chenkecheng** [comment]
@sgowroji I found the problem :
  Samsung SM-G5528 glEsVersion = 3.0， but the min glEsVersion required by mediapipe is 3.1
