### ISSUE TITLE
Traceback (most recent call last): File "D:/tjwork/pythonproject/pythonProject/RFIDtest/rfopencv.py", line 15, in import mediapipe as mp File "D:\softwareDevelop\python\Anocoda\Anacoda\lib\site-packages\mediapipe_init_.py", line 16, in from mediapipe.python import * File "D:\softwareDevelop\python\Anocoda\Anacoda\lib\site-packages\mediapipe\python_init_.py", line 16, in from mediapipe.python._framework_bindings import resource_util ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'  Process finished with exit code 1

### ISSUE THREAD

**Issue by mdhuzaifapatel** [google/mediapipe#2459]
Pls help with this ...
Actually I was trying to convert .py to .exe 
When I run the exe file its shows the error 
No module named mediapipe_framework_bindings

**Comment by sgowroji** [comment]
Hi @mdhuzaifapatel, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by mdhuzaifapatel** [comment]
Someone Please help

**Comment by sgowroji** [comment]
Similar https://github.com/google/mediapipe/issues/2162#issuecomment-876830557 ?
