### ISSUE TITLE
Integration @mediapipe/hands in React JS

### ISSUE THREAD

**Issue by devewok** [google/mediapipe#2495]
![image](https://user-images.githubusercontent.com/87552609/131921154-cc12b402-ffa2-4cc6-b99b-42a072983e65.png)

I have that problem using React JS, any help ?

My code:
`
import {useEffect, useRef} from "react";
import {Hands} from "@mediapipe/hands";
import {Camera} from "@mediapipe/camera_utils";
const SignalToText = () => {
  const hands = new Hands()
  const videoElement = useRef(null)
  const onResult = (resp) => {
    if (resp.multiHandLanmarks)
      console.log(resp.multiHandLanmarks)
    else
      console.log("error", resp)
  }
  useEffect(() => {
    hands.setOptions({
      maxNumHands: 2,
      minDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5
    });
    hands.onResults(onResult)
  }, [])
  useEffect(() => {
    if (videoElement) {
      const camera = new Camera(videoElement.current, {
        onFrame: async () => {
          await hands.send({image: videoElement.current});
        },
        width: 1280,
        height: 720
      })
      camera.start()
    }
  }, [videoElement])
  return (
    <div>
      <h1>Signal to Text</h1>
      <video ref={videoElement}></video>
    </div>
  )
}
`

**Comment by sgowroji** [comment]
Hi @devewok, Could you please check whether the imports are loaded appropriately. Thanks!

**Comment by devewok** [comment]
i checked the imports and i changed it to import {Hands} from "@mediapipe/hands/hands.js";
import {Camera} from "@mediapipe/camera_utils/camera_utils.js"; but that doesnt worked.
I removed those librarys and i installed @tensorflow-models/handpose and that works fine.

**Comment by bsjaramillo** [comment]
Hi @sgowroji , sorry... i'm not looking resolution for this already, thanks

**Comment by karen-pal** [comment]
I got it working on react by importing it as

`import * as Hands from "@mediapipe/hands";`


later, for usage I would do 
`new Hands.Hands(...`

or

`Hands.HAND_CONNECTIONS`

for example.

Hope this helps anyone stuck.

**Comment by sgowroji** [comment]
@karen-pal  Thank you for providing your solution. This is very helpful to the community who are looking our for similar queries.

**Comment by konerunatwar** [comment]
> I am trying to detect my hand using mediapipe i am getting below error 

Uncaught (in promise) RuntimeError: Aborted(native code called abort())
    at abort (hands_solution_simd_wasm_bin.js:9:25546)
    at _abort (hands_solution_simd_wasm_bin.js:9:163781)
    at hands_solution_simd_wasm_bin.wasm:0x51ad24
    at hands_solution_simd_wasm_bin.wasm:0x51abc9
    at hands_solution_simd_wasm_bin.wasm:0x51ad99
    at hands_solution_simd_wasm_bin.wasm:0x1f191
    at hands_solution_simd_wasm_bin.wasm:0x198f7
    at SolutionWasm$send [as send] (eval at new_ (hands_solution_simd_wasm_bin.js:9:140730), <anonymous>:9:1)
    at pa.h (hands.js:73:1)
    at G (hands.js:14:1)
    at sa.next (hands.js:15:1)
    at b (hands.js:15:1)

My code:


import React, { useRef, useEffect } from "react";
import * as Hands from "@mediapipe/hands";
import * as cam from "@mediapipe/camera_utils";
import Webcam from "react-webcam";
function App() {
  const webcamRef = useRef(null);
  const canvasRef = useRef(null);
  const connect = window.drawConnectors;
  var camera = null;
  function onResults(results) {
    // const video = webcamRef.current.video;
    const videoWidth = webcamRef.current.video.videoWidth;
    const videoHeight = webcamRef.current.video.videoHeight;

    // Set canvas width
    canvasRef.current.width = videoWidth;
    canvasRef.current.height = videoHeight;

    const canvasElement = canvasRef.current;
    const canvasCtx = canvasElement.getContext("2d");

    canvasCtx.save();
    canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
    canvasCtx.drawImage(
      results.image, 0, 0, canvasElement.width, canvasElement.height);

    if (results.multiHandLandmarks) {
        
        for (const landmarks of results.multiHandLandmarks) {
        console.log(landmarks)
        window.drawConnectors(canvasCtx, landmarks, Hands.HAND_CONNECTIONS,{color: '#00FF00', lineWidth: 5});
        window.drawLandmarks(canvasCtx, landmarks, {color: '#FF0000', lineWidth: 2});
      }
    }
    canvasCtx.restore();
  }
  // }

  // setInterval(())
  useEffect(() => {
    const hands = new Hands.Hands({
      locateFile: (file) => {
        return `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`;
      },
    });
    

    hands.setOptions({
      maxNumFaces: 1,
      minDetectionConfidence: 0.5,
      minTrackingConfidence: 0.5,
    });

    hands.onResults(onResults);

    if (
      typeof webcamRef.current !== "undefined" &&
      webcamRef.current !== null
    ) {
      camera = new cam.Camera(webcamRef.current.video, {
        onFrame: async () => {
          await hands.send({ image: webcamRef.current.video });
        },
        width: 640,
        height: 480,
      });
      camera.start();
    }
  }, []);
  return (
    <center>
      <div className="App">
        <Webcam
          ref={webcamRef}
          style={{
            position: "absolute",
            marginLeft: "auto",
            marginRight: "auto",
            left: 0,
            right: 0,
            textAlign: "center",
            zindex: 9,
            width: 640,
            height: 480,
          }}
        />{" "}
        <canvas
          ref={canvasRef}
          className="output_canvas"
          style={{
            position: "absolute",
            marginLeft: "auto",
            marginRight: "auto",
            left: 0,
            right: 0,
            textAlign: "center",
            zindex: 9,
            width: 640,
            height: 480,
          }}
        ></canvas>
      </div>
    </center>
  );
}

export default App;
