### ISSUE TITLE
No registered object with name: PoseRendererGpu; Unable to find Calculator "PoseRendererGpu"

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#2498]
When i use mediapipe_holistic_tracking.aar in my android project, I get this Error: 
`No registered object with name: PoseRendererGpu; Unable to find Calculator "PoseRendererGpu"`

mediapipe v0.8.7
build env : macOS 10.15.7

Here is my steps:
#### 1.   build mediapipe_holistic_tracking.aar
- WORKSPACE file: I use mediapipe-master/WORKSPACE,  and i deleted ios reference content , and edit sdk/ndk value to:
```
android_sdk_repository(
    name = "androidsdk",
    build_tools_version = "28.0.3",
    path = "/Users/username/Library/Android/sdk",
)

android_ndk_repository(
    name = "androidndk",
    path = "/Users/username/Library/Android/sdk/ndk/20.0.5594570",
)
```

- BUILD file :  I use /Users/usename/doc/mediapipe-master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu/BUILD , 
the BUILD file all content is :
``` 
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_holistic_tracking",
    calculators = ["//mediapipe/graphs/holistic_tracking:holistic_tracking_gpu_deps"],
) 
```

- bazel command :
```
bazel build -c opt --strip=ALWAYS   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   
--fat_apk_cpu=arm64-v8a,armeabi-v7a  
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/holistictrackinggpu:mediapipe_holistic_tracking.aar

```
- copy the aar package to project lib directory.

#### 2 build binary graph
bazel command :
```
bazel build -c opt mediapipe/graphs/holistic_tracking:holistic_tracking_gpu
```
then copy holistic_tracking_gpu.binarypb and  mediapipe/modules/holistic_landmark/hand_recrop.tflite    to my project asserts directory .

this steps refer to https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-build-a-mediapipe-aar

#### 3 this is my referenced code :
```
        eglManager = new EglManager(null);
        processor = new FrameProcessor(this,eglManager.getNativeContext(),
                "holistic_tracking_gpu.binarypb","input_video","output_video");
        processor.getVideoSurfaceOutput().setFlipY(true);

        ProtoUtil.registerTypeName(NormalizedLandmarkList.class, "mediapipe.NormalizedLandmarkList");

        processor.addPacketCallback("holistic_landmarks", new PacketCallback() {
            @Override
            public void process(Packet packet) {
                Log.d(TAG,  " packetCount " + i++);
                try {
                    NormalizedLandmarkList poseLandmarks = PacketGetter.getProto(packet, NormalizedLandmarkList.class);
                    String marks = getPoseLandmarksDebugString(poseLandmarks);
                    if (frameNum >= frameCount) return;
                    frameNum++;
                } catch (InvalidProtocolBufferException exception) {
                    Log.e(TAG, "Failed to get proto.", exception);
                }
            }
        });
```
when i use mediapipe_pose_tracking.aar (get from mediapipe v0.8.6) in my project, it not get this error. 

complete error message:
```
E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.ai.yijian, PID: 22445
    com.google.mediapipe.framework.MediaPipeException: not found: ValidatedGraphConfig Initialization failed.
    No registered object with name: PoseRendererGpu; Unable to find Calculator "PoseRendererGpu"
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
E/RtgSchedManager: endActivityTransaction: margin state not match
```

**Comment by sgowroji** [comment]
Hi @wingdi , Could  you please find the duplicate issue https://github.com/google/mediapipe/issues/1994#issuecomment-892270523

**Comment by wingdi** [comment]
> Hi @wingdi , Could you please find the duplicate issue [#1994 (comment)](https://github.com/google/mediapipe/issues/1994#issuecomment-892270523)

Yes, i have read that comment before, that not solve my problem.   I build gpu verison , not cpu verison

**Comment by jiuqiant** [comment]
Can you double check if you use the latest version of https://github.com/google/mediapipe/blob/master/mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt? I don't see that the holistic graph uses the pose gpu renderer and not sure why "PoseRendererGpu" is required. The holistic tracking gpu graph has its standalone rendering component at https://github.com/google/mediapipe/blob/master/mediapipe/graphs/holistic_tracking/holistic_tracking_gpu.pbtxt#L58.

**Comment by wingdi** [comment]
@jiuqiant  very thanks your reply .
Today i  use the lastest code build to generate the new holistictrackinggpu.aar and holistic_tracking_gpu.bin, and put them in my project.   But i didn't find relative *.tflite file in path " //mediapipe/modules/holistic_landmark ", in the path i only find a hand_recrop.tflite.  And i put hand_recrop.tflite in project's assets folder.   does the .tflite is necessary ?  After running my project, It did't have previous error, but i got this Error:
```
java.lang.ExceptionInInitializerError
        at com.google.common.flogger.backend.Platform$LazyHolder.access$100(Platform.java:65)
        at com.google.common.flogger.backend.Platform.getCallerFinder(Platform.java:189)
        at com.google.common.flogger.FluentLogger.forEnclosingClass(FluentLogger.java:70)
        at com.google.mediapipe.framework.Graph.<clinit>(Graph.java:33)
        at com.google.mediapipe.components.FrameProcessor.initializeGraphAndPacketCreator(FrameProcessor.java:139)
        at com.google.mediapipe.components.FrameProcessor.<init>(FrameProcessor.java:96)
        at com.ai.yijian.test.BaseMediaPipeActivity.onCreate(BaseMediaPipeActivity.java:85)
```
I thinks this maybe because lacking relative .tflite file,  how can i get/generate *.tflite file ? 
thanks.
