### ISSUE TITLE
TypeError: create_bool(): incompatible function arguments. Mediapipe error when using the latest version

### ISSUE THREAD

**Issue by Vatsa0408** [google/mediapipe#2544]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): ```yes```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): ```Windows 10```
- [MediaPipe version](https://github.com/google/mediapipe/releases): ```0.8.7.1```
- Bazel version: NA (Not build from scratch)
- Solution (e.g. FaceMesh, Pose, Holistic): ```Pose```
- Programming Language and version ( e.g. C++, Python, Java):```Python```

**Describe the expected behavior:**
When using the ```v0.8.6```, i faced no issues while running the Pose Model. But when running the ```v0.8.7.1```, i get the following error

**Standalone code you may have used to try to get what you need :**
``` python
def __init__(self, staticMode, model_complexity, smooth, enable_segmentation, smooth_segmentation, minDetectionCon, minTrackCon):
        """
        Initialize Parameters for the Pose Detection and Tracking.
        Needs 7 parameters.
        """
    #  def __init__(self, staticMode,model_complexity, smooth,enable_segmentation, smooth_segmentation ,minDetectionCon, minTrackCon):

        self.staticMode = staticMode
        self.modelComplexity = model_complexity
        self.smooth = smooth
        self.enableSegmentation = enable_segmentation
        self.smoothSegmentation = smooth_segmentation
        self.minDetectionCon = minDetectionCon
        self.minTrackCon = minTrackCon

        self.mpDraw = mp.solutions.drawing_utils
        self.mpPose = mp.solutions.pose
        self.pose = self.mpPose.Pose(static_image_mode = self.staticMode,model_complexity = self.modelComplexity, smooth_landmarks = self.smooth, enable_segmentation = self.enableSegmentation, smooth_segmentation = self.smoothSegmentation, min_detection_confidence = self.minDetectionCon, min_tracking_confidence = self.minTrackCon)
        self.drawLandmarkSpec = self.mpDraw.DrawingSpec(
            thickness=5, circle_radius=2, color=BLUE_COLOR)
        self.drawConnectionSpec = self.mpDraw.DrawingSpec(
            thickness=2, color=RED_COLOR)

    def findPose(self, frame, draw=True):
        """
        Finds Pose in the image frame. 
        Takes one argument. i.e frame

        """
        self.imgRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        self.results = self.pose.process(self.imgRGB)
        if self.results.pose_world_landmarks:
            if draw:
                self.mpDraw.draw_landmarks(frame, self.results.pose_landmarks,  # world_landmarks draw is not available. Touse pose_landmarks
                                           self.mpPose.POSE_CONNECTIONS, self.drawLandmarkSpec, self.drawConnectionSpec)
               #  self.mpDraw.plot_landmarks( self.results.pose_world_landmarks,  # world_landmarks draw is not available. Touse pose_landmarks
               #                             self.mpPose.POSE_CONNECTIONS)
                # self.mpDraw.plot_landmarks(self.results.pose_world_landmarks, self.mpPose.POSE_CONNECTIONS)
        return frame
```
The functions are in the class ```PoseDetector()``` which is called in ```main()```
I configure the parameters for the ```Pose``` model with the help of a ```config``` text file
``` text
ModelComplexity = 1;Complexity of the pose landmark model. Allows to load pose model, 0 for lite, 1 for normal and 2 for heavy model.
MinDetectionConfidence = 0.9 ; Minimum confidence value ([0.0, 1.0]) for person detection to be considered successful. Ideally 0.5 is to be written 
MinTrackingConfidence = 0.9 ; Minimum Tracking value ([0.0, 1.0]) for person detection to be considered successful. Ideally 0.5 is to be written 
StaticMode = False; Whether to treat the input images as a batch of static and possibly unrelated images, or a video stream. True is set for image input and False is set for video input
SmoothLandmarks = True;Whether to filter landmarks across different input images to reduce jitter. Write True to enable SmoothLandmarks. To disable, write False
EnableSegmentation = True; Whether to filter landmarks across different input images to reduce jitter. Write True to enable EnableSegmentation. To disable, write False
SmoothSegmentation = True; Whether to filter landmarks across different input images to reduce jitter. Write True to enable SmoothSegmentation. To disable, write False
```
``` python
pose = PoseDetector(static_mode, model_complexity,smooth_lm, enableSegmentation, smoothSegmentation,minDetectCon, minTrackCon)
frame = pose.findPose(frame)
```

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:
**The complete traceback log is attached above**

**Comment by sgowroji** [comment]
Hi @Vatsa0408, Could you please share your console logs to understand the issue with complete details. And you can set false to the above attributes as mentioned (https://google.github.io/mediapipe/solutions/pose#enable_segmentation) (https://google.github.io/mediapipe/solutions/pose#smooth_segmentation)

**Comment by Vatsa0408** [comment]
Hi @sgowroj, Thanks for the quick reply.
Sorry i forgot to attach the traceback log
Here is the log
``` console
PS C:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement>  c:; cd 'c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement'; & 'C:\ins\Python\Python37\python.exe' 'c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy\launcher' '49807' '--' 'c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py' 
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\ins\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ins\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\ins\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ins\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ins\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 2096, in <module>
    main()
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 1983, in main
    smooth_lm, enableSegmentation, smoothSegmentation,minDetectCon, minTrackCon)
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 670, in __init__
    self.pose = self.mpPose.Pose(static_image_mode = self.staticMode,model_complexity = self.modelComplexity, smooth_landmarks = self.smooth, enable_segmentation = self.enableSegmentation, smooth_segmentation = self.smoothSegmentation, min_detection_confidence = self.minDetectionCon, min_tracking_confidence = self.minTrackCon)
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solutions\pose.py", line 166, in __init__
    outputs=['pose_landmarks', 'pose_world_landmarks', 'segmentation_mask'])
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in __init__
    for name, data in (side_inputs or {}).items()
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in <dictcomp>
    for name, data in (side_inputs or {}).items()
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 'True'
```
When i changed it to False, i get the same log, but with ```Invoked with: 'False'```

**Comment by jiuqiant** [comment]
Can you verify  staticMode, smooth, enable_segmentation, and smooth_segmentation are all bool type (not str type) in Python before calling self.pose = self.mpPose.Pose(...) ? Another thing to try is to set just one of them in self.pose = self.mpPose.Pose(...) to identify which causes problem.

**Comment by Vatsa0408** [comment]
@jiuqiant , Thank you for the answer provided. I will implement these solutions and update you with the solutions

**Comment by Vatsa0408** [comment]
Hi @jiuqiant, staticMode, smooth, enable_segmentation & smooth_segmentation are all bool types.
Here is how i extract them in my python program
``` python
model_complexity = params["BodyMotion.Project.ModelComplexity"]
    if type(model_complexity) != int:
        print("Entered number is not integer. Please Enter 0 or 1 or 2.")
    if (model_complexity > 2):
        print("Entered number has to be 0 or 1 or 2 for Model Complexity. Please check")
        sys.exit()
    minDetectCon = params["BodyMotion.Project.MinDetectionConfidence"]
    if type(minDetectCon) != float:
        print("Entered Number is wrong, Please enter a number between 0.0 and 1.0")
    if (minDetectCon > 1):
        print("Entered number has to be in the range from 0.0 to 1.0 for Minimum Detection Confidence. Please check")
        sys.exit()
    minTrackCon = params["BodyMotion.Project.MinTrackingConfidence"]
    if type(minTrackCon) != float:
        print("Entered Number is wrong, Please enter a number between 0.0 and 1.0")
    if (minTrackCon > 1):
        print("Entered number has to be in the range from 0.0 to 1.0 for Minimum Tracking Confidence. Please check")
        sys.exit()
    static_mode = params["BodyMotion.Project.StaticMode"]
    if type(static_mode) == bool(static_mode):
        print("Static Mode Parameter value has to be True or False.")
        sys.exit()
    smooth_lm = params["BodyMotion.Project.SmoothLandmarks"]
    if type(smooth_lm) == bool(smooth_lm):
        print("Smooth Landmarks Parameter value has to be True or False.")
        sys.exit()
    enableSegmentation = params["BodyMotion.Project.EnableSegmentation"]
    if type(enableSegmentation) == bool(enableSegmentation):
        print("Enable Segmentation Parameter value has to be True or False.")
        sys.exit()
    smoothSegmentation = params["BodyMotion.Project.SmoothSegmentation"]
    if type(smoothSegmentation) == bool(smoothSegmentation):
        print("Smooth Segmentation Parameter value has to be True or False.")
        sys.exit()
```

As you mentioned, i tried to call only one value as following
```
 self.pose = self.mpPose.Pose(self.staticMode)
```
The program runs fine if i provide only a single parameter. But if i provide all the parameters, i get the same error.
I have also attached the error log
``` console
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "C:\ins\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ins\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>      
    cli.main()
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in 
main
    run()
  File "c:\Users\srivatsa.diwakar\.vscode\extensions\ms-python.python-2021.9.1230869389\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in 
run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\ins\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ins\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ins\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 2100, in <module>
    main()
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 1988, in main
    pose = PoseDetector(static_mode, model_complexity, smooth_lm, enableSegmentation, smoothSegmentation, minDetectCon, minTrackCon)
  File "c:\Sri\Projects\ADrive_Projects\motion_emotion\code\py\position_measurement\PoseEstimator.py", line 678, in __init__
    self.pose = self.mpPose.Pose(self.staticMode ,self.modelComplexity, self.smooth,self.enableSegmentation, self.smoothSegmentation,self.minDetectionCon, self.minTrackCon)
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solutions\pose.py", line 166, in __init__
    outputs=['pose_landmarks', 'pose_world_landmarks', 'segmentation_mask'])
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in __init__
    for name, data in (side_inputs or {}).items()
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 260, in <dictcomp>
    for name, data in (side_inputs or {}).items()
  File "C:\ins\Python\Python37\lib\site-packages\mediapipe\python\solution_base.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_bool(): incompatible function arguments. The following argument types are supported:
    1. (arg0: bool) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 'True'
```

**Comment by sgowroji** [comment]
Hi @Vatsa0408, You should try building your code similar like this https://github.com/google/mediapipe/issues/2562#issuecomment-922670108. Reach us back if you still have queries on the above issue.

**Comment by sgowroji** [comment]
Hi @Vatsa0408,  Did you get a chance to go through the above https://github.com/google/mediapipe/issues/2544#issuecomment-934334406

**Comment by sgowroji** [comment]
Hi @Vatsa0408, I can reopen the issue if the above fix doesn't work.

**Comment by Vatsa0408** [comment]
Hi @sgowroji, I am using version 0.8.8 and I am not facing any issue as of now.
Thanks for the support provided.

**Comment by JoeyMyMan** [comment]
I think you could try to remove the parameter here , and it would be : `self.pose = self.mpPose.Pose()`
