### ISSUE TITLE
SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by ForLovelj** [google/mediapipe#2547]
I use pose_traking_gpu in a android project and sometimes I get this error

error log:
```
#00 pc 0000000000032270 /apex/com.android.runtime/lib64/bionic/libc.so (strlen+16) [arm64-v8a::9c968730cee26016ccc9ed9e8449ea5b]
2
#01 pc 00000000005a3a68 /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::PathToResourceAsFile(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)+572) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
3
#02 pc 00000000004a60b8 /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::LocalFileContentsCalculator::Open(mediapipe::CalculatorContext*)+504) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
4
#03 pc 00000000009d2f90 /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::CalculatorNode::OpenNode()+840) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
5
#04 pc 00000000009c214c /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::internal::SchedulerQueue::OpenCalculatorNode(mediapipe::CalculatorNode*)+276) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
6
#05 pc 00000000009c1ee8 /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::internal::SchedulerQueue::RunNextTask()+220) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
7
#06 pc 00000000009f3ee4 /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::ThreadPool::RunWorker()+380) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
8
#07 pc 00000000009f3b34 /data/app/com.xxx.xxx-pmj_-fUTGEEyq47w6pziVQ==/lib/arm64/libmediapipe_jni.so (mediapipe::ThreadPool::WorkerThread::ThreadBody(void*)+1380) [arm64-v8a::45ae0b8fb0e27d95fa6613fc62961cc3]
9
#08 pc 000000000009b1a0 /apex/com.android.runtime/lib64/bionic/libc.so (res_nsend_ipv6_simple+1232) [arm64-v8a::9c968730cee26016ccc9ed9e8449ea5b]
10
#09 pc 00000000000379d4 /apex/com.android.runtime/lib64/bionic/libc.so [arm64-v8a::9c968730cee26016ccc9ed9e8449ea5b]
```
```
09-14 13:36:38.657 27040 27175 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
209-14 13:36:38.659 27040 27088 W Binder : Caught a RuntimeException from the binder stub implementation.
309-14 13:36:38.659 27040 27088 W Binder : java.lang.IllegalStateException: Not in applications main thread
409-14 13:36:38.659 27040 27088 W Binder : at me.jessyan.autosize.utils.Preconditions.checkMainThread(Preconditions.java:2)
509-14 13:36:38.659 27040 27088 W Binder : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensity(AutoSizeCompat.java:2)
609-14 13:36:38.659 27040 27088 W Binder : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityBaseOnWidth(AutoSizeCompat.java:1)
709-14 13:36:38.659 27040 27088 W Binder : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:2)
809-14 13:36:38.659 27040 27088 W Binder : at com.xxx.xxx.app.base.BaseActivity.getResources(BaseActivity.kt:1)
909-14 13:36:38.659 27040 27088 W Binder : at com.android.internal.policy.DecorContext.getResources(DecorContext.java:90)
1009-14 13:36:38.659 27040 27088 W Binder : at android.view.ViewRootImpl.isShouldDelayMsg4SeamlessLauncher(ViewRootImpl.java:8390)
1109-14 13:36:38.659 27040 27088 W Binder : at android.view.ViewRootImpl.dispatchResized(ViewRootImpl.java:8380)
1209-14 13:36:38.659 27040 27088 W Binder : at android.view.ViewRootImpl.access$5200(ViewRootImpl.java:168)
1309-14 13:36:38.659 27040 27088 W Binder : at android.view.ViewRootImpl$W.resized(ViewRootImpl.java:9919)
1409-14 13:36:38.659 27040 27088 W Binder : at android.view.IWindow$Stub.onTransact(IWindow.java:358)
1509-14 13:36:38.659 27040 27088 W Binder : at android.os.Binder.execTransactInternal(Binder.java:1028)
1609-14 13:36:38.659 27040 27088 W Binder : at android.os.Binder.execTransact(Binder.java:1001)
1709-14 13:36:38.659 27040 27040 D RenderService: RCS is disable
1809-14 13:36:38.665 27040 27483 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
1909-14 13:36:38.670 27040 27040 D DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
2009-14 13:36:38.683 27040 27175 D OpenGLRenderer: disableOutlineDraw is true
2109-14 13:36:38.685 27040 27040 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
2209-14 13:36:38.685 27040 27040 W InputMethodManager: startInputReason = 1
2309-14 13:36:38.748 27040 27040 D DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
2409-14 13:36:38.949 27040 27040 I RmeSchedManager: init Rme, version is: v1.0
2509-14 13:36:39.646 27040 27061 D ZrHung.AppEyeUiProbe: not watching, wait.
2609-14 13:36:51.181 27040 27040 D ActivityThread: Won't deliver top position change in state=4
2709-14 13:36:51.194 27040 27483 W libEGL : EGLNativeWindowType 0x7d0c146010 disconnect failed
2809-14 13:36:51.226 27040 27061 D ZrHung.AppEyeUiProbe: restart watching
2909-14 13:36:51.238 27040 27040 I RmeSchedManager: init Rme, version is: v1.0
3009-14 13:36:51.239 27040 27040 I RtgSchedEvent: current pid:27040 AppType:-1
3109-14 13:36:51.241 27040 27040 I HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
3209-14 13:36:51.241 27040 27040 D RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:22, errno:103
3309-14 13:36:51.242 27040 27040 D RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:23, errno:103
3409-14 13:36:51.242 27040 27040 D RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:22, errno:103
3509-14 13:36:51.255 27040 27040 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
3609-14 13:36:51.255 27040 27040 W InputMethodManager: startInputReason = 1
3709-14 13:36:51.256 27040 27040 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cc35234
3809-14 13:36:51.263 27040 27040 V ActivityThread: callActivityOnCreate
3909-14 13:36:51.269 27040 27040 I DecorView[]: pkgName:com.xxx.xxx old windowMode:0 new windoMode:1, isFixedSize:false
4009-14 13:36:51.281 27040 27040 I native : I20210914 13:36:51.279950 27040 asset_manager_util.cc:59] Created global reference to asset manager.
4109-14 13:36:51.285 27040 27040 E libEGL : validate_display:104 error 3008 (EGL_BAD_DISPLAY)
4209-14 13:36:51.292 27040 27040 I native : I20210914 13:36:51.291932 27040 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
4309-14 13:36:51.295 27040 27558 I native : I20210914 13:36:51.295732 27558 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 v1.r18p0-01rel0.c3422a5a15429235949540558f14d585)
4409-14 13:36:51.305 27040 27040 D ActivityThread: add activity client record, r= ActivityRecord{bbf7b18 token=android.os.BinderProxy@cc35234 {com.xxx.xxx/com.xxx.xxx.ui.actioncheck.ActionCheckActivity}} token= android.os.BinderProxy@cc35234
4509-14 13:36:51.320 27040 27040 V AudioManager: getStreamVolume streamType: 3 volume: 3
4609-14 13:36:51.320 27040 27040 V AudioManager: isStreamMute streamType: 3
4709-14 13:36:51.321 27040 27040 V AudioManager: getStreamMaxVolume treamType: 3
4809-14 13:36:51.360 27040 27040 D MouseWheelSynthesizer: mMoveStepInDp: 64, mMoveStepInPixel: 183, mUpTimeDelayed: 100
4909-14 13:36:51.360 27040 27040 D ViewRootImpl: ViewRootImpl mIsInProductivePCDisplay: false
5009-14 13:36:51.361 27040 27573 I CameraManagerGlobal: Connecting to camera service
5109-14 13:36:51.361 27040 27040 I DecorView[]: pkgName:com.xxx.xxx old windowMode:1 new windoMode:1, isFixedSize:false
5209-14 13:36:51.364 27040 27040 D InputEventReceiver: dispatchInputInterval 1000000
5309-14 13:36:51.370 27040 27574 D HiTouch_PressGestureDetector: onAttached, package=com.xxx.xxx, windowType=1, mIsHiTouchRestricted=false
5409-14 13:36:51.378 27040 27175 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
5509-14 13:36:51.382 27040 27558 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
5609-14 13:36:51.385 27040 27602 D CCodec : allocate(c2.android.mp3.decoder)
5709-14 13:36:51.387 27040 27602 I CCodec : Created component [c2.android.mp3.decoder]
5809-14 13:36:51.387 27040 27602 D CCodecConfig: read media type: audio/mpeg
5909-14 13:36:51.392 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
6009-14 13:36:51.392 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
6109-14 13:36:51.393 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
6209-14 13:36:51.393 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
6309-14 13:36:51.394 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
6409-14 13:36:51.394 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
6509-14 13:36:51.394 27040 27602 D ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
6609-14 13:36:51.396 27040 27602 I CCodecConfig: query failed after returning 7 values (BAD_INDEX)
6709-14 13:36:51.396 27040 27602 D CCodecConfig: c2 config is Dict {
6809-14 13:36:51.396 27040 27602 D CCodecConfig: c2::u32 coded.bitrate.value = 64000
6909-14 13:36:51.396 27040 27602 D CCodecConfig: c2::u32 input.buffers.max-size.value = 8192
7009-14 13:36:51.396 27040 27602 D CCodecConfig: c2::u32 input.delay.value = 0
7109-14 13:36:51.396 27040 27602 D CCodecConfig: string input.media-type.value = "audio/mpeg"
7209-14 13:36:51.396 27040 27602 D CCodecConfig: string output.media-type.value = "audio/raw"
7309-14 13:36:51.396 27040 27602 D CCodecConfig: c2::u32 raw.channel-count.value = 2
7409-14 13:36:51.396 27040 27602 D CCodecConfig: c2::u32 raw.sample-rate.value = 44100
7509-14 13:36:51.396 27040 27602 D CCodecConfig: }
7609-14 13:36:51.397 27040 27040 D DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
7709-14 13:36:51.398 27040 27602 D CCodecConfig: config failed => CORRUPTED
7809-14 13:36:51.398 27040 27602 D CCodecConfig: c2 config is Dict {
7909-14 13:36:51.398 27040 27602 D CCodecConfig: c2::u32 coded.bitrate.value = 64000
8009-14 13:36:51.398 27040 27602 D CCodecConfig: c2::u32 input.buffers.max-size.value = 8192
8109-14 13:36:51.398 27040 27602 D CCodecConfig: c2::u32 input.delay.value = 0
8209-14 13:36:51.398 27040 27602 D CCodecConfig: string input.media-type.value = "audio/mpeg"
8309-14 13:36:51.398 27040 27602 D CCodecConfig: string output.media-type.value = "audio/raw"
8409-14 13:36:51.398 27040 27602 D CCodecConfig: c2::u32 raw.channel-count.value = 2
8509-14 13:36:51.398 27040 27602 D CCodecConfig: c2::u32 raw.sample-rate.value = 48000
8609-14 13:36:51.398 27040 27602 D CCodecConfig: }
8709-14 13:36:51.398 27040 27602 W Codec2Client: query -- param skipped: index = 1107298332.
8809-14 13:36:51.398 27040 27602 D CCodec : client requested max input size 4096, which is smaller than what component recommended (8192); overriding with component recommendation.
8909-14 13:36:51.398 27040 27602 W CCodec : This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
9009-14 13:36:51.398 27040 27602 D CCodec : setup formats input: AMessage(what = 0x00000000) = {
9109-14 13:36:51.398 27040 27602 D CCodec : int32_t channel-count = 2
9209-14 13:36:51.398 27040 27602 D CCodec : int32_t max-input-size = 8192
9309-14 13:36:51.398 27040 27602 D CCodec : string mime = "audio/mpeg"
9409-14 13:36:51.398 27040 27602 D CCodec : int32_t sample-rate = 48000
9509-14 13:36:51.398 27040 27602 D CCodec : } and output: AMessage(what = 0x00000000) = {
9609-14 13:36:51.398 27040 27602 D CCodec : int32_t channel-count = 2
9709-14 13:36:51.398 27040 27602 D CCodec : string mime = "audio/raw"
9809-14 13:36:51.398 27040 27602 D CCodec : int32_t sample-rate = 48000
9909-14 13:36:51.398 27040 27602 D CCodec : }
10009-14 13:36:51.399 27040 27602 W Codec2Client: query -- param skipped: index = 1342179345.
10109-14 13:36:51.399 27040 27602 W Codec2Client: query -- param skipped: index = 2415921170.
10209-14 13:36:51.400 27040 27175 D OpenGLRenderer: disableOutlineDraw is true
10309-14 13:36:51.400 27040 27602 D BufferPoolAccessor: bufferpool2 0x7cdf57f820 : 4(32768 size) total buffers - 4(32768 size) used buffers - 0/5 (recycle/alloc) - 36/272 (fetch/transfer)
10409-14 13:36:51.400 27040 27602 D BufferPoolManager: # of cleaned connections: 14
10509-14 13:36:51.400 27040 27602 D BufferPoolManager: create new connection 116137547281650
10609-14 13:36:51.400 27040 27602 D CCodecBufferChannel: [c2.android.mp3.decoder#628] Created input block pool with allocatorID 16 => poolID 32 - OK (0)
10709-14 13:36:51.402 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d06193a20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/86 (fetch/transfer)
10809-14 13:36:51.402 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d06193a20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 86, 95% unfetced
10909-14 13:36:51.402 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d08b99c20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/186 (fetch/transfer)
11009-14 13:36:51.402 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d08b99c20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 186, 98% unfetced
11109-14 13:36:51.402 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d6dd44420 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/336 (fetch/transfer)
11209-14 13:36:51.402 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d6dd44420 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 336, 99% unfetced
11309-14 13:36:51.402 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d6dd44620 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/464 (fetch/transfer)
11409-14 13:36:51.402 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d6dd44620 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 464, 99% unfetced
11509-14 13:36:51.402 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d079d5c20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/186 (fetch/transfer)
11609-14 13:36:51.402 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d079d5c20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 186, 98% unfetced
11709-14 13:36:51.402 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d079d5020 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 7/370 (fetch/transfer)
11809-14 13:36:51.402 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d079d5020 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 370, 98% unfetced
11909-14 13:36:51.403 27040 27127 D BufferPoolAccessor: bufferpool2 0x7cec6e5020 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/384 (fetch/transfer)
12009-14 13:36:51.403 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7cec6e5020 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 384, 99% unfetced
12109-14 13:36:51.403 27040 27127 D BufferPoolAccessor: bufferpool2 0x7cec706820 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/168 (fetch/transfer)
12209-14 13:36:51.403 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7cec706820 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 168, 98% unfetced
12309-14 13:36:51.403 27040 27127 D BufferPoolAccessor: bufferpool2 0x7cec706a20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/464 (fetch/transfer)
12409-14 13:36:51.403 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7cec706a20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 464, 99% unfetced
12509-14 13:36:51.403 27040 27127 D BufferPoolAccessor: bufferpool2 0x7cec74c020 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/465 (fetch/transfer)
12609-14 13:36:51.403 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7cec74c020 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 465, 99% unfetced
12709-14 13:36:51.403 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d6dd44a20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/464 (fetch/transfer)
12809-14 13:36:51.403 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d6dd44a20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 464, 99% unfetced
12909-14 13:36:51.403 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d6dd44c20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/332 (fetch/transfer)
13009-14 13:36:51.404 27040 27602 I CCodecBufferChannel: [c2.android.mp3.decoder#628] Created output block pool with allocatorID 16 => poolID 4145 - OK
13109-14 13:36:51.404 27040 27602 D CCodecBufferChannel: [c2.android.mp3.decoder#628] Configured output block pool ids 4145 => OK
13209-14 13:36:51.404 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d6dd44c20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 332, 99% unfetced
13309-14 13:36:51.404 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d6dd44e20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/466 (fetch/transfer)
13409-14 13:36:51.404 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d6dd44e20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 466, 99% unfetced
13509-14 13:36:51.404 27040 27127 D BufferPoolAccessor: bufferpool2 0x7d08b99e20 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/48 (fetch/transfer)
13609-14 13:36:51.404 27040 27127 D BufferPoolAccessor: Destruction - bufferpool2 0x7d08b99e20 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 48, 92% unfetced
13709-14 13:36:51.404 27040 27314 W Binder : Caught a RuntimeException from the binder stub implementation.
13809-14 13:36:51.404 27040 27314 W Binder : java.lang.IllegalStateException: Not in applications main thread
13909-14 13:36:51.404 27040 27314 W Binder : at me.jessyan.autosize.utils.Preconditions.checkMainThread(Preconditions.java:2)
14009-14 13:36:51.404 27040 27314 W Binder : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensity(AutoSizeCompat.java:2)
14109-14 13:36:51.404 27040 27314 W Binder : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityBaseOnWidth(AutoSizeCompat.java:1)
14209-14 13:36:51.404 27040 27314 W Binder : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:2)
14309-14 13:36:51.404 27040 27314 W Binder : at com.xxx.xxx.app.base.BaseActivity.getResources(BaseActivity.kt:1)
14409-14 13:36:51.404 27040 27314 W Binder : at com.android.internal.policy.DecorContext.getResources(DecorContext.java:90)
14509-14 13:36:51.404 27040 27314 W Binder : at android.view.ViewRootImpl.isShouldDelayMsg4SeamlessLauncher(ViewRootImpl.java:8390)
14609-14 13:36:51.404 27040 27314 W Binder : at android.view.ViewRootImpl.dispatchResized(ViewRootImpl.java:8380)
14709-14 13:36:51.404 27040 27314 W Binder : at android.view.ViewRootImpl.access$5200(ViewRootImpl.java:168)
14809-14 13:36:51.404 27040 27314 W Binder : at android.view.ViewRootImpl$W.resized(ViewRootImpl.java:9919)
14909-14 13:36:51.404 27040 27314 W Binder : at android.view.IWindow$Stub.onTransact(IWindow.java:358)
15009-14 13:36:51.404 27040 27314 W Binder : at android.os.Binder.execTransactInternal(Binder.java:1028)
15109-14 13:36:51.404 27040 27314 W Binder : at android.os.Binder.execTransact(Binder.java:1001)
15209-14 13:36:51.409 27040 27602 D BufferPoolManager: client death recipient registered 116137547281651
15309-14 13:36:51.410 27040 27127 D BufferPoolManager: register new connection 4747568440979
15409-14 13:36:51.417 27040 27566 I AudioTrack-JNI: AudioTrack_setup for usage=1 content=0 flags=0x0xa00 tags=
15509-14 13:36:51.418 27040 27040 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
15609-14 13:36:51.418 27040 27040 W InputMethodManager: startInputReason = 1
15709-14 13:36:51.431 27040 27175 W libEGL : EGLNativeWindowType 0x7d0c0e7a50 disconnect failed
15809-14 13:36:51.433 27040 27566 D PlayerBase: baseStart() piid=22391
15909-14 13:36:51.448 27040 27566 D android.media.AudioTrack: [HSM] AudioTrace play() uid: 10415, pid: 27040
16009-14 13:36:51.453 27040 27626 I CameraManager: open camera: 1, package name: com.xxx.xxx
16109-14 13:36:51.463 27040 27040 I DecorView[]: pkgName:com.xxx.xxx old windowMode:1 new windoMode:1, isFixedSize:false
16209-14 13:36:51.512 27040 27382 W Gralloc3: allocator 3.x is not supported
16309-14 13:36:51.938 27040 27569 I native : I20210914 13:36:51.938406 27569 graph.cc:474] Start running the graph, waiting for inputs.
16409-14 13:36:51.938 27040 27569 I native : I20210914 13:36:51.938593 27569 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 4
16509-14 13:36:51.940 27040 27757 I native : I20210914 13:36:51.940435 27757 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 v1.r18p0-01rel0.c3422a5a15429235949540558f14d585)
16609-14 13:36:51.941 27040 27747 I native : I20210914 13:36:51.941466 27747 jni_util.cc:41] GetEnv: not attached
16709-14 13:36:51.941 27040 27558 W native : W20210914 13:36:51.941499 27558 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; could not read asset: mediapipe/modules/pose_detection/pose_detection.tflite
16809-14 13:36:51.955 27040 27558 I native : I20210914 13:36:51.955508 27558 resource_util_android.cc:89] Successfully loaded: pose_detection.tflite
16909-14 13:36:51.965 27040 27558 I tflite : Initialized TensorFlow Lite runtime.
17009-14 13:36:51.969 27040 27558 I tflite : Created TensorFlow Lite delegate for GPU.
17109-14 13:36:51.971 27040 27558 I tflite : Replacing 229 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
17209-14 13:36:51.971 27040 27757 I native : I20210914 13:36:51.971823 27757 jni_util.cc:41] GetEnv: not attached
17309-14 13:36:52.020 27040 27745 I native : I20210914 13:36:52.020090 27745 jni_util.cc:41] GetEnv: not attached
```

**Comment by sgowroji** [comment]
Hi @ForLovelj, Could you please share  your steps to reproduce the issue. And also graph &  code changes if there are any. Thanks!

**Comment by ForLovelj** [comment]
@sgowroji Sorry, that's a low probability question. I can't reproduce the issue.
The framework code only changes this one:
```
ExternalTextureConverter:
public void setSurfaceTextureAndAttachToGLContext(
            SurfaceTexture texture, int width, int height) {
            setSurfaceTexture(texture, width, height);
            int[] textures = new int[1];
            GLES20.glGenTextures(1, textures, 0);
            surfaceTexture.attachToGLContext(textures[0]);
            // Update texture image
            surfaceTexture.updateTexImage();
        }
```

**Comment by sgowroji** [comment]
Hi @ForLovelj, Could you please verify the above issue with the latest release. Thanks!
