### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'local_config_git':  Error in fail: Git Configuration Error: Traceback (most recent call last):

### ISSUE THREAD

**Issue by DLGL99GL** [google/mediapipe#2557]
![image](https://user-images.githubusercontent.com/69023459/133763605-9a74b785-bc97-4515-a488-ed546b152cb5.png)
Ubuntu 18.04   
gcc version:7.5.0  
bazel:3.7.2 
OpenCV：3.4.15 

it's OK when I bazel build hellow world;
but is not work in other example,likes hand_tracking  :
bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \ mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

logs：
**ERROR: An error occurred during the fetch of repository 'local_config_git':**
   Traceback (most recent call last):
	File "/home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/git/git_configure.bzl", line 64, column 14, in _git_conf_impl
		_fail(result.stderr)
	File "/home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/git/git_configure.bzl", line 14, column 9, in _fail
		fail("%sGit Configuration Error:%s %s\n" % (red, no_color, msg))
**Error in fail: Git Configuration Error: Traceback (most recent call last):**
  File "/home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

INFO: Repository cpuinfo instantiated at:
  /home/test/mediapipe/WORKSPACE:403:14: in <toplevel>
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/workspace2.bzl:1088:28: in workspace
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/workspace2.bzl:59:12: in _initialize_third_party
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/cpuinfo/workspace.bzl:6:20: in repo
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/repo.bzl:66:35: in <toplevel>
INFO: Repository 'cpuinfo' used the following cache hits instead of downloading the corresponding file.
 * Hash '2a160c527d3c58085ce260f34f9e2b161adc009b34186a2baf24e74376e89e6d' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/pytorch/cpuinfo/archive/5916273f79a21551890fd3d56fc5375a78d1598d.zip
If the definition of 'cpuinfo' was updated, verify that the hashes were also updated.
INFO: Repository XNNPACK instantiated at:
  /home/test/mediapipe/WORKSPACE:403:14: in <toplevel>
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/workspace2.bzl:1095:21: in workspace
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/workspace2.bzl:130:20: in _tf_repositories
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/third_party/repo.bzl:66:35: in <toplevel>
ERROR: /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: @org_tensorflow//tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Git Configuration Error: Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: @org_tensorflow//tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/head in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Git Configuration Error: Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: /home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/core/util/BUILD:374:24: @org_tensorflow//tensorflow/core/util:version_info_gen depends on @local_config_git//:gen/branch_ref in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Git Configuration Error: Traceback (most recent call last):
  File "/home/test/.cache/bazel/_bazel_test/61253509906368cb7173caaaf2923611/external/org_tensorflow/tensorflow/tools/git/gen_git_source.py", line 32, in <module>
    from builtins import bytes  # pylint: disable=redefined-builtin
ImportError: No module named builtins

ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.722s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (113 packages loaded, 3866 targets\
 configured)
    Fetching ...puinfo; Extracting /home/test/.cache/bazel/_bazel_test/6125350\
9906368cb7173caaaf2923611/external/cpuinfo/temp621439184272611716/5916273f79a2\
1551890fd3d56fc5375a78d1598d.zip

**Comment by DLGL99GL** [comment]
oh ，Got the wrong keyword of logs,  when  I search "ImportError: No module named builtins" ,found a solution,install future ：

pip install future
