### ISSUE TITLE
Iris depth error in python 

### ISSUE THREAD

**Issue by rogomezto** [google/mediapipe#2570]
I'm trying to use iris depth in python through a webcam (using [this ](https://github.com/google/mediapipe/issues/1530#issuecomment-790210796)compilation guide) and after processing the first frame it crashes and give me the following error:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20210921 13:05:15.929889   812 calculator_graph.cc:804] ALREADY_EXISTS: CalculatorGraph::Run() failed in Run:
; Output side packet "image_file_properties" was already set.
Traceback (most recent call last):
  File "C:\Users\Roberto\Documents\testing\iris_mediapipe\deteccionOjoRabbitMQ.py", line 135, in <module>
    ch.start_consuming()
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\pika\adapters\blocking_connection.py", line 1865, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\pika\adapters\blocking_connection.py", line 2026, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\pika\adapters\blocking_connection.py", line 833, in process_data_events
    self._dispatch_channel_events()
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\pika\adapters\blocking_connection.py", line 567, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\pika\adapters\blocking_connection.py", line 1492, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "C:\Users\Roberto\Documents\testing\iris_mediapipe\deteccionOjoRabbitMQ.py", line 69, in callback
    result = iris.process(body)
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solutions\iris.py", line 34, in process
    return super().process(input_data={'input_image_bytes': image})
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 334, in process
    self._graph.wait_until_idle()
FileExistsError: CalculatorGraph::Run() failed in Run:
; Output side packet "image_file_properties" was already set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Roberto\Documents\testing\iris_mediapipe\deteccionOjoRabbitMQ.py", line 135, in <module>
    ch.start_consuming()
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 546, in __exit__
    self.close()
  File "C:\Users\Roberto\AppData\Local\Programs\Python\Python39\lib\site-packages\mediapipe\python\solution_base.py", line 352, in close
    self._graph.close()
FileExistsError: CalculatorGraph::Run() failed in Run:
; Output side packet "image_file_properties" was already set.
```
Can someone help me to solve this error?

**Comment by sgowroji** [comment]
Hi @rogomezto, Can you try testing the IRIS as mentioned here https://github.com/google/mediapipe/issues/2605#issuecomment-938049615
