### ISSUE TITLE
Android: An error occurred during the fetch of repository 'XNNPACK'

### ISSUE THREAD

**Issue by mnayef95impressions** [google/mediapipe#2629]
**System information**
- OS Platform and Distribution: macOS Big Sur 11.5.2 (20G95)
- Compiler version: 12.0.5 (clang-1205.0.22.11)
- Programming Language and version: Java 11.0.10 2021-01-19
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest
- Bazel version: bazel 3.7.2
- Android SDK and NDK versions: SDK (30), ndk (21.4.7075529) 

**Describe the problem**:
Failed after run this command:
```
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectioncpu:objectdetectioncpu
```
```
Starting local Bazel server and connecting to it...
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:109:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
INFO: Repository XNNPACK instantiated at:
  /Users/mnayef95/mediapipe/WORKSPACE:405:14: in <toplevel>
  /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/tensorflow/workspace2.bzl:1095:21: in workspace
  /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/tensorflow/workspace2.bzl:130:20: in _tf_repositories
  /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl:66:35: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/28407b24f04694a1353ffca91248e89bc250eb5b.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'XNNPACK':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_mnayef95/4fb57cf6de750d889237ef2deda5e8af/external/org_tensorflow/third_party/repo.bzl", line 53, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: thread interrupted
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@google_toolbox_for_mac//:GTM_Defines, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:MPPGraphGPUData, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:582)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:273)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:377)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1043)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1087)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:973)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:374)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:193)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more

INFO: Elapsed time: 18.018s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (172 packages loaded, 13122 target\
s configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@google_toolbox_for_mac//:GTM_Defines, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:MPPGraphGPUData, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:582)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:273)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:377)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1043)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1087)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:973)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:374)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:193)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=@google_toolbox_for_mac//:GTM_Defines, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:MPPGraphGPUData, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[5d8be7d3b63d22369e641ffa4417bfdc2125aa849a4e329efa43184a4871cf75]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:513)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:582)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:273)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:377)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1043)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1087)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:973)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:374)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:193)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:938)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1013)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$EvaluateFAILED: Build did NOT complete successfully (172 packages loaded, 13122 target\
s configured)
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

```
export ANDROID_NDK_HOME=
export ANDROID_HOME=
```

**Comment by sgowroji** [comment]
Hi @mnayef95impressions, Could you please have a look at this https://github.com/google/mediapipe/issues/54#issuecomment-705064578 and try the workaround mentioned in it. Thanks!
