### ISSUE TITLE
Which deprecation warning breaks python_configure.bzl _check_python_bin()

### ISSUE THREAD

**Issue by simlevesque** [google/mediapipe#2777]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Ubuntu 21.04
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): GCC 11.2
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 3.9.8, openjdk 11.0.10
- Installed using virtualenv? pip? Conda? (if python): no
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.8
- Bazel version: bazel 3.7.2
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:

The new Debian `which` utility throws a warning message in stderr: 
```
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
```

For more info on this, checkout this LWN article from two weeks ago named "Debian's which hunt": https://lwn.net/Articles/874049/

 If I substitute the which binary for a bash script calling that binary and redirecting stderr to null, it works as always.

Example fix:

```
#!/bin/bash

/usr/bin/which_backup $1 2>/dev/null
```

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

Running `./build_android_examples.sh`. It worked just before I updated `which`.

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

```
~/w/mediapipe master• ❱ ./build_android_examples.sh
app_dir: mediapipe/examples/android/src/java/com/google/mediapipe/apps
out_dir: .
strip: true
Switching to OpenCV 3
=== Target: mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip) = c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/deagle/web/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/main.zip) = 3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
DEBUG: Repository rules_cc instantiated at:
  /home/deagle/web/mediapipe/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository local_execution_config_python instantiated at:
  /home/deagle/web/mediapipe/WORKSPACE:408:14: in <toplevel>
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/tensorflow/workspace2.bzl:1085:19: in workspace
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
		_check_python_bin(repository_ctx, python_bin)
	File "/home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/py/python_configure.bzl", line 143, column 52, in _check_python_bin
		result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
	File "/home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/remote_config/common.bzl", line 88, column 26, in get_bash_bin
		bash_bin_path = which(repository_ctx, "bash")
	File "/home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/remote_config/common.bzl", line 36, column 18, in which
		out = execute(
	File "/home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
INFO: Repository rules_java instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:269:6: in <toplevel>
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962d37/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'rules_java' used the following cache hits instead of downloading the corresponding file.
 * Hash 'bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598' for https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip
If the definition of 'rules_java' was updated, verify that the hashes were also updated.
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld' failed; build aborted: Repository command failed
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
INFO: Elapsed time: 5.264s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 12 targets configured)
    currently loading: @rules_foreign_cc//tools/build_defs/shell_toolchain/toolchains ... (2 packages)
    Fetching @androidsdk; Restarting.
    Fetching ...s_java; Extracting /home/deagle/.cache/bazel/_bazel_deagle/0f8a4212a5a7c782e03841d221962\
d37/external/rules_java/temp14524008665011611532/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip

```

**Comment by simlevesque** [comment]
The real fix would be to rely on 'command -v' since it is in the POSIX standard and should work forever.

**Comment by sgowroji** [comment]
Hi @simlevesque,  Glad to know you resolved. Thank you for sharing the resolution which will help the community. https://github.com/google/mediapipe/issues/2777#issuecomment-969377436
