### ISSUE TITLE
Application crash with  cannot locate symbol "_ZN2cv19getRotationMatrix2DENS_6Point_IfEEdd message

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#278]
Hi,
I am getting following crash and I do not have any knowledge about why it is getting crashed
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol 
                   "_ZN2cv19getRotationMatrix2DENS_6Point_IfEEdd" referenced by 
                  "/data/app/com.example.faceapp- 
                   qU8aUM8ct6Np0SVrAu0umA==/lib/arm64/libmediapipe_jni.so"...
                   at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
                   at java.lang.System.loadLibrary(System.java:1669)
                   at com.example.faceapp.MainActivity.<clinit>(MainActivity.java:50)

**Comment by suraj-0387** [comment]
This answer is form them who might face same issue.We succeeded when we change facedetectiongpu to facedetectioncpu in the below command.

        bazel build -c opt 
        mediapipe/examples/android/src/java/com/google/mediapipe/apps/
        facedetectiongpu:binary_graph
        cp bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/
        apps/facedetectiongpu/facedetectiongpu.binarypb /path/to/your/app/src/main/assets/
        cp mediapipe/models/face_detection_front.tflite /path/to/your/app/src/main/assets/
        cp mediapipe/models/face_detection_front_labelmap.txt /path/to/your/app/src/main/assets/

**Comment by suraj-0387** [comment]
Issue is fixed
