### ISSUE TITLE
An error occurred during the fetch of repository 'local_execution_config_python':

### ISSUE THREAD

**Issue by pekochun** [google/mediapipe#2806]
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4):
- Windows and WSL(Ubuntu)
- 
- Bazel version:
Bazelisk version: development
Build label: 3.7.2
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 17 16:57:23 2020 (1608224243)
Build timestamp: 1608224243
Build timestamp as int: 1608224243

**Describe the problem**:
I ran the following command in Windows WSL.

`bazel build -c opt --config=android_arm64 --define 3D=true mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu`

Then I got the following error message.
```
emoto@DESKTOP-O3JDT6Q:~/mediapipe$ bazel build -c opt --config=android_arm64 --define 3D=true mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  /home/emoto/mediapipe/WORKSPACE:409:14: in <toplevel>
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/tensorflow/workspace2.bzl:1085:19: in workspace
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 1.558s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 12 targets configured)
```
I have set up a Python action_env, referring to the troubleshooting section. 
https://google.github.io/mediapipe/getting_started/troubleshooting.html

The code I ran looks like this, but I get the exact same error.
`bazel build -c opt --config=android_arm64 --define 3D=true --action_env PYTHON_BIN_PATH="C:/Users/emoto/AppData/Local/Microsoft/WindowsApps/python.exe" mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu`

The error message looks something like this
```
oto@DESKTOP-O3JDT6Q:~/mediapipe$ bazel build -c opt --config=android_arm64 --define 3D=true --action_env PYTHON_BIN_PATH="C:/Users/emoto/AppData/Local/Microsoft/WindowsApps/python.exe" mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'bazel_skylib' because it already exists.
DEBUG: /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/repo.bzl:109:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  /home/emoto/mediapipe/WORKSPACE:409:14: in <toplevel>
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/tensorflow/workspace2.bzl:1085:19: in workspace
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/tensorflow/workspace2.bzl:85:27: in _tf_toolchains
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/py/python_configure.bzl", line 209, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "/home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "/home/emoto/.cache/bazel/_bazel_emoto/f422d987460e9e43f8ecbef2688bd1f7/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/emoto/AppData/Local/Microsoft/WindowsApps/python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facemeshgpu:facemeshgpu' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/emoto/AppData/Local/Microsoft/WindowsApps/python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 0.642s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 12 targets configured)
```

Is there any way to fix this error?

**Comment by pekochun** [comment]
Doing this solved the problem.

```
echo $PYTHON_BIN_PATH
export PYTHON_BIN_PATH=/usr/bin/python3
pip3 install numpy
$PYTHON_BIN_PATH -c 'import numpy'
```
