### ISSUE TITLE
Bazel crashed while installing building an android example

### ISSUE THREAD

**Issue by khkred** [google/mediapipe#2923]
**System information** (Please provide as much relevant information as possible)
- macOS Monterey 12.0.1
- Bazel version: 4.2.1
- Android SDK and NDK versions (if android): SDK: 30.0.3, NDK: 21.3.6528147

I was following this [link](https://google.github.io/mediapipe/getting_started/android.html#prerequisite) to install the first app.

When I faced the following error:
`FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ConfiguredTargetKey{label=//mediapipe/gpu:pixel_buffer_pool_util, config=BuildConfigurationValue.Key[1aa35b811f55b9291edee3b2d6b7a72975310b735c19e56f18c38321f11b55e6]}' (requested by nodes 'ConfiguredTargetKey{label=//mediapipe/gpu:gpu_buffer_multi_pool, config=BuildConfigurationValue.Key[1aa35b811f55b9291edee3b2d6b7a72975310b735c19e56f18c38321f11b55e6]}', 'ConfiguredTargetKey{label=//mediapipe/objc:mediapipe_framework_ios, config=BuildConfigurationValue.Key[1aa35b811f55b9291edee3b2d6b7a72975310b735c19e56f18c38321f11b55e6]}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:574)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:268)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:372)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1006)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1068)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:954)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:81)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:42)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:385)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:195)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:940)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1031)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:371)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 7 more`

**Comment by sgowroji** [comment]
Hi @khkred, Please have a look at this similar issue which as  resolution https://github.com/google/mediapipe/issues/54#issuecomment-705064578

**Comment by khkred** [comment]
I have installed Xcode but even now I get the following errors.

`WARNING: /Users/khkr/Coding/MediaPipeProjects/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
ERROR: /private/var/tmp/_bazel_khkr/e3f1093244af17366cbc5979ef177ba4/external/google_toolbox_for_mac/BUILD.bazel:21:13: in objc_library rule @google_toolbox_for_mac//:GTM_Defines: Expected action_config for 'objc-fully-link' to be configured
ERROR: /private/var/tmp/_bazel_khkr/e3f1093244af17366cbc5979ef177ba4/external/google_toolbox_for_mac/BUILD.bazel:21:13: in objc_library rule @google_toolbox_for_mac//:GTM_Defines: Expected action_config for 'c++-link-static-library' to be configured
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: Analysis of target '@google_toolbox_for_mac//:GTM_Defines' failed
INFO: Elapsed time: 0.776s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 8923 targets configured)`

**Comment by sgowroji** [comment]
Hi @khkred, Could you please confirm if you still see the above error while building the Handtrackinggpu code.  Did you try above commands by executing " bazel clean --expunge" .

**Comment by khkred** [comment]
Yes I did. I had to downgrade my Android SDK, it's working now.

**Comment by sgowroji** [comment]
Glad that worked. Thank you for the update. We are closing this issue now.
