### ISSUE TITLE
libmediapipe_jni.so not found after building an android archive for hair segmentation solution

### ISSUE THREAD

**Issue by ya332** [google/mediapipe#2976]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Windows 11, Android 11 API 30
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): 
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):Python 3.6, 
- java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

- Installed using virtualenv? pip? Conda? (if python):pip
- [MediaPipe version](https://github.com/google/mediapipe/releases):v0.8.9
- Bazel version: Build label: 4.2.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:17:47 2021 (1630336667)
Build timestamp: 1630336667
Build timestamp as int: 1630336667
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android): Android Studio Arctic Fox | 2020.3.1 Patch 3
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):hair_segmentation.aar
- OpenCV version (if running on desktop):

**Describe the problem**:

I am using a custom aar for the hair segmentation solution. I built the aar by following these steps (https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-build-a-mediapipe-aar) and now I am trying to use it as a library again by using the same instructions here: https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-build-a-mediapipe-aar 
 You can find my full code here: 
https://github.com/ya332/hairsegmentation

I tracked a similar issue opened against another aar example, but it was not provided an answer.
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example/issues/4

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
git clone this repo: `https://github.com/ya332/hairsegmentation`
Open it Android Studio and Build -> Clean Project and Build -> Rebuild Project. 
Run app. 
Error is produced. 
**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
Source code: `https://github.com/ya332/hairsegmentation`
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.introtuce.mediapipesegmentationgradle, PID: 6777
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at co.introtuce.mediapipesegmentationgradle.MainActivity.<clinit>(MainActivity.java:36)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by sgowroji** [comment]
Hi @ya332,  Similar https://github.com/google/mediapipe/issues/1224

**Comment by ya332** [comment]
Thank you. I am closing the issue.
