### ISSUE TITLE
Face Mesh pipeline: turning refined landmarks off yields an exception in python

### ISSUE THREAD

**Issue by matanster** [google/mediapipe#3006]
In the face mesh solution, running the provided [python sample code](https://google.github.io/mediapipe/solutions/face_mesh.html#python-solution-api) seems to run into the following error, if `refine_landmarks` is set to `False`:

> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "face_landmarks.py", line 48, in <module>
    mp_drawing.draw_landmarks(
  File "mediapipe/python/solutions/drawing_utils.py", line 176, in draw_landmarks
    raise ValueError(f'Landmark index is out of range. Invalid connection '
ValueError: Landmark index is out of range. Invalid connection from landmark #475 to landmark #476.

## System information 
- The example solution code from above, with only the single above mentioned value changed.
- Ubuntu 20.04
- MediaPipe version 0.8.9
- Python 3.8.3

**Comment by matanster** [comment]
# Solution
Obviously one has to remove the drawing of the detailed eye landmarks (iris landmarks) which are not calculated/detected, when choosing to set refined landmarks to off:

```python
        mp_drawing.draw_landmarks(
            image=image,
            landmark_list=face_landmarks,
            connections=mp_face_mesh.FACEMESH_CONTOURS,
            landmark_drawing_spec=None,
            connection_drawing_spec=mp_drawing_styles
            .get_default_face_mesh_contours_style())
```
