### ISSUE TITLE
Building for GPU causes problems - An error occurred during the fetch of repository 'local_config_cuda'

### ISSUE THREAD

**Issue by KulkarniKaustubh** [google/mediapipe#3044]
**System information** (Please provide as much relevant information as possible)
- Linux Tensorflow container tensorflow/tensorflow:2.2.3-gpu
- g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- Python 3.6.9
- No virtual environment
- Cloned the mediapipe repository and ran commands inside this repository
- Bazel version: 4.2.1
- OpenCV version (if running on desktop): used `pip install opencv-python` `opencv-python==4.5.5.62`
- CUDA version: 10.1

The first error out of all the errors is as follows:

`ERROR: An error occurred during the fetch of repository 'local_config_cuda'`

Sequence of commands:

```
apt update && apt install -y ffmpeg git vim

pip install -U pip
pip install opencv-python numpy

apt install apt-transport-https curl gnupg
curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
mv bazel.gpg /etc/apt/trusted.gpg.d/
echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
ln -s /usr/bin/bazel-4.2.1 /usr/bin/bazel

echo "export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}" >> /root/.bashrc
echo " export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64,/usr/local/cuda10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> /root/.bashrc

ldconfig

echo "export TF_CUDA_PATHS=/usr/local/cuda-10.1,/usr/lib/x86_64-linux-gnu,/usr/include" >> /root/.bashrc

```

Then copied the following in .bazelrc of mediapipe's repository:

```
# This config refers to building with CUDA available. It does not necessarily
# mean that we build CUDA op kernels.
build:using_cuda --define=using_cuda=true
build:using_cuda --action_env TF_NEED_CUDA=1
build:using_cuda --crosstool_top=@local_config_cuda//crosstool:toolchain

# This config refers to building CUDA op kernels with nvcc.
build:cuda --config=using_cuda
build:cuda --define=using_cuda_nvcc=true
```

Then ran the build command:
```
bazel build -c opt --config=cuda --spawn_strategy=local \
    --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS \
    mediapipe/examples/desktop/object_detection:object_detection_tensorflow
```

Output of the build command:
```
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_foreign_cc/archive/0.1.0.zip) = c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /workspace/repos/mp_repository/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/repo.bzl:122:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/main.zip) = 3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3839996049629e6377abdfd04681ddeeb0cc3db13b9d2ff81bf46700cb4529f7"
DEBUG: Repository rules_cc instantiated at:
  /workspace/repos/mp_repository/WORKSPACE:36:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository local_config_cuda instantiated at:
  /workspace/repos/mp_repository/WORKSPACE:400:14: in <toplevel>
  /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/tensorflow/workspace2.bzl:876:19: in workspace
  /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/tensorflow/workspace2.bzl:94:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 978, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/include'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda-10.1'
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 978, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/include'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda-10.1'
INFO: Repository com_google_protobuf instantiated at:
  /workspace/repos/mp_repository/WORKSPACE:130:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/a2f8fa5a97866f12e9a3fc36bb89d415/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /workspace/repos/mp_repository/mediapipe/examples/desktop/object_detection/BUILD:19:10: //mediapipe/examples/desktop/object_detection:object_detection_tensorflow depends on @local_config_cuda//crosstool:toolchain in repository @local_config_cuda which failed to fetch. no such package '@local_config_cuda//crosstool': Repository command failed
Could not find any cublas_api.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/include'
        '/usr/lib/x86_64-linux-gnu'
        '/usr/local/cuda-10.1'
ERROR: Analysis of target '//mediapipe/examples/desktop/object_detection:object_detection_tensorflow' failed; build aborted: Analysis failed
INFO: Elapsed time: 13.361s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (21 packages loaded, 52 targets configured)
    currently loading: @org_tensorflow//tensorflow/core
    Fetching @local_config_cc; fetching
```

**Comment by sgowroji** [comment]
Hi @KulkarniKaustubh, Did you get a chance to refer the similar issue https://github.com/google/mediapipe/issues/852#issuecomment-651919898.

**Comment by KulkarniKaustubh** [comment]
Yes, I tried replacing `cuda_config.cudnn_version` with `'8'` as suggested, but this did not work.

After seeing some of the comments in the issue you have mentioned, I think I need to mention that I am trying to get the blazepose human pose estimation model to work on the GPU, not just object detection. Am I going about this the wrong way?

**Comment by sgowroji** [comment]
Yes, From the above commands i see you are trying to build object detection not pose. For Pose on desktop you should refer this https://google.github.io/mediapipe/solutions/pose#desktop

**Comment by KulkarniKaustubh** [comment]
The thing is, I need a Python interface of Medipipe that runs BlazePose inference on the GPU, using CUDA. Is that possible?

**Comment by mcdonasd1212** [comment]
@KulkarniKaustubh  I am curious about the solution you find.  I see you commented on my post #3020.   I have moved onto to using OpenGL https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-821/install-guide/index.html.  But I really would like a CUDA solution.

**Comment by KulkarniKaustubh** [comment]
Any updates on this?

**Comment by mcdonasd1212** [comment]
I am having the same issue.

I have mediapipe pose running on a machine with an i5 cpu and GTX 1660 gpu. I followed the Open GL instructions since I could not get a successful build with tensorflow. With the light model, gpu usage is around 23% and fps is 25-27 fps.

For our implementation we need 30+ fps. Any recommendations?

**Comment by khayyat71** [comment]
> 

I'm facing the same!
Did you find any solution?

**Comment by kuaashish** [comment]
Hello @KulkarniKaustubh,
We are upgrading the [MediaPipe Legacy Solutions](https://developers.google.com/mediapipe/solutions/guide#legacy) to [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) However, the libraries, documentation, and source code for all the MediapPipe Legacy Solutions will continue to be available in our [GitHub repository](https://github.com/google/mediapipe) and through library distribution services, such as [Maven](https://maven.google.com/web/index.html?#com.google.mediapipe) and [NPM](https://www.npmjs.com/search?q=%40mediapipe).

You can continue to use those legacy solutions in your applications if you choose. Though, we would request you to check [new MediaPipe solutions](https://developers.google.com/mediapipe/solutions) which can help you more easily build and customize ML solutions for your applications. These new solutions will provide a superset of capabilities available in the legacy solutions. Thank you
