### ISSUE TITLE
Building Python Package

### ISSUE THREAD

**Issue by tom-doerr** [google/mediapipe#3102]
## URL(s) with the issue:
https://google.github.io/mediapipe/getting_started/gpu_support.html
https://google.github.io/mediapipe/getting_started/python.html

## Description of issue (what needs changing):

Unclear how to build Python package with GPU support.

### Clear description

To me it's not clear from the documentation how to build the Python package with GPU support.
I can successfully build the project (1. link) with GPU support using 
```
bazel run --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \
    mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu 
```
but when I run `pip3 install -e .` in the root, the command doesn't return.
When following the guide for building the Python package (2. link) the package is successfully installed but doesn't use the GPU.
Are users supposed to modify the `setup.py` to change the bazel command that is run?

Edit:
`pip3 install -e .` eventually returns, but the installed package throws the error
```
Traceback (most recent call last):
  File "/home/tom/git/dl_input/media_pipe_test.py", line 19, in <module>
    mp_drawing = mediapipe.solutions.drawing_utils
AttributeError: module 'mediapipe' has no attribute 'solutions'

```
.

**Comment by sureshdagooglecom** [comment]
Hi @tom-doerr ,can you please check this [issue](https://github.com/google/mediapipe/issues/2954) once.

**Comment by tom-doerr** [comment]
When I print the path 
```
print(mediapipe.__path__)
```
I get 
```
['/home/tom/git/mediapipe/mediapipe']
```
which is what I would expect. It's the mediapipe folder in the mediapipe git repo.

**Comment by sureshdagooglecom** [comment]
@tom-doerr , could you provide your code changes to investigate further.

**Comment by tom-doerr** [comment]
This is what I'm doing:
```
#!/bin/bash

git clone --depth 1 git@github.com:google/mediapipe.git 
cd mediapipe

pip3 install -e . 

cd /
ls 

python3 -c "import mediapipe; print(mediapipe.__path__); mp_drawing = mediapipe.solutions.drawing_utils"
```
This is the output that I get:
```
...
Installing collected packages: mediapipe
  Attempting uninstall: mediapipe
    Found existing installation: mediapipe dev
    Uninstalling mediapipe-dev:
      Successfully uninstalled mediapipe-dev
  Running setup.py develop for mediapipe
Successfully installed mediapipe
bin   cdrom  etc   lib	 lib64   lost+found  mnt  proc  run   snap  swapfile  timeshift  usr
boot  dev    home  lib32  libx32  media       opt  root  sbin  srv   sys       tmp	 var
['/home/tom/test/mediapipe_test/mediapipe/mediapipe']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'mediapipe' has no attribute 'solutions'
```

**Comment by tom-doerr** [comment]
Instead of installing mediapipe with `pip install -e .` I now tried to install it using
```
python3 setup.py gen_protos
python3 setup.py install --link-opencv
```
but with a modified `setup.py`. I remove the two lines `'--define=MEDIAPIPE_DISABLE_GPU=1',` from the script, which seems to trigger the build for GPU.
However now I'm getting the following error:
```
...
WARNING: /home/tom/git/mediapipe_4/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /home/tom/git/mediapipe_4/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/modules/face_detection:face_detection_short_range_cpu (129 packages loaded, 5521 targets configured).
INFO: Found 1 target...
ERROR: /home/tom/.cache/bazel/_bazel_tom/a5446076a6846dfb6c126d4617c0ca65/external/org_tensorflow/tensorflow/lite/delegates/gpu/BUILD:177:11: Compiling tensorflow/lite/delegates/gpu/api.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 53 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/opencl_headers/CL/cl.h:32,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.cc:16:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |                                                                                                        ^
In file included from /usr/include/EGL/eglplatform.h:128,
                 from /usr/include/EGL/egl.h:39,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/portable_gl31.h:21,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:50,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.cc:16:
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:261:17: error: expected unqualified-id before 'int'
  261 |   virtual absl::Status SetInputShape(int index,
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:271:17: error: expected unqualified-id before 'int'
  271 |   virtual absl::Status SetInputObjectDef(int index, ObjectDef def) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:272:17: error: expected unqualified-id before 'int'
  272 |   virtual absl::Status SetOutputObjectDef(int index, ObjectDef def) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:273:17: error: expected unqualified-id before 'int'
  273 |   virtual absl::Status SetAllInputObjectDefsTo(ObjectDef def) {
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:280:17: error: expected unqualified-id before 'int'
  280 |   virtual absl::Status SetAllOutputObjectDefsTo(ObjectDef def) {
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:293:17: error: expected unqualified-id before 'int'
  293 |   virtual absl::Status Build(std::unique_ptr<InferenceRunner>* runner) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:310:17: error: expected unqualified-id before 'int'
  310 |   virtual absl::Status GetInputObject(int index, TensorObject* object) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:311:17: error: expected unqualified-id before 'int'
  311 |   virtual absl::Status GetOutputObject(int index, TensorObject* object) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:312:17: error: expected unqualified-id before 'int'
  312 |   virtual absl::Status SetInputObject(int index, TensorObject object) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:313:17: error: expected unqualified-id before 'int'
  313 |   virtual absl::Status SetOutputObject(int index, TensorObject object) = 0;
      |                 ^~~~~~
external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:315:17: error: expected unqualified-id before 'int'
  315 |   virtual absl::Status Run() = 0;
      |                 ^~~~~~
Target //mediapipe/modules/face_detection:face_detection_short_range_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 79.289s, Critical Path: 48.93s
INFO: 1117 processes: 271 internal, 846 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by tom-doerr** [comment]
### Summary
Steps to build python package with GPU support:
```
git clone --depth 1 git@github.com:google/mediapipe.git
cd mediapipe
```

In the file `setup.py`, replace all lines 
```
'--define=MEDIAPIPE_DISABLE_GPU=1',
```
with 
```
'--copt=-DMESA_EGL_NO_X11_HEADERS',
'--copt=-DEGL_NO_X11',   
```

Run
```
python3 setup.py gen_protos
python3 setup.py install --link-opencv
```

**Comment by sureshdagooglecom** [comment]
Hi @tom-doerr ,Can you please share  which version of mediapipe you are using.

**Comment by tom-doerr** [comment]
I'm using mediapipe 0.8.9, hash of the git HEAD: `e6c19885c6d3c6f410c730952aeed2852790d306`

**Comment by sureshdagooglecom** [comment]
Hi @tom-doerr , Please follow this steps mentioned in this https://github.com/google/mediapipe/issues/724.

**Comment by mcdonasd1212** [comment]
> Hi @tom-doerr , Please follow this steps mentioned in this https://github.com/google/mediapipe/issues/724.

This reference is for windows what about Ubuntu?
