### ISSUE TITLE
Issues with Nextjs and usestate hook

### ISSUE THREAD

**Issue by dr804** [google/mediapipe#3110]
I am using the holistic solution with the CDN delivered file. I have implemented it as part of a Nextjs project. The page works fine, but as soon as I start using the usestate hook, it gives the following error:

RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.js:9:69364)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.js:9:69540)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.js:9:43094)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.js:9:180749)
    at https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.wasm:wasm-function[8271]:0x5686f9
    at https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.wasm:wasm-function[8269]:0x56859e
    at https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.wasm:wasm-function[8273]:0x568712
    at https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.wasm:wasm-function[225]:0x1ce27
    at https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.wasm:wasm-function[195]:0x17ecd
    at SolutionWasm$send [as send] (eval at new_ [(https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.js:9:161523),](http://localhost:3000/(https://cdn.jsdelivr.net/npm/@mediapipe/holistic@0.5.1635989137/holistic_solution_simd_wasm_bin.js:9:161523),) <anonymous>:9:1)
    at oa.eval [as h] (webpack-internal:///./node_modules/@mediapipe/holistic/holistic.js:74:19)
    at ra (webpack-internal:///./node_modules/@mediapipe/holistic/holistic.js:14:299)
    at sa.next (webpack-internal:///./node_modules/@mediapipe/holistic/holistic.js:15:91)
    at b (webpack-internal:///./node_modules/@mediapipe/holistic/holistic.js:15:330)

**Comment by dr804** [comment]
May have found a fix for this, will update this thread if it doesn't work, otherwise I will close it.

**Comment by sureshdagooglecom** [comment]
Hi @dr804 , please provide steps to reproduce this issue.
