### ISSUE TITLE
Trying to run inference with Android Gradle Hands Solution; Error occurs in the solution graph. Error details: internal: CalculatorGraph::Run() failed in Run

### ISSUE THREAD

**Issue by asluborski98** [google/mediapipe#3153]
Hello, I am trying to run hands solution in Android Studio. I got the application built and can get it to launch with emulator and my webcam camera enabled as emulator webcam. No matter which 3 of the buttons I choose, the app crashes and I get multiple errors relating to GL2/egl, and the calculator::open(). I am not sure what the issue is as I am new to Android dev and suspecting it might just be the emulator?

- I am running Android Studio bumblebee 2021 11.0.1 AMD runtime w/ OpenJDK 64-bit server
- My min SDK is 21 and targetSdk is 30 
- The emulator I have tried is Nexus 5 API 29 and Pixel XL API 30 
- Latest release
- Hands Solution
- Java/Android 

Here is the error log I get 

```
03/08 00:02:53: Launching 'hands' on Nexus 5 API 29.
Install successfully finished in 8 s 583 ms.
$ adb shell am start -n "com.google.mediapipe.apps.hands/com.google.mediapipe.examples.hands.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4749 on device 'Nexus_5_API_29 [emulator-5558]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/pipe.apps.hand: Late-enabling -Xcheck:jni
E/pipe.apps.hand: Unknown bits set in runtime_flags: 0x8000
W/pipe.apps.hand: Unexpected CPU variant for X86 using defaults: x86
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/pipe.apps.hand: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/RenderThread: type=1400 audit(0.0:20): avc: denied { write } for name="property_service" dev="tmpfs" ino=8441 scontext=u:r:untrusted_app:s0:c134,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
D/HostConnection: HostConnection::get() New Host Connection established 0xda521f00, tid 4814
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xe5b30b00: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe5b30b00: ver 3 0 (tinfo 0xda58b760)
W/Gralloc3: mapper 3.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xda523a80, tid 4814
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3ff805000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0xe5b30b00: ver 3 0 (tinfo 0xda58b760)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->objectFieldOffset(Ljava/lang/reflect/Field;)J (greylist,core-platform-api, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->peekLong(JZ)J (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->pokeLong(JJZ)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->pokeInt(JIZ)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->peekInt(JZ)I (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->peekByte(J)B (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->pokeByteArray(J[BII)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Llibcore/io/Memory;->peekByteArray(J[BII)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->arrayBaseOffset(Ljava/lang/Class;)I (greylist,core-platform-api, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->arrayIndexScale(Ljava/lang/Class;)I (greylist, linking, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection, allowed)
W/pipe.apps.hand: Accessing hidden field Ljava/nio/Buffer;->address:J (greylist, reflection, allowed)
I/native: I20220308 05:04:04.640043  4749 asset_manager_util.cc:59] Created global reference to asset manager.
D/HostConnection: HostConnection::get() New Host Connection established 0xda524200, tid 4749
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xf0d530e0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xf0d530e0: ver 3 0 (tinfo 0xda5a8950)
E/libEGL: validate_display:91 error 3008 (EGL_BAD_DISPLAY)
I/native: I20220308 05:04:04.663566  4749 gl_context_egl.cc:162] Successfully initialized EGL. Major : 1 Minor: 4
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xf0d53260: maj 3 min 0 rcv 3
D/HostConnection: HostConnection::get() New Host Connection established 0xda524930, tid 7541
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: eglMakeCurrent: 0xf0d53260: ver 3 0 (tinfo 0xc6354be0)
I/native: I20220308 05:04:04.680604  7541 gl_context.cc:334] GL version: 3.0 (OpenGL ES 3.0 (4.5.0 NVIDIA 510.54))
I/native: I20220308 05:04:04.687937  4749 graph.cc:476] Start running the graph, waiting for inputs.
I/native: I20220308 05:04:04.705732  7544 resource_util_android.cc:89] Successfully loaded: palm_detection_full.tflite
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBindBuffer:546 GL error 0x500
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glBufferData:571 GL error 0x500
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000090d3
E/eglCodecCommon: glUtilsParamSize: unknow param 0x000090d3
I/native: I20220308 05:04:04.711028  7542 resource_util_android.cc:89] Successfully loaded: hand_landmark_full.tflite
E/native: E20220308 05:04:04.712111  4749 calculator_graph.cc:805] INTERNAL: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
E/SolutionBase: Error occurs while starting the MediaPipe solution graph. Error details: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:452)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.solutions.hands.Hands.<init>(Hands.java:155)
        at com.google.mediapipe.examples.hands.MainActivity.setupStaticImageModePipeline(MainActivity.java:199)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupStaticImageDemoUiComponents$2$MainActivity(MainActivity.java:178)
        at com.google.mediapipe.examples.hands.-$$Lambda$MainActivity$XUSpvKWFkD59akqMXzYYnGSm0eA.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.hands, PID: 4749
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarktrackinggpu__palmdetectiongpu__inferencecalculator__handlandmarktrackinggpu__palmdetectiongpu__InferenceCalculator" failed: ; (TfLiteGpuDelegateBindBufferToTensor( delegate_.get(), gpu_buffers_in_.back()->GetOpenGlBufferWriteView().name(), interpreter_->inputs()[i]))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:452)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.solutions.hands.Hands.<init>(Hands.java:155)
        at com.google.mediapipe.examples.hands.MainActivity.setupStaticImageModePipeline(MainActivity.java:199)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupStaticImageDemoUiComponents$2$MainActivity(MainActivity.java:178)
        at com.google.mediapipe.examples.hands.-$$Lambda$MainActivity$XUSpvKWFkD59akqMXzYYnGSm0eA.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=COREML_ON_DEVICE_SOLUTIONS for destination cct
I/Process: Sending signal. PID: 4749 SIG: 9
```

**Comment by sureshdagooglecom** [comment]
Hi @asluborski98 , did you get a chance to check this closed issue https://github.com/google/mediapipe/issues/1224#issuecomment-745168596

**Comment by asluborski98** [comment]
Thanks I got it to work but camera is still failing on emulator. not sure if it is possible to use camera? I went into my device properties and set webcam as webcam0 for both front and back which is my own webcam. I also tried using emulated webcam for both front and back. 


Is it possible to run using android emulator and your webcam camera?

Here is the specific error I am getting
```
E/EGL_emulation: eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation: tid 10572: eglQueryContext(1902): error 0x3004 (EGL_BAD_ATTRIBUTE)
I/CameraManagerGlobal: Connecting to camera service
D/CameraRepository: Added camera: 0
I/Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED
D/UseCaseAttachState: Active and attached use case: [] for camera: 0
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.hands, PID: 10349
    java.lang.IllegalArgumentException: No available camera can be found.
        at androidx.camera.core.CameraSelector.filter(CameraSelector.java:100)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:389)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:275)
        at com.google.mediapipe.components.CameraXPreviewHelper.lambda$startCamera$4$CameraXPreviewHelper(CameraXPreviewHelper.java:317)
        at com.google.mediapipe.components.-$$Lambda$CameraXPreviewHelper$XxlOsze8Y8Q9eLsR5HjR1U3b8zU.run(Unknown Source:16)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process: Sending signal. PID: 10349 SIG: 9
```

**Comment by jiuqiant** [comment]
MediaPipe GPU requires OpenGLES 3.1, but the Android Studio is still with OpenGLES 2.0 or 3.0 by default. Therefore, MediaPipe GPU graphs are not working properly in Android Studio emulators  due to the incompatible OpenGLES version. 

To use MediaPipe solutions in emulators, you can set [ the "runOnGpu" option](https://google.github.io/mediapipe/solutions/hands.html#android-solution-api) to False and send Bitmaps into the hands solution instead.

**Comment by sureshdagooglecom** [comment]
Hi @asluborski98 ,
OpenglES 2.0 is not supported. please try with 3.0 ,refer this [link](https://google.github.io/mediapipe/getting_started/gpu_support.html#opengl-es-support)
