### ISSUE TITLE
Error :    env: python: No such file or directory

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#3184]
Platform： macOS 12.3 
Bazel version: 4.2.1
Mediapipe Version: 0.8.9

This is my build command :
```
bazel build -c opt --strip=ALWAYS \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--fat_apk_cpu=arm64-v8a \ 
--spawn_strategy=standalone  \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect
```
Get this error: 

<img width="1422" alt="截屏2022-03-19 13 47 06" src="https://user-images.githubusercontent.com/25787391/159142258-a83c1f39-fa5f-40c7-932a-d64ee8a44e0e.png">

It's wired, because  having numpy.

Then i add `--action_env PYTHON_BIN_PATH=/usr/local/bin/python `  according other issue's solution.
```
bazel build -c opt --strip=ALWAYS \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--fat_apk_cpu=arm64-v8a \ 
--spawn_strategy=standalone \
--action_env PYTHON_BIN_PATH=/usr/local/bin/python \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect
```
<img width="1431" alt="截屏2022-03-19 14 33 33" src="https://user-images.githubusercontent.com/25787391/159142420-8a0c7542-3cc6-4cf6-b833-e06278227b37.png">

Another, macOS 12.3 not support python2.7 officially, is it relative?

**Comment by wingdi** [comment]
Reference:
https://github.com/tensorflow/tensorflow/issues/15618#issuecomment-376009820
https://github.com/tensorflow/tensorflow/issues/10289#issuecomment-868247016

macOS 12.3 not support add link to /usr/bin/ ,  even if diable System Integrity Protection(SIP).

**Comment by wingdi** [comment]
Solved , because bazel use python3, not python2.

**Comment by wingdi** [comment]
Still build failed .
```
ERROR: /Users/zhengying/Downloads/mediapipe-0.8.9/mediapipe/java/com/google/mediapipe/framework/BUILD:34:16: Validating proguard configuration failed: (Exit 127): proguard_whitelister failed: error executing command bazel-out/darwin-opt-exec-50AE0418/bin/external/bazel_tools/tools/jdk/proguard_whitelister --path mediapipe/java/com/google/mediapipe/framework/proguard.pgcfg --output ... (remaining 1 argument(s) skipped)
env: python: No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 820.192s, Critical Path: 359.98s
INFO: 3732 processes: 434 internal, 3298 local.
FAILED: Build did NOT complete successfully
```
Before update macOS to version 12.3, there is no this problem. Is this  because /usr/bin/ don't have python, just have python3?   

Build command:
```
zhengying@wingdideMacBook-Pro mediapipe-0.8.9 % bazel build -c opt --strip=ALWAYS \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--fat_apk_cpu=arm64-v8a --spawn_strategy=standalone \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/faceeffect:faceeffect
```

**Comment by sureshdagooglecom** [comment]
Hi @wingdi ,
Could you provide steps to reproduce this issue.

**Comment by joewilbert** [comment]
I'm experiencing the same issue trying to build the handtracking example in ios, which was working fine before upgrading to macOS 12.3

Platform: macOS 12.3
Bazel version: 3.7.2 (also tried 5.0.0 with no luck)
Mediapipe Version: 0.8.9 

I agree the issue relates to removal of python 2 in macOS 12.3, and the fact that there's no python in /usr/bin. The following two attempted build commands resulting in the following failure, which is identical for both commands: 

```
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp
```

```
bazel build -c opt --config=ios_arm64 --action_env PYTHON_BIN_PATH=$(which python3) mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp 
```

```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jory/f9f0f6bca00c121e1c40b0977e1c780a/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 41, in _create_local_python_repository
		python_include = _get_python_include(repository_ctx, python_bin)
	File "/private/var/tmp/_bazel_jory/f9f0f6bca00c121e1c40b0977e1c780a/external/org_tensorflow/third_party/py/python_configure.bzl", line 152, column 21, in _get_python_include
		result = execute(
	File "/private/var/tmp/_bazel_jory/f9f0f6bca00c121e1c40b0977e1c780a/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Problem getting python include path.
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
ERROR: Analysis of target '//mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp' failed; build aborted: Problem getting python include path.
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Is the Python binary path set up right? (See ./configure or PYTHON_BIN_PATH.) Is distutils installed?
INFO: Elapsed time: 3.406s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded, 179 targets configured)
```

As an attempted fix, I installed python 2 manually from https://www.python.org/downloads/release/python-2718/. Separately, I tried setting action-env to the python3 that's in /usr/bin. In those cases, the following two build commands result in the following identical failure: 

```
bazel build -c opt --config=ios_arm64 --action_env PYTHON_BIN_PATH=/usr/local/bin/python --verbose_failures mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp 
```

```
bazel build -c opt --config=ios_arm64 --action_env PYTHON_BIN_PATH=/usr/bin/python3 --verbose_failures mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp 
```

```
INFO: Analyzed target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp (168 packages loaded, 10586 targets configured).
INFO: Found 1 target...
ERROR: /Users/jory/mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD:34:16: StoryboardCompile mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/Base.lproj_storyboardc/Main.storyboardc failed (Exit 127): xctoolrunner failed: error executing command 
  (cd /private/var/tmp/_bazel_jory/f9f0f6bca00c121e1c40b0977e1c780a/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneOS \
    APPLE_SDK_VERSION_OVERRIDE=15.4 \
    XCODE_VERSION_OVERRIDE=13.3.0.13E5104i \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner ibtool --compilation-directory '[ABSOLUTE]bazel-out/ios_arm64-opt/bin/mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp-intermediates/Base.lproj_storyboardc' --minimum-deployment-target 10.0 --target-device iphone --target-device ipad --module HandTrackingGpuApp '[ABSOLUTE]mediapipe/examples/ios/common/Base.lproj/Main.storyboard')
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp failed to build
INFO: Elapsed time: 4.168s, Critical Path: 0.04s
INFO: 6 processes: 6 internal.
FAILED: Build did NOT complete successfully
```

**Comment by wingdi** [comment]
it's a bazel problem .
In `bazel-out/darwin-opt-exec-50AE0418/bin/external/bazel_tools/tools/jdk/proguard_whitelister` file, the first line is `#!/usr/bin/env python` , this error come from here.

Then i found this in bazel :

<img width="1244" alt="截屏2022-03-22 05 35 25" src="https://user-images.githubusercontent.com/25787391/159367954-a529ec88-460c-416d-b0ef-452cf0806487.png">

So maybe bazel 6.0.0-pre.20220310.1 work. 
I need go to sleep now.

**Comment by wingdi** [comment]
Problem solved.
Use bazel 5.0.0,  don't use bazel 4.2.1
