### ISSUE TITLE
Got exception when load inference delegate.

### ISSUE THREAD

**Issue by kuangzy2011** [google/mediapipe#3186]
- Have I written custom code (Yes):
- OS Platform and Distribution (Android 10):
- [MediaPipe version](https://github.com/google/mediapipe/tree/v0.8.9):
- Bazel version: 3.7.2
- Solution (Holistic):
- Programming Language and version ( Java):

```
Refer solution Android FaceMesh to create an Android solution Holistic, offen got following exception when trigger button "Start Camera"
```

```
E/tflite: Following operations are not supported by GPU delegate:
    DEQUANTIZE: 
    DEQUANTIZE: Operation is not supported.
    63 operations will run on the GPU, and the remaining 102 operations will run on the CPU.
I/tflite: Replacing 63 node(s) with delegate (TfLiteGpuDelegate) node, yielding 2 partitions.
E/tflite: TfLiteGpuDelegate Prepare: Only identical batch dimension is supported
E/tflite: Node number 165 (TfLiteGpuDelegate) failed to prepare.
E/tflite: Restored original execution plan after delegate application failure.
I/tflite: Replacing 165 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
E/native: E20220319 23:30:24.713230 30070 calculator_graph.cc:805] INTERNAL: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__inferencecalculator__holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__InferenceCalculator" failed: ; (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)gl.cc:431) 
E/SolutionBase: Error occurs while starting the MediaPipe solution graph. Error details: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__inferencecalculator__holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__InferenceCalculator" failed: ; (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)gl.cc:431) 
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__inferencecalculator__holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__InferenceCalculator" failed: ; (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)gl.cc:431) 
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:452)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.signlanguage.solution.Holistic.<init>(Holistic.java:164)
        at com.google.mediapipe.signlanguage.MainActivity.setupStreamingModePipeline(MainActivity.java:340)
        at com.google.mediapipe.signlanguage.MainActivity.setupLiveDemoUiComponentsAction(MainActivity.java:327)
        at com.google.mediapipe.signlanguage.MainActivity.lambda$setupLiveDemoUiComponents$9$MainActivity(MainActivity.java:321)
        at com.google.mediapipe.signlanguage.-$$Lambda$MainActivity$akHIeSmzG2p4ceDHh6srnA1A8Lg.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7252)
        at android.view.View.performClickInternal(View.java:7229)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27765)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.signlanguage, PID: 30070
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__inferencecalculator__holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__InferenceCalculator" failed: ; (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)gl.cc:431) 
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:452)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.signlanguage.solution.Holistic.<init>(Holistic.java:164)
        at com.google.mediapipe.signlanguage.MainActivity.setupStreamingModePipeline(MainActivity.java:340)
        at com.google.mediapipe.signlanguage.MainActivity.setupLiveDemoUiComponentsAction(MainActivity.java:327)
        at com.google.mediapipe.signlanguage.MainActivity.lambda$setupLiveDemoUiComponents$9$MainActivity(MainActivity.java:321)
        at com.google.mediapipe.signlanguage.-$$Lambda$MainActivity$akHIeSmzG2p4ceDHh6srnA1A8Lg.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7252)
        at android.view.View.performClickInternal(View.java:7229)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27765)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process: Sending signal. PID: 30070 SIG: 9
```

**Comment by sureshdagooglecom** [comment]
Hi @kuangzy2011 ,
Could you provide steps to reproduce this issue.
