### ISSUE TITLE
Packet timestamp mismatch on a calculator receiving from stream "output_video". 

### ISSUE THREAD

**Issue by wingdi** [google/mediapipe#3207]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
 -- No 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
-- Android api_level 31
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
-- Huawei Meta30
- Programming Language and version ( e.g. C++, Python, Java):
-- C++ default
- [MediaPipe version](https://github.com/google/mediapipe/releases):
-- 0.8.9
- Bazel version (if compiling from source):
-- 5.0.0
- Solution ( e.g. FaceMesh, Pose, Holistic ):
-- FaceMesh 
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
-- Android Studio bumblebee; NDK - 21.4.7075529 ;  SDK - 31

**Describe the current behavior:**
```
Android Studio --> Run/Debug Config -->  Enable native debugging. when check it having this issue, 
When uncheck Enable native debugging, There are no this issue.
```
**Describe the expected behavior:**
```
E/MainActivity: Exception while adding packet to input stream while switching effects: com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 
    ; Packet timestamp mismatch on a calculator receiving from stream "output_video". Current minimum expected timestamp is 2328858984941 but received 2328857103604. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
    ; Packet timestamp mismatch on a calculator receiving from stream "output_video". Current minimum expected timestamp is 2328858984941 but received 2328857103604. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
    ; Packet timestamp mismatch on a calculator receiving from stream "output_video". Current minimum expected timestamp is 2328858984941 but received 2328857103604. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: invalid argument: Graph has errors: 
    ; Packet timestamp mismatch on a calculator receiving from stream "output_video". Current minimum expected timestamp is 2328858984941 but received 2328857103604. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
    ; Packet timestamp mismatch on a calculator receiving from stream "output_video". Current minimum expected timestamp is 2328858984941 but received 2328857103604. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
    ; Packet timestamp mismatch on a calculator receiving from stream "output_video". Current minimum expected timestamp is 2328858984941 but received 2328857103604. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:457)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
```

**Comment by sureshdagooglecom** [comment]
@wingdi ,
Can you provide steps to reproduce this issue.
