### ISSUE TITLE
 Error loading libarsceneview_jni.so

### ISSUE THREAD

**Issue by suraj-0387** [google/mediapipe#323]
I am getting following error when I tried to integrate Arcore with mediapipe

2019-12-17 13:41:56.250 29352-29352/com.example.handtrackinggradle E/ArSceneView: Error loading libarsceneview_jni.so
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.handtrackinggradle-q6m5wHvnCOyhXe1Fqp66cQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.handtrackinggradle-q6m5wHvnCOyhXe1Fqp66cQ==/lib/arm64, /data/app/com.example.handtrackinggradle-q6m5wHvnCOyhXe1Fqp66cQ==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libarsceneview_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:232)
        at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:51)
        at com.google.ar.sceneform.ArSceneView.resume(SourceFile:41)
        at com.google.ar.sceneform.ux.BaseArFragment.start(BaseArFragment.java:507)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:315)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7634)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4013)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4053)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7076)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by mgyong** [comment]
Has this issue been resolved on your end? @suraj-0387

**Comment by suraj-0387** [comment]
No.But you can close the ticket as nobody has answer for it
