### ISSUE TITLE
Make android solutions(face mesh) buildable with 'minifyEnabled true' build option.

### ISSUE THREAD

**Issue by batkhishign55** [google/mediapipe#3236]
**System information** (Please provide as much relevant information as possible)

- MediaPipe Solution (you are using): Face mesh
- Programming language : Android Java
- Are you willing to contribute it (Yes/No): Yes (if I can)

**Describe the feature and the current behavior/state:**
I followed [Mediapipe Android Solutions](https://google.github.io/mediapipe/getting_started/android_solutions.html) tutorial to build facemesh app and ran it on my device. It worked perfectly. However, when I changed `minifyEnabled` configuration to `true` in build.gradle file, the app crashed on `FaceMeshOptions.builder().build()` step.

**Will this change the current api? How?**
Yes.

**Who will benefit with this feature?**
Anyone who wants to shrink their app.

**Please specify the use cases for this feature:**
The solutions apps will be shrinkable.

**Error log from android studio:**
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.facemesh, PID: 8042
    java.lang.RuntimeException: Field platform_ for b.a.d.d.o not found. Known fields are [private int b.a.d.d.o.h, private int b.a.d.d.o.i, private java.lang.String b.a.d.d.o.j, private java.lang.String b.a.d.d.o.k, private java.lang.String b.a.d.d.o.l, private static final b.a.d.d.o b.a.d.d.o.f, private static volatile b.a.e.b1 b.a.d.d.o.g]
        at b.a.e.v0.n0(:614)
        at b.a.e.v0.T(:507)
        at b.a.e.v0.R(:227)
        at b.a.e.k0.e(:77)
        at b.a.e.k0.a(:71)
        at b.a.e.e1.d(:90)
        at b.a.e.e1.e(:104)
        at b.a.e.z.B(:175)
        at b.a.e.z$a.p(:397)
        at b.a.e.z$a.o(:405)
        at b.a.d.e.z.f.<init>(:108)
        at b.a.d.e.t.j(:70)
        at b.a.d.e.o.j(:53)
        at b.a.d.f.a.e.<init>(:88)
        at com.google.mediapipe.examples.facemesh.MainActivity.t0(:273)
        at com.google.mediapipe.examples.facemesh.MainActivity.Q(:258)
        at com.google.mediapipe.examples.facemesh.MainActivity.R(Unknown Source:0)
        at com.google.mediapipe.examples.facemesh.k.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6897)
        at android.widget.TextView.performClick(TextView.java:12727)
        at android.view.View$PerformClick.run(View.java:26104)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=-1827657096 in 30000ms(Backend next call timestamp 1649061592881). Attempt 1

**Comment by sureshdagooglecom** [comment]
Hi @batkhishign55 ,
Did you get chance to check this closed issue https://github.com/google/mediapipe/issues/2446 for refrence.

**Comment by batkhishign55** [comment]
hi @sureshdagooglecom, thanks for the reply. Looks like [#2446](https://github.com/google/mediapipe/issues/2446) issue addressing a different problem.

**Comment by batkhishign55** [comment]
So I have been investigating this issue for the past few days, and finally found the solution. According to [this issue](https://github.com/protocolbuffers/protobuf/issues/6463), **GeneratedMessageLite** class from protobuf was causing the problem. Using [this workaround](https://github.com/protocolbuffers/protobuf/blob/main/java/lite/proguard.pgcfg) fixed the problem for me.

Adding the following lines in `proguard-rules.pro` prevented the release build crash:
```
-keep class com.google.mediapipe.solutioncore.** {*;}
-keep class com.google.protobuf.** {*;}
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {
  <fields>;
}
```

Closing this issue.
