### ISSUE TITLE
removing the input video in output leaving only hand keypoints, MultihandtrackingGPU

### ISSUE THREAD

**Issue by alizahidraja** [google/mediapipe#326]
Is there a way i can remove the input video from output and have only the hand landmarks on the screen?
Thanks in advance

**Comment by eknight7** [comment]
Yes, https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt can be modified for the same. In this graph, there is an `AnnotationOverlayCalculator` which takes an input image and renders the landmarks on the screen.

From what I understand, you want a black image with only landmarks, and no input video. In that case you can modify the calculator to draw the annotation on a blank frame.

**Comment by alizahidraja** [comment]
yes that is exactly where i went but i couldn't edit it to have a black background
can you assist me in anyway?

**Comment by mcclanahoochie** [comment]
you can remove the input stream to the annotation calculator, then the results will be drawn on cpu to a solid color (specified by options), then use cpu->gpu to output the frame


```
node {
  calculator: "AnnotationOverlayCalculator"
##  input_stream: "INPUT_FRAME_GPU:input_image"
  input_stream: "detection_render_data"
  input_stream: "landmark_render_data"
  input_stream: "rect_render_data"
  output_stream: "OUTPUT_FRAME:output_image_cpu"
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "output_image_cpu"
  output_stream: "output_image"
}
```

**Comment by eknight7** [comment]
Yes, you can use `canvas_color` option to specify a solid color: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/annotation_overlay_calculator.proto

**Comment by eknight7** [comment]
@alizahidraja were you able to get this working?

**Comment by razak-io** [comment]
Hi, I wanted to the something similar to @alizahidraja and used the tutorials provided by @eknight7 and @mcclanahoochie but i got the following output:

I0205 12:18:08.843401 15837 demo_run_graph_main_gpu.cc:57] Initialize the calculator graph.
I0205 12:18:08.848351 15837 demo_run_graph_main_gpu.cc:61] Initialize the GPU.
I0205 12:18:08.874284 15837 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 4
I0205 12:18:08.936925 15846 gl_context.cc:233] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 384.130)
I0205 12:18:08.937070 15837 demo_run_graph_main_gpu.cc:67] Initialize the camera or load the video.
I0205 12:18:10.308974 15837 demo_run_graph_main_gpu.cc:88] Start running the calculator graph.
I0205 12:18:10.309249 15837 gl_context_egl.cc:158] Successfully initialized EGL. Major : 1 Minor: 4
I0205 12:18:10.347685 15847 gl_context.cc:233] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 384.130)
I0205 12:18:10.348506 15837 demo_run_graph_main_gpu.cc:93] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
E0205 12:18:10.909931 15837 demo_run_graph_main_gpu.cc:186] Failed to run the graph: Graph has errors: 
Calculator::Open() for node "[AnnotationOverlayCalculator, AnnotationOverlayCalculator with output stream: __sg2_output_image_cpu]" failed: ; options_.has_canvas_width_px()alculators/util/annotation_overlay_calculator.cc:243) 

Can I have some assistance on this? 

Thanks in advance

**Comment by mcclanahoochie** [comment]
Looks like there needs to be additional options provided to that calculator 

```
node {
  calculator: "AnnotationOverlayCalculator"
##  input_stream: "INPUT_FRAME_GPU:input_image"
  input_stream: "detection_render_data"
  input_stream: "landmark_render_data"
  input_stream: "rect_render_data"
  output_stream: "OUTPUT_FRAME:output_image_cpu"
  canvas_width_px: 720
  canvas_height_px: 1280
}
```

the output width & height were previously determined from the incoming 'input_image', and now that is removed, an output size needs to be defined (can change to fit your screen).

**Comment by romaindebraize** [comment]
Hi @mcclanahoochie ,

I tried to modify the renderer_gpu options calculator as you explained but i have this error when building :

```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format mediapipe.CalculatorGraphConfig: 103:18: Message type "mediapipe.CalculatorGraphConfig.Node" has no field named "canvas_width_px".
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format mediapipe.CalculatorGraphConfig: 103:18: Message type "mediapipe.CalculatorGraphConfig.Node" has no field named "canvas_width_px".
E0312 15:59:39.956148     3 text_to_binary_graph.cc:108] Internal: ; could not parse text proto: mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hand_tracking_aar failed to build
```

Are there more things to change ? 

Thanks

**Comment by eknight7** [comment]
Calculator options `canvas_width_px` and `canvas_height_px` for `AnnotationOverlayCalculator` are declared here: https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/annotation_overlay_calculator.proto#L34-L35

Can you share the modified `renderer_gpu.pbtxt` ?

**Comment by mcclanahoochie** [comment]
sorry, i meant to have those inside the options block

```
node {
  calculator: "AnnotationOverlayCalculator"
  ...
  node_options: {
    [type.googleapis.com/mediapipe. AnnotationOverlayCalculator Options] {
      canvas_width_px: 720
      canvas_height_px: 1280
  }
 }
}
```

**Comment by romaindebraize** [comment]
Hi,

I tried to change the "AnnotationOverlayCalculator" node like @mcclanahoochie  but this error shows up : 
```
2020-03-17 10:55:50.372 4479-4615/com.example.handtrackingpits E/native: E0317 10:55:50.371992  4615 graph.cc:391] ValidatedGraphConfig Initialization failed.
    AnnotationOverlayCalculator: GPU output must have GPU input.
2020-03-17 10:55:50.419 4479-4615/com.example.handtrackingpits E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.example.handtrackingpits, PID: 4479
    com.google.mediapipe.framework.MediaPipeException: internal: ValidatedGraphConfig Initialization failed.
    AnnotationOverlayCalculator: GPU output must have GPU input.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:306)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:229)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:244)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:261)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:211)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)
```

Then i tried to remove the line for the input stream image in the hand_tracking_mobile.pbtx like that : 
```
# Subgraph that renders annotations and overlays them on top of the input
# images (see renderer_gpu.pbtxt).
node {
  calculator: "RendererSubgraph"
  # input_stream: "IMAGE:throttled_input_video"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "NORM_RECT:hand_rect"
  input_stream: "DETECTIONS:palm_detections"
  output_stream: "IMAGE:output_video"
}
```` 

but i have now this error : 
```
2020-03-17 10:31:40.250 1648-1770/com.example.handtrackingpits E/native: E0317 10:31:40.250102  1770 graph.cc:391] while processing the input streams of subgraph node RendererSubgraph: ; Tag "IMAGE" does not exist in the subgraph config.
2020-03-17 10:31:40.260 1648-1770/com.example.handtrackingpits E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.example.handtrackingpits, PID: 1648
    com.google.mediapipe.framework.MediaPipeException: invalid argument: while processing the input streams of subgraph node RendererSubgraph: ; Tag "IMAGE" does not exist in the subgraph config.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:306)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:229)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:244)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:261)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:211)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)
```

Are you sure that the only thing to do is to update the node from the AnnotationOverlayCalculator ??

Thanks

**Comment by eknight7** [comment]
Hi @romaindebraize, since you are using https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt, i.e. the graph running on gpu, the image input and output streams should specify that the images are on the GPU. Try using the following modified `AnnotationOverlayCalculator` node:

```
# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:input_image"
  input_stream: "detection_render_data"
  input_stream: "landmark_render_data"
  input_stream: "rect_render_data"
  output_stream: "IMAGE_GPU:output_image"
  node_options: {
    [type.googleapis.com/mediapipe. AnnotationOverlayCalculator Options] {
      canvas_width_px: 720
      canvas_height_px: 1280
  }
}
```

**Comment by jiuqiant** [comment]
Closing due to lack of activity.

**Comment by MaRauder111** [comment]
> Hi @romaindebraize, since you are using https://github.com/google/mediapipe/blob/master/mediapipe/graphs/hand_tracking/subgraphs/renderer_gpu.pbtxt, i.e. the graph running on gpu, the image input and output streams should specify that the images are on the GPU. Try using the following modified `AnnotationOverlayCalculator` node:
> 
> ```
> # Draws annotations and overlays them on top of the input images.
> node {
>   calculator: "AnnotationOverlayCalculator"
>   input_stream: "IMAGE_GPU:input_image"
>   input_stream: "detection_render_data"
>   input_stream: "landmark_render_data"
>   input_stream: "rect_render_data"
>   output_stream: "IMAGE_GPU:output_image"
>   node_options: {
>     [type.googleapis.com/mediapipe.AnnotationOverlayCalculatorOptions] {
>       canvas_width_px: 720
>       canvas_height_px: 1280
>   }
> }
> ```

I'm able to successfully build with the changes. I made the changes in hand_renderer_cpu . When I run. The windows didn't pop up it got stuck. Any suggestion?

@eknight7

**Comment by eknight7** [comment]
Hi @MaRauder111 Can you please open a new issue? Since this is closed it would be better to follow-up in a new ticket. I only accidentally saw this right now. Just copy and open a new issue thank you!
