### ISSUE TITLE
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'

### ISSUE THREAD

**Issue by zhiheng-ldj** [google/mediapipe#3286]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS: 12.3.1 / Android emulator
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): python 3.9
- Installed using virtualenv? pip? Conda? (if python): conda
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1
- Android SDK and NDK versions (if android): NDK: 21.4.7075529 / SDK: 30.0.2

**Describe the problem**:
I am trying to use mediapipe in my Android app and it crashes.

I have checked the #1839 but cannot pip install msvc_runtime and I guess it may be my OS is not windows?

```
(py3.7) dingjieliu@B-Q39SMD6P-0448 mediapipe_dev % pip3 install msvc-runtime
ERROR: Could not find a version that satisfies the requirement msvc-runtime (from versions: none)
```

Can I solve that problem under my platform? Thanks for your help!

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

```
[mediapipe_dev] Starting app on @beePhone2 (running emulator) (device ID emulator-5554)

[mediapipe_dev] Stopping old versions of the app...

[mediapipe_dev] Installing app...

[mediapipe_dev] Clearing device log...

[mediapipe_dev] Launching app...

[mediapipe_dev] Following device log output (type CTRL-C to stop log)...
===========================================================================
--------- beginning of system
--------- beginning of main
04-25 19:59:28.127  3024  3024 D MainActivity: onCreate() start
04-25 19:59:28.127  3024  3024 D MainActivity: onCreate(): captured stdout/stderr
04-25 19:59:28.149  3024  3041 D stdio   : Starting to capture stdout/stderr to Android log.
04-25 19:59:28.149  3024  3041 D stdio   : stdout now successfully routes into the stdio logger.
04-25 19:59:28.229  3024  3024 D MainActivity: Python stdlib already exists for stdlib/pythonhome.f84820393f82281a82f4418f2fbd5bb7452e4612a224ebeafdebfee405b54104.x86.zip
04-25 19:59:28.229  3024  3024 D MainActivity: Unpacking Python assets to /data/user/0/com.example.mediapipe_dev/files/python/user_code
04-25 19:59:34.364  3024  3024 D MainActivity: Replacing old lastUpdateTime = 1650887876676 with actualLastUpdateTime = 1650887966794
04-25 19:59:34.365  3024  3024 D MainActivity: unpackPython() complete
04-25 19:59:34.365  3024  3024 D MainActivity: setPythonEnvVars() start
04-25 19:59:34.365  3024  3024 V MainActivity: pythonHome=/data/user/0/com.example.mediapipe_dev/files/python/stdlib
04-25 19:59:34.365  3024  3024 D MainActivity: setPythonEnvVars() complete
04-25 19:59:34.365  3024  3024 D MainActivity: Computing Python version.
04-25 19:59:34.365  3024  3024 D MainActivity: Computed Python version: 3.9
04-25 19:59:34.366  3024  3024 I Python  : Start Python runtime...
04-25 19:59:34.367  3024  3024 D Python  : PYTHONHOME=/data/user/0/com.example.mediapipe_dev/files/python/stdlib
04-25 19:59:34.367  3024  3024 D Python  : PYTHONPATH=/data/user/0/com.example.mediapipe_dev/files/python/stdlib/lib/python3.9/:/data/user/0/com.example.mediapipe_dev/files/python/user_code/app_packages:/data/user/0/com.example.mediapipe_dev/files/python/user_code/app
04-25 19:59:34.367  3024  3024 D Python  : Not setting RUBICON_LIBRARY
04-25 19:59:34.367  3024  3024 I Python  : Adding Android logging module to default modules...
04-25 19:59:34.367  3024  3024 D Python  : Initializing Python runtime...
04-25 19:59:34.409  3024  3024 D Python  : Initializing Python threads...
04-25 19:59:34.409  3024  3024 D Python  : Replacing sys.stdout/sys.stderr with Android log wrappers...
04-25 19:59:34.410  3024  3024 I Python  : sys.stdout/stderr replaced with Android log wrappers.
04-25 19:59:34.410  3024  3024 V Python  : Import rubicon...
04-25 19:59:34.497  3024  3024 V Python  : Got rubicon python module
04-25 19:59:34.497  3024  3024 V Python  : Got method dispatch handler
04-25 19:59:34.497  3024  3024 I Python  : Python runtime started.
04-25 19:59:34.497  3024  3024 D MainActivity: Python.init() complete
04-25 19:59:34.497  3024  3024 D MainActivity: Python.run() start
04-25 19:59:34.497  3024  3024 D Python  : Running 'mediapipe_dev' as __main__...
04-25 19:59:35.015  3024  3024 E Python  : Application quit abnormally!
04-25 19:59:35.016  3024  3024 E Python  : Traceback (most recent call last):
04-25 19:59:35.016  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/stdlib/lib/python3.9/runpy.py", line 197, in _run_module_as_main
04-25 19:59:35.018  3024  3024 E Python  :     return _run_code(code, main_globals, None,
04-25 19:59:35.018  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/stdlib/lib/python3.9/runpy.py", line 87, in _run_code
04-25 19:59:35.018  3024  3024 E Python  :     exec(code, run_globals)
04-25 19:59:35.018  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app/mediapipe_dev/__main__.py", line 1, in <module>
04-25 19:59:35.018  3024  3024 E Python  :     from mediapipe_dev.app import main
04-25 19:59:35.018  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app/mediapipe_dev/app.py", line 8, in <module>
04-25 19:59:35.018  3024  3024 E Python  :     import task_src.poseDetection as my_poseDetection
04-25 19:59:35.018  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app/task_src/poseDetection.py", line 1, in <module>
04-25 19:59:35.018  3024  3024 E Python  :     import mediapipe as mp
04-25 19:59:35.018  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app_packages/mediapipe/__init__.py", line 16, in <module>
04-25 19:59:35.018  3024  3024 E Python  :     from mediapipe.python import *
04-25 19:59:35.018  3024  3024 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app_packages/mediapipe/python/__init__.py", line 17, in <module>
04-25 19:59:35.018  3024  3024 E Python  :     from mediapipe.python._framework_bindings import resource_util
04-25 19:59:35.018  3024  3024 E Python  : ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
04-25 19:59:35.018  3024  3024 D MainActivity: Python.run() end
04-25 19:59:35.019  3024  3024 D MainActivity: startPython() end
04-25 19:59:35.019  3024  3024 D MainActivity: user code onCreate() start
--------- beginning of crash
```

**Comment by sureshdagooglecom** [comment]
Hi @zhiheng-ldj ,
Could you please use  Android NDK version between 18 and 21.

**Comment by zhiheng-ldj** [comment]
> Hi @zhiheng-ldj , Could you please use Android NDK version between 18 and 21.

Hi @sureshdagooglecom ,

I am using ndk 19.2.5345600 and the problem still exists:

```
===========================================================================
--------- beginning of main
--------- beginning of system
04-26 16:35:31.300  3099  3099 D MainActivity: onCreate() start
04-26 16:35:31.301  3099  3099 D MainActivity: onCreate(): captured stdout/stderr
04-26 16:35:31.306  3099  3117 D stdio   : Starting to capture stdout/stderr to Android log.
04-26 16:35:31.308  3099  3117 D stdio   : stdout now successfully routes into the stdio logger.
04-26 16:35:31.516  3099  3099 D MainActivity: Python stdlib already exists for stdlib/pythonhome.f84820393f82281a82f4418f2fbd5bb7452e4612a224ebeafdebfee405b54104.x86.zip
04-26 16:35:31.516  3099  3099 D MainActivity: Unpacking Python assets to /data/user/0/com.example.mediapipe_dev/files/python/user_code
04-26 16:35:42.449  3099  3099 D MainActivity: Replacing old lastUpdateTime = 1650887966794 with actualLastUpdateTime = 1650962129383
04-26 16:35:42.452  3099  3099 D MainActivity: unpackPython() complete
04-26 16:35:42.453  3099  3099 D MainActivity: setPythonEnvVars() start
04-26 16:35:42.453  3099  3099 V MainActivity: pythonHome=/data/user/0/com.example.mediapipe_dev/files/python/stdlib
04-26 16:35:42.454  3099  3099 D MainActivity: setPythonEnvVars() complete
04-26 16:35:42.454  3099  3099 D MainActivity: Computing Python version.
04-26 16:35:42.456  3099  3099 D MainActivity: Computed Python version: 3.9
04-26 16:35:42.461  3099  3099 I Python  : Start Python runtime...
04-26 16:35:42.462  3099  3099 D Python  : PYTHONHOME=/data/user/0/com.example.mediapipe_dev/files/python/stdlib
04-26 16:35:42.462  3099  3099 D Python  : PYTHONPATH=/data/user/0/com.example.mediapipe_dev/files/python/stdlib/lib/python3.9/:/data/user/0/com.example.mediapipe_dev/files/python/user_code/app_packages:/data/user/0/com.example.mediapipe_dev/files/python/user_code/app
04-26 16:35:42.462  3099  3099 D Python  : Not setting RUBICON_LIBRARY
04-26 16:35:42.462  3099  3099 I Python  : Adding Android logging module to default modules...
04-26 16:35:42.462  3099  3099 D Python  : Initializing Python runtime...
04-26 16:35:42.525  3099  3099 D Python  : Initializing Python threads...
04-26 16:35:42.525  3099  3099 D Python  : Replacing sys.stdout/sys.stderr with Android log wrappers...
04-26 16:35:42.527  3099  3099 I Python  : sys.stdout/stderr replaced with Android log wrappers.
04-26 16:35:42.527  3099  3099 V Python  : Import rubicon...
04-26 16:35:42.641  3099  3099 V Python  : Got rubicon python module
04-26 16:35:42.642  3099  3099 V Python  : Got method dispatch handler
04-26 16:35:42.642  3099  3099 I Python  : Python runtime started.
04-26 16:35:42.642  3099  3099 D MainActivity: Python.init() complete
04-26 16:35:42.643  3099  3099 D MainActivity: Python.run() start
04-26 16:35:42.643  3099  3099 D Python  : Running 'mediapipe_dev' as __main__...
04-26 16:35:43.335  3099  3099 E Python  : Application quit abnormally!
04-26 16:35:43.335  3099  3099 E Python  : Traceback (most recent call last):
04-26 16:35:43.335  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/stdlib/lib/python3.9/runpy.py", line 197, in _run_module_as_main
04-26 16:35:43.336  3099  3099 E Python  :     return _run_code(code, main_globals, None,
04-26 16:35:43.336  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/stdlib/lib/python3.9/runpy.py", line 87, in _run_code
04-26 16:35:43.337  3099  3099 E Python  :     exec(code, run_globals)
04-26 16:35:43.337  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app/mediapipe_dev/__main__.py", line 1, in <module>
04-26 16:35:43.337  3099  3099 E Python  :     from mediapipe_dev.app import main
04-26 16:35:43.337  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app/mediapipe_dev/app.py", line 8, in <module>
04-26 16:35:43.337  3099  3099 E Python  :     import task_src.poseDetection as my_poseDetection
04-26 16:35:43.337  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app/task_src/poseDetection.py", line 1, in <module>
04-26 16:35:43.337  3099  3099 E Python  :     import mediapipe as mp
04-26 16:35:43.337  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app_packages/mediapipe/__init__.py", line 16, in <module>
04-26 16:35:43.338  3099  3099 E Python  :     from mediapipe.python import *
04-26 16:35:43.338  3099  3099 E Python  :   File "/data/user/0/com.example.mediapipe_dev/files/python/user_code/app_packages/mediapipe/python/__init__.py", line 17, in <module>
04-26 16:35:43.338  3099  3099 E Python  :     from mediapipe.python._framework_bindings import resource_util
04-26 16:35:43.338  3099  3099 E Python  : ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
04-26 16:35:43.338  3099  3099 D MainActivity: Python.run() end
04-26 16:35:43.338  3099  3099 D MainActivity: startPython() end
04-26 16:35:43.338  3099  3099 D MainActivity: user code onCreate() start
--------- beginning of crash
```

Thanks for your help!

**Comment by zhiheng-ldj** [comment]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.example.mediapipe_dev"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 100
        versionName "0.0.1"
        ndkVersion '19.2.5345600'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++14"
            }
        }
    }
    compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
      targetCompatibility JavaVersion.VERSION_1_8
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    aaptOptions {
        // Use default ignore rule *except* allow directories starting with _,
        // so that pyc files in __pycache__ directories flow through into apps.
        // https://android.googlesource.com/platform/frameworks/base/+/b41af58f49d371cedf041443d20a1893f7f6c840/tools/aapt/AaptAssets.cpp#60
        ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation files('libs/rubicon.jar')
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
}
repositories {
    mavenCentral()
}

```

Here is how I change my ndk version.

**Comment by ayushgdev** [comment]
Hello @zhiheng-ldj 
1. Can you please let us know the solution you are trying to use in the Android app?
2. Have you tried building the example solution with AAR/Maven build first?
