### ISSUE TITLE
Failed to build via brazel.

### ISSUE THREAD

**Issue by moonBirdKiss** [google/mediapipe#3296]
Hello, I am new to use gVisor. And I followed the introduction to build gVisor from the source, but I failed. 
Here is the information about OS:
```shell
(base) ubuntu@ip-172-31-38-121:~/code/gvisor$ cat /proc/version
Linux version 5.4.0-1072-aws (buildd@lcy02-amd64-049) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #77~18.04.1-Ubuntu SMP Thu Apr 7 21:38:47 UTC 2022
```

And here is the information about docker.
```shell
(base) ubuntu@ip-172-31-38-121:~/code/gvisor$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:46 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Here is the log.
```
(base) ubuntu@ip-172-31-38-121:~/code/gvisor$ sudo make copy TARGETS=runsc DESTINATION=bin/
--- TAG default
--- DOCKER BUILD
gvisor-builder-1c9e5a27-x86_64
sha256:2deccfd866cb2c747b116798ce7c23153d7a14417b9c49e04fd8de529ab8fdbb
--- DOCKER RUN
5fc0baac24faabc7c93a7efa71da521620a73f6deced1fe1a68ed56d246b9565
--- COPY runsc bin/
Another command holds the client lock:
pid=8
owner=client
cwd=/home/ubuntu/code/gvisor

Waiting for it to complete...
Another command (pid=8) is running. Waiting for it to complete on the server (server_pid=16)...
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /root/.cache/bazel/_bazel_root/5a0953e0b248bc640ac88d9f5df91e14/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/5a0953e0b248bc640ac88d9f5df91e14/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: rbe_default not using checked in configs; Bazel version 4.2.1 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"], "0.29.0": ["9.0.0"], "0.29.1": ["9.0.0", "10.0.0"], "1.0.0": ["9.0.0", "10.0.0"], "1.0.1": ["10.0.0"], "1.1.0": ["10.0.0"], "1.2.0": ["10.0.0"], "1.2.1": ["10.0.0"], "2.0.0": ["10.0.0"], "2.1.0": ["10.0.0"], "2.1.1": ["10.0.0", "11.0.0"], "2.2.0": ["11.0.0"], "3.0.0": ["11.0.0"], "3.1.0": ["11.0.0"], "3.2.0": ["11.0.0"], "3.3.0": ["11.0.0"], "3.3.1": ["11.0.0"], "3.4.1": ["11.0.0"], "3.5.0": ["11.0.0"], "3.5.1": ["11.0.0"], "3.6.0": ["11.0.0"], "3.7.0": ["11.0.0"], "3.7.1": ["11.0.0"], "3.7.2": ["11.0.0"], "4.0.0": ["11.0.0"]}
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: runsc
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/b7fe9697c0c76ab2fd431a891dbb9a6a32ed7c3e.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Analyzing: target //runsc:runsc (2 packages loaded, 0 targets configured)
INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = 6fcae9bbdd6275d99be6d5fc2b77b2b8f83e362520d8a461968e64c6d95dfe01
Analyzing: target //runsc:runsc (11 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (11 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (11 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (12 packages loaded, 6 targets configured)
Analyzing: target //runsc:runsc (23 packages loaded, 2185 targets configured)
Analyzing: target //runsc:runsc (23 packages loaded, 2185 targets configured)
Analyzing: target //runsc:runsc (23 packages loaded, 2185 targets configured)
Analyzing: target //runsc:runsc (23 packages loaded, 2185 targets configured)
Analyzing: target //runsc:runsc (23 packages loaded, 2185 targets configured)
INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
  /home/ubuntu/code/gvisor/WORKSPACE:76:21: in <toplevel>
  /root/.cache/bazel/_bazel_root/5a0953e0b248bc640ac88d9f5df91e14/external/bazel_gazelle/deps.bzl:75:24: in gazelle_dependencies
Repository rule go_repository_tools defined at:
  /root/.cache/bazel/_bazel_root/5a0953e0b248bc640ac88d9f5df91e14/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/5a0953e0b248bc640ac88d9f5df91e14/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
		fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: Timed out
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/5a0953e0b248bc640ac88d9f5df91e14/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
		fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: Timed out
ERROR: /home/ubuntu/code/gvisor/runsc/cli/BUILD:5:11: no such package '@com_github_google_subcommands//': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': failed to build tools: Timed out and referenced by '//runsc/cli:cli'
ERROR: Analysis of target '//runsc:runsc' failed; build aborted: Analysis failed
INFO: Elapsed time: 642.102s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (23 packages loaded, 2185 targets configured)
FAILED: Build did NOT complete successfully (23 packages loaded, 2185 targets configured)
Makefile:67: recipe for target 'copy' failed
make: *** [copy] Error 1
```

 I've been haunted by this question for a long time. And thank you very much. I personally think this problem is caused by some changes in some repo addresses, however, I have no idea how to solve it.
Thanks again.

**Comment by sureshdagooglecom** [comment]
Hi @moonBirdKiss ,
Could you please share steps to reproduce this issue.
