### ISSUE TITLE
All MediaPipe solutions on Python do not work with Turkish locale

### ISSUE THREAD

**Issue by insanolanbiri** [google/mediapipe#3311]
**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No. I used examples [here](https://google.github.io/mediapipe/solutions/)
- OS Platform and Distribution: Ubuntu 22.04 LTS with Turkish locale (tr_TR.UTF8)
- Programming Language and version: Python 3.10.4
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1 (Latest PyPI package)
- Solution: All python solutions in [here](https://google.github.io/mediapipe/solutions/)

**Describe the current behavior:**
All MediaPipe solutions in python fail when using Turkish locale (tr_TR.UTF8):
```
(mp) erena@Casper-PC:~/mp$ LC_ALL=tr_TR.UTF8 python3 hand.py 
Traceback (most recent call last):
  File "/home/erena/mp/hand.py", line 10, in <module>
    with mp_hands.Hands(
  File "/home/erena/mp/lib/python3.10/site-packages/mediapipe/python/solutions/hands.py", line 114, in __init__
    super().__init__(
  File "/home/erena/mp/lib/python3.10/site-packages/mediapipe/python/solution_base.py", line 237, in __init__
    validated_graph.initialize(
ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:palmdetectioncpu__Inferencecalculator__palmdetectioncpu__input_tensor" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").
```
**Describe the expected behavior:**
Solutions must work without any errors like in any other locale:
```
(mp) erena@Casper-PC:~/mp$ LC_ALL=en_US.UTF8 python3 hand.py 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
<example just works>
```

**Standalone code to reproduce the issue:**
All python solutions in [here](https://google.github.io/mediapipe/solutions/) can be used to reproduce the error; for example [this](https://google.github.io/mediapipe/solutions/hands.html#python-solution-api).

**Other info / Complete Logs :**
Since the error is something with regex, I think the issue is something about uppercase 'i' (which is 'İ', not 'I') and lowercase 'I' (which is 'ı', not 'i') in Turkish.

Also; #2306, #2603 and #1778 are related to this problem

**Comment by sureshdagooglecom** [comment]
Hi @insanolanbiri ,
Could you share code changes to investigate further on this issue.

**Comment by insanolanbiri** [comment]
> Hi @insanolanbiri ,
> Could you share code changes to investigate further on this issue.

Code changes? I tried every solutions' example in [here](https://google.github.io/mediapipe/solutions/) without any changes and any of them worked.

**Comment by insanolanbiri** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you.
> 

why

**Comment by sureshdagooglecom** [comment]
Hi @insanolanbiri ,
This could be a internationalization in mediapipe validation code on ValidfatedGraphConfig or a general bug in python internationalization.

**Comment by insanolanbiri** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you.
> 
why

**Comment by insanolanbiri** [comment]
> Closing as stale. Please reopen if you'd like to work on this further.

Why

**Comment by sureshdagooglecom** [comment]
Hi @insanolanbiri ,
Could you please check my above comments https://github.com/google/mediapipe/issues/3311#issuecomment-1125652702 and rever back still if you are facing any challenges.

**Comment by egirgin** [comment]
changing locale fixed my problem: https://askubuntu.com/a/227513

then log-out and log in back.

**Comment by serkancam** [comment]
> **System information** (Please provide as much relevant information as possible)
> 
>     * Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No. I used examples [here](https://google.github.io/mediapipe/solutions/)
> 
>     * OS Platform and Distribution: Ubuntu 22.04 LTS with Turkish locale (tr_TR.UTF8)
> 
>     * Programming Language and version: Python 3.10.4
> 
>     * [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.9.1 (Latest PyPI package)
> 
>     * Solution: All python solutions in [here](https://google.github.io/mediapipe/solutions/)
> 
> 
> **Describe the current behavior:** All MediaPipe solutions in python fail when using Turkish locale (tr_TR.UTF8):
> 
> ```
> (mp) erena@Casper-PC:~/mp$ LC_ALL=tr_TR.UTF8 python3 hand.py 
> Traceback (most recent call last):
>   File "/home/erena/mp/hand.py", line 10, in <module>
>     with mp_hands.Hands(
>   File "/home/erena/mp/lib/python3.10/site-packages/mediapipe/python/solutions/hands.py", line 114, in __init__
>     super().__init__(
>   File "/home/erena/mp/lib/python3.10/site-packages/mediapipe/python/solution_base.py", line 237, in __init__
>     validated_graph.initialize(
> ValueError: while processing the input streams of subgraph node InferenceCalculator: TAG:index:name is invalid, "TENSORS:palmdetectioncpu__Inferencecalculator__palmdetectioncpu__input_tensor" does not match "([A-Z_][A-Z0-9_]*:((0|[1-9][0-9]*):)?)?[a-z_][a-z0-9_]*" (examples: "TAG:name" "VIDEO:2:name_b", "longer_name").
> ```
> 
> **Describe the expected behavior:** Solutions must work without any errors like in any other locale:
> 
> ```
> (mp) erena@Casper-PC:~/mp$ LC_ALL=en_US.UTF8 python3 hand.py 
> INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> <example just works>
> ```
> 
> **Standalone code to reproduce the issue:** All python solutions in [here](https://google.github.io/mediapipe/solutions/) can be used to reproduce the error; for example [this](https://google.github.io/mediapipe/solutions/hands.html#python-solution-api).
> 
> **Other info / Complete Logs :** Since the error is something with regex, I think the issue is something about uppercase 'i' (which is 'İ', not 'I') and lowercase 'I' (which is 'ı', not 'i') in Turkish.
> 
> Also; #2306, #2603 and #1778 are related to this problem

Thanks
