### ISSUE TITLE
[Python] Error on import mediapipe

### ISSUE THREAD

**Issue by giannilabella** [google/mediapipe#3379]
**System information** 
- Windows 10
- Python 3.10.4
- Just installed mediapipe with pip
- ![image](https://user-images.githubusercontent.com/59416872/170405451-761b1a61-0e43-48b5-98f2-8d8b28285742.png)

**Describe the problem**:
I just installed mediapipe and I'm getting an error when I import it to my python file

Already tested and I get the error even with a blank file with just the import or import it on the python interactive console

**Complete Logs:**
```
Traceback (most recent call last):
  File "d:\Code\CodingChallenge-TheCodingTrain\ASCIIVideo-CC166\test.py", line 1, in <module>
    import mediapipe
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\__init__.py", line 17, 
in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\python\solutions\drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\framework\formats\detection_pb2.py", line 16, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 16, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\gianni\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 3. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by sureshdagooglecom** [comment]
Hi @giannilabella ,
Please try with below steps and share if any errors you face again.
!pip install mediapipe
pip show mediapipe
import mediapipe as mp

**Comment by lllying** [comment]
Hi @[giannilabella](https://github.com/giannilabella) ,
I met the same problem as you did, and I solved it by changing the package 'protobuf' to another version. Please try with it.

**Comment by giannilabella** [comment]
> Hi @giannilabella , Please try with below steps and share if any errors you face again. !pip install mediapipe pip show mediapipe import mediapipe as mp

I tried these steps but got the exact same error

> Hi @[giannilabella](https://github.com/giannilabella) , I met the same problem as you did, and I solved it by changing the package 'protobuf' to another version. Please try with it.

Downgraded protobuf to 3.20.1 and now it's working. 

Thanks for all the replies

**Comment by 1725917163** [comment]
> 下步骤，如果您再次遇到任何错误，请

Hello, I will try according to your method, but it is still the same mistake

**Comment by Sibtain-Iqbal** [comment]
> Hi @[giannilabella](https://github.com/giannilabella) , I met the same problem as you did, and I solved it by changing the package 'protobuf' to another version. Please try with it.

how to change protobuf
