### ISSUE TITLE
Default dependency with protobuf causes errors during import

### ISSUE THREAD

**Issue by FedericoCozziVM** [google/mediapipe#3392]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code: No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: No
- Programming Language and version ( e.g. C++, Python, Java): Python 3.8.10
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10
- Bazel version (if compiling from source):
- Solution ( e.g. FaceMesh, Pose, Holistic ):
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment):
- Xcode & Tulsi version (if issue is related to building for iOS):

**Describe the current behavior:**
When installing latest mediapipe version (0.8.10) via `pip install mediapipe` it install also required `protobuf` package at version `4.21.1`, which seems to cause error during import statements (i.e. `import mediapipe as mp`).

**Describe the expected behavior:**
Mediapipe should be installed and used without manually downgrade protobuf version

**Standalone code to reproduce the issue:**
```
python -m venv venv
source venv/bin/activate
pip install mediapipe
python -c "import mediapipe as mp"
```
**Error stack generated**:

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/python/solutions/drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/framework/formats/detection_pb2.py", line 16, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/framework/formats/location_data_pb2.py", line 16, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/mediapipe/framework/formats/annotation/rasterization_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/federico/Desktop/venv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```
**Other info :**
**FIX**: Downgrading to `protobuf==3.20.1` solves the problem.

**Comment by ayushgdev** [comment]
@FedericoCozziVM Can you please try with the latest version of MediaPipe since this isn't reproducible at our end.
