### ISSUE TITLE
android Failed to read file (.tflite file)

### ISSUE THREAD

**Issue by summer-dev** [google/mediapipe#3395]
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/holistic.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (No):
- OS Platform and Distribution (e.g., Ubuntu18.04 Win10 WSL):
- [MediaPipe version](https://github.com/google/mediapipe/releases/tag/v0.8.9): In fact,i downloaded the latest code(April 15 2022)
- Bazel version:5.0.0
- Solution (e.g. Holistic):
- Programming Language and version ( e.g. Java):Android java

**Describe the expected behavior:**

Dear Contributers:

I deployed the holistic solution as a aar to my android project,I can get all the landmark and everything goes well.

However this solution fails to load all the 7 tflite files with some occurrence and then my frame processor got stuck.

I know all the needed tflite(ie,pose_detection.tflite,face_landmark.tflite,pose_landmark_full.tflite,hand_landmark_full.tflite,face_detection_short_range.tflite,hand_recrop.tflite,handedness.txt,) files must be loaded before further processing,but it  only load several of these files sometimes.

The load task is executed within my main thread,below content is some log info

```
2022-03-28 15:44:35.177 13691-14281/cn.nubia.redmagickyi I/native: I20220328 15:44:35.177546 14281 jni_util.cc:41] GetEnv: not attached
2022-03-28 15:44:35.178 13691-14208/cn.nubia.redmagickyi I/native: I20220328 15:44:35.178539 14208 resource_util_android.cc:89] Successfully loaded: pose_detection.tflite
2022-03-28 15:44:35.179 13691-14209/cn.nubia.redmagickyi D/ExternalTextureConv: Created output texture: 1209 width: 720 height: 1280
2022-03-28 15:44:35.182 13691-14208/cn.nubia.redmagickyi I/tflite: Replacing 291 node(s) with delegate (unknown) node, yielding 1 partitions.
2022-03-28 15:44:35.182 13691-14284/cn.nubia.redmagickyi I/native: I20220328 15:44:35.182204 14284 resource_util_android.cc:89] Successfully loaded: face_landmark.tflite
2022-03-28 15:44:35.191 13691-14209/cn.nubia.redmagickyi D/ExternalTextureConv: Created output texture: 1210 width: 720 height: 1280
2022-03-28 15:44:35.201 13691-14285/cn.nubia.redmagickyi I/native: I20220328 15:44:35.201622 14285 jni_util.cc:41] GetEnv: not attached
2022-03-28 15:44:35.205 13691-14286/cn.nubia.redmagickyi I/native: I20220328 15:44:35.204953 14286 jni_util.cc:41] GetEnv: not attached
2022-03-28 15:44:35.210 13691-14279/cn.nubia.redmagickyi I/native: I20220328 15:44:35.210752 14279 resource_util_android.cc:89] Successfully loaded: pose_landmark_full.tflite
2022-03-28 15:44:35.217 13691-14282/cn.nubia.redmagickyi I/native: I20220328 15:44:35.217196 14282 resource_util_android.cc:89] Successfully loaded: hand_landmark_full.tflite
2022-03-28 15:44:35.224 13691-14280/cn.nubia.redmagickyi I/native: I20220328 15:44:35.224440 14280 resource_util_android.cc:89] Successfully loaded: hand_landmark_full.tflite

2022-03-28 15:44:35.230 13691-14209/cn.nubia.redmagickyi E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: unknown: Graph has errors: 
    Calculator::Open() for node "holisticlandmarkgpu__handlandmarksleftandrightgpu__handlandmarksfromposegpu_2__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read file
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:395)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:458)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:425)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:360)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:379)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
2022-03-28 15:44:35.251 13691-14208/cn.nubia.redmagickyi I/tflite: Replacing 291 node(s) with delegate (unknown) node, yielding 1 partitions.

```

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by sureshdagooglecom** [comment]
Hi @summer-dev ,
Could you provide steps to reproduce this issue.
