### ISSUE TITLE
I get this error if i run my project in vs code with "import mediapipe"

### ISSUE THREAD

**Issue by spaceathome100** [google/mediapipe#3426]
System information

- Windows 11
-Python 3.7.9
-installed opencv-python, mediapipe

Describe the problem:
I just installed mediapipe in vs code and I'm getting an error when I import it to my python file
Already tested and I get the error even with a blank file with just the import

```
PS C:\Opencv vs> & "c:/Opencv vs/venv/Scripts/python.exe" "c:/Opencv vs/Test.py"
Traceback (most recent call last):
  File "c:\Opencv vs\Test.py", line 2, in <module>
    import mediapipe as mp
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\__init__.py", line 17, in <module> 
    import mediapipe.python.solutions as solutions
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 16, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 16, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "C:\Opencv vs\venv\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Opencv vs\venv\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:   
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

Note:
-I have tried changing the protobuf version to 3.20.1 as it said but nothing changed it shows the same error
-even tried multiplayer python version interpreters like 3.8 and now i am using 3.7.10 but still this issue persists

Please help me guys

**Comment by kuaashish** [comment]
Hi @spaceathome100!, Could you try these two options.

1. **pip install protobuf==3.20.*** (It will downgrade the protobuf plugin to 3.20.x).
2. set the following environment variable **export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python**.

Attached is relevant [thread](https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly) for reference.

Thank you!

**Comment by spaceathome100** [comment]
dammm really thank finally it's working thank you very much

I tried out the first method and it magically work for me thank you so much

**Comment by ZaWarudo111** [comment]
`pip install protobuf==3.20.*` worked for me too! Thanks!

**Comment by YousefWaelSaleh** [comment]
Thank you very much!!!
