### ISSUE TITLE
Windows: Hello world build fails - python.exe is not executable

### ISSUE THREAD

**Issue by CookieHCl** [google/mediapipe#3459]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): **Windows 11 21H2 (22000.739)**
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): **gcc 11.2 (mingw-w64)**
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): **VS Build Tools 16.11.16/MSVC v142 VS 2019 C++ x64/x86 build tools**
- Installed using virtualenv? pip? Conda? (if python): **installed python from executable, Python 3.10.5**
- [MediaPipe version](https://github.com/google/mediapipe/releases): **v0.8.10**
- Bazel version: **5.1.0**
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop): **4.6.0**

- Also **Windows 11 SDK 10.0.22000.0**

**Describe the problem**:

I was trying to install mediapipe on Windows, and trying to test with Hello World example.

But bazel build failed with `Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\\Python310\\python.exe' is not executable. Is it the python binary?`, while `C:\\Python310\\python.exe` is a perfectly valid python executable and also runnable.

Seriously I have no idea what is going on. I've google the error message and the only answer was "just use the correct path".... Well I used the correct path!

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

I followed [install guide for windows](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) from 1~8,
and I ran `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Python310\\python.exe" mediapipe/examples/desktop/hello_world` at the mediapipe repository.

**Complete Logs:**
```
PS C:\mediapipe > bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Python310\\python.exe" mediapipe/examples/desktop/hello_world
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  C:/mediapipe/WORKSPACE:403:14: in <toplevel>
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\\Python310\\python.exe' is not executable. Is it the python binary?
ERROR: C:/mediapipe/WORKSPACE:403:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\\Python310\\python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:\\Python310\\python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 0.227s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 11 targets configured)
    Fetching @local_jdk; fetching
```
but python works just fine....
```
PS C:\mediapipe > C:\\Python310\\python.exe
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print('hello world')
hello world
>>> exit()
```

**Comment by kuaashish** [comment]
Hi @CookieHCl, Seems you have used the path where Python has installed, You need to add the Python Binary path to install MediaPipe.
Could you try following commands to find the binary path in Python interpreter:

 `>>> import os`
 `>>> import sys`
 `>>> os.path.dirname(sys.executable)`
 `>>> Python Binary Path`

I hope it will work. Thank you!

**Comment by CookieHCl** [comment]
Still, it seems `C:\\Python310\\python.exe` is the correct path..
```
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> os.path.dirname(sys.executable)
'C:\\Python310'
>>> sys.executable
'C:\\Python310\\python.exe'
```

**Comment by kuaashish** [comment]
Hi @CookieHCl, Seems unable to understand the same path for both. Could you look into the below path on your Windows(**If Exist**) and try to add the similar path to install the MediaPipe.

> 'C:/Users/Username/AppData/Local/Programs/Python/Python310/python.exe'

Please let us know if this resolves the issue. Thank you

**Comment by CookieHCl** [comment]
OK. I've managed to get a new error message...

I'm using PowerShell 7.2.5 to type install command, but it seems bazel uses bash (likely msys2, since I don't have other bash) to run command. So `C:\\Python310\\python.exe` was the correct path in windows, but I had to use `/mnt/c/Python310/python.exe` in bazel.

Now _python.exe is not executable_ error doesn't appears, but here is the new error....

```
PS C:\mediapipe [master ≡]> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="/mnt/c/Python310/python.exe" mediapipe/examples/desktop/hello_world
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  C:/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/mediapipe/WORKSPACE:403:14: in <toplevel>
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\cookiehcl\_bazel_cookiehcl\3vmcl3ou\external\local_execution_config_python\mnt\c\Python310\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + l(...)): ??? ??? ?? ? ????.
 (error: 2)
ERROR: C:/mediapipe/WORKSPACE:403:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\cookiehcl\_bazel_cookiehcl\3vmcl3ou\external\local_execution_config_python\mnt\c\Python310\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + l(...)): ??? ??? ?? ? ????.
 (error: 2)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed
java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("C:\users\cookiehcl\_bazel_cookiehcl\3vmcl3ou\external\local_execution_config_python\mnt\c\Python310\python.exe" -c "from os import linesep;f = open('script.py', 'w');f.write(\"from __future__ import print_function\" + linesep);f.write(\"import site\" + linesep);f.write(\"import os\" + linesep);f.write(\"python_paths = []\" + linesep);f.write(\"if os.getenv('PYTHONPATH') is not None:\" + linesep);f.write(\"  python_paths = os.getenv('PYTHONPATH').split(':')\" + linesep);f.write(\"try:\" + l(...)): ??? ??? ?? ? ????.
 (error: 2)
INFO: Elapsed time: 3.783s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

OK so error message is `??? ??? ?? ? ????`..... I thought this was cp949 (Korean codepage, the default codepage I'm using.) problem, so I used `$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding` to make my Powershell's codepage to UTF-8, but error message still appears as `??? ??? ?? ? ????`.  
Maybe bazel or msys2 bash encoding is wrong? But I don't know how to solve it....

However I was able to find the reason of the error: `C:\users\cookiehcl\_bazel_cookiehcl\3vmcl3ou\external\local_execution_config_python\mnt\c\Python310\python.exe` just simply didn't exist.

Only `C:\Users\CookieHCl\_bazel_CookieHCl\3vmcl3ou\external\local_execution_config_python\` exists, and it's empty directory. (i.e. there wasn't such thing as `mnt\c\Python310\python.exe`)  
Any idea how to solve this issue?

**Comment by kuaashish** [comment]
Hi @CookieHCl, MediaPipe currently tested with Bash MSMY2. Please follow the [instructions](recommend) mentioned in the official documentation. Thank you

**Comment by kuaashish** [comment]
Hi @CookieHCl, Did you try with [above](https://github.com/google/mediapipe/issues/3459#issuecomment-1165307148) workaround mentioned. If tried, Could you please share the complete error log. Thank you

**Comment by CookieHCl** [comment]
@kuaashish No, I couldn't do it because that path didn't exist. `'C:/Users/Username/AppData/Local/Programs/` didn't have `Python` directory. (Also checked LocalLow, Roaming)

If you really need the log, here's the log, but it's the same `python.exe is not executable` error.

```
C:\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:/Users/CookieHCl/AppData/Local/Programs/Python/Python310/python.exe" mediapipe/examples/desktop/hello_world
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/mediapipe/WORKSPACE:403:14: in <toplevel>
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolchains
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/CookieHCl/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
ERROR: C:/mediapipe/WORKSPACE:403:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/cookiehcl/_bazel_cookiehcl/3vmcl3ou/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/CookieHCl/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:/Users/CookieHCl/AppData/Local/Programs/Python/Python310/python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 0.211s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by kuaashish** [comment]
Hi @sureshdagooglecom, Could you please look into this issue. Thank you!

**Comment by CookieHCl** [comment]
Oops... Sorry this was my issue..
I just found out WSL also makes bash command... I thought `wsl` was the only way to open WSL, but `bash` can also open WSL too...
So instead of msys2 bash, WSL bash was opening...

I solved this by setting BAZEL_SH environment variable mentioned [here](https://docs.bazel.build/versions/main/install-windows.html#bazel-does-not-find-bash-or-bashexe).

**Comment by kuaashish** [comment]
Hi @CookieHCl, Thanks for the confirmation! Can we move this issue to close status.
Thank you

**Comment by CookieHCl** [comment]
Yes, I'll close this issue.
Thanks for your help!

**Comment by nurshafiza** [comment]
> Hi @CookieHCl, Seems you have used the path where Python has installed, You need to add the Python Binary path to install MediaPipe. Could you try following commands to find the binary path in Python interpreter:
> 
> `>>> import os` `>>> import sys` `>>> os.path.dirname(sys.executable)` `>>> Python Binary Path`
> 
> I hope it will work. Thank you!
I've tried as what you suggested but it occur like this

>>> import os
>>> import sys
>>> os.path.dirname(sys.executable)
'C:\\Python 3.10'
>>> Python Binary Path
  File "<stdin>", line 1
    Python Binary Path
           ^^^^^^
SyntaxError: invalid syntax

**Comment by kuaashish** [comment]
Hi @nurshafiza, Could you please raise a separate new issue and provide the complete details to reproduce the issue from our end. Thank you!
