### ISSUE TITLE
RuntimeError: failed to invoke XNNPACK runtimeNode number 205 (TfLiteXNNPackDelegate) failed to invoke.

### ISSUE THREAD

**Issue by TranDuyNhat** [google/mediapipe#3463]
Hello, I'am running yolo v4 on raspberry pi wwith tensorflow 2.9. I met this error while running. Please help me. Thanks

Traceback (most recent call last):
  File "/home/pi/Final_Project/tensorflow-yolov4-tflite-ok/detectvideo.py", line 97, in <module>
    app.run(main)
  File "/home/pi/.local/bin/.virtualenvs/hope_env/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/pi/.local/bin/.virtualenvs/hope_env/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/pi/Final_Project/tensorflow-yolov4-tflite-ok/detectvideo.py", line 63, in main
    interpreter.invoke()
  File "/home/pi/.local/bin/.virtualenvs/hope_env/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py", line 915, in invoke
    self._interpreter.Invoke()
RuntimeError: failed to invoke XNNPACK runtimeNode number 205 (TfLiteXNNPackDelegate) failed to invoke.

**Comment by sureshdagooglecom** [comment]
Hi @TranDuyNhat ,
This issue is related to Tensorflow , please post this issue in Tensorflow repo since this is MediaPipe repo.
