### ISSUE TITLE
TfLiteGpuDelegate Prepare: OpenGL ES 3.1 or above is required to use OpenGL inference arm64-v8a

### ISSUE THREAD

**Issue by monxarat** [google/mediapipe#3480]
Hi guys,

When I ran FaceDetection mode on the mobile device `arm64-v8a`, the below error has occurred, how to solve this problem.

My device uses OpenGL ES 3.2
```
2022-07-01 16:17:57.670 8348-8353/com.test.face I/art: Do partial code cache collection, code=27KB, data=29KB
2022-07-01 16:17:57.671 8348-8353/com.test.face I/art: After code cache collection, code=27KB, data=29KB
2022-07-01 16:17:57.671 8348-8353/com.test.face I/art: Increasing code cache capacity to 128KB
2022-07-01 16:17:57.742 8348-8348/com.test.face I/native: I20220701 16:17:57.742640  8348 asset_manager_util.cc:59] Created global reference to asset manager.
2022-07-01 16:17:57.776 8348-8348/com.test.face E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
2022-07-01 16:17:57.776 8348-8348/com.test.face I/native: I20220701 16:17:57.776747  8348 gl_context_egl.cc:84] Successfully initialized EGL. Major : 1 Minor: 4
2022-07-01 16:17:57.780 8348-8459/com.test.face I/native: I20220701 16:17:57.779997  8459 gl_context.cc:335] GL version: 3.0 (OpenGL ES 3.0 r16p0-00rel0.7fb0319.5cd653ef10a8dffb3fe634024e9eda82)
2022-07-01 16:17:57.794 8348-8348/com.test.face I/native: I20220701 16:17:57.794626  8348 graph.cc:478] Start running the graph, waiting for inputs.
2022-07-01 16:17:57.809 8348-8459/com.test.face I/native: I20220701 16:17:57.809724  8459 resource_util_android.cc:89] Successfully loaded: face_detection_short_range.tflite
2022-07-01 16:17:57.811 8348-8459/com.test.face I/tflite: Initialized TensorFlow Lite runtime.
2022-07-01 16:17:57.812 8348-8459/com.test.face I/tflite: Created TensorFlow Lite delegate for GPU.
2022-07-01 16:17:57.814 8348-8459/com.test.face I/tflite: Replacing 164 node(s) with delegate (TfLiteGpuDelegate) node, yielding 1 partitions.
2022-07-01 16:17:57.823 8348-8459/com.test.face E/tflite: TfLiteGpuDelegate Prepare: OpenGL ES 3.1 or above is required to use OpenGL inference.
2022-07-01 16:17:57.823 8348-8459/com.test.face E/tflite: Node number 164 (TfLiteGpuDelegate) failed to prepare.
2022-07-01 16:17:57.824 8348-8459/com.test.face E/tflite: Restored original execution plan after delegate application failure.
2022-07-01 16:17:57.825 8348-8348/com.test.face E/native: E20220701 16:17:57.825652  8348 calculator_graph.cc:844] INTERNAL: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "facedetectionshortrange__facedetection__inferencecalculator__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:222) (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)
2022-07-01 16:17:57.836 8348-8348/com.test.face E/SolutionBase: Error occurs while starting the MediaPipe solution graph. Error details: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "facedetectionshortrange__facedetection__inferencecalculator__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:222) (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)
    com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "facedetectionshortrange__facedetection__inferencecalculator__facedetectionshortrange__facedetection__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:222) (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)
        at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
        at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:452)
        at com.google.mediapipe.solutioncore.SolutionBase.start(SolutionBase.java:126)
        at com.google.mediapipe.solutions.facedetection.FaceDetection.<init>(FaceDetection.java:85)
        at vtm.co.jp.facevtz.DetectorFragment.onCreate(DetectorFragment.java:250)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
        at android.app.Activity.performStart(Activity.java:6699)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2022-07-01 16:17:57.837 8348-8348/com.test.face D/AndroidRuntime: Shutting down VM
2022-07-01 16:17:57.850 8348-8404/com.test.face D/TransportRuntime.SQLiteEventStore: Storing event with priority=DEFAULT, name=COREML_ON_DEVICE_SOLUTIONS for destination cct

```

**Comment by kuaashish** [comment]
Hi @monxarat, Please refer this issue #3153 for your query. Thank you
