### ISSUE TITLE
"'NoneType' object is not subscriptable" in pose.process(im)

### ISSUE THREAD

**Issue by JoseBarreiros-TRI** [google/mediapipe#3485]
- Linux Ubuntu 20.04:
- Solution: Pose
- Python 3

Hi, I am writing a wrapper for the pose solution such that the initialization and processing of a frame are easily accessible. 
When running `pose.process(image)`, I get a `'NoneType' object is not subscriptable` error at the second iteration. Here is the code to reproduce it.
import cv2
import mediapipe as mp
import pdb
import time

```
class MediapipeController:
  def __init__(self,camera_port):
      self.mp_drawing = mp.solutions.drawing_utils
      self.mp_drawing_styles = mp.solutions.drawing_styles
      self.mp_pose = mp.solutions.pose
      # For webcam input:
      self.cap = cv2.VideoCapture(camera_port)
      # self.pose=self.mp_pose.Pose(
      #     min_detection_confidence=0.5,
      #     min_tracking_confidence=0.5)
      self.pose=self.mp_pose.Pose(
          static_image_mode=True,
          model_complexity=2,
          enable_segmentation=True,
          min_detection_confidence=0.5) 
      time.sleep(1)
      #pdb.set_trace()

  def process_frame(self):
      #pdb.set_trace()
      with self.pose as pose:
          if self.cap.isOpened():
              success, image = self.cap.read()
              if not success:
                  print("Ignoring empty camera frame.")
                  # If loading a video, use 'break' instead of 'continue'.

              # To improve performance, optionally mark the image as not writeable to
              # pass by reference.
              image.flags.writeable = False
              image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
              results = pose.process(image)
              
              # Draw the pose annotation on the image.
              image.flags.writeable = True
              image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
              # self.mp_drawing.draw_landmarks(
              #     image,
              #     results.pose_landmarks,
              #     self.mp_pose.POSE_CONNECTIONS,
              #     landmark_drawing_spec=self.mp_drawing_styles.get_default_pose_landmarks_style())
              # Flip the image horizontally for a selfie-view display.
              #cv2.imshow('MediaPipe Pose', cv2.flip(image, 1))
              #cv2.waitKey(1) 
      return results

if __name__ == "__main__":
  TeleopManager=MediapipeController(0)
  n=10
  i=0
  while i<n:
    print("i: ", i,"\n")
    results=TeleopManager.process_frame()
    i+=1
```

Traceback:
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
i:  0 

i:  1 

Traceback (most recent call last):
  File "/home/josebarreiros/.cache/bazel/_bazel_josebarreiros/90f3e8e4e37bf5312f47e87299f7a9c9/execroot/drake/bazel-out/k8-opt/bin/examples/ruxid/python_humanoid_torso_idc_box_lcm/mediapipe_test2.runfiles/drake/examples/ruxid/python_humanoid_torso_idc_box_lcm/mediapipe_test2.py", line 37, in process_frame
    results = pose.process(image)
  File "/home/josebarreiros/.local/lib/python3.8/site-packages/mediapipe/python/solutions/pose.py", line 185, in process
    results = super().process(input_data={'image': image})
  File "/home/josebarreiros/.local/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 342, in process
    input_stream_type = self._input_stream_type_info[stream_name]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by kuaashish** [comment]
Hi @JoseBarreiros-TRI, Could you please provide the reproducible code to investigate it further. Thank you!
