### ISSUE TITLE
Face mesh memory leak

### ISSUE THREAD

**Issue by stoneaccount** [google/mediapipe#3487]
when i use face mesh in my program，I find that the face mesh cause my activity leak. the gc cannot clear the activity after i finished it

in method onCreate i init face mesh
        facemesh =
                new FaceMesh(
                        this,
                        FaceMeshOptions.builder()
                                .setStaticImageMode(false)
                                .setRefineLandmarks(true)
                                .setRunOnGpu(RUN_ON_GPU)
                                .build());
        facemesh.setErrorListener((message, e) -> Log.e(TAG, "MediaPipe Face Mesh error:" + message));
//        cameraInput = new CameraInput(this);
//        cameraInput.setNewFrameListener(textureFrame -> facemesh.send(textureFrame));

        // Initializes a new Gl surface view with a user-defined FaceMeshResultGlRenderer.
        glSurfaceView =
                new SolutionGlSurfaceView<>(this, facemesh.getGlContext(), facemesh.getGlMajorVersion());
        glSurfaceView.setSolutionResultRenderer(new FaceMeshResultGlRenderer());
        glSurfaceView.setRenderInputImage(true);
        facemesh.setResultListener(
                faceMeshResult -> {
                    glSurfaceView.setRenderData(faceMeshResult);
                    glSurfaceView.requestRender();
                    checkLandMark(faceMeshResult, /*showPixelValues=*/ false);
                });

in method  i started the camera input

        cameraInput = new CameraInput(this);
        cameraInput.setNewFrameListener(consumer);
        glSurfaceView.post(new Runnable() {
            @Override
            public void run() {
                startCamera();
            }
        });
        glSurfaceView.setVisibility(View.VISIBLE);

in method onPause i recycled

        glSurfaceView.setVisibility(View.GONE);
        cameraInput.setNewFrameListener(null);
        cameraInput.close();

in method onDestory i released
        if (facemesh != null) {
            facemesh.close();
            consumer = null;
        }

but the LeakCanary report show me that and profile show me the activity more than 5 instance in java heap after gc
![Screenshot_2022-07-04-09-22-05-358_com btn skin_ B@e554b02](https://user-images.githubusercontent.com/39260652/177066509-401bd229-3156-439b-a616-812488b1ff3e.jpg)

**Comment by sureshdagooglecom** [comment]
Hi @stoneaccount ,
Can you share the error logs to investigate further ?

**Comment by stoneaccount** [comment]
The log below is my app crashed log


07-01 16:07:21.076 11302 11302 E AndroidRuntime: FATAL EXCEPTION: main
07-01 16:07:21.076 11302 11302 E AndroidRuntime: Process: com.btn.skin, PID: 11302
07-01 16:07:21.076 11302 11302 E AndroidRuntime: java.lang.RuntimeException: lock buffer failed for format 0x21
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.media.ImageReader$SurfaceImage.nativeCreatePlanes(Native Method)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:1013)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.AndroidImageProxy.<init>(AndroidImageProxy.java:48)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.AndroidImageReaderProxy.acquireNextImage(AndroidImageReaderProxy.java:94)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.MetadataImageReader.imageIncoming(MetadataImageReader.java:320)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.MetadataImageReader.lambda$new$0$MetadataImageReader(MetadataImageReader.java:63)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.-$$Lambda$MetadataImageReader$DONJ_Tb-b_WYV8EceE_yMZTG_HA.onImageAvailable(Unknown Source:2)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.AndroidImageReaderProxy.lambda$setOnImageAvailableListener$0$AndroidImageReaderProxy(AndroidImageReaderProxy.java:139)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at androidx.camera.core.-$$Lambda$AndroidImageReaderProxy$RyV51268LxqXqf_5yS6H_QoqpDY.run(Unknown Source:4)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:233)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.os.Looper.loop(Looper.java:344)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8210)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
07-01 16:07:21.076 11302 11302 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)


i repeat that action that  starting the the face mesh activity and taking photo about fifty times，then my app crashed the log show me that

07-01 16:07:21.057 11302 11302 D qdgralloc: GetYUVPlaneInfo: Invalid format passed: 0x21
07-01 16:07:21.057 11302 11302 E qdgralloc: ion: Failed to map memory in the client: Out of memory


when i use the leakCanary and check the memory show me  that the activity was hold by the face mesh as you see

**Comment by stoneaccount** [comment]
[log11111.txt](https://github.com/google/mediapipe/files/9051951/log11111.txt)

**Comment by sureshdagooglecom** [comment]
Hi @stoneaccount ,
It  should now be fixed with the latest update. I tried the link you provided just now (on Chrome Desktop), and was unable to reproduce the leak, taking snapshots every 10 seconds .

**Comment by stoneaccount** [comment]
taking snapshots donot product the leak， starting activity ---> taking snapshots  --->finish activity will make the activity leak

**Comment by sureshdagooglecom** [comment]
Hi @stoneaccount ,
can you provide code changes to investigate further on this issue.
