### ISSUE TITLE
pip install mediapipe does not work

### ISSUE THREAD

**Issue by DereAbdulhameed** [google/mediapipe#3549]
System information:

OS Platform and Distribution: Windows 11.0.1
Python version: 3.9.0
opencv-python | 4.6.0.66

I tried installing mediapipe through pip on pycharm

Describe the problem:
I've followed all the instructions on how to install mediapipe from the official website but have been unsuccessful. "pip install mediapipe" and "pip3 install mediapipe" unfortunately returns the errors of "pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files
.pythonhosted.org', port=443): Read timed out."

"complete logs":
Collecting mediapipe
  Downloading mediapipe-0.8.10.1-cp39-cp39-win_amd64.whl (48.7 MB)
     ------------- ------------------------- 16.3/48.7 MB 13.7 kB/s eta 0:39:26
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\urllib3\response.py", line 435, in _error_catcher
    yield
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\http\client.py",
line 458, in read
    n = self.readinto(b)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\http\client.py",
line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\socket.py", line
704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 124
1, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 109
9, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_
link
    self._link_candidate_cache[link] = LinkCandidate(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribut
ion
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)

  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip
\_vendor\urllib3\response.py", line 538, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\contextlib.py", l
ine 135, in __exit__                                 ine 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\hp\pycharmprojects\bodyposedetection\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

I'm trying to run the sample videocamera code for mediapipe to detect body poses.

Is there a way to make the "pip install mediapipe" step to run properly? Thank you.

**Comment by onuralpszr** [comment]
The error you got pointing that you have a network. You may want to check that one out. Because installation in here works just fine. Also you when you create virtualenv or using your main python installation on windows make sure you also have "updated" "pip" as well. (pip install pip --upgrade)

**Comment by kuaashish** [comment]
Hi @DereAbdulhameed, Could you please refer to this [issue](https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port) for your query. Thank you!

**Comment by DSNOffa** [comment]
> Hi @DereAbdulhameed, Could you please refer to this [issue](https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port) for your query. Thank you!
I have gone through the solution here and it work absolutely fine. Thank you

**Comment by DereAbdulhameed** [comment]
> > Hi @DereAbdulhameed, Could you please refer to this [issue](https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port) for your query. Thank you!
> > I have gone through the solution here and it work absolutely fine. Thank you

Thank you. It has worked now. It was largely due to network issues
