### ISSUE TITLE
Pose - 404 error when loading model

### ISSUE THREAD

**Issue by bossebandowski** [google/mediapipe#3675]
Loading the pose model fails across multiple platforms and devices
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.10.2
- Bazel version: 5.2.0
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): Python3.10

**Describe the expected behavior:**
Expecting
```
        with mp_pose.Pose(
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5,
            model_complexity=model_complexity,
            smooth_landmarks=True,
        ) as pose:
```
to load the model and allow me to run subsequent inferences. Instead, I get the following error:

```
Downloading model to /usr/local/lib/python3.10/site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite
Traceback (most recent call last):
  File "/usr/local/bin/pose_estimation", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/pose_estimation/pose_estimation.py", line 279, in main
    pose_estimator.start_pose_estimation(
  File "/usr/local/lib/python3.10/site-packages/pose_estimation/pose_estimation.py", line 142, in start_pose_estimation
    with mp_pose.Pose(
  File "/usr/local/lib/python3.10/site-packages/mediapipe/python/solutions/pose.py", line 145, in __init__
    _download_oss_pose_landmark_model(model_complexity)
  File "/usr/local/lib/python3.10/site-packages/mediapipe/python/solutions/pose.py", line 100, in _download_oss_pose_landmark_model
    download_utils.download_oss_model(
  File "/usr/local/lib/python3.10/site-packages/mediapipe/python/solutions/download_utils.py", line 32, in download_oss_model
    with urllib.request.urlopen(model_url) as response, open(model_abspath,
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Looks like this might be related to #3674

**Comment by RichardLindhout** [comment]
Same problem it worked before!

**Comment by RichardLindhout** [comment]
Thanks @bossebandowski!

Added this to my Dockerfile
```
# bugfix for https://github.com/google/mediapipe/issues/3675
COPY pose_landmark_heavy.tflite /usr/local/lib/python3.8/dist-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite

```

**Comment by schmidt-sebastian** [comment]
The download script has been updated. Please pull the latest update from `master`.

**Comment by kuaashish** [comment]
Hi @bossebandowski, The model should now work as expected it was working earlier. Could you confirm that and close this issue as it has been resolved. Thank you!

**Comment by bossebandowski** [comment]
Yes, thanks for the quick work
