### ISSUE TITLE
Bazel can't recognize python binary path

### ISSUE THREAD

**Issue by nurshafiza** [google/mediapipe#3692]
Hi, can you help me with this issue:

`ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'system' is not defined
ERROR: C:/users/user/mediapipe_repo/mediapipe/WORKSPACE:476:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'system' is not defined
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'system' is not defined
INFO: Elapsed time: 6.055s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 11 targets config\
ured)`

I've tried this solution #724 but still didn't work for me. I also tried to recognize the path by run `sys.executable` on python interpreter but it still didn't work. I'm using the latest version of Bazel, python 3.10 and Git Bash

This is the command that i run
`C:\Users\User\mediapipe_repo\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python_3.10//python.exe" mediapipe/examples/desktop/hello_world`

**Comment by nurshafiza** [comment]
Update:
I've tried to run the command as below
`bazel build -c opt \
  --define MEDIAPIPE_DISABLE_GPU=1 \
  --action_env PYTHON_BIN_PATH=$(C://Python_3.10//python.ex) \
  mediapipe/examples/desktop/hello_world`

and seems the error occured when i ran `bazel build mediapipe/examples/desktop/hello_world`. This is the error:

`ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
ERROR: C:/users/user/mediapipe_repo/mediapipe/WORKSPACE:476:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/user/_bazel_user/bkk7hz7b/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
INFO: Elapsed time: 2.433s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 11 targets config\
ured)`

**Comment by kishor-e** [comment]
Could you check if the python environment path is set `C:\Python_3.10\` . If so, try running this command

**Comment by kuaashish** [comment]
Hi @nurshafiza, It seems the command used to reproduce this issue is not clear. Could you provide the clear command and steps  to reproduce the issue. Thank you!

**Comment by kishor-e** [comment]
Could you check if Python Environment Path is set `C:\Python_3.10\` .                                                                                             If so try running this command `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Python_3.10\python.exe" mediapipe/examples/desktop/hello_world` . If It still doesnt work try installing numpy and then try again.

**Comment by RuentGen** [comment]
I have a similar problem 

DEBUG: C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  C:/users/ruentgen/documents/mediapipe/WORKSPACE:479:14: in <toplevel>
  C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/tensorflow/workspace2.bzl:879:19: in workspace
  C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/tensorflow/workspace2.bzl:86:27: in _tf_toolchains
  C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'system' is not defined
ERROR: C:/users/ruentgen/documents/mediapipe/WORKSPACE:479:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'system' is not defined
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'system' is not defined
INFO: Elapsed time: 0.397s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (37 packages loaded, 11 targets configured)

**Comment by nurshafiza** [comment]
> Could you check if Python Environment Path is set `C:\Python_3.10\` . If so try running this command `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Python_3.10\python.exe" mediapipe/examples/desktop/hello_world` . If It still doesnt work try installing numpy and then try again.

Thanks! this solution works well for me

**Comment by kuaashish** [comment]
Hi @nurshafiza, Glad to hear that issue has been fixed. Could we move this issue to close status as it has been resolved. Thank you!

**Comment by nurshafiza** [comment]
> Hi @nurshafiza, Glad to hear that issue has been fixed. Could we move this issue to close status as it has been resolved. Thank you!

Yes, thank you so much for your reply!

**Comment by AlexiaAnn** [comment]
> Hi guys I'm trying to build the hello_workd solution and I get this similar problem I already tried this [steps](https://github.com/google/mediapipe/issues/724#issue-622686030) but it does not fix the problem
> 
> ERROR: An error occurred during the fetch of repository 'local_execution_config_python': Traceback (most recent call last): File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository python_lib = _get_python_lib(repository_ctx, python_bin) File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib result = execute(repository_ctx, [python_bin, "-c", cmd]) File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute fail( Error in fail: Repository command failed Traceback (most recent call last): File "", line 1, in NameError: name 'system' is not defined ERROR: C:/users/ruentgen/documents/mediapipe/WORKSPACE:479:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last): File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 33, in _create_local_python_repository python_lib = _get_python_lib(repository_ctx, python_bin) File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib result = execute(repository_ctx, [python_bin, "-c", cmd]) File "C:/users/ruentgen/_bazel_programmerruent/badkprfe/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute fail( Error in fail: Repository command failed Traceback (most recent call last): File "", line 1, in NameError: name 'system' is not defined ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository command failed Traceback (most recent call last): File "", line 1, in NameError: name 'system' is not defined INFO: Elapsed time: 0.397s INFO: 0 processes. FAILED: Build did NOT complete successfully (37 packages loaded, 11 targets configured)

Have you solved it?

**Comment by kewell-tsao** [comment]
[https://github.com/google-ai-edge/mediapipe/issues/4622#issuecomment-2268186119](https://github.com/google-ai-edge/mediapipe/issues/4622#issuecomment-2268186119)
