### ISSUE TITLE
Backward compatibility for downloading tflite files from the repository

### ISSUE THREAD

**Issue by eyalgomel** [google/mediapipe#3698]
I'm using mediapipe 0.8.10 and can't download the models due to an HTTP error.
I suspect the issue come mediapipe/python/solutions/download_utils.py, 
where _OSS_URL_PREFIX = 'https://github.com/google/mediapipe/raw/master/'
but the tflite files aren't stored in the master anymore.

log:
Traceback (most recent call last):
    mp_extractor = mp.solutions.holistic.Holistic(
  File "/env/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 113, in __init__
    _download_oss_pose_landmark_model(model_complexity)
  File "/env/lib/python3.8/site-packages/mediapipe/python/solutions/holistic.py", line 59, in _download_oss_pose_landmark_model
    download_utils.download_oss_model(
  File "/env/lib/python3.8/site-packages/mediapipe/python/solutions/download_utils.py", line 32, in download_oss_model
    with urllib.request.urlopen(model_url) as response, open(model_abspath,
  File "/env/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/env/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/env/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/env/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/env/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/env/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Thanks,

**Comment by kuaashish** [comment]
Hi @eyalgomel, This is due to latest release `8.11` downloading `*.tflite model` files and other large binaries from our `GitHub repository` has moved to `Google Cloud Storage`. If you are fetching problem to download then please update the file [download_utils.py](https://github.com/google/mediapipe/blob/d3f98334bfe533a57ec2c2fa85294c21e25fe0af/mediapipe/python/solutions/download_utils.py) as mentioned [here](https://github.com/google/mediapipe/releases/tag/v0.8.11). Thank you!

**Comment by kuaashish** [comment]
Hi @andrechen, Thank you for brining up to our notice. Could you raise a new separate issue for problem you are facing to fetch files and will raise this concern with the internal team. Thank you!

**Comment by kuaashish** [comment]
Hi @eyalgomel, Could you please let us know if your issue has been resolved as per the above [comment.](https://github.com/google/mediapipe/issues/3698#issuecomment-1247905371) Thank you!

**Comment by eyalgomel** [comment]
Yes,
Though I wish there was a way to work with previous versions without update the download script.

Thank you!
