### ISSUE TITLE
Autoflip error when bazel build（Windows11）

### ISSUE THREAD

**Issue by photkey** [google/mediapipe#3718]
**System information** 
- OS Platform and Distribution:Windows11 21H2 (22000.978)
- gcc.exe (GCC) 11.2.0, Python 3.9
- Bazel 5.3.1
- OpenCV 3.4.15

**Describe the problem**:
I have followed the installation tutorial of Mediapipe on windows11 platform. Mediapipe could be built.
But there was a confusing error when I wanted to build the Autoflip solution.

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://Program Files//Python//Python39//python.exe" mediapipe/examples/desktop/autoflip:run_autoflip`

For this problem, I have tried to clean the bazel file through "bazel clean --expunge". This issue still happened. What detail am I missing?
Thanks!
**Complete Logs:**
`
PS D:\MySoft\RunAny\Python\mediapipe> bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="D://Program Files//Python//Python39//python.exe" mediapipe/examples/desktop/autoflip:run_autoflip`
```
Starting local Bazel server and connecting to it...
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  D:/mysoft/runany/python/mediapipe/WORKSPACE:49:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "691a29db9c336349e48e04c5c2f4873f2890af5cbfa6e51f4de87fefe6169294"
DEBUG: Repository rules_cc instantiated at:
  D:/mysoft/runany/python/mediapipe/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
WARNING: D:/mysoft/runany/python/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: D:/mysoft/runany/python/mediapipe/mediapipe/framework/tool/BUILD:185:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Repository libyuv instantiated at:
  D:/mysoft/runany/python/mediapipe/WORKSPACE:122:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
WARNING: Download from https://chromium.googlesource.com/libyuv/libyuv/+archive/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'libyuv':
   Traceback (most recent call last):
        File "C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://chromium.googlesource.com/libyuv/libyuv/+archive/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz] to C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/libyuv/temp14820430777943765884/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz: connect timed out
ERROR: D:/mysoft/runany/python/mediapipe/WORKSPACE:122:13: fetching http_archive rule //external:libyuv: Traceback (most recent call last):
        File "C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://chromium.googlesource.com/libyuv/libyuv/+archive/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz] to C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/libyuv/temp14820430777943765884/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz: connect timed out
ERROR: D:/mysoft/runany/python/mediapipe/mediapipe/calculators/image/BUILD:392:11: //mediapipe/calculators/image:scale_image_calculator depends on @libyuv//:libyuv in repository @libyuv which failed to fetch. no such package '@libyuv//': java.io.IOException: Error downloading [https://chromium.googlesource.com/libyuv/libyuv/+archive/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz] to C:/users/vimcode/_bazel_vimcode/qoddrxn6/external/libyuv/temp14820430777943765884/2525698acba9bf9b701ba6b4d9584291a1f62257.tar.gz: connect timed out
ERROR: Analysis of target '//mediapipe/examples/desktop/autoflip:run_autoflip' failed; build aborted:
INFO: Elapsed time: 211.795s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (134 packages loaded, 5731 targets configured)```

**Comment by kuaashish** [comment]
Hi @photkey, 
Have you looked at this similar closed issue #1545 and [comment(1545)](https://github.com/google/mediapipe/issues/1545#issuecomment-766588998). Thank you!
