### ISSUE TITLE
Unable to build via Android Studio

### ISSUE THREAD

**Issue by Acimaz** [google/mediapipe#373]
Im somehow unable to build with android studio. This is the log i get when running the bazel mobile install config in android studio:

`C:\Users\acima\Downloads\bazel.exe mobile-install --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no -c opt --config=android_arm -- //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (1 packages loaded, 0 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (40 packages loaded, 243 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (42 packages loaded, 704 targets configured)
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (42 packages loaded, 704 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (43 packages loaded, 704 targets configured)
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (43 packages loaded, 6988 targets configured)
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl:121:19):
 - C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/tensorflow/workspace.bzl:435:5
 - C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - C:/office/repositories/mediapipe/WORKSPACE:133:1
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (43 packages loaded, 6988 targets configured)
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 101
		_apply_patch(ctx, <1 more arguments>)
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		_execute_and_check_ret_code(ctx, <1 more arguments>)
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\Windows\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/acima/_bazel_acima/a7wwyyzn/external/com_google_protobuf" "-i" "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/protobuf/protobuf.patch"':
Stdout: 
Stderr: patch: **** Can't change to directory C:/users/acima/_bazel_acima/a7wwyyzn/external/com_google_protobuf : No such file or directory
Analyzing: target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (43 packages loaded, 6988 targets configured)
ERROR: C:/office/repositories/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/BUILD:64:1: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:mediapipe_lib depends on //mediapipe/framework/formats:landmark_java_proto_lite in repository @ which failed to fetch. no such package '@com_google_protobuf//': Traceback (most recent call last):
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 101
		_apply_patch(ctx, <1 more arguments>)
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		_execute_and_check_ret_code(ctx, <1 more arguments>)
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\Windows\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/acima/_bazel_acima/a7wwyyzn/external/com_google_protobuf" "-i" "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/protobuf/protobuf.patch"':
Stdout: 
Stderr: patch: **** Can't change to directory C:/users/acima/_bazel_acima/a7wwyyzn/external/com_google_protobuf : No such file or directory
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 101
		_apply_patch(ctx, <1 more arguments>)
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
		_execute_and_check_ret_code(ctx, <1 more arguments>)
	File "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\Windows\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/acima/_bazel_acima/a7wwyyzn/external/com_google_protobuf" "-i" "C:/users/acima/_bazel_acima/a7wwyyzn/external/org_tensorflow/third_party/protobuf/protobuf.patch"':
Stdout: 
Stderr: patch: **** Can't change to directory C:/users/acima/_bazel_acima/a7wwyyzn/external/com_google_protobuf : No such file or directory
INFO: Elapsed time: 30.489s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (43 packages loaded, 6988 targets configured)
FAILED: Build did NOT complete successfully (43 packages loaded, 6988 targets configured)
`

**Comment by Acimaz** [comment]
Ok, mediapipe doesn't support windows. Closing this issue.
