### ISSUE TITLE
Expected action_config for 'objc++-compile' to be configured

### ISSUE THREAD

**Issue by riyouxi** [google/mediapipe#3757]
ERROR: /Users/luowei/Downloads/mediapipe/mediapipe/gpu/BUILD:393:13: in objc_library rule //mediapipe/gpu:pixel_buffer_pool_util: Expected action_config for 'objc++-compile' to be configured
ERROR: /Users/luowei/Downloads/mediapipe/mediapipe/gpu/BUILD:393:13: in objc_library rule //mediapipe/gpu:pixel_buffer_pool_util: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 127, column 124, in _objc_library_impl
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 316, column 50, in _register_compile_and_archive_actions
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 394, column 66, in _cc_compile_and_link
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 193, column 29, in _compile
Error in compile: Expected action_config for 'objc++-compile' to be configured
ERROR: /Users/luowei/Downloads/mediapipe/mediapipe/gpu/BUILD:393:13: Analysis of target '//mediapipe/gpu:pixel_buffer_pool_util' failed
INFO: Repository android_opencv instantiated at:
  /Users/luowei/Downloads/mediapipe/WORKSPACE:284:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_luowei/b13368dfe5b3978e0d56fee30014ecd8/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mediapipe_hand_tracking' failed; build aborted: 
INFO: Elapsed time: 196.357s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (148 packages loaded, 11388 targets configured)
    currently loading: @org_tensorflow//tensorflow/lite/delegates/gpu/gl ... (5 packages)
    Fetching @flatbuffers; fetching
    Fetching @com_github_grpc_grpc; fetching
    Fetching ...pc_grpc; Extracting /private/var/tmp/_bazel_luowei/b13368dfe5b3978e0d56fee30014ecd8/external/com_github_grpc_grpc/temp12902929766635230737/b54a5b338637f92bfcf4b0bc05e0f57a5fd8fadd.tar.gz
    Fetching ...368dfe5b3978e0d56fee30014ecd8/external/flatbuffers; Extracting /private/var/tmp/_bazel_luowei/b13368dfe5b3978e0d56fee30014ecd8/external/flatbuffers/temp16997117833424458656/v2.0.6.tar.gz
    Fetching https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip

**Comment by kuaashish** [comment]
Hi @riyouxi, 
Could you please elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!

**Comment by lyqaiym** [comment]
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

ERROR: /Users/**/github/mediapipe/mediapipe/gpu/BUILD:522:13: in objc_library rule //mediapipe/gpu:metal_shared_resources: Expected action_config for 'objc++-compile' to be configured
ERROR: /Users/**/github/mediapipe/mediapipe/gpu/BUILD:522:13: in objc_library rule //mediapipe/gpu:metal_shared_resources: 
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 55, column 82, in _objc_library_impl
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 312, column 50, in _register_compile_and_archive_actions
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 389, column 66, in _cc_compile_and_link
	File "/virtual_builtins_bzl/common/objc/compilation_support.bzl", line 182, column 29, in _compile
Error in compile: Expected action_config for 'objc++-compile' to be configured

--define MEDIAPIPE_DISABLE_GPU=1

**Comment by lyqaiym** [comment]
adb install handtrackinggpu.apk
crash 
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG: pid: 25379, tid: 25379, name: handtrackinggpu  >>> com.google.mediapipe.apps.handtrackinggpu <<<
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG: uid: 10672
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x0  0000000000000000  x1  0000000000006323  x2  0000000000000006  x3  0000007fed7e7dd0
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x4  0000006ed9dfaf5f  x5  0000006ed9dfaf5f  x6  0000006ed9dfaf5f  x7  73696874206e6920
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x8  00000000000000f0  x9  0000006fef722e60  x10 0000000000000001  x11 0000006fef788a44
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x12 0000000000000001  x13 0000000000000002  x14 0000000000000010  x15 0000006fef726ac2
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x16 0000006fef7f28f0  x17 0000006fef7cc890  x18 0000006edb403560  x19 0000000000006323
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x20 0000000000006323  x21 00000000ffffffff  x22 0000006fef7f4a98  x23 0000006ed9debe82
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x24 0000007018aa3000  x25 0000007018aa3000  x26 0000000000000021  x27 0000000000000000
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     x28 0000007fed7e8040  x29 0000007fed7e7e50
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:     lr  0000006fef779a08  sp  0000007fed7e7db0  pc  0000006fef779a34  pst 0000000000001000
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG: backtrace:
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #00 pc 000000000007da34  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #01 pc 0000000000b25578  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/lib/arm64/libmediapipe_jni.so (google::logging_fail()+8)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #02 pc 0000000000b24c60  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/lib/arm64/libmediapipe_jni.so (google::LogMessage::SendToLog()+1036)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #03 pc 0000000000b251f0  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/lib/arm64/libmediapipe_jni.so (google::LogMessage::Flush()+228)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #04 pc 0000000000b28604  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/lib/arm64/libmediapipe_jni.so (google::LogMessageFatal::~LogMessageFatal()+16)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #05 pc 00000000008af99c  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/lib/arm64/libmediapipe_jni.so (mediapipe::android::Graph::SetParentGlContext(long)+56)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #06 pc 00000000008b3f6c  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/lib/arm64/libmediapipe_jni.so (Java_com_google_mediapipe_framework_Graph_nativeSetParentGlContext+44)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #07 pc 000000000021a354  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #08 pc 000000000020a910  /apex/com.android.art/lib64/libart.so (nterp_helper+5648) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #09 pc 0000000000345934  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/oat/arm64/base.vdex (com.google.mediapipe.framework.Graph.setParentGlContext+60)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #10 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #11 pc 000000000033d830  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/oat/arm64/base.vdex (com.google.mediapipe.components.FrameProcessor.addVideoStreams+12)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #12 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #13 pc 000000000033d65a  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/oat/arm64/base.vdex (com.google.mediapipe.components.FrameProcessor.<init>+66)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #14 pc 000000000020a958  /apex/com.android.art/lib64/libart.so (nterp_helper+5720) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #15 pc 000000000033915c  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/oat/arm64/base.vdex (com.google.mediapipe.apps.basic.MainActivity.onCreate+228)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #16 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #17 pc 000000000033a578  /data/app/~~DmIrWWa8kKptu8m1Hy6qfA==/com.google.mediapipe.apps.handtrackinggpu-MoxYTlIuXKapsWciw1H6Dw==/oat/arm64/base.vdex (com.google.mediapipe.apps.handtrackinggpu.MainActivity.onCreate+0)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #18 pc 00000000004e782c  /system/framework/arm64/boot-framework.oat (android.app.Activity.performCreate+1132) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #19 pc 000000000021e318  /system/framework/arm64/boot-framework.oat (android.app.Instrumentation.callActivityOnCreate+88) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #20 pc 0000000000320f00  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.performLaunchActivity+3824) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #21 pc 0000000000329098  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.handleLaunchActivity+776) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #22 pc 00000000004f65f4  /system/framework/arm64/boot-framework.oat (android.app.servertransaction.LaunchActivityItem.execute+500) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #23 pc 000000000025026c  /system/framework/arm64/boot-framework.oat (android.app.servertransaction.TransactionExecutor.executeCallbacks+588) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #24 pc 000000000024ff98  /system/framework/arm64/boot-framework.oat (android.app.servertransaction.TransactionExecutor.execute+776) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #25 pc 0000000000306188  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread$H.handleMessage+1384) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #26 pc 00000000005e0a00  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+192) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #27 pc 00000000005e3f1c  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1276) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #28 pc 00000000005e3978  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+648) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #29 pc 000000000031f34c  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+1628) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #30 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #31 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #32 pc 00000000006105b8  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1400) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #33 pc 00000000005900d4  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #34 pc 00000000000a1148  /system/framework/arm64/boot.oat (art_jni_trampoline+120) (BuildId: 64b90e1946c4040a8fdd4e07387e0466a7c65f75)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #35 pc 0000000000873be0  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+144) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #36 pc 000000000087f314  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+4212) (BuildId: a9d160ae978645adc45b44ae28cfd3489af343ff)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #37 pc 0000000000210c00  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #38 pc 000000000027b4ac  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+240) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #39 pc 0000000000610d40  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+452) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #40 pc 000000000061122c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+96) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #41 pc 00000000004fac28  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+600) (BuildId: 00a2520c1f20f8992ac743328e7fadc3)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #42 pc 00000000000c0c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: 39023390ba25abcc16f4d8ad93112d56)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #43 pc 00000000000cd228  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+936) (BuildId: 39023390ba25abcc16f4d8ad93112d56)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #44 pc 0000000000002610  /system/bin/app_process64 (main+1464) (BuildId: 8198beb2d5e7f73418c12a4f1374ff9b)
2023-04-13 10:31:38.875 29500-29500/? A/DEBUG:       #45 pc 0000000000075c7c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100) (BuildId: 59222d1015276d9a9031ee1ea28c0bcd)
