### ISSUE TITLE
 Framebuffer not complete

### ISSUE THREAD

**Issue by ylj318** [google/mediapipe#3814]
hi, how do you do
i used hair_segmentation_aar.aar file  and basic code of mediapipe project  (examples\android\src\java\com\google\mediapipe\apps\basic) 
when do i run to  code 
" cameraHelper.startCamera(this, cameraFacing, previewFrameTexture, cameraTargetResolution());"
the project take wrong 

022-11-03 18:11:49.178 6259-6395/com.yt.hair4 E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.yt.hair4, PID: 6259
    java.lang.RuntimeException: Framebuffer not complete, status=36054
        at com.google.mediapipe.glutil.GlThread.bindFramebuffer(GlThread.java:114)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.createFrame(ExternalTextureConverter.java:509)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.nextOutputFrame(ExternalTextureConverter.java:538)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:466)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$com-google-mediapipe-components-ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:413)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$ExternalSyntheticLambda1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:224)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

**Comment by kuaashish** [comment]
Hi @ylj318,
Could you elaborate your query with complete details and steps to reproduce the issue from our end. Thank you!
