### ISSUE TITLE
 multi hand tracking Black Screen api 23 Moto G3 Android 6.0  arm

### ISSUE THREAD

**Issue by Jaguaribe21** [google/mediapipe#383]
Got the same bug, any procedure to fix it?
Being able to open the app in api 23, only it is on the black screen.

Logcat:

01-09 15:06:00.591 24537-24602/? E/FrameProcessor: Mediapipe error: 
    com.google.mediapipe.framework.MediaPipeException: internal: Graph has errors: 
    Calculator::Process() for node "[TfLiteConverterCalculator_1, TfLiteConverterCalculator with output stream: __sg0_image_tensor]" failed: [GL_INVALID_ENUM]: An unacceptable value is specified for an enumerated argument.: glBufferData in external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/gl_buffer.h:253
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:380)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:258)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:261)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:211)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:746)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)
01-09 15:06:00.608 323-24657/? E/mm-camera-CORE: af_get_params: Focus is not initialized yet
01-09 15:06:00.641 323-24657/? E/mm-camera-CORE: af_get_params: Focus is not initialized yet
01-09 15:06:00.675 323-24657/? E/mm-camera-CORE: af_get_params: Focus is not initialized yet
01-09 15:06:00.707 323-24657/? E/mm-camera-CORE: af_get_params: Focus is not initialized yet
01-09 15:06:00.741 323-24657/? E/mm-camera-CORE: af_get_params: Focus is not initialized yet
01-09 15:06:00.774 323-24657/? E/mm-camera-CORE: af_get_params: Focus is not initialized yet

Note: After I run the application I get in logcat only this message:

af_get_params: Focus is not initialized yet

I've tried using other applications and all had black screen, was having difficulty opening the application but the collaborators helped me open the application in api 23, but now I get this black screen, any procedure to correct this error or bug?
![a04a9b28-9c40-4005-9b60-662271e378d7](https://user-images.githubusercontent.com/56888429/72092970-42a7f780-32f2-11ea-8e6f-afc1e2a527b9.jpeg)

**Comment by mcclanahoochie** [comment]
The Moto G3 has an Adreno 306 GPU, which only supports OpenGL ES up to 3.0, and OpenGL ES 3.1 is the minimum required to run all the MediaPipe ML examples. 
https://en.wikipedia.org/wiki/Moto_G_(3rd_generation)
https://developer.qualcomm.com/software/adreno-gpu-sdk/gpu

The [edgedetectiongpu](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu) example should work though.

**Comment by Jaguaribe21** [comment]
Thanks for the support, but I still have the black screen in edge detection example.

logcat:
01-09 18:37:15.256 282-30616/? E/QCameraHWI_Mem: int qcamera::QCameraMemoryPool::allocateBuffer(qcamera::QCameraMemory::QCameraMemInfo&, unsigned int, size_t, bool, cam_stream_type_t) : Buffer not found!
01-09 18:37:15.281 282-30616/? E/QCameraHWI_Mem: int qcamera::QCameraMemoryPool::allocateBuffer(qcamera::QCameraMemory::QCameraMemInfo&, unsigned int, size_t, bool, cam_stream_type_t) : Buffer not found!
01-09 18:37:15.316 282-30616/? E/QCameraHWI_Mem: int qcamera::QCameraMemoryPool::allocateBuffer(qcamera::QCameraMemory::QCameraMemInfo&, unsigned int, size_t, bool, cam_stream_type_t) : Buffer not found!
01-09 18:37:15.357 282-30616/? E/QCameraHWI_Mem: void qcamera::QCameraMemory::traceLogAllocEnd(size_t) 97853440
01-09 18:37:15.363 282-30616/? E/QCameraHWI_Mem: void qcamera::QCameraMemory::traceLogAllocEnd(size_t) 97853440
01-09 18:37:15.371 282-30616/? E/mm-camera-intf: mm_stream_request_buf: buf_num = 5, stream type = 3
01-09 18:37:15.388 323-30640/? E/mm-camera-sensor: sensor_set_resolution:2560 set_fps=30.000000 > max_fps=29.370001, capping to max
01-09 18:37:15.389 323-30640/? E/mm-camera: isp_sink_port_stream_config: E, session_id = 2, stream_id = 2, stream_type = 1
01-09 18:37:15.389 323-30640/? E/mm-camera: isp_sink_port_stream_config: session_id = 2, stream_id = 2, is_split = 0
01-09 18:37:15.389 323-30640/? E/mm-camera: isp_sink_port_stream_config: old vfe_id_mask = 0x1, new vfe_id_mask = 0x1
01-09 18:37:15.389 323-30640/? E/mm-camera: isp_sink_port_stream_config: E, session_id = 2, stream_id = 3, stream_type = 3
01-09 18:37:15.389 323-30640/? E/mm-camera: isp_sink_port_stream_config: session_id = 2, stream_id = 3, is_split = 0
01-09 18:37:15.389 323-30640/? E/mm-camera: isp_sink_port_stream_config: old vfe_id_mask = 0x1, new vfe_id_mask = 0x1
01-09 18:37:15.389 323-30640/? E/mm-camera: is_port_handle_stream_config_event: w = 4160, h = 3120, ma = 90, p = 0
01-09 18:37:15.391 323-30640/? E/mm-camera: is_port_handle_set_is_enable: IS enable = 0
01-09 18:37:15.391 323-30665/? E/mm-camera-CORE: af_set_parameters: Unsupported parameter:0
01-09 18:37:15.392 323-30640/? E/mm-camera: isp_tintless_config: same cfg as current
01-09 18:37:15.392 323-30640/? E/mm-camera: isp_tintless_update_chromatix_params: lib returned config err=0
01-09 18:37:15.392 323-30640/? E/mm-camera: is_port_handle_set_is_enable: IS enable = 0
01-09 18:37:15.392 323-30665/? E/mm-camera-CORE: af_set_parameters: Unsupported parameter:0
01-09 18:37:15.392 323-30640/? E/mm-camera: port_isp_mct_ctrl_cmd: E, identity = 0x20003, STREAMON
01-09 18:37:15.393 323-30640/? E/mm-camera: awb_port_update_awb_data r_gain; 1.647707, g_gain: 1.000000, b_gain: 2.301766, cct: 4100
01-09 18:37:15.393 323-30640/? E/mm-camera: isp_streamon: E, session_id = 2, stream_id = 3, active_count = 0 flash=FALSE
01-09 18:37:15.393 323-30635/? E/mm-camera: isp_proc_streamon: E, session_id = 2, stream_id = 3, stream_type = 3
01-09 18:37:15.393 323-30635/? E/mm-camera: isp_ch_util_sync_stream_cfg_to_channel: cannot find channel, Adding new channel for stream id 2
01-09 18:37:15.393 323-30635/? E/mm-camera: isp_add_meta_channel: no meta data, session_id = 2, stream_id = 2
01-09 18:37:15.393 323-30635/? E/mm-camera: isp_ch_util_sync_stream_cfg_to_channel: cannot find channel, Adding new channel for stream id 3
01-09 18:37:15.393 323-30635/? E/mm-camera: isp_add_meta_channel: no meta data, session_id = 2, stream_id = 3
01-09 18:37:15.394 323-30635/? E/mm-camera: is_port_event:610 id = 20002, steam_type = 1, w = 960, h = 720, IS mode = 0
01-09 18:37:15.394 323-30679/? E/mm-camera: isp_thread_proc_cmd: start/stop, thread_data = 0xb742d580, action_code = 0
01-09 18:37:15.394 323-30635/? E/mm-camera: isp_ch_util_streamon: session_id = 2, vfe_mask = 0x1, async streamon, rc = 0
01-09 18:37:15.396 323-30679/? E/mm-camera: isp_tintless_config: cfg: 10x13 mesh, 8x8 subgrid, subgrid sz 44x44
01-09 18:37:15.396 323-30679/? E/mm-camera: isp_tintless_mesh_config: lib returned mesh config err=0
01-09 18:37:15.398 323-30679/? E/mm-camera: color_xform_update_s_value path 0 scaling_factor 0.000000 
01-09 18:37:15.398 323-30679/? E/mm-camera: color_xform_update_s_value path 1 scaling_factor 0.000000 
01-09 18:37:15.398 323-30679/? E/mm-camera: linearization_set_params: param_id is not supported in this module
01-09 18:37:15.398 323-30679/? E/mm-camera: mesh_rolloff_set_params: param_id is not supported in this module
01-09 18:37:15.398 323-30679/? E/mm-camera: wb_set_params: param_id is not supported in this module
01-09 18:37:15.398 323-30679/? E/mm-camera: demosaic_set_params: param_id 7, is not supported in this module
01-09 18:37:15.398 323-30679/? E/mm-camera: demux_set_params: param_id 7, is not supported in this module
01-09 18:37:15.399 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.399 323-30679/? E/mm-camera: mce_set_params: param_id is not supported in this module
01-09 18:37:15.399 323-30679/? E/mm-camera: sce_set_params: param_id is not supported in this module
01-09 18:37:15.399 323-30679/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
01-09 18:37:15.399 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.399 323-30679/? E/mm-camera: la_hist_trigger_update: luma target from AEC = 0! use default LA curve
01-09 18:37:15.399 323-30679/? E/mm-camera: isp_tintless_stat_config: pointer okay 
01-09 18:37:15.399 323-30679/? E/mm-camera: isp_tintless_config: cfg: camif 4160x3120, elem sz 130x130, elems 24x32
01-09 18:37:15.400 323-30679/? E/mm-camera: isp_tintless_stat_config: lib returned config err=0
01-09 18:37:15.401 323-30679/? E/mm-camera: stats_action_buf_config: cfg = 1, stats_mask = 0x7b8
01-09 18:37:15.403 323-30679/? E/mm-camera: stats_action: stats mask = 0x7b8
01-09 18:37:15.406 323-30679/? E/mm-camera: isp_axi_util_subscribe_v4l2_event: event_type = 0x8000101, is_subscribe = 1
01-09 18:37:15.407 323-30635/? E/mm-camera: isp_ch_util_streamon: session_id = 2, sync ack done
01-09 18:37:15.407 323-30679/? E/mm-camera: isp_thread_proc_cmd: start/stop ack done, thread_data = 0xb742d580, action_code = 1, rc = 0
01-09 18:37:15.407 323-30679/? E/mm-camera: color_xform_update_s_value path 0 scaling_factor 1.000000 
01-09 18:37:15.407 323-30679/? E/mm-camera: color_xform_update_s_value path 1 scaling_factor 4.333333 
01-09 18:37:15.407 323-30640/? E/mm-camera: isp_streamon: X, session_id = 2, rc = 0
01-09 18:37:15.407 323-30640/? E/mm-camera: port_isp_send_streamon_done_event_downstream: notify stream done downstream
01-09 18:37:15.407 323-30640/? E/mm-camera: port_isp_mct_ctrl_cmd: X, identity = 0x20003, STREAMON, ret = 0
01-09 18:37:15.411 323-30640/? E/mm-camera-sensor: module_sensor_stream_on: Sending start bus message
01-09 18:37:15.411 323-30684/? E/mm-camera: mct_bus_sof_thread_run thread_id is 30684
01-09 18:37:15.412 282-30619/? E/QCameraPostProc: int32_t qcamera::QCameraPostProcessor::start(qcamera::QCameraChannel*): use count reset to 0
01-09 18:37:15.413 323-30640/? E/mm-camera: mct_pipeline_send_ctrl_events: Send Set Parm events
01-09 18:37:15.414 323-30640/? E/mm-camera: mct_pipeline_send_ctrl_events: Send Set Parm events
01-09 18:37:15.415 323-30640/? E/mm-camera: mct_pipeline_send_ctrl_events: Send Set Parm events
01-09 18:37:15.417 323-30640/? E/mm-camera: mct_pproc_sink_port_caps_reserve:198] The port 0xb6fa14f8 is not free
01-09 18:37:15.418 282-30619/? E/QCameraHWI_Mem: void qcamera::QCameraMemory::traceLogAllocStart(size_t, int, const char*):StreamMemsize 19570688
01-09 18:37:15.418 282-30619/? E/QCameraHWI_Mem: void qcamera::QCameraMemory::traceLogAllocStart(size_t, int, const char*):Memsize 19570688
01-09 18:37:15.418 282-30619/? E/QCameraHWI_Mem: int qcamera::QCameraMemoryPool::allocateBuffer(qcamera::QCameraMemory::QCameraMemInfo&, unsigned int, size_t, bool, cam_stream_type_t) : Buffer not found!
01-09 18:37:15.425 323-30679/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
01-09 18:37:15.425 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.425 323-30679/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
01-09 18:37:15.425 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.427 323-30665/? E/mm-camera-CORE: af_set_parameters: Unsupported parameter:35
01-09 18:37:15.442 282-30619/? E/QCameraHWI_Mem: void qcamera::QCameraMemory::traceLogAllocEnd(size_t) 19570688
01-09 18:37:15.443 282-30619/? E/QCameraHWI_Mem: void qcamera::QCameraMemory::traceLogAllocEnd(size_t) 19570688
01-09 18:37:15.445 282-30619/? E/mm-camera-intf: mm_stream_request_buf: buf_num = 1, stream type = 9
01-09 18:37:15.459 323-30679/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
01-09 18:37:15.459 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.479 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.493 323-30679/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
01-09 18:37:15.493 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.493 323-30679/? E/mm-camera: la_hist_trigger_update: luma target from AEC = 0! use default LA curve
01-09 18:37:15.494 323-30677/? E/mm-camera: awb_port_update_awb_info AWB Decision is not valid. Dont send metadata
01-09 18:37:15.495 323-30679/? E/mm-camera: color_correct_trigger_update: Ignore AEC settled
01-09 18:37:15.495 323-30679/? E/mm-camera: color_conversion_trigger_update: Ignore AEC settled
01-09 18:37:15.513 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.533 260-260/? E/lowmemorykiller: Error writing /proc/30479/oom_score_adj; errno=22
01-09 18:37:15.546 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.579 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.596 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
01-09 18:37:15.612 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.628 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
01-09 18:37:15.646 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.660 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
01-09 18:37:15.679 323-30665/? E/mm-camera-CORE: af_process_parse_stats: Invalid FV data!
01-09 18:37:15.697 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
01-09 18:37:15.704 282-30670/? E/MotISP_GPU: int MotISP_GPU::Init(int, int): GPU resolution: 960x720
01-09 18:37:15.729 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
01-09 18:37:15.765 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return
01-09 18:37:15.799 323-30664/? E/mm-camera-CORE: awb_bayer_set_led_gains AWB decision invalid. return


Note:? E / mm-camera-CORE: awb bayer_set_led gains AWB decision invalid. return in loop in logcat
![f0480df9-cbbb-484a-95b9-dc0fc29c08db](https://user-images.githubusercontent.com/56888429/72107135-7d6c5880-330f-11ea-8e29-fa8b6d63777f.jpeg)

**Comment by Jaguaribe21** [comment]
> O Moto G3 possui uma GPU Adreno 306, que suporta apenas OpenGL ES até 3.0, e OpenGL ES 3.1 é o mínimo necessário para executar todos os exemplos do MediaPipe ML.
> [https://en.wikipedia.org/wiki/Moto_G_(3rd_generation) ](https://en.wikipedia.org/wiki/Moto_G_(3rd_generation))
> https://developer.qualcomm.com/software/adreno-gpu-sdk/gpu
> 
> O exemplo [edgedetectiongpu](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu) deve funcionar.


Note: Edge Detection example successfully opened and worked, how can I change the version of OpenGL in the multihand tracking example?

**Comment by eknight7** [comment]
Can you share the bug you are seeing in the edge detection example?

**Comment by Jaguaribe21** [comment]
Moto G3 gave this bug, I also tested it on LG X Screen android 6.0 it worked better than the moto G3 but still there are oscillations.
![edge detection](https://user-images.githubusercontent.com/56888429/72162344-8fe2a280-33a0-11ea-9ea6-da3bcf2d87e7.gif)





> Can you share the bug you are seeing in the edge detection example?

**Comment by mcclanahoochie** [comment]
very strange artifacts

are there any errors or warnings printed in the adb log ?

can you share the graph you are running also?

**Comment by jiuqiant** [comment]
Closing due to lack of activity.
