### ISSUE TITLE
How to solve "ValidatedGraphConfig Initialization failed" error?

### ISSUE THREAD

**Issue by celsodasecond** [google/mediapipe#3831]
**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 11, Ubuntu 20.04 LTS
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0): gcc/g++ 9.4.0
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ): Python 2.7.18 / cpp 9.4.0 / jdk 1.8.0_342
- [MediaPipe version](https://github.com/google/mediapipe/releases): v.0.8.9
- Bazel version:  5.2.2
- Android SDK and NDK versions (if android): Default Working SDK and NDK from "setup_android_sdk_and_ndk.sh"
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android): YES

**Describe the problem**:
I am trying to concatenate the pose_landmarks, face_landmarks, right_hand_landmarks, and left_hand_landmarks in the holistic_tracking_to_render_data.pbtxt. The AAR and the .binarypb file both build successfully. However, the application crashes and this error shows whenever I run the application:
```
E20221108 22:01:15.433691 30112 graph.cc:472] ValidatedGraphConfig Initialization failed. 
ConcatenateNormalizedLandmarkListCalculator: ; (kIn(cc).Count())>=(1)iapipe/calculators/core/concatenate_normalized_landmark_list_calculator.cc:40) 
```
What is the possible fix? Am I missing something?

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**
Here are the following that is added to the **holistic_tracking_to_render_data.pbtxt** graph:
```
# Output
output_stream: "MERGED_LANDMARKS:landmarks_concat_merged"
.
.
.
# NEW - Merges all the landmarks
node {
  calculator: "ConcatenateNormalizedLandmarkListCalculator"
  input_stream: "FACE_LMARKS:face_landmarks"
  input_stream: "LHAND_LMARKS:left_hand_landmarks"
  input_stream: "RHAND_LMARKS:right_hand_landmarks"
  input_stream: "POSE_LANDMARKS:landmarks"
  output_stream: "MERGED_LANDMARKS:landmarks_concat_merged"
  node_options: {
    [type.googleapis.com/mediapipe.ConcatenateVectorCalculatorOptions] {
      only_emit_if_all_present: true
    }
  }
}
```
And here are the following that is added to the **holistic_tracking_gpu.pbtxt** graph:
```
# Output Results
output_stream: "MERGED_LANDMARKS:landmarks_concat_merged"
.
.
.
# Converts pose, hands and face landmarks to a render data vector.
node {
  calculator: "HolisticTrackingToRenderData"
  input_stream: "IMAGE_SIZE:image_size"
  input_stream: "POSE_LANDMARKS:pose_landmarks"
  input_stream: "POSE_ROI:pose_roi"
  input_stream: "LEFT_HAND_LANDMARKS:left_hand_landmarks"
  input_stream: "RIGHT_HAND_LANDMARKS:right_hand_landmarks"
  input_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "RENDER_DATA_VECTOR:render_data_vector"
  # NEW
  output_stream: "MERGED_LANDMARKS:landmarks_concat_merged"
}
```

To further visualize, here is what the **holistic_tracking_to_render_data.pbtxt** graph looked like:
![image](https://user-images.githubusercontent.com/75917932/200587538-5a3764a4-8325-4e69-8068-d7fd806e405d.png)

And here is what the **holistic_tracking_gpu.pbtxt** graph looked like:
![image](https://user-images.githubusercontent.com/75917932/200587884-e58e0c5f-fa2b-4ead-b657-ac208970fba3.png)

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:
```
2022-11-08 22:01:15.433 30049-30112 native                  com.lite.holistic_tracking           E  E20221108 22:01:15.433691 30112 graph.cc:472] ValidatedGraphConfig Initialization failed.
                                                                                                    ConcatenateNormalizedLandmarkListCalculator: ; (kIn(cc).Count())>=(1)iapipe/calculators/core/concatenate_normalized_landmark_list_calculator.cc:40) 
--------- beginning of crash

2022-11-08 22:01:15.439 30049-30112 GlThread                com.lite.holistic_tracking           D  Stopping GL thread ExternalTextureConverter
2022-11-08 22:01:15.441 30049-30112 AndroidRuntime          com.lite.holistic_tracking           E  FATAL EXCEPTION: ExternalTextureConverter
                                                                                                    Process: com.lite.holistic_tracking, PID: 30049
                                                                                                    com.google.mediapipe.framework.MediaPipeException: internal: ValidatedGraphConfig Initialization failed.
                                                                                                    ConcatenateNormalizedLandmarkListCalculator: ; (kIn(cc).Count())>=(1)iapipe/calculators/core/concatenate_normalized_landmark_list_calculator.cc:40) 
                                                                                                    	at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
                                                                                                    	at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:324)
                                                                                                    	at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
                                                                                                    	at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
                                                                                                    	at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
                                                                                                    	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:403)
                                                                                                    	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
                                                                                                    	at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:254)
                                                                                                    	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

```

**Comment by tyrmullen** [comment]
That error just means your MediaPipe graph is not formatted correctly.  Specifically, you gave it a format which compiles (so it is a valid *graph*) but which will not run (because one of the calculators in the graph expects different input/outputs).

In particular, you added a `ConcatenateNormalizedLandmarkListCalculator`, which does not use any of the tags being given to it (`FACE_LMARKS`, `RHAND_LMARKS`, etc.).  The streams are up to you to name in your graph, but the tags must match what the calculator expects, so each of these would cause an error.  Most calculators expect specific names for those tags, but `ConcatenateNormalizedLandmarkListCalculator` expects *NO* tags, so just removing those should fix that error:
```
node {
  calculator: "ConcatenateNormalizedLandmarkListCalculator"
  input_stream: "face_landmarks"
  input_stream: "left_hand_landmarks"
  input_stream: "right_hand_landmarks"
  input_stream: "landmarks"
  output_stream: "landmarks_concat_merged"
  node_options: {
    [type.googleapis.com/mediapipe.ConcatenateVectorCalculatorOptions] {
      only_emit_if_all_present: true
    }
  }
}
```
