### ISSUE TITLE
Crash when call surfaceTexture.updateTexImage()

### ISSUE THREAD

**Issue by beakyangsu** [google/mediapipe#3840]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android SOS
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S22+
Bazel version: bazel 5.3.1
Android Studio, NDK, SDK versions (if issue is related to building in mobile dev enviroment):
AndroidStudio Chipmunk NDK : 20.0.5594570, SDK: 30.0.3
Xcode & Tulsi version (if issue is related to building in mobile dev enviroment):

error occured by followed step.
ExternalTextureConverter.renderNext() -> ExternalTextureConverter.updateOutputFrame() -> 
 ExternalTextureRenderer.render() -> surfaceTexture.updateTexImage();

here is error message.
```
10-31 18:22:23.231 11072 11293 E AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
10-31 18:22:23.231 11072 11293 E AndroidRuntime: Process: com.lge.camera, PID: 11072
10-31 18:22:23.231 11072 11293 E AndroidRuntime: java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:249)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at com.google.mediapipe.glutil.ExternalTextureRenderer.render(ExternalTextureRenderer.java:116)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.updateOutputFrame(ExternalTextureConverter.java:447)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:350)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:309)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
10-31 18:22:23.231 11072 11293 E AndroidRuntime: 	at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
```

here is my full code.
```

class HandDectionController(val mSCInf: ShotCtxInf) {
    private val TAG = "mediapipe"
    private val BINARY_GRAPH_NAME = "hand_tracking_mobile_gpu.binarypb"
    private val INPUT_VIDEO_STREAM_NAME = "input_video"
    private val OUTPUT_VIDEO_STREAM_NAME = "output_video"
    private val OUTPUT_LANDMARKS_STREAM_NAME = "hand_landmarks"
    private val INPUT_NUM_HANDS_SIDE_PACKET_NAME = "num_hands"
    private val NUM_HANDS = 2
    private val DBG = true
    // Flips the camera-preview frames vertically before sending them into FrameProcessor to be
    // processed in a MediaPipe graph, and flips the processed frames back when they are displayed.
    // This is needed because OpenGL represents images assuming the image origin is at the bottom-left
    // corner, whereas MediaPipe in general assumes the image origin is at top-left.
    private val FLIP_FRAMES_VERTICALLY = true
    private var eglManager: EglManager? = null

    // Sends camera-preview frames into a MediaPipe graph for processing, and displays the processed
    // frames onto a {@link Surface}.
    private var processor: FrameProcessor? = null
    private var converter: ExternalTextureConverter? = null
    private var mOutputView : SurfaceView? = null

    init {
        System.loadLibrary("mediapipe_jni")
        System.loadLibrary("opencv_java3")
    }

    private fun getMultiHandLandmarksDebugString(multiHandLandmarks: kotlin.collections.List<LandmarkProto.NormalizedLandmarkList>): String {
        if (multiHandLandmarks.isEmpty()) {
            return "No hand landmarks"
        }
        var multiHandLandmarksStr = """
            Number of hands detected: ${multiHandLandmarks.size}
            
            """.trimIndent()
        var handIndex = 0
        for (landmarks in multiHandLandmarks) {
            multiHandLandmarksStr += """	#Hand landmarks for hand[$handIndex]: ${landmarks.landmarkCount}
"""
            var landmarkIndex = 0
            for (landmark in landmarks.landmarkList) {
                multiHandLandmarksStr += """		Landmark [$landmarkIndex]: (${landmark.x}, ${landmark.y}, ${landmark.z})
"""
                ++landmarkIndex
            }
            ++handIndex
        }
        return multiHandLandmarksStr
    }

    fun init(){
        Log.d(TAG, "solsol init.")
        AndroidAssetUtil.initializeNativeAssetManager(mSCInf.act)
        eglManager = EglManager(null)
        processor = FrameProcessor(
                mSCInf.act,
                eglManager!!.nativeContext,
                BINARY_GRAPH_NAME,
                INPUT_VIDEO_STREAM_NAME,
                OUTPUT_VIDEO_STREAM_NAME)

        val packetCreator = processor!!.packetCreator
        val inputSidePackets: MutableMap<String, Packet> = HashMap()
        inputSidePackets[INPUT_NUM_HANDS_SIDE_PACKET_NAME] = packetCreator.createInt32(NUM_HANDS)
        processor!!.setInputSidePackets(inputSidePackets)

        processor!!.addPacketCallback(OUTPUT_LANDMARKS_STREAM_NAME) { packet: Packet ->
            Log.d(TAG, "solsol Received multi-hand landmarks packet.")
            val multiHandLandmarks = PacketGetter.getProtoVector(packet, LandmarkProto.NormalizedLandmarkList.parser())
            Log.d(TAG, "solsol [TS:"
                    + packet.timestamp
                    + "] "
                    + getMultiHandLandmarksDebugString(multiHandLandmarks))
        }
// adb shell setprop log.tag.MainActivity VERBOSE
        processor!!.addPacketCallback(OUTPUT_VIDEO_STREAM_NAME) { packet: Packet ->
            Log.d(TAG, "solsol OUTPUT_VIDEO_STREAM_NAME")

        }
    }

    private fun initView(){
        Log.d(TAG, "solsol initView.")
        mOutputView = SurfaceView(mSCInf.actCtx)
        val parent = mSCInf.act.findViewById<View>(R.id.shotmode_parent_layout) as ViewGroup
        val boxView = mSCInf.act.findViewById<View>(R.id.obt_result_layout)
        val index = parent.indexOfChild(boxView)
        parent.addView(mOutputView, index)

        mOutputView!!.holder!!.addCallback(
                object : SurfaceHolder.Callback {
                    override fun surfaceCreated(holder: SurfaceHolder) {
                        Log.d("solsol", "solsol surfaceCreated.")
                        processor!!.videoSurfaceOutput.setSurface(holder.surface)
                        processor!!.videoSurfaceOutput.setFlipY(FLIP_FRAMES_VERTICALLY)
                    }

                    override fun surfaceChanged(holder: SurfaceHolder, format: Int, width: Int, height: Int) {
                        val size = mSCInf.camCtx.previewSize
                        Log.d("solsol", "solsol  surfaceChanged ${mSCInf.glCtx.getPreviewSurfaceTexture(true)}  ${size.width}  ${size.height}")
                        converter?.setSurfaceTexture(mSCInf.glCtx.getPreviewSurfaceTexture(true), size.width, size.height)

                    }

                    override fun surfaceDestroyed(holder: SurfaceHolder) {
                        processor!!.videoSurfaceOutput.setSurface(null)
                    }
                })


        mOutputView?.visibility = VISIBLE
    }

    fun start(){
        Log.d(TAG, "solsol start.")
        converter = ExternalTextureConverter(
                eglManager!!.context, 2)
        converter?.setFlipY(FLIP_FRAMES_VERTICALLY)
        converter?.setConsumer(processor)
        initView()
    }

    fun stop(){
        converter?.close()
        processor?.close()
    }

    fun clearView(){
        mOutputView?.visibility = INVISIBLE
        mSCInf.removeView(mOutputView)
    }
}
```

**Comment by kuaashish** [comment]
Hi @beakyangsu,
Could you elaborate your query with complete details and steps followed to reproduce the issue from our end. Thank you!

**Comment by beakyangsu** [comment]
@kuaashish

I created APK using custom code above. 
Error occured when right after APK started. 

1. create FrameProcerror
```
 processor = FrameProcessor(
                mSCInf.act,
                eglManager!!.nativeContext,
                BINARY_GRAPH_NAME,
                INPUT_VIDEO_STREAM_NAME,
                OUTPUT_VIDEO_STREAM_NAME)
```

2. create ExternalTextureConverter 
```
converter = ExternalTextureConverter(
                eglManager!!.context, 2)
        converter?.setFlipY(FLIP_FRAMES_VERTICALLY)
        converter?.setConsumer(processor)
```

3. create OutputView 
```
  mOutputView = SurfaceView(mSCInf.actCtx)
        val parent = mSCInf.act.findViewById<View>(R.id.shotmode_parent_layout) as ViewGroup
        val boxView = mSCInf.act.findViewById<View>(R.id.obt_result_layout)
        val index = parent.indexOfChild(boxView)
        parent.addView(mOutputView, index)
```

4.  register OutputSurface for FrameProcessor and register inputSurface for  ExternalTextureConverter 
```
        mOutputView!!.holder!!.addCallback(
                object : SurfaceHolder.Callback {
                    override fun surfaceCreated(holder: SurfaceHolder) {
                        Log.d("solsol", "solsol surfaceCreated.")
//register OutputSurface for FrameProcessor
                        processor!!.videoSurfaceOutput.setSurface(holder.surface)
                        processor!!.videoSurfaceOutput.setFlipY(FLIP_FRAMES_VERTICALLY)
                    }

                    override fun surfaceChanged(holder: SurfaceHolder, format: Int, width: Int, height: Int) {
                        val size = mSCInf.camCtx.previewSize
//register inputSurface for  ExternalTextureConverter 
                        Log.d("solsol", "solsol  surfaceChanged ${mSCInf.glCtx.getPreviewSurfaceTexture(true)}  ${size.width}  ${size.height}")
                        converter?.setSurfaceTexture(mSCInf.glCtx.getPreviewSurfaceTexture(true), size.width, size.height)

                    }

                    override fun surfaceDestroyed(holder: SurfaceHolder) {
                        processor!!.videoSurfaceOutput.setSurface(null)
                    }
                })

```
I used setSurfaceTexture(), not setSurfaceTextureAndAttachToGL() as example for resgister previewSurface for ExternalTextureConverter. because i already attach my previewSurface to GL.

Now ExternalTextureConverter register previewSurface's onImageAvaliable callback. 
And onImageAvaliable() called, in onImageAvaliable(), renderNext() method called.

here is my steps when error occured. 
ExternalTextureConverter.renderNext() -> ExternalTextureConverter.updateOutputFrame() ->
ExternalTextureRenderer.render() -> surfaceTexture.updateTexImage();->android runtime error

**Comment by beakyangsu** [comment]
I used aar and graph file uploaded here. 
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example

**Comment by kuaashish** [comment]
Hi @beakyangsu,
Please allow us some time to review your query. Team is following up with the issue and let you know once we have any update. Thank you!

**Comment by kuaashish** [comment]
Hi @beakyangsu,
Could you please inspect the following:

- We see that chain of Texture processing it first fails.
- After each step, try to verify the texture output.

We should see a valid SurfaceTexture output from ExternalTextureConverter.
