### ISSUE TITLE
mediapipe android customize output packets

### ISSUE THREAD

**Issue by QuiLevitin** [google/mediapipe#3850]
Hello, i would like to create my own output stream from graph ("merged_landmarks" for ex.). How will I able to initialize this in addpacketcallback because it seems it is not yet defined somewhere in the mediapipe workspace aside from the graph. thank you very much.

Here is my modified holistic_tracking_to_render_data.pbtxt with the "merged_landmarks" output stream in middle part
![image](https://user-images.githubusercontent.com/93040604/201323653-93eb2edb-9723-4db0-86e1-4e7cae1e1d9e.png)

**### The code snippet**
![image](https://user-images.githubusercontent.com/93040604/201456705-813f4375-3c56-4fa4-9116-94b9c20a93c8.png)

**### The error**
2022-11-12 12:02:45.067 28089-28166/com.lite.holistic_tracking E/native: E20221112 12:02:45.067229 28166 graph.cc:474] ; **Input Stream "landmarks_merged" for node with sorted index 2 name callback_calculator_that_collects_stream_landmarks_merged does not have a corresponding output stream.**
2022-11-12 12:02:45.068 28089-28166/com.lite.holistic_tracking D/GlThread: Stopping GL thread ExternalTextureConverter
2022-11-12 12:02:45.069 28089-28166/com.lite.holistic_tracking E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.lite.holistic_tracking, PID: 28089
    com.google.mediapipe.framework.MediaPipeException: unknown: ; Input Stream "landmarks_merged" for node with sorted index 2 name callback_calculator_that_collects_stream_landmarks_merged does not have a corresponding output stream.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:336)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:553)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:421)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:439)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:485)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:413)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)

_Originally posted by @QuiLevitin in https://github.com/google/mediapipe/issues/2317#issuecomment-1311487215_

**Comment by QuiLevitin** [comment]
I just want to close this problem because I forgot to update the binarypb from Android Studio which solves the issue. Thank you and happy Coding!
