### ISSUE TITLE
Tulsi project does not generate; cannot find numpy

### ISSUE THREAD

**Issue by monkeyswarm** [google/mediapipe#3857]
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution: Mac M1 chip, MacOS 12.6.1, attempting to use Tulsi to generate iOS 
- [MediaPipe version](https://github.com/google/mediapipe/releases): top of tree
- Bazel version: using bazelisk. Bazel is currently at 5.3.2
- XCode and Tulsi versions (if iOS): Xcode 13.4.1, Tulsi from top of tree
- Python is at Python 3.10.6. I cannot use Python 3.7 on Mac M1 computers. I can switch to 3.8 if needed but I don't think that's the issue here.

**Describe the problem**:
Follow directions to build for iOS. On generating xcode project in Tulsi, get this:
```
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: /Users/diglesia/mediapipe/WORKSPACE:488:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//mediapipe/objc:mediapipe_framework_ios' failed; build aborted: Problem getting numpy include path.Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
General failure: Bazel aspects could not be built.
```

Python is at 
/opt/homebrew/bin/python
and it finds numpy correctly when used.

**Comment by monkeyswarm** [comment]
Some more logs:
```
[3:15:43 PM](3): Running /opt/homebrew/bin/bazel info '--override_repository=tulsi=/Users/diglesia/Library/Application Support/Tulsi/0.20221005.88/Bazel'
[3:22:35 PM](3): Running /opt/homebrew/bin/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/diglesia/Library/Application Support/Tulsi/0.20221005.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress 'kind(rule, :all)+kind(rule, mediapipe:all)+kind(rule, mediapipe/examples/ios:all)+kind(rule, mediapipe/examples/ios/facedetectioncpu:all)+kind(rule, mediapipe/examples/ios/facedetectiongpu:all)+kind(rule, mediapipe/examples/ios/faceeffect:all)+kind(rule, mediapipe/examples/ios/facemeshgpu:all)+kind(rule, mediapipe/examples/ios/handdetectiongpu:all)+kind(rule, mediapipe/examples/ios/handtrackinggpu:all)+kind(rule, mediapipe/examples/ios/holistictrackinggpu:all)+kind(rule, mediapipe/examples/ios/iristrackinggpu:all)+kind(rule, mediapipe/examples/ios/objectdetectioncpu:all)+kind(rule, mediapipe/examples/ios/objectdetectiongpu:all)+kind(rule, mediapipe/examples/ios/objectdetectiontrackinggpu:all)+kind(rule, mediapipe/examples/ios/posetrackinggpu:all)+kind(rule, mediapipe/examples/ios/selfiesegmentationgpu:all)+kind(rule, mediapipe/objc:all)' --output xml
[3:22:58 PM](3): Running /opt/homebrew/bin/bazel info '--override_repository=tulsi=/Users/diglesia/Library/Application Support/Tulsi/0.20221005.88/Bazel'
[3:22:58 PM](3): Build Events JSON file at "/var/folders/fm/yng8gs1s2kb1kwv6gvsv4nc4007656/T/build_events_65322.json"
[3:22:58 PM](3): Running /opt/homebrew/bin/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc '--override_repository=tulsi=/Users/diglesia/Library/Application Support/Tulsi/0.20221005.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/fm/yng8gs1s2kb1kwv6gvsv4nc4007656/T/build_events_65322.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --noexperimental_run_validations --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-dsyms //mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp //mediapipe/examples/ios/facedetectiongpu:FaceDetectionGpuApp //mediapipe/examples/ios/faceeffect:FaceEffectApp //mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp //mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp //mediapipe/examples/ios/helloworld:HelloWorldApp //mediapipe/examples/ios/holistictrackinggpu:HolisticTrackingGpuApp //mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp //mediapipe/examples/ios/objectdetectioncpu:ObjectDetectionCpuApp //mediapipe/examples/ios/objectdetectiongpu:ObjectDetectionGpuApp //mediapipe/examples/ios/objectdetectiontrackinggpu:ObjectDetectionTrackingGpuApp //mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp //mediapipe/examples/ios/selfiesegmentationgpu:SelfieSegmentationGpuApp //mediapipe/objc:mediapipe_framework_ios
[3:22:59 PM](0): Failed to retrieve information about the Bazel workspace. This usually means that the contents of a BUILD file are incorrect or flags are missing. Read the message log carefully for details. [Details]: ERROR: An error occurred during the fetch of repository 'local_execution_config_python':Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: /Users/diglesia/mediapipe/WORKSPACE:488:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: Analysis of target '//mediapipe/objc:mediapipe_framework_ios' failed; build aborted: Problem getting numpy include path.Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
[3:22:59 PM](0): Project generation failed.
[3:22:59 PM](4): Printing Bazel logs that could contain the error.
[3:22:59 PM](3): Log of Bazel aspect info output follows:
[3:22:59 PM](3): Bazel command info:
/opt/homebrew/bin/bazel build --announce_rc --show_result=0 --noshow_loading_progress --noshow_progress --symlink_prefix=/ --apple_platform_type=ios --cpu=ios_x86_64 --watchos_cpus=i386 --announce_rc '--override_repository=tulsi=/Users/diglesia/Library/Application Support/Tulsi/0.20221005.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:generator --build_event_json_file=/var/folders/fm/yng8gs1s2kb1kwv6gvsv4nc4007656/T/build_events_65322.json --noexperimental_build_event_json_file_path_conversion --noexpand_test_suites --features=-parse_headers --noexperimental_run_validations --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_sources_aspect --output_groups=tulsi_info,-dsyms //mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp //mediapipe/examples/ios/facedetectiongpu:FaceDetectionGpuApp //mediapipe/examples/ios/faceeffect:FaceEffectApp //mediapipe/examples/ios/facemeshgpu:FaceMeshGpuApp //mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp //mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp //mediapipe/examples/ios/helloworld:HelloWorldApp //mediapipe/examples/ios/holistictrackinggpu:HolisticTrackingGpuApp //mediapipe/examples/ios/iristrackinggpu:IrisTrackingGpuApp //mediapipe/examples/ios/objectdetectioncpu:ObjectDetectionCpuApp //mediapipe/examples/ios/objectdetectiongpu:ObjectDetectionGpuApp //mediapipe/examples/ios/objectdetectiontrackinggpu:ObjectDetectionTrackingGpuApp //mediapipe/examples/ios/posetrackinggpu:PoseTrackingGpuApp //mediapipe/examples/ios/selfiesegmentationgpu:SelfieSegmentationGpuApp //mediapipe/objc:mediapipe_framework_ios
Exited with code 1

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/diglesia/mediapipe/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/diglesia/mediapipe/.bazelrc:
  'build' options: --jobs 128 --define=absl=1 --enable_platform_specific_config --apple_platform_type=macos --per_file_copt=.*.mm$@-std=c++17 --apple_generate_dsym
INFO: Found applicable config definition build:macos in file /Users/diglesia/mediapipe/.bazelrc: --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --copt=-w
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  /Users/diglesia/mediapipe/WORKSPACE:49:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/131dda9acc6978aba4740d75ca45f411fbabd726.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/8700849191dea2ca9c12a3d26ec41fac0814671b.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  /Users/diglesia/mediapipe/WORKSPACE:488:14: in <toplevel>
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/tensorflow/workspace2.bzl:879:19: in workspace
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/tensorflow/workspace2.bzl:86:27: in _tf_toolchains
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/py/python_configure.bzl", line 216, column 39, in _create_local_python_repository
		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
	File "/private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/py/python_configure.bzl", line 190, column 19, in _get_numpy_include
		return execute(
	File "/private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
ERROR: /Users/diglesia/mediapipe/WORKSPACE:488:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/py/python_configure.bzl", line 216, column 39, in _create_local_python_repository
		numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
	File "/private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/py/python_configure.bzl", line 190, column 19, in _get_numpy_include
		return execute(
	File "/private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Repository ios_opencv instantiated at:
  /Users/diglesia/mediapipe/WORKSPACE:301:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_diglesia/2a7c7eef140c086170c425266ceff07c/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/objc:mediapipe_framework_ios' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 1.110s
INFO: 0 processes.
INFO: Build Event Protocol files produced successfully.

[3:22:59 PM](0): Generate[FAIL]: 1.3041s [Details]: General failure: Bazel aspects could not be built.
[3:22:59 PM](0): Failed to create Xcode project.
```

**Comment by kuaashish** [comment]
Hi @monkeyswarm,
Could you let us know if this closed issue [#2701(Comment)](https://github.com/google/mediapipe/issues/2701#issuecomment-952504461) resolves the above error. Thank you!

**Comment by monkeyswarm** [comment]
Yes, it does resolve it, thank you. 
Is there a tracking issue for this kind of Tulsi environment variable issue?

**Comment by kuaashish** [comment]
Hi @monkeyswarm,
We do not have any this kind of tracking issue as of now but we see this can be brought up to notice of the internal team. Thank you!

**Comment by kuaashish** [comment]
Hi @monkeyswarm,
Could you update the status of the above issue if we can move this to close status as it has been resolved. Thank you!
