### ISSUE TITLE
No source tarball on PYPI

### ISSUE THREAD

**Issue by yurivict** [google/mediapipe#4003]
[here](https://pypi.org/project/mediapipe/#files)

**Comment by yurivict** [comment]
PYPI doesn't have the source tarball mediapipe-0.9.0.1.tar.gz
Only wheels with binary files that were already built are supplied.
This is needed because packaging systems download tarballs from there.
Most projects provide source tarballs.

**Comment by ayushgdev** [comment]
Hello @jiuqiant 
Can you please take a look at this issue?

**Comment by e-yes** [comment]
The lack of a link to the source code prevents tools like [scanpypi from Buildroot](https://github.com/buildroot/buildroot/blob/master/utils/scanpypi) from automatically generating package information. This potentially affects not only Buildroot, other Linux distros/build systems.

```
buildroot package name for mediapipe: python-mediapipe
Package: python-mediapipe
Fetching package mediapipe
Traceback (most recent call last):
  File "/home/e-yes/projects/opensource/buildroot/./utils/scanpypi", line 750, in <module>
    main()
  File "/home/e-yes/projects/opensource/buildroot/./utils/scanpypi", line 680, in main
    package.download_package()
  File "/home/e-yes/projects/opensource/buildroot/./utils/scanpypi", line 218, in download_package
    raise DownloadFailed('Failed to download package {pkg}: '
__main__.DownloadFailed: Failed to download package mediapipe: No source archive available

```

**Comment by schmidt-sebastian** [comment]
@ayushgdev Is this something you could work on?
