### ISSUE TITLE
Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite

### ISSUE THREAD

**Issue by syanenko** [google/mediapipe#4012]
<em>Please make sure that this is a bug and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html), FAQ documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
Project is here: https://github.com/syanenko/ShaderPipe 
 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
Windows 7 

- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser:
 Google Chrome  Version 109.0.5414.75 (Official Build) (64-bit)
 
- Programming Language and version ( e.g. C++, Python, Java):
JS
- [MediaPipe version](https://github.com/google/mediapipe/releases):
0.4.1646424915
- Solution ( e.g. FaceMesh, Pose, Holistic ):
Hands

**Describe the current behavior:**
Getting error in console: "Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite"

**Describe the expected behavior:**
Load module and landmarks file

**Standalone code to reproduce the issue:**
Project is here: https://github.com/syanenko/ShaderPipe 
Live demo: https://virtualkiln.ru
Select "Fireball" from  "Effects" menu, open console.

**Other info / Complete Logs :**
Face_mesh works fine with the same initialization, but Hands fails. 
Hands initialization is here: https://github.com/syanenko/ShaderPipe/blob/main/src/mediapipe.js#L9

**Comment by kuaashish** [comment]
Hi @syanenko,
Have you looked at this closed issue #2181 and try the workaround mentioned here[#4007(comment)](https://github.com/google/mediapipe/issues/2181#issuecomment-863420824) But you need to update the hands solution.

**Comment by syanenko** [comment]
Hi , @kuaashish ,
Thanks for suggestion, but this is not works for me, having error:

Uncaught SyntaxError: Unexpected token '<' (at hands_solution_packed_assets_loader.js:1:1)

Code:

     const handsProc = new Hands({locateFile: (file) => {
     return `assets/models/mediapipe/hands/${file}`;
     }});

     handsProc.setOptions({
     maxNumHands: 2,
     minDetectionConfidence: 0.5,
     minTrackingConfidence: 0.5,
     modelComplexity: 1
     });

Local directory:


     C:\Projects\ShaderPipe>dir assets\models\mediapipe\hands
     README.md
     hand_landmark_lite.tflite  hands.js
     hands_solution_packed_assets_loader.js
     hands_solution_simd_wasm_bin.js
     hands_solution_wasm_bin.js    index.d.ts
     hand_landmark_full.tflite  hands.binarypb
     hands_solution_packed_assets.data  hands_solution_simd_wasm_bin.data
     hands_solution_simd_wasm_bin.wasm  hands_solution_wasm_bin.wasm  package.json


Version: https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4.1657299676/

**Comment by kuaashish** [comment]
Hi @ayushgdev,
Could you please look into this issue?

**Comment by syanenko** [comment]
Hi, guys !
Do you have any update about this issue ?

**Comment by syanenko** [comment]
Hi,
Month has passed, since opening this issue, could you please give any prognosys about fixing it ?

**Comment by ayushgdev** [comment]
Hello @syanenko 
We are unable to recreate the issue at our end. The model files do take a while to load, but once loaded, both Face and Hands are working and no errors are raised on the console. Please refer the screenshot attached. The `hand` object in the onResults callback is getting populated once the results are back from the MP graph. This indicates model is getting loaded.
<img width="1522" alt="Screenshot 2023-02-20 at 4 35 01 PM" src="https://user-images.githubusercontent.com/118424249/220090003-b9eab0d7-51f8-457f-a2f5-6e7e05b639af.png">

Would you please specify if there are any specific steps need to be followed to reproduce the issue?

**Comment by syanenko** [comment]
Hi, @ayushgdev

This is what I see in my Chrome  Version 109.0.5414.120:

![image](https://user-images.githubusercontent.com/6688301/220097335-317bed59-56d8-48c1-b1c5-1afd14b9dadb.png)

independant on waiting time.
All the best,
Sergey.

**Comment by ayushgdev** [comment]
Hi @syanenko 
This is a different error from the one originally reported. I see there are three different errors you are facing:
1. Getting error in console: "Failed to read file third_party/mediapipe/modules/hand_landmark/hand_landmark_full.tflite"
2. Uncaught SyntaxError: Unexpected token '<' (at hands_solution_packed_assets_loader.js:1:1)
3. RuntimeError: Aborted(native code called abort())

We request you to provide recreation steps of the original issue, from the beginning that you have followed, to reproduce error on our end. With different errors and no _consistent_ recreation steps, it is difficult for us to extend our support.
**Note:** For `abort()`, it can happen due to multiple reasons, but initial thoughts are to try including the latest version number in return value of locateFile function. 
```
const hands = new Hands({
    locateFile: (file) => {
        return https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4.1675469240/${file};
    },
});
```

**Comment by syanenko** [comment]
Hi, @ayushgdev
Thank you very much for your support and effort, I don't know what is happening with Chrome, I have not changed my previously working code for about half a year, but after Chrome's update I am getting new errors.

I decided not to continue with this project and switch to another technology, more stable and reliable, so please close this issue.

Thanks  again and all the best,
Sergey Yanenko.

**Comment by yancoo** [comment]
I have some problem with Chrome 110.0.5481.96, would you pls focus this issue to reproduce and fix?  @ayushgdev @kuaashish 

Thanks.
Figo.

**Comment by ayushgdev** [comment]
@yancoo As there were different errors encountered over the course of time in this issue thread, the issue is difficult to reproduce at our end. We suggest you open a new issue with crisp reproduction steps for your issue. We shall surely look at the problem and resolve it.

**Comment by ayushgdev** [comment]
Closing this issue due to lack of activity.
