### ISSUE TITLE
Asset Loader Failing Sometimes

### ISSUE THREAD

**Issue by AmitMY** [google/mediapipe#4063]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): macOS 10.16
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Google Chrome 109
- Programming Language and version ( e.g. C++, Python, Java): Typescript
- [MediaPipe version](https://github.com/google/mediapipe/releases): [February 1st, 2023](https://github.com/google/mediapipe/releases/tag/v0.9.1) [Latest](https://github.com/google/mediapipe/releases/latest)
- Solution ( e.g. FaceMesh, Pose, Holistic ): Holistic

**Describe the current behavior:**
*Sometimes*, when loading holistic (maybe one out of 10 times), I get the following error:
> Uncaught TypeError: Cannot read properties of undefined (reading 'assets/models/holistic/holistic_solution_packed_assets.data')

This seem to come from the last line in:
```js
            if (!xhr.addedTotal) {
              xhr.addedTotal = true;
              if (!Module.dataFileDownloads) Module.dataFileDownloads = {};
              Module.dataFileDownloads[url] = {
                loaded: event.loaded,
                total: size
              };
            } else {
              Module.dataFileDownloads[url].loaded = event.loaded;
            }
```

Which makes sense, sine the file is cached, and is fully loaded.

**Describe the expected behavior:**
Cached or not, the file loading should not fail.

I think that the following solution would be fitting, since there really isn't any use for 'addedTotal'.
```js
if (!Module.dataFileDownloads) Module.dataFileDownloads = {};
Module.dataFileDownloads[url] = {
  loaded: event.loaded,
  total: Module.dataFileDownloads[url]?.total ?? size 
};
```

**Other info / Complete Logs :**
```
zone.js:1714 Uncaught TypeError: Cannot read properties of undefined (reading 'assets/models/holistic/holistic_solution_packed_assets.data')
    at xhr.onprogress [as __zone_symbol__ON_PROPERTYprogress] (VM5550 holistic_solution_packed_assets_loader.js:58:39)
    at XMLHttpRequest.wrapFn (zone.js:769:39)
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:490:34)
    at invokeTask (zone.js:1664:18)
    at globalCallback (zone.js:1695:29)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1728:16)
```

This also leads to:
```
TypeError: Cannot read properties of undefined (reading 'buffer')
    at Object.write (holistic_solution_simd_wasm_bin.js:9:37724)
    at Object.write (holistic_solution_simd_wasm_bin.js:9:60120)
    at Object.createDataFile (holistic_solution_simd_wasm_bin.js:9:67461)
    at finish (holistic_solution_simd_wasm_bin.js:9:73505)
    at processData (holistic_solution_simd_wasm_bin.js:9:73732)
    at Object.createPreloadedFile [as FS_createPreloadedFile] (holistic_solution_simd_wasm_bin.js:9:73859)
    at DataRequest.finish (VM5906 holistic_solution_packed_assets_loader.js:143:43)
    at DataRequest.onload (VM5906 holistic_solution_packed_assets_loader.js:138:16)
    at processPackageData (VM5906 holistic_solution_packed_assets_loader.js:171:63)
    at runWithFS (VM5906 holistic_solution_packed_assets_loader.js:181:9)
```

And sometimes:
```
holistic_solution_packed_assets_loader.js:78 ERROR Error: Uncaught (in promise): RuntimeError: memory access out of bounds
RuntimeError: memory access out of bounds
    at holistic_solution_simd_wasm_bin.wasm:0x4fa7cd
    at holistic_solution_simd_wasm_bin.wasm:0x4fa7b6
    at holistic_solution_simd_wasm_bin.wasm:0x1fe08
    at holistic_solution_simd_wasm_bin.wasm:0x1e94a
```

**Comment by AmitMY** [comment]
**Solution:**
Make sure not to `send` twice, or `send` while the model is `initialize`.

Make sure to `await model.initialize()` and only then `send` in a row
