### ISSUE TITLE
dlopen failed: cannot locate symbol "__isOSVersionAtLeast"

### ISSUE THREAD

**Issue by kuangzy2011** [google/mediapipe#4128]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution
Ubuntu18
Physical device: Android 13

### MediaPipe version

0.9.1

### Bazel version

5.2.0

### Solution

handtrackinggpu

### Programming Language and version

Java 11, 
opencv-3.4.3-android-sdk.zip
android-sdk 30
android-ndk 21

### Describe the actual behavior

```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe9_hands_landmark, PID: 19208
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__isOSVersionAtLeast" referenced by "/data/app/~~7QALOfaA6IVGul4R-_cS9A==/com.google.mediapipe9_hands_landmark-ha5b5imLtz4-79znm4bBIQ==/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.google.mediapipe.solutioncore.SolutionBase.<clinit>(SolutionBase.java:51)
        at com.google.mediapipe.examples.hands.MainActivity.setupStreamingModePipeline(MainActivity.java:268)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupLiveDemoUiComponents$9$com-google-mediapipe-examples-hands-MainActivity(MainActivity.java:260)
        at com.google.mediapipe.examples.hands.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7560)
        at android.view.View.performClickInternal(View.java:7533)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29754)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8133)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
E/gralloc4: Empty SMPTE 2094-40 data
W/_hands_landmark: type=1400 audit(0.0:153728): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
W/OOMEventManagerFK: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/_hands_landmark: type=1400 audit(0.0:153729): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
W/_hands_landmark: type=1400 audit(0.0:153730): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
W/_hands_landmark: type=1400 audit(0.0:153731): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
W/_hands_landmark: type=1400 audit(0.0:153732): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
W/_hands_landmark: type=1400 audit(0.0:153733): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
E/gralloc4: Empty SMPTE 2094-40 data
```

### Describe the expected behaviour

```shell
Run HandTrackingGpu on Android13 and click "START CAMERA", got above errors.
```

**Comment by kuaashish** [comment]
@kuangzy2011,
Would you confirm that you are building/running the solutions in the emulator or in the physical device? Please provide the complete steps followed to reproduce the issue from our end.

**Comment by kuangzy2011** [comment]
Running handtrackinggpu solution in physical device.

#1. [test helloworld.apk] - run build_android_examples.sh to build helloworld.apk, it worked in physical device.

#2. [test handtrackinggpu] - run build_android_example.sh to build handtrackinggpu,  when app started the screen flashed and gone.

#3. [test android source example of handtrackinggpu] - But I don't know what happened at  #2, so I build solution_core.aar, and create a project with Android-studio base on mediapipe\examples\android\solutions\hands\src\main\java\com\google\mediapipe\examples\hands,. Then install apk and run, click "START CAMERA", got the errors.




```
E/gralloc4: Empty SMPTE 2094-40 data
E/gralloc4: Empty SMPTE 2094-40 data
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe9_hands_landmark, PID: 3456
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__isOSVersionAtLeast" referenced by "/data/app/~~dZH-ziZDNVDgKSzvueO9Pw==/com.google.mediapipe9_hands_landmark-qVVfjaeps1zxtarS_FATMg==/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.google.mediapipe.solutioncore.SolutionBase.<clinit>(SolutionBase.java:51)
        at com.google.mediapipe.examples.hands.MainActivity.setupStreamingModePipeline(MainActivity.java:268)
        at com.google.mediapipe.examples.hands.MainActivity.lambda$setupLiveDemoUiComponents$9$com-google-mediapipe-examples-hands-MainActivity(MainActivity.java:260)
        at com.google.mediapipe.examples.hands.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7560)
        at android.view.View.performClickInternal(View.java:7533)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:29754)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8133)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
W/OOMEventManagerFK: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/_hands_landmark: type=1400 audit(0.0:187507): avc: denied { search } for name="miuilog" dev="dm-61" ino=810799 scontext=u:r:untrusted_app_30:s0:c51,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.google.mediapipe9_hands_landmark
```

**Comment by kuangzy2011** [comment]
Seems there is something wrong with 30.0.3, I changed to compile with android sdk-33.0.2, and it worked fine.

Close it.

**Comment by kuangzy2011** [comment]
Close.
