### ISSUE TITLE
Sometime android app quit for unknown reason

### ISSUE THREAD

**Issue by kuangzy2011** [google/mediapipe#4148]
Process: com.google.mediapipe.examples.holistic.landmark, PID: 23030
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.mediapipe.examples.holistic.landmark/com.google.mediapipe.examples.holistic.MainActivity}: com.google.mediapipe.framework.MediaPipeException: unknown: CalculatorGraph::Run() failed in Run: 
    Calculator::Open() for node "handlandmarksleftandrightgpu__handlandmarksfromposegpu_1__handlandmarkgpu__handlandmarkmodelloader__LocalFileContentsCalculator" failed: Failed to read file
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3948)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8133)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
     Caused by: com.google.mediapipe.framework.MediaPipeException: unknown: CalculatorGraph::Run() failed in Run:

**Comment by kuaashish** [comment]
Hello @kuangzy2011,
Would you let us know the complete info about the issue such as the OS you are using, steps you have followed we suggest to fill the template mentioned [here](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build.install_issue_template.yaml) to get maximum relevant information to debug into this issue. thank you!
