### ISSUE TITLE
window build error mediapipe 0.8.10.2   mediapipe/examples/desktop/hello_world

### ISSUE THREAD

**Issue by fishboyzyf** [google/mediapipe#4175]
### OS Platform and Distribution

window 10 桌面

### Compiler version

vc 2019

### Programming Language and version

vc 2019 python 3.9.10

### Installed using virtualenv? pip? Conda?(if python)

python

### MediaPipe version

0.8.10.2

### Bazel version

5.2

### XCode and Tulsi versions (if iOS)

none

### Android AAR (if android)

None

### Describe the problem

```shell
build error
```

### Complete Logs

```shell
D:\mediapipe-0.8.10.2>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\zhaoyun
fei\AppData\Local\Programs\Python\Python39\python.exe" mediapipe/examples/desktop/hello_world
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha25
6 = "c2cdcf55ffaf49366725639e45dedd449b8c3fe22b54e31625eb80ce3a240f1e"
DEBUG: Repository rules_foreign_cc instantiated at:
  D:/mediapipe-0.8.10.2/WORKSPACE:43:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <topleve
l>
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2f6de3
7d68a4c69e2ff9eec3cebbf1369e496940.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
Analyzing: target //mediapipe/examples/desktop/hello_world:hello_world (1 packages loaded, 0 targets configured)
INFO: Repository local_execution_config_python instantiated at:
  D:/mediapipe-0.8.10.2/WORKSPACE:404:14: in <toplevel>
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/tensorflow/workspace2.bzl:868:19: in workspace
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/tensorflow/workspace2.bzl:91:27: in _tf_toolcha
ins
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in in
itialize_rbe_configs
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27:
in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in
<toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/py/python_configure.bzl
", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/py/python_configure.bzl
", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/remote_config/common.bz
l", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
File "<string>", line 1
    from os import linesep;f = open('script.py', 'w');f.write("from __future__ import print_function" + linesep);f.write
("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('P
YTHONPATH') is not None:" + linesep);f.write("  python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("t
ry:" + linesep);f.write("  library_paths = site.getsitepackages()" + linesep);f.write("except AttributeError:" + linesep
);f.write("  from distutils.sysconfig import get_python_lib" + linesep);f.write("  library_paths = [get_python_lib()]" +
 linesep);f.write("all_paths = set(python_paths + library_paths)" + linesep);f.write("paths = []" + linesep);f.write("fo
r path in all_paths:" + linesep);f.write("  if os.path.isdir(path):" + linesep);f.write("    paths.append(path)" + lines
ep);f.write("if len(paths) >=1:" + linesep);f.write("  print(paths[0])" + linesep);f.close();from subprocess import call
;call(["C:\Users\zhaoyunfei\AppData\Local\Programs\Python\Python39\python.exe", "script.py"]);








                                                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
ERROR: D:/mediapipe-0.8.10.2/WORKSPACE:404:14: fetching local_python_configure rule //external:local_execution_config_py
thon: Traceback (most recent call last):
        File "C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/py/python_configure.bzl
", line 213, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/py/python_configure.bzl
", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/org_tensorflow/third_party/remote_config/common.bz
l", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
File "<string>", line 1
    from os import linesep;f = open('script.py', 'w');f.write("from __future__ import print_function" + linesep);f.write
("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('P
YTHONPATH') is not None:" + linesep);f.write("  python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("t
ry:" + linesep);f.write("  library_paths = site.getsitepackages()" + linesep);f.write("except AttributeError:" + linesep
);f.write("  from distutils.sysconfig import get_python_lib" + linesep);f.write("  library_paths = [get_python_lib()]" +
 linesep);f.write("all_paths = set(python_paths + library_paths)" + linesep);f.write("paths = []" + linesep);f.write("fo
r path in all_paths:" + linesep);f.write("  if os.path.isdir(path):" + linesep);f.write("    paths.append(path)" + lines
ep);f.write("if len(paths) >=1:" + linesep);f.write("  print(paths[0])" + linesep);f.close();from subprocess import call
;call(["C:\Users\zhaoyunfei\AppData\Local\Programs\Python\Python39\python.exe", "script.py"]);








                                                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
INFO: Repository rules_java instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:429:6: in <toplevel>
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  C:/users/zhaoyunfei/_bazel_zhaoyunfei/mqtfca5o/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <topleve
l>
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Repository comma
nd failed
File "<string>", line 1
    from os import linesep;f = open('script.py', 'w');f.write("from __future__ import print_function" + linesep);f.write
("import site" + linesep);f.write("import os" + linesep);f.write("python_paths = []" + linesep);f.write("if os.getenv('P
YTHONPATH') is not None:" + linesep);f.write("  python_paths = os.getenv('PYTHONPATH').split(':')" + linesep);f.write("t
ry:" + linesep);f.write("  library_paths = site.getsitepackages()" + linesep);f.write("except AttributeError:" + linesep
);f.write("  from distutils.sysconfig import get_python_lib" + linesep);f.write("  library_paths = [get_python_lib()]" +
 linesep);f.write("all_paths = set(python_paths + library_paths)" + linesep);f.write("paths = []" + linesep);f.write("fo
r path in all_paths:" + linesep);f.write("  if os.path.isdir(path):" + linesep);f.write("    paths.append(path)" + lines
ep);f.write("if len(paths) >=1:" + linesep);f.write("  print(paths[0])" + linesep);f.close();from subprocess import call
;call(["C:\Users\zhaoyunfei\AppData\Local\Programs\Python\Python39\python.exe", "script.py"]);








                                                                              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
INFO: Elapsed time: 415.506s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (37 packages loaded, 11 targets configured)
FAILED: Build did NOT complete successfully (37 packages loaded, 11 targets configured)
```

**Comment by kuaashish** [comment]
Hi @fishboyzyf,
Use double slashes to specify the python path as mentioned below:

`--action_env PYTHON_BIN_PATH="C://Users//zhaoyunfei//AppData//Local//Programs//Python//Python39//python.exe"`

Please let us know if this resolves the issue. Thank you!

Ref:[buildning example app on windows fails](https://github.com/google/mediapipe/issues/936#issuecomment-663144708)

**Comment by kuaashish** [comment]
@fishboyzyf,
Could you please update the status of the above [comment](https://github.com/google/mediapipe/issues/4175#issuecomment-1467668625). Thank you!

**Comment by fishboyzyf** [comment]
Hi @fishboyzyf,
Use double slashes to specify the python path as mentioned below:

--action_env PYTHON_BIN_PATH="C://Users//zhaoyunfei//AppData//Local//Programs//Python//Python39//python.exe"

Please let us know if this resolves the issue. Thank you!

Ref:buildning example app on windows fails
