### ISSUE TITLE
Binary Graph Build Bazel

### ISSUE THREAD

**Issue by jimwinkpresage** [google/mediapipe#4239]
### OS Platform and Distribution

MacOS 12.4

### Programming Language and version

N/A

### MediaPipe version

Latest Master Branch as of 4/4/23

### Bazel version

bazel 6.1.1-homebrew

### Android AAR (if android)

None

### Describe the problem

```shell
When running the following: 
bazel build -c opt mediapipe/graphs/face_detection:face_detection_mobile_gpu_binary_graph
```

### Complete Logs

```shell
2 warnings generated.
ERROR: /Users/jimwinkelmann/mediapipe/mediapipe/graphs/face_detection/BUILD:63:23: Linking mediapipe/graphs/face_detection/face_detection_mobile_gpu_binary_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/graphs/face_detection:face_detection_mobile_gpu_binary_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/graphs/face_detection/face_detection_mobile_gpu_binary_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/execroot/mediapipe/bazel-out/_tmp/actions/stderr-1520) 1872680 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe/graphs/face_detection:face_detection_mobile_gpu_binary_graph failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 291.135s, Critical Path: 160.26s
INFO: 875 processes: 44 internal, 831 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by jimwinkpresage** [comment]
More color here. The following builds fine for the Helloworld basic app build: 
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld

I cannot get this to run though either:
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

outputs the following build failure: 
ERROR: /Users/jimwinkelmann/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:42:26: Linking mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_gpu_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_gpu_graph_text_to_binary_graph) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_gpu_graph_text_to_binary_graph-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/execroot/mediapipe/bazel-out/_tmp/actions/stderr-33) 1460956 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.728s, Critical Path: 4.13s
INFO: 144 processes: 131 internal, 13 darwin-sandbox.

**Comment by jimwinkpresage** [comment]
Showing the error running in verbose mode: 
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu --verbose_failures

WARNING: /Users/jimwinkelmann/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/jimwinkelmann/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/jimwinkelmann/mediapipe/mediapipe/graphs/hand_tracking/subgraphs/BUILD:42:26: Linking mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_gpu_graph_text_to_binary_graph [for tool] failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_gpu_graph_text_to_binary_graph) 
  (cd /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/sandbox/darwin-sandbox/2095/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=12.3 \
    PATH=/Users/jimwinkelmann/opt/anaconda3/bin:/Users/jimwinkelmann/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    XCODE_VERSION_OVERRIDE=13.4.0.13F17a \
    ZERO_AR_DATE=1 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/graphs/hand_tracking/subgraphs/hand_renderer_gpu_graph_text_to_binary_graph-2.params)
# Configuration: 3d7d60613c2d7f274cecf45f11c2317bf43b0482607a7603f501eeaa0bc3b25c
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
stderr (/private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/execroot/mediapipe/bazel-out/_tmp/actions/stderr-15) 1460956 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
INFO: Elapsed time: 6.779s, Critical Path: 6.54s
INFO: 131 processes: 124 internal, 6 darwin-sandbox, 1 worker.
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hello @jimwinkpresage,
From our end, We could successfully reproduce the issue without any error in macOS 13.2.1 (22D68), Chip Apple M1 Pro, Android Studio Dolphin | 2021.3.1 Patch 1, Bazel 6.1.1-homebrew, Latest clone of Mediapipe 04/05/2023. Please try to upgrade to latest version of macOS 13.2.1 and let us know if the issue still persists. Attached the screenshot here of build
process. 
<img width="1712" alt="Issue" src="https://user-images.githubusercontent.com/98159216/229995555-31b4cfcd-1399-48c4-b07c-bc6f319e1182.png">
Thank you!

**Comment by jimwinkpresage** [comment]
Okay updating to macOS 13.3. I will also note I have an intel based mac.  Will report back with the result.

**Comment by jimwinkpresage** [comment]
After updating my mac to 13.3 I know cannot even build the basic hello world example: 
jimwinkelmann@Jims-MacBook-Pro mediapipe % bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
    mediapipe/examples/desktop/hello_world:hello_world
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/e510d0bda0876c4baa3a270dca39b95da7ec6d9e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/9084a21c1fb3a8eb411a7ed010ec1e9fcaa01b01.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Build options --compilation_mode, --cpu, --crosstool_top, and 3 more have changed, discarding analysis cache.
INFO: Repository local_config_apple_cc instantiated at:
  /Users/jimwinkelmann/mediapipe/WORKSPACE:119:31: in <toplevel>
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_rules_swift/swift/extras.bzl:35:31: in swift_rules_extra_dependencies
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_apple_support/lib/repositories.bzl:49:23: in apple_support_dependencies
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_apple_support/crosstool/setup.bzl:59:23: in apple_cc_configure
Repository rule _apple_cc_autoconf defined at:
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_apple_support/crosstool/setup.bzl:44:37: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_apple_cc':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_apple_support/crosstool/setup.bzl", line 40, column 17, in _apple_cc_autoconf_impl
		fail("Failed to configure Apple CC toolchain, if you only have the command line tools installed and not Xcode, you cannot use this toolchain. You should either remove it or temporarily set '{}=1' in the environment".format(_DISABLE_ENV_VAR))
Error in fail: Failed to configure Apple CC toolchain, if you only have the command line tools installed and not Xcode, you cannot use this toolchain. You should either remove it or temporarily set 'BAZEL_NO_APPLE_CPP_TOOLCHAIN=1' in the environment
ERROR: /Users/jimwinkelmann/mediapipe/WORKSPACE:119:31: fetching _apple_cc_autoconf rule //external:local_config_apple_cc: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_apple_support/crosstool/setup.bzl", line 40, column 17, in _apple_cc_autoconf_impl
		fail("Failed to configure Apple CC toolchain, if you only have the command line tools installed and not Xcode, you cannot use this toolchain. You should either remove it or temporarily set '{}=1' in the environment".format(_DISABLE_ENV_VAR))
Error in fail: Failed to configure Apple CC toolchain, if you only have the command line tools installed and not Xcode, you cannot use this toolchain. You should either remove it or temporarily set 'BAZEL_NO_APPLE_CPP_TOOLCHAIN=1' in the environment
INFO: Repository nodejs_darwin_amd64 instantiated at:
  /Users/jimwinkelmann/mediapipe/WORKSPACE:511:18: in <toplevel>
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl:50:31: in node_repositories
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/rules_nodejs/nodejs/repositories.bzl:400:26: in nodejs_register_toolchains
Repository rule node_repositories defined at:
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/rules_nodejs/nodejs/repositories.bzl:374:36: in <toplevel>
INFO: Repository com_google_protobuf instantiated at:
  /Users/jimwinkelmann/mediapipe/WORKSPACE:57:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /Users/jimwinkelmann/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:10: //mediapipe/examples/desktop/hello_world:hello_world depends on @local_config_apple_cc//:cc-compiler-darwin_x86_64 in repository @local_config_apple_cc which failed to fetch. no such package '@local_config_apple_cc//': Failed to configure Apple CC toolchain, if you only have the command line tools installed and not Xcode, you cannot use this toolchain. You should either remove it or temporarily set 'BAZEL_NO_APPLE_CPP_TOOLCHAIN=1' in the environment
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 1.622s
INFO: 0 processes.
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (2 packages loaded, 219 targets configured)
    currently loading: mediapipe/framework ... (2 packages)
    Fetching repository @npm; Restarting.
    Fetching repository @yarn; Restarting.
    Fetching https://nodejs.org/dist/v16.19.0/node-v16.19.0-darwin-x64.tar.gz; 9.4 MiB (9,868,257B)
    Fetching https://github.com/protocolbuffers/protobuf/archive/v3.19.1.tar.gz; 1.5 MiB (1,556,300B)

**Comment by jimwinkpresage** [comment]
I updated X-code and now can build the hello world example. However I am still getting the same error with building any of the graphs: 

bazel build -c opt --config=android_arm64 mediapipe/graphs/object_detection:mobile_cpu_binary_graph --sandbox_debug

![image](https://user-images.githubusercontent.com/127884236/230135244-b51e789b-acb3-4286-834e-1b306e6165fd.png)

**Comment by jimwinkpresage** [comment]
when I run the command that is getting the error: `(cd /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/sandbox/darwin-sandbox/1249/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.3 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    PATH=/Users/jimwinkelmann/opt/anaconda3/bin:/Users/jimwinkelmann/opt/anaconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk \
    TMPDIR=/var/folders/8g/9rknwgpd4_sb75_mpnzxxtr40000gn/T/ \
    XCODE_VERSION_OVERRIDE=14.3.0.14E222b \
    ZERO_AR_DATE=1 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/sandbox/darwin-sandbox/1249/sandbox.sb /var/tmp/_bazel_jimwinkelmann/install/75b50ce753c66b4b3e83f1baa209bfd7/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_jimwinkelmann/23fdfb0389e746539a3bdbeb73034436/sandbox/darwin-sandbox/1249/stats.out' external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/graphs/object_detection/mobile_cpu_binary_graph_text_to_binary_graph-2.params)`

I get the following: 
![image](https://user-images.githubusercontent.com/127884236/230156803-873ad603-ba68-4bf8-9a6d-fbd0e1d3810c.png)

**Comment by jimwinkpresage** [comment]
So more info completely wiped my mac and did step by step installation instruction for mediapipe on mac. Same error: 
![image](https://user-images.githubusercontent.com/127884236/230242500-f452b27b-a417-43eb-b424-5de5912c86cc.png)

running the command that failed: 
![image](https://user-images.githubusercontent.com/127884236/230242540-72ff4285-e467-4099-b226-9db686125896.png)

I also had someone else try on their mac and same issue. Not sure if mediapipe has made intel based macs obsolete or whats going on. Here is my hardware info: 
![image](https://user-images.githubusercontent.com/127884236/230242770-544189cf-8703-4027-94f6-1734c1e62ebd.png)

**Comment by jimwinkpresage** [comment]
Today I was able to successfully build graphs on ubuntu 18.04 with intel cpu. Still no luck on mac though. Waiting for response...

**Comment by rolandeke** [comment]
I am having this error building the handtracking example. Can I get help on how to solve this

ERROR: /home/chinedumeke/.cache/bazel/_bazel_chinedumeke/9b0c45ac7d66435dc85b349a16a12d35/external/XNNPACK/BUILD.bazel:2494:19: Compiling src/microparams-init.c failed: (Exit 1): clang failed: error executing command (from target @XNNPACK//:microparams_init) external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 94 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/main/tools/linux-sandbox-pid1.cc:518: "execvp(external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang, 0x121eb70)": No such file or directory
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2784.290s, Critical Path: 75.84s
INFO: 589 processes: 332 internal, 257 linux-sandbox.
FAILED: Build did NOT complete successfully

**Comment by kuaashish** [comment]
Hello @jimwinkpresage,
Suggest running with "--subcommands" to get a better error log, but now from log not sure the actual error causing to fail the build. Team uses Intel Macs for build verification so nothing should be broken.

**Comment by jimwinkpresage** [comment]
Here is the output with --subcommands and --verbose_failures
![image](https://user-images.githubusercontent.com/127884236/233681594-8c870b86-fa08-4b3f-930e-da7171815910.png)

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,
Could you please look into this issue. Thank you

**Comment by lazeintech** [comment]
I got the same issue, someone please support

**Comment by schmidt-sebastian** [comment]
Is this on Intel or M1 Macs? I am not able to reproduce on M1.

**Comment by jimwinkpresage** [comment]
Intel.

**Comment by prakashsrv** [comment]
Facing the same issue while I am trying to build .aar file (android archive) got facemesh. 

`ERROR: /Users/saurav/Documents/mediapipe/mediapipe/modules/face_detection/BUILD:99:26: Linking mediapipe/modules/face_detection/face_detection_graph_text_to_binary_graph [for tool] failed: (Exit 1): sandbox-exec failed: error executing command 
  (cd /private/var/tmp/_bazel_root/5bc38dea76c985b4052848234924bf2f/sandbox/darwin-sandbox/542/execroot/mediapipe && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=13.3 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    PATH=/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/saurav/Downloads/flutter/bin/flutter/bin:/Users/saurav/Downloads/flutter/bin:/Users/saurav/.pub-cache/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk \
    TMPDIR=/tmp \
    XCODE_VERSION_OVERRIDE=14.3.0.14E222b \
    ZERO_AR_DATE=1 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_root/5bc38dea76c985b4052848234924bf2f/sandbox/darwin-sandbox/542/sandbox.sb /var/tmp/_bazel_root/install/f822566ff435ccaad75bcfd3b2719b0b/process-wrapper '--timeout=0' '--kill_delay=15' '--stats=/private/var/tmp/_bazel_root/5bc38dea76c985b4052848234924bf2f/sandbox/darwin-sandbox/542/stats.out' external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/mediapipe/modules/face_detection/face_detection_graph_text_to_binary_graph-2.params)
stderr (/private/var/tmp/_bazel_root/5bc38dea76c985b4052848234924bf2f/execroot/mediapipe/bazel-out/_tmp/actions/stderr-7) 1872147 exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //mediapipe/examples/android/aar_example:mediapipe_face_detection.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.200s, Critical Path: 8.76s
INFO: 144 processes: 130 internal, 14 darwin-sandbox.
`

**Comment by yulf** [comment]
I've had compilation problems too and I finally solved it through changing the ndk version to 20.0.5594570.

**Comment by prakashsrv** [comment]
Use M1 machine. I had the same issue.

**Comment by schmidt-sebastian** [comment]
Closing due to inactivity. Please re-open if necesssary.
