### ISSUE TITLE
holistic model_complexity=0 

### ISSUE THREAD

**Issue by bme323** [google/mediapipe#4260]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Raspbian OS, Debian Linux Bullseye 

### MediaPipe version

0.8.9.1

### Bazel version

(Not using Bazel)

### Solution

Holistic

### Programming Language and version

Python 3.9.2

### Describe the actual behavior

```shell
Changing model_complexity=1 to model_complexity=0  outputs error:

benselig@raspberrypi:~/MediapipePose $ /bin/python /home/benselig/MediapipePose/mp_hollistic.py
[1:00:06.183576845] [3338]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[1:00:06.316465361] [3351]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media0 and ISP device /dev/media2
[1:00:06.332670213] [3338]  INFO Camera camera.cpp:1028 configuring streams: (0) 1280x720-RGB888
[1:00:06.333176873] [3351]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected unicam format: 1536x864-pBAA
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "/home/benselig/MediapipePose/mp_hollistic.py", line 109, in <module>
    PoseEstimation()
  File "/home/benselig/MediapipePose/mp_hollistic.py", line 54, in PoseEstimation
    image = cv2.resize(image, (1080,720))
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'

benselig@raspberrypi:~/MediapipePose $ /bin/python /home/benselig/MediapipePose/mp_hollistic.py
[1:00:56.137222165] [3383]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[1:00:56.250491452] [3396]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media0 and ISP device /dev/media2
[1:00:56.257428013] [3383]  INFO Camera camera.cpp:1028 configuring streams: (0) 1280x720-RGB888
[1:00:56.257873323] [3396]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected unicam format: 1536x864-pBAA
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
benselig@raspberrypi:~/MediapipePose $ /bin/python /home/benselig/MediapipePose/mp_hollistic.py
[1:05:07.318393491] [3471]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[1:05:07.434449934] [3486]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media0 and ISP device /dev/media2
[1:05:07.441735289] [3471]  INFO Camera camera.cpp:1028 configuring streams: (0) 1280x720-RGB888
[1:05:07.443611340] [3486]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected unicam format: 1536x864-pBAA
Downloading model to /home/benselig/.local/lib/python3.9/site-packages/mediapipe/modules/pose_landmark/pose_landmark_lite.tflite
Traceback (most recent call last):
  File "/home/benselig/MediapipePose/mp_hollistic.py", line 109, in <module>
    PoseEstimation()
  File "/home/benselig/MediapipePose/mp_hollistic.py", line 37, in PoseEstimation
    with mp_holistic.Holistic(
  File "/home/benselig/.local/lib/python3.9/site-packages/mediapipe/python/solutions/holistic.py", line 113, in __init__
    _download_oss_pose_landmark_model(model_complexity)
  File "/home/benselig/.local/lib/python3.9/site-packages/mediapipe/python/solutions/holistic.py", line 59, in _download_oss_pose_landmark_model
    download_utils.download_oss_model(
  File "/home/benselig/.local/lib/python3.9/site-packages/mediapipe/python/solutions/download_utils.py", line 32, in download_oss_model
    with urllib.request.urlopen(model_url) as response, open(model_abspath,
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### Describe the expected behaviour

```shell
Expect to run with higher frame rate using model_complexity=0
```

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/bme323/Mediapipe_holistic/blob/main/mp_hollistic.py 

with mp_holistic.Holistic(
        model_complexity = 1,
        min_detection_confidence = 0.5,
        min_tracking_confidence = 0.5) as holistic:
 ...

when changing to model_complexity = 0, produces error
```

**Comment by ayushgdev** [comment]
@bme323 This error originates if the download of model is not completing. In v0.8.10, we upgraded the Mediapipe package to enable download from GCS storage and this error is fixed now. Please consider upgrading the version of your package to latest. This issue will resolve.

**Comment by bme323** [comment]
Hi, it doesn’t allow me to install any higher mediapipe versions with error message ‘could not find distribution that satisfies the requirement mediapipe==0.8.10.1
No matching distribution found for mediapipe (mediapipe 0.8.9.1)’

I have tried with other mediapipe versions and only distrib that works is 0.8.9.1. I have updated pip v23.

**Comment by ayushgdev** [comment]
Hello @bme323 
MediaPipe is not officially supported in linux aarch64 yet. Hence the reason you cannot find the mediapipe installation through pip. you can build Python wheels yourself from the source code as guided [here](https://github.com/google/mediapipe/blob/master/docs/getting_started/python.md#building-mediapipe-python-package) or follow the steps given [here](https://github.com/jiuqiant/mediapipe_python_aarch64) to install Mediapipe on Raspberry Pi.
