### ISSUE TITLE
Can't find the com.google.mediapipe.framework.image.MPImage 

### ISSUE THREAD

**Issue by BTLDXX-x** [google/mediapipe#4299]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

android 

### MediaPipe version

latest

### Bazel version

5.2.0

### Solution

FaceMesh

### Programming Language and version

java

### Describe the actual behavior

```shell
I built the android aar file with `LandmarksSmoothingCalculator ` based on FaceMesh.
```

### Standalone code/steps you may have used to try to get what you need

```shell
the build file:
`load(
    "//mediapipe/framework/tool:mediapipe_graph.bzl",
    "mediapipe_binary_graph",
)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "smoothed_face_mesh",
    deps = [
        "//mediapipe/calculators/core:concatenate_detection_vector_calculator",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/calculators/core:split_vector_calculator",
        "//mediapipe/calculators/image:image_transformation_calculator",
        "//mediapipe/calculators/util:from_image_calculator",
        "//mediapipe/graphs/face_mesh_smooth/subgraphs:face_landmarks_smoothing",
        "//mediapipe/modules/face_landmark:face_landmark_front_gpu",
    ],
)


mediapipe_binary_graph(
    name = "smoothed_face_landmark_front_gpu_image_graph",
    graph = "smoothed_face_landmark_front_gpu_image.pbtxt",
    output_name = "smoothed_face_landmark_front_gpu_image.binarypb",
    deps = [":smoothed_face_mesh"]
)`

1.build aar
`bazel build -c opt --strip=ALWAYS  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --legacy_whole_archive=0 --features=-legacy_whole_archive --copt=-fvisibility=hidden --copt=-ffunction-sections --copt=-fdata-sections --copt=-fstack-protector --copt=-Oz --copt=-fomit-frame-pointer --copt=-DABSL_MIN_LOG_LEVEL=2 --linkopt=-Wl,--gc-sections,--strip-all //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facesmoothaar:mediapipe_face_mesh_smooth.aar`

2.build graph
bazel build -c opt mediapipe/graphs/face_mesh_smooth:smoothed_face_landmark_front_gpu_image_graph
```

### Other info / Complete Logs

```shell
E/native: E20230418 07:34:51.758706 22058 graph.cc:472] ValidatedGraphConfig Initialization failed.
    No registered object with name: FromImageCalculator; Unable to find Calculator "FromImageCalculator"
    No registered object with name: ImageTransformationCalculator; Unable to find Calculator "ImageTransformationCalculator"
    No registered object with name: ConcatenateNormalizedLandmarkListVectorCalculator; Unable to find Calculator "ConcatenateNormalizedLandmarkListVectorCalculator"
```

**Comment by BTLDXX-x** [comment]
At begining, i copy `mediapipe/java/com/google/mediapipe/solutioncore` to my project. it crashes the problem:

```
ImageSolutionBase.java:141: error: Unable to access MPImage
        imagePacket = packetCreator.createImage((TextureFrame) imageObj);
                                   ^
  Can't find the com.google.mediapipe.framework.image.MPImage class files
```

Then, i create the class `MyAndroidPacketCreator` that copy from `AndroidPacketCreator`, but it crashes the problem:

```
E/mediapipemyfac: No implementation found for long com.example.mediapipemyface.solutioncore.MyAndroidPacketCreator.nativeCreateRgbaImage(long, android.graphics.Bitmap) (tried Java_com_example_mediapipemyface_solutioncore_MyAndroidPacketCreator_nativeCreateRgbaImage and Java_com_example_mediapipemyface_solutioncore_MyAndroidPacketCreator_nativeCreateRgbaImage__JLandroid_graphics_Bitmap_2)
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
I/QarthLog: [PatchStore] create disable file for com.example.mediapipemyface uid is 10132
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mediapipemyface, PID: 11464
    java.lang.UnsatisfiedLinkError: No implementation found for long com.example.mediapipemyface.solutioncore.MyAndroidPacketCreator.nativeCreateRgbaImage(long, android.graphics.Bitmap) (tried Java_com_example_mediapipemyface_solutioncore_MyAndroidPacketCreator_nativeCreateRgbaImage and Java_com_example_mediapipemyface_solutioncore_MyAndroidPacketCreator_nativeCreateRgbaImage__JLandroid_graphics_Bitmap_2)
        at com.example.mediapipemyface.solutioncore.MyAndroidPacketCreator.nativeCreateRgbaImage(Native Method)
        at com.example.mediapipemyface.solutioncore.MyAndroidPacketCreator.createRgbaImage(MyAndroidPacketCreator.java:41)
        at com.example.mediapipemyface.solutioncore.ImageSolutionBase.sendImage(ImageSolutionBase.java:145)
        at com.example.mediapipemyface.solutioncore.ImageSolutionBase.send(ImageSolutionBase.java:112)
        at com.example.mediapipemyface.MainActivity.lambda$setupStaticImageDemoUiComponents$1$com-example-mediapipemyface-MainActivity(MainActivity.java:188)
        at com.example.mediapipemyface.MainActivity$$ExternalSyntheticLambda8.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1307)
        at android.app.Activity.performStart(Activity.java:8277)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4084)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

What should i do to solve these? 
How can i use the `com.google.mediapipe.framework.image.MPImage ` in my own `solution` ? Could it can be built in the aar? I can import the classes from `com.google.mediapipe.framework`, but why does it don't contain the package of 'com.google.mediapipe.framework.image'?

**Comment by BTLDXX-x** [comment]
this is my project directory:
![168179006498111](https://user-images.githubusercontent.com/75558083/232669427-24aaea40-6504-41b0-96ea-471b375669dc.jpg)

**Comment by BTLDXX-x** [comment]
i run this command:

```
bazel build -c opt --strip=ALWAYS \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--fat_apk_cpu=arm64-v8a,armeabi-v7a \
--legacy_whole_archive=0 \
--features=-legacy_whole_archive \
--copt=-fvisibility=hidden \
--copt=-ffunction-sections \
--copt=-fdata-sections \
--copt=-fstack-protector \
--copt=-Oz \
--copt=-fomit-frame-pointer \
--copt=-DABSL_MIN_LOG_LEVEL=2 \
--linkopt=-Wl,--gc-sections,--strip-all \
--config=android_arm64 \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/facesmoothaar:mediapipe_face_mesh_smooth.aar --define MEDIAPIPE_DISABLE_GPU=false --define BUILD_SKIMAGE=false --define ENABLE_CV_IMGCODECS_INTERFACE=false --define ENABLE_CV_IMGPROC_INTERFACE=false --define IMAGE_INTERFACES=true
```

set the `--define IMAGE_INTERFACES=true`, but the built aar still didn't have image directory

**Comment by pczhu** [comment]
this is my solution:
change the code in "mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl" like this:
```
    android_library(
        name = name + "_android_lib",
        srcs = srcs + [
                   "//mediapipe/java/com/google/mediapipe/components:java_src",
                   "//mediapipe/java/com/google/mediapipe/framework:java_src",
                   "//mediapipe/java/com/google/mediapipe/glutil:java_src",
                   "//mediapipe/java/com/google/mediapipe/framework/image:java_src", #add this line
               ] + mediapipe_java_proto_srcs() +
               select({
                   "//conditions:default": [],
                   "enable_stats_logging": mediapipe_logging_java_proto_srcs(),
               }),
        manifest = "AndroidManifest.xml",
        proguard_specs = ["//mediapipe/java/com/google/mediapipe/framework:proguard.pgcfg"],
```

**Comment by BTLDXX-x** [comment]
@pczhu , thanks for your solution. it has MPImage now. but it couldn't find "libmediapipe_jni.so". did you have any idea?
how can i build .so file?

```
public class SolutionBase implements AutoCloseable {
  private static final String TAG = "SolutionBase";
  protected Graph solutionGraph;
  protected MyAndroidPacketCreator packetCreator;
  protected ErrorListener errorListener;
  protected String imageInputStreamName;
  protected long lastTimestamp = Long.MIN_VALUE;
  protected final AtomicBoolean solutionGraphStarted = new AtomicBoolean(false);
  protected SolutionStatsLogger statsLogger;

  static {
    System.loadLibrary("mediapipe_jni");
  }

  /**
   * Initializes solution base with Android context, solution specific settings, and solution result
   * handler.
   *
   * @param context an Android {@link Context}.
   * @param solutionInfo a {@link SolutionInfo} contains binary graph file path, graph input and
   *     output stream names.
   * @param outputHandler a {@link OutputHandler} handles both solution result object and runtime
   *     exception.
   */
  public synchronized void initialize(
      Context context,
      SolutionInfo solutionInfo,
      OutputHandler<? extends SolutionResult> outputHandler) {
    this.imageInputStreamName = solutionInfo.imageInputStreamName();
    this.statsLogger =
        new SolutionStatsDummyLogger(context, this.getClass().getSimpleName(), solutionInfo);
    try {
      AndroidAssetUtil.initializeNativeAssetManager(context);
      solutionGraph = new Graph();
      if (new File(solutionInfo.binaryGraphPath()).isAbsolute()) {
        solutionGraph.loadBinaryGraph(solutionInfo.binaryGraphPath());
      } else {
        solutionGraph.loadBinaryGraph(
            AndroidAssetUtil.getAssetBytes(context.getAssets(), solutionInfo.binaryGraphPath()));
      }
      outputHandler.setStatsLogger(statsLogger);
      solutionGraph.addMultiStreamCallback(
          solutionInfo.outputStreamNames(),
          outputHandler::run,
          /*observeTimestampBounds=*/ outputHandler.handleTimestampBoundChanges());
      packetCreator = new MyAndroidPacketCreator(solutionGraph);
    } catch (MediaPipeException e) {
      statsLogger.logInitError();
      reportError("Error occurs while creating the MediaPipe solution graph.", e);
    }
  }

  /** Reports error with the detailed error message. */
  protected void reportError(String message, MediaPipeException e) {
    String detailedErrorMessage = String.format("%s Error details: %s", message, e.getMessage());
    if (errorListener != null) {
      errorListener.onError(detailedErrorMessage, e);
    } else {
      Log.e(TAG, detailedErrorMessage, e);
      throw e;
    }
  }

  /**
   * A convinence method to get proto list from a packet. If packet is empty, returns an empty list.
   */
  protected <T> List<T> getProtoVector(Packet packet, Parser<T> messageParser) {
    return packet.isEmpty()
        ? ImmutableList.<T>of()
        : PacketGetter.getProtoVector(packet, messageParser);
  }

  /** Gets current timestamp in microseconds. */
  protected long getCurrentTimestampUs() {
    return MICROSECONDS.convert(SystemClock.elapsedRealtime(), MILLISECONDS);
  }

  /** Starts the solution graph by taking an optional input side packets map. */
  public synchronized void start(@Nullable Map<String, Packet> inputSidePackets) {
    try {
      if (inputSidePackets != null) {
        solutionGraph.setInputSidePackets(inputSidePackets);
      }
      if (!solutionGraphStarted.get()) {
        solutionGraph.startRunningGraph();
        // Wait until all calculators are opened and the graph is truly started.
        solutionGraph.waitUntilGraphIdle();
        solutionGraphStarted.set(true);
//        statsLogger.logSessionStart();
      }
    } catch (MediaPipeException e) {
//      statsLogger.logInitError();
      reportError("Error occurs while starting the MediaPipe solution graph.", e);
    }
  }

  /** A blocking API that returns until the solution finishes processing all the pending tasks. */
  public void waitUntilIdle() {
    try {
      solutionGraph.waitUntilGraphIdle();
    } catch (MediaPipeException e) {
      reportError("Error occurs while waiting until the MediaPipe graph becomes idle.", e);
    }
  }

  /** Closes and cleans up the solution graph. */
  @Override
  public void close() {
    if (solutionGraphStarted.get()) {
      try {
        solutionGraph.closeAllPacketSources();
        solutionGraph.waitUntilGraphDone();
//        statsLogger.logSessionEnd();
      } catch (MediaPipeException e) {
        // Note: errors during Process are reported at the earliest opportunity,
        // which may be addPacket or waitUntilDone, depending on timing. For consistency,
        // we want to always report them using the same async handler if installed.
        reportError("Error occurs while closing the Mediapipe solution graph.", e);
      }
      try {
        solutionGraph.tearDown();
      } catch (MediaPipeException e) {
        reportError("Error occurs while closing the Mediapipe solution graph.", e);
      }
    }
  }
}

```

**Comment by BTLDXX-x** [comment]
i rebuild the aar, it's ok. thanks!
