### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by PiPiCode** [google/mediapipe#4328]
com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
 Calculator::Open() for node "facelandmarkfrontgpu__facelandmarkgpu__inferencecalculator__facelandmarkfrontgpu__facelandmarkgpu__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculato

**Comment by kuaashish** [comment]
Hello @PiPiCode,
Would you let us know the complete steps you have followed, need information such as the OS you are using? 
We recommend filling the issue [template](https://github.com/google/mediapipe/issues/new/choose) to receive information to reproduce the issue from our end.

**Comment by prakashsrv** [comment]
Getting the same error.

Device Model: Galaxy J4+
Android Version: 9

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lenskart.aqualens/com.lenskart.cltryon.TryOnActivity}: com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed in Run: 
Calculator::Open() for node "facelandmarkfrontgpu__facelandmarkgpu__inferencecalculator__facelandmarkfrontgpu__facelandmarkgpu__InferenceCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/inference_calculator_gl.cc:195) (interpreter_->ModifyGraphWithDelegate(delegate_.get()))==(kTfLiteOk)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3126)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3269)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```
