### ISSUE TITLE
android cannot open faceMesh again.

### ISSUE THREAD

**Issue by PiPiCode** [google/mediapipe#4329]
Received exception on GL render thread: 
                                                              java.lang.IllegalStateException: swapBuffers: EGL error: 0x300d
                                                                	at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkEglError(SurfaceTextureRenderer.java:530)
                                                                	at android.hardware.camera2.legacy.SurfaceTextureRenderer.swapBuffers(SurfaceTextureRenderer.java:523)
                                                                	at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:727)
                                                                	at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
                                                                	at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                	at android.os.Looper.loop(Looper.java:148)
                                                                	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ayushgdev** [comment]
Hello @PiPiCode Would you please elaborate your query with complete details on the following areas:
- OS you are developing the android app on
- Are you using new MediaPipe tasks API?
- A _minimal_ code and steps you have followed to reproduce the issue at our end
- Are you using AAR build or Maven build?
- Android SDK and NDK versions
