### ISSUE TITLE
On Android 7, the official gesture testing program reported an error

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4334]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

android7 

### Mobile device if the issue happens on mobile device

MI4  LTE 

### Programming Language and version

JAVA

### MediaPipe version

3.7.2

### Bazel version

3.7.2

### Solution

gesture recognition

### Describe the actual behavior

```shell
Crush
```

### Describe the expected behaviour

```shell
run  correct
```

### Standalone code/steps you may have used to try to get what you need

```shell
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example
```

### Other info / Complete Logs

```shell
2023-04-24 09:58:49.384 7450-7450/? I/art: Late-enabling -Xcheck:jni
2023-04-24 09:58:49.419 7450-7450/? W/ReflectionUtils: java.lang.NoSuchMethodException: android.os.MessageQueue#enableMonitor()#bestmatch
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:338)
        at miui.util.ReflectionUtils.findMethodBestMatch(ReflectionUtils.java:375)
        at miui.util.ReflectionUtils.callMethod(ReflectionUtils.java:800)
        at miui.util.ReflectionUtils.tryCallMethod(ReflectionUtils.java:818)
        at android.os.BaseLooper.enableMonitor(BaseLooper.java:47)
        at android.os.Looper.prepareMainLooper(Looper.java:111)
        at android.app.ActivityThread.main(ActivityThread.java:5667)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
2023-04-24 09:58:49.472 7450-7450/com.example.mediapipemultihandstrackingapp W/ResourceType: No package identifier when getting name for resource number 0x00000000
2023-04-24 09:58:49.550 7450-7450/com.example.mediapipemultihandstrackingapp W/linker: /data/app/com.example.mediapipemultihandstrackingapp-2/lib/arm/libmediapipe_jni.so: unused DT entry: type 0x1d arg 0x2e9312
2023-04-24 09:58:49.604 7450-7450/com.example.mediapipemultihandstrackingapp D/AndroidRuntime: Shutting down VM
2023-04-24 09:58:49.604 7450-7450/com.example.mediapipemultihandstrackingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mediapipemultihandstrackingapp, PID: 7450
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.example.mediapipemultihandstrackingapp-2/lib/arm/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.example.mediapipemultihandstrackingapp.MainActivity.<clinit>(MainActivity.java:58)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
        at android.app.ActivityThread.access$1100(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
```

**Comment by kuaashish** [comment]
Hi @jiuqiant,
Could you please help here. Thank you

**Comment by chensisi0730** [comment]
@kuaashish

**Comment by kuaashish** [comment]
Hi @chensisi0730,

We no longer maintain the legacy hand solution, as it has been integrated into the new Hand Landmarker task API, as explained in our [documentation](https://developers.google.com/mediapipe/solutions/guide#legacy). If your use case involves implementing Gesture Recognition, we would like to inform you that it has been separated from the legacy hand solution. 

We have introduced a new Gesture Recognition Task API along with corresponding documentation, available [here](https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/android). We request you to explore and implement our upgraded Gesture Recognition Task in Android, adhering to the steps outlined in our [documentation](https://developers.google.com/mediapipe/solutions/vision/gesture_recognizer/android). Additionally, we kindly request you to notify us of any errors encountered during the exploration process.

Thank you
