### ISSUE TITLE
Holistic - Module.arguments error  - when recreating the code in React Typescript

### ISSUE THREAD

**Issue by AliceHincu** [google/mediapipe#4360]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 10

### MediaPipe version

9.6.4

### Solution

Holistic

### Programming Language and version

Typescript

### Describe the actual behavior

```shell
I have the 2 errors from "Other info / Complete Logs" (separated by "===") when trying to recreate https://codepen.io/mediapipe/pen/LYRRYEw?editors=0010

When I downloaded the zip to try to see if the js version works in visual studio code, it did work indeed, and the behavior was just like in CodePen. I am trying to reproduce the code in React, but first I wanted to make sure that the js still works (hence why I didn't use the useRef hook). It doesn't work, and I get one of the 2 errors stated below every time I refresh. I also tried using the useRef hook, but without success. 

I have commented almost anything in my code to see if I can spot the problem (almost all comments were deleted in the code that I submitted), but I still don't see where the problem is. 

I also had a different project using mediapipe holistic with the same configuration, but using an uploaded image instead of the ControlPanel's SourcePicker, so I believe the problem is there.
```

### Describe the expected behaviour

```shell
What I want to get: https://codepen.io/mediapipe/pen/LYRRYEw?editors=0010
```

### Standalone code/steps you may have used to try to get what you need

```shell
import { Holistic } from "@mediapipe/holistic";
import { useEffect } from "react";
import { ControlPanel, SourcePicker, OptionMap } from "@mediapipe/control_utils";

const initialConfig: OptionMap = {
  selfieMode: true,
  modelComplexity: 1,
  smoothLandmarks: true,
  enableSegmentation: false,
  smoothSegmentation: true,
  minDetectionConfidence: 0.5,
  minTrackingConfidence: 0.5,
  effect: "background",
};

export const PoseAnalysis = () => {
   useEffect(() => {
       const config = {
         locateFile: (file: any) => {
           return `https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/${file}`;
         },
       };

      const canvasElement: any = document.getElementsByClassName("output_canvas")[0];
      const controlsElement: any = document.getElementsByClassName("control-panel")[0];

      function onResults(results: any) {
         console.log("here");
      }

      const holistic = new Holistic(config);
      holistic.onResults(onResults);

      new ControlPanel(controlsElement, initialConfig)
         .add([new SourcePicker({
             onSourceChanged: () => {
               // Resets because the pose gives better results when reset between
               // source changes.
               holistic.reset();
             },
             onFrame: async (input, size) => {
               const aspect = size.height / size.width;
               let width, height;
               if (window.innerWidth > window.innerHeight) {
                 height = window.innerHeight;
                 width = height / aspect;
               } else {
                 width = window.innerWidth;
                 height = width * aspect;
               }
               canvasElement.width = width;
               canvasElement.height = height;
               await holistic.send({ image: input });
             },
           }),])
         .on((x) => {
           const options = x;
           //@ts-ignore
           // videoElement.classList.toggle("selfie", options.selfieMode);
           // activeEffect = x["effect"];
           // console.log("here");
           // holistic.setOptions(options);
         });
     }, []);

    return (
    <div>
      <div className="container">
        <video className="input_video"></video>
        <div className="canvas-container">
          <canvas className="output_canvas" width="1280px" height="720px">
            {" "}
          </canvas>
        </div>
        <div className="loading">
          <div className="spinner"></div>
          <div className="message">Loading</div>
        </div>
      </div>
      <div className="control-panel"></div>
    </div>
  );
}
```

### Other info / Complete Logs

```shell
61946 holistic_solution_simd_wasm_bin.js:9 Aborted(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
abort @ VM61946 holistic_solution_simd_wasm_bin.js:9
get @ VM61946 holistic_solution_simd_wasm_bin.js:9
(anonymous) @ holistic_solution_simd_wasm_bin.js:9
(anonymous) @ holistic.js:77
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
(anonymous) @ holistic.js:77
Promise.then (async)
(anonymous) @ holistic.js:77
ua @ holistic.js:14
next @ holistic.js:15
b @ holistic.js:15
Promise.then (async)
f @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
Sd @ holistic.js:76
(anonymous) @ holistic.js:85
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
__webpack_modules__../node_modules/@mediapipe/holistic/holistic.js.x.initialize @ holistic.js:85
(anonymous) @ holistic.js:86
ua @ holistic.js:14
next @ holistic.js:15
b @ holistic.js:15
Promise.then (async)
f @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
__webpack_modules__../node_modules/@mediapipe/holistic/holistic.js.x.send @ holistic.js:86
(anonymous) @ holistic.js:103
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
__webpack_modules__../node_modules/@mediapipe/holistic/holistic.js.x.send @ holistic.js:103
onFrame @ PostureAnalysis.tsx:375
__webpack_modules__.../node_modules/@mediapipe/control_utils/control_utils.js.U.tick @ control_utils.js:44
(anonymous) @ control_utils.js:43
requestAnimationFrame (async)
V @ control_utils.js:43
c @ control_utils.js:45
2VM61946 holistic_solution_simd_wasm_bin.js:9 Uncaught (in promise) RuntimeError: Aborted(Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))
    at abort (VM61946 holistic_solution_simd_wasm_bin.js:9:17640)
    at Object.get (VM61946 holistic_solution_simd_wasm_bin.js:9:7759)
    at holistic_solution_simd_wasm_bin.js:9:5881
    at ra.i (holistic.js:77:1)
    at ua (holistic.js:14:1)
    at va.next (holistic.js:15:1)
    at holistic.js:15:1
    at new Promise (<anonymous>)
    at wa (holistic.js:15:1)
    at D (holistic.js:16:1)
abort @ VM61946 holistic_solution_simd_wasm_bin.js:9
get @ VM61946 holistic_solution_simd_wasm_bin.js:9
(anonymous) @ holistic_solution_simd_wasm_bin.js:9
(anonymous) @ holistic.js:77
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
(anonymous) @ holistic.js:77
Promise.then (async)
__webpack_modules__.../node_modules/@mediapipe/control_utils/control_utils.js.U.tick @ control_utils.js:44
(anonymous) @ control_utils.js:43
requestAnimationFrame (async)
V @ control_utils.js:43
c @ control_utils.js:45
VM61946 holistic_solution_simd_wasm_bin.js:9 Aborted(Assertion failed)
abort @ VM61946 holistic_solution_simd_wasm_bin.js:9
assert @ VM61946 holistic_solution_simd_wasm_bin.js:9
addRunDependency @ VM61946 holistic_solution_simd_wasm_bin.js:9
open @ VM61944 holistic_solution_packed_assets_loader.js:133
runWithFS @ VM61944 holistic_solution_packed_assets_loader.js:159
callRuntimeCallbacks @ VM61946 holistic_solution_simd_wasm_bin.js:9
preRun @ VM61946 holistic_solution_simd_wasm_bin.js:9
run @ VM61946 holistic_solution_simd_wasm_bin.js:9
runCaller @ VM61946 holistic_solution_simd_wasm_bin.js:9
removeRunDependency @ VM61946 holistic_solution_simd_wasm_bin.js:9
receiveInstance @ VM61946 holistic_solution_simd_wasm_bin.js:9
receiveInstantiationResult @ VM61946 holistic_solution_simd_wasm_bin.js:9
Promise.then (async)
(anonymous) @ VM61946 holistic_solution_simd_wasm_bin.js:9
Promise.then (async)
instantiateAsync @ VM61946 holistic_solution_simd_wasm_bin.js:9
createWasm @ VM61946 holistic_solution_simd_wasm_bin.js:9
(anonymous) @ VM61946 holistic_solution_simd_wasm_bin.js:9
(anonymous) @ holistic.js:77
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
(anonymous) @ holistic.js:77
Promise.then (async)
(anonymous) @ holistic.js:77
ua @ holistic.js:14
next @ holistic.js:15
b @ holistic.js:15
Promise.then (async)
f @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
Sd @ holistic.js:76
(anonymous) @ holistic.js:85
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
__webpack_modules__../node_modules/@mediapipe/holistic/holistic.js.x.initialize @ holistic.js:85
(anonymous) @ holistic.js:86
ua @ holistic.js:14
next @ holistic.js:15
b @ holistic.js:15
Promise.then (async)
f @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
__webpack_modules__../node_modules/@mediapipe/holistic/holistic.js.x.send @ holistic.js:86
(anonymous) @ holistic.js:103
ua @ holistic.js:14
next @ holistic.js:15
(anonymous) @ holistic.js:15
wa @ holistic.js:15
D @ holistic.js:16
__webpack_modules__../node_modules/@mediapipe/holistic/holistic.js.x.send @ holistic.js:103
onFrame @ PostureAnalysis.tsx:375
__webpack_modules__.../node_modules/@mediapipe/control_utils/control_utils.js.U.tick @ control_utils.js:44
(anonymous) @ control_utils.js:43
requestAnimationFrame (async)
V @ control_utils.js:43
c @ control_utils.js:45


===================================================

ERROR
File exists
Error
    at new ErrnoError (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:64591)
    at Object.mknod (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:51452)
    at Object.create (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:51671)
    at Object.createDataFile (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:67248)
    at finish (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:73505)
    at processData (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:73732)
    at Object.createPreloadedFile [as FS_createPreloadedFile] (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_simd_wasm_bin.js:9:73859)
    at DataRequest.finish (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_packed_assets_loader.js:143:43)
    at DataRequest.onload (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_packed_assets_loader.js:138:16)
    at processPackageData (https://cdn.jsdelivr.net/npm/@mediapipe/holistic@latest/holistic_solution_packed_assets_loader.js:171:63)
```

**Comment by ayushgdev** [comment]
Hello @AliceHincu To update you, we are able to recreate this issue. We will provide a resolution for it in sometime.

**Comment by ayushgdev** [comment]
@AliceHincu Which version of React are you using? 
Most probably it seems like you are running react 18. If so, please downgrade it to 17.0.2.  In react 18, this is happening due to the changes introduced by React team in version 18. In version 18, it calls `useEffect()` twice (due to mount->unmount->mount cycle, details [here](https://www.youtube.com/watch?v=MXSuOR2yRvQ)) which causes two listeners to be created with the SourcePicker's `onFrame` listener.
Hence whenever a frame arrives, it calls two onFrame listener. 
In this code, the onFrame listener calls `holistic.send()` which sends two frames to the same holistic object twice. This causes breakdown. Either you need to have teardown logic in your app so that the first call to `useEffect()` will be nullified and only one listener remains, or downgrade the react version to 17.

**Comment by redamsy** [comment]
> Hi! Thank you, I was not aware of the new behavior of useEffect(). For React 18, I used the second fix for the hook from this video: https://www.youtube.com/watch?v=81faZzp18NM
> 
> Also, if anyone wants to know the useRef for the other elements: `const effectRan = useRef(false);` `const videoElement = useRef<HTMLVideoElement>(null);` `const canvasElement = useRef<HTMLCanvasElement>(null);` `const controlsElement = useRef<HTMLDivElement>(null);`
> 
> And then check them to not be null...also you need to declare the "onResults" function outside:
> 
> ```
> useEffect(() => {
>     if (effectRan.current === true) { // nullify first useEffect because of version 18.0.0
>          if (canvasElement.current && controlsElement.current) {
>               // the logic
>          }
>     }
>     
>     return () => {
>       effectRan.current = true;
>     };
> }, []);
> ```

thank you thank you, i didn't that useEffect react 18 was the issue, the video you provided was so helpful
