### ISSUE TITLE
mediapipe.tasks.python.vision.FaceLandmarker to produce output blendshapes

### ISSUE THREAD

**Issue by Barissevilmis** [google/mediapipe#4366]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows 10

### MediaPipe Tasks SDK version

0.9.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Landmark Recognition

### Programming Language and version (e.g. C++, Python, Java)

Python 3.10.9

### Describe the actual behavior

```shell
Dear Mediapipe Team,

I have been trying to utilize the FaceLandmarker class to produce output blendshapes from a livestream. Therefore, I was trying to do tests with a single image to check whether I can produce the output blendshape coefficients. However, I continuosly get the following error for my simple code.

Code:
--------------------------------------------------------------------
import numpy as np 
import mediapipe as mp
import cv2
import numpy as np
from time import time
from mediapipe.tasks import python
from mediapipe.tasks.python import vision


base_options = python.BaseOptions(model_asset_path="face_landmarker_with_blendshapes.task")
options = vision.FaceLandmarkerOptions(base_options=base_options, output_face_blendshapes=True)

detector = vision.FaceLandmarker.create_from_options(options)
tpk = mp.Image.create_from_file('reference_img.jpg')
res2 = detector.detect(tpk) 
print(res2.face_blendshapes)


```

### Describe the expected behaviour

```shell
Print statement to output blendshape coefficients. I have found task file from the link: https://github.com/google/mediapipe/tree/54e4dfc853ddb6d75004a0bb79ef72dcdd8308f9/mediapipe/tasks/testdata/vision
```

### Standalone code/steps you may have used to try to get what you need

```shell
reference_img.jpg is simply my own Face image, you can use any face image instead. There is no specific or important detail for the image.
```

### Other info / Complete Logs

```shell
python blendshape_test.py 
----------------------------------------------------------------------------------------
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20230503 10:08:16.234967  8760 face_landmarker_graph.cc:169] Face blendshape model contains CPU only ops. Sets FaceBlendshapesGraph acceleration to Xnnpack.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
E20230503 10:08:16.288591  8760 calculator_graph.cc:846] INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_face_landmarker_facelandmarkergraph__mediapipe_tasks_vision_face_landmarker_multifacelandmarksdetectorgraph__mediapipe_tasks_vision_face_landmarker_singlefacelandmarksdetectorgraph__TensorsToFloatsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_floats_calculator.cc:99) (num_values)==(1)
Traceback (most recent call last):
  File "C:\Users\Sevilmis\facial-emg-morph\blendshape_test.py", line 17, in <module>
    res2 = detector.detect(tpk)
  File "C:\Users\Sevilmis\AppData\Roaming\Python\Python310\site-packages\mediapipe\tasks\python\vision\face_landmarker.py", line 3143, in detect
    output_packets = self._process_image_data({
  File "C:\Users\Sevilmis\AppData\Roaming\Python\Python310\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 96, in _process_image_data
    return self._runner.process(inputs)
RuntimeError: CalculatorGraph::Run() failed in Run:
Calculator::Process() for node "mediapipe_tasks_vision_face_landmarker_facelandmarkergraph__mediapipe_tasks_vision_face_landmarker_multifacelandmarksdetectorgraph__mediapipe_tasks_vision_face_landmarker_singlefacelandmarksdetectorgraph__TensorsToFloatsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_floats_calculator.cc:99) (num_values)==(1)
```

**Comment by Barissevilmis** [comment]
I found out the issue luckily, as the .task graph I was using was not working: I replaced mine with the .task provided in the below link  https://storage.googleapis.com/mediapipe-assets/face_landmarker_with_blendshapes.task
