### ISSUE TITLE
Tried to install all day yesterday but still failed, so here I am

### ISSUE THREAD

**Issue by happypuppy20** [google/mediapipe#4416]
### OS Platform and Distribution

Win 10

### Programming Language and version

Python 3.10.0

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

0.10.0

### Bazel version

NONE

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.7.0.68

### Describe the problem

```shell
Trying to get mediapipe to work with my Python but it just won't go.
```

### Complete Logs

```shell
(venv) PS C:\Users\HappyPuppy\stable-diffusion-webui\venv\Scripts> pip install mediapipe
WARNING: Ignoring invalid distribution -rotobuf (c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages)
Requirement already satisfied: mediapipe in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (0.10.0)
Requirement already satisfied: absl-py in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (1.4.0)
Requirement already satisfied: attrs>=19.1.0 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (22.2.0)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (23.1.21)
Requirement already satisfied: matplotlib in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (3.7.0)
Requirement already satisfied: numpy in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (1.23.5)
Requirement already satisfied: opencv-contrib-python in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (4.7.0.72)
Requirement already satisfied: protobuf<4,>=3.11 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (3.19.6)
Requirement already satisfied: sounddevice>=0.4.4 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from mediapipe) (0.4.6)
Requirement already satisfied: CFFI>=1.0 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from sounddevice>=0.4.4->mediapipe) (1.15.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->mediapipe) (2.8.2)
Requirement already satisfied: pycparser in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\happypuppy\stable-diffusion-webui\venv\lib\site-packages)


=========================================================================

Error loading script: batch_face_swap.py
Traceback (most recent call last):
  File "C:\Users\HappyPuppy\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\HappyPuppy\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\HappyPuppy\stable-diffusion-webui\extensions\batch-face-swap\scripts\batch_face_swap.py", line 8, in <module>
    from bfs_utils import *
  File "C:\Users\HappyPuppy\stable-diffusion-webui\extensions\batch-face-swap\scripts\bfs_utils.py", line 11, in <module>
    import mediapipe as mp
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

Error loading script: bfs_utils.py
Traceback (most recent call last):
  File "C:\Users\HappyPuppy\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\HappyPuppy\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\HappyPuppy\stable-diffusion-webui\extensions\batch-face-swap\scripts\bfs_utils.py", line 11, in <module>
    import mediapipe as mp
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

Error loading script: face_detect.py
Traceback (most recent call last):
  File "C:\Users\HappyPuppy\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\HappyPuppy\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\HappyPuppy\stable-diffusion-webui\extensions\batch-face-swap\scripts\face_detect.py", line 10, in <module>
    import mediapipe as mp
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 24, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 8, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\HappyPuppy\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)
```

**Comment by ayushgdev** [comment]
@happypuppy20 Would you please let us know exact steps followed for the installation apart from `pip install mediapipe`?
For example, the following questions may give you idea on the information required:
- Were there any virtual environments set up? 
- Did you install OpenCV separately?

**Comment by happypuppy20** [comment]
I have it done on both with and without venv.
I think I have OpenCV from other times installing other stuff..

**Comment by happypuppy20** [comment]
no idea?

**Comment by ayushgdev** [comment]
@happypuppy20 We are not able to replicate this issue at our end. We created a fresh VM of Windows 10 and tested it with Python 3.10.0. 

However, from the logs, it looks like protobuf installed in the system is not a compatible version with MediaPipe. 

Also, I would recommend deleting the virtual environment and recreating it. Run the python interpreter and ensure that python 3.10.0 is the version which is being invoked for that environment.
