### ISSUE TITLE
try to produce an exe file from an example and have the following problem

### ISSUE THREAD

**Issue by neruiz** [google/mediapipe#4466]
### OS Platform and Distribution

windows

### Compiler version

python 3.10

### Programming Language and version

python 3.10

### Installed using virtualenv? pip? Conda?(if python)

no

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

opencv-python-4.7.0.72

### Describe the problem

```shell
I try to produce an exe file from the following code:

import cv2
import mediapipe as mp

# Crear una instancia de la tarea de detección de manos
mp_hands = mp.solutions.hands.Hands()

# Capturar video desde la cámara
cap = cv2.VideoCapture(0)

while True:
    # Leer el siguiente frame del video
    ret, frame = cap.read()

    # Convertir el frame a formato RGB
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Detectar manos en el frame
    results = mp_hands.process(frame_rgb)

    # Verificar si se detectaron manos
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            # Acceder a los puntos clave de la mano detectada
            for landmark in hand_landmarks.landmark:
                # Obtener las coordenadas normalizadas de cada punto clave
                x = int(landmark.x * frame.shape[1])
                y = int(landmark.y * frame.shape[0])

                #

                # Dibujar un círculo en cada punto clave
                cv2.circle(frame, (x, y), 5, (0, 255, 0), -1)

    # Mostrar el frame en una ventana
    cv2.imshow('Hand Detection', frame)

    # Salir del bucle si se presiona la tecla 'Esc'
    if cv2.waitKey(1) == 27:
        break

# Liberar el recurso de la cámara y cerrar la ventana
cap.release()
cv2.destroyAllWindows()


I have that in pycharm. I run from the pyacharm enviroment and works fine. then I run using: from the comand line python main.py and works fine
then I try to produce the exe file ussing
pyinstaller --onefile main.py 
it generate the exe file but when I try to run it is show the following and it does not work


C:\Users\NER\PycharmProjects\pythonProject\dist>main
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "mediapipe\python\solutions\hands.py", line 114, in __init__
  File "mediapipe\python\solution_base.py", line 264, in __init__
FileNotFoundError: The path does not exist.

what can be the problem for producing the exe file?
```

### Complete Logs

```shell
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "mediapipe\python\solutions\hands.py", line 114, in __init__
  File "mediapipe\python\solution_base.py", line 264, in __init__
FileNotFoundError: The path does not exist.
```

**Comment by kuaashish** [comment]
@neruiz,
This error occurs when there are non-unicode characters in the path of the project. It is not only related with the username, but with all the characters included in the pathname. For example, if you have characters in the pathname of your project like "ç", "ş", "ü", "ğ", "ı", "ö", etc you will have this error.

In order to eliminate this error, build your project in a folder that does not have "non-unicode" characters. Further, You can follow this additional [thread](https://superuser.com/questions/890812/how-to-rename-the-user-folder-in-windows-10) for better understanding. Thank you
