### ISSUE TITLE
ImageCloneCalculator: GPU processing is disabled in build flags

### ISSUE THREAD

**Issue by mozhijing** [google/mediapipe#4515]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Ubuntu 20.04.1

### MediaPipe Tasks SDK version

0.10.1

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose landmark detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

```shell
I use GPU to run Pose landmark detection.
```

### Describe the expected behaviour

```shell
Running with GPU
```

### Standalone code/steps you may have used to try to get what you need

```shell
# STEP 1: Import the necessary modules.
import time

import cv2
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision, BaseOptions

from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2
import numpy as np


def draw_landmarks_on_image(rgb_image, detection_result):
    pose_landmarks_list = detection_result.pose_landmarks
    annotated_image = np.copy(rgb_image)

    # Loop through the detected poses to visualize.
    for idx in range(len(pose_landmarks_list)):
        pose_landmarks = pose_landmarks_list[idx]

        # Draw the pose landmarks.
        pose_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
        pose_landmarks_proto.landmark.extend([
            landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in pose_landmarks
        ])
        solutions.drawing_utils.draw_landmarks(
            annotated_image,
            pose_landmarks_proto,
            solutions.pose.POSE_CONNECTIONS,
            solutions.drawing_styles.get_default_pose_landmarks_style())
    return annotated_image


VisionRunningMode = mp.tasks.vision.RunningMode
base_options = python.BaseOptions(model_asset_path='model/pose_landmarker_full.task', delegate=BaseOptions.Delegate.GPU)
VisionRunningMode = mp.tasks.vision.RunningMode
options = vision.PoseLandmarkerOptions(
    base_options=base_options,
    output_segmentation_masks=False,
    num_poses=1,
    min_pose_detection_confidence=0.6,
    running_mode=VisionRunningMode.VIDEO)
detector = vision.PoseLandmarker.create_from_options(options)

cap = cv2.VideoCapture("video/temp/13.mp4")

frame_count = 0
while cap.isOpened():
    frame_count = frame_count + 1
    catch, frame = cap.read()
    height, width = frame.shape[:2]
    image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)
    detection_result = detector.detect_for_video(mp_image, frame_count)
    # STEP 5: Process the detection result. In this case, visualize it.
    annotated_image = draw_landmarks_on_image(mp_image.numpy_view(), detection_result)
    rgb_annotated_image = cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB)
    cv2.imshow('img', rgb_annotated_image)
    cv2.waitKey(1)
```

### Other info / Complete Logs

```shell
Traceback (most recent call last):
  File "/home/root/PycharmProjects/pythonProject/new_pose/pose_detect.py", line 44, in <module>
    detector = vision.PoseLandmarker.create_from_options(options)
  File "/home/root/anaconda3/lib/python3.9/site-packages/mediapipe/tasks/python/vision/pose_landmarker.py", line 319, in create_from_options
    return cls(
  File "/home/root/anaconda3/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
NotImplementedError: ValidatedGraphConfig Initialization failed.
ImageCloneCalculator: GPU processing is disabled in build flags
ImageCloneCalculator: GPU processing is disabled in build flags
```

**Comment by mozhijing** [comment]
@kuaashish I am waiting for your solution

**Comment by deniz-birlikci** [comment]
I'm also looking for a solution. I have the same issue regarding GPU support with Python.

**Comment by kuaashish** [comment]
Hello @schmidt-sebastian,

Could you please look into this issue. Thank you!

**Comment by schmidt-sebastian** [comment]
We are working on this at the moment.

**Comment by jarvijd** [comment]
Any updates on this?  Getting GPU working in the python version could be a huge performance improvement.

**Comment by schmidt-sebastian** [comment]
Hopefully included in our next release.

**Comment by deniz-birlikci** [comment]
Hi Sebastian, what would be the timeline for that? Currently, is there any way to make the GPU work with the python version?

**Comment by jarvijd** [comment]
Just did a pip install mediapipe and still not able to get the GPU delegate working.

  base_options = python.BaseOptions(model_asset_path='model/pose_landmarker_full.task', delegate=BaseOptions.Delegate.GPU)

Are there any workarounds available to get this running?

**Comment by mosamman** [comment]
> Hopefully included in our next release.

Hi @schmidt-sebastian this issue is still present in the latest release 0.10.5
any idea when to expect a fix

thank you

**Comment by kuaashish** [comment]
Hi @mozhijing,

We are pleased to announce the release of MP version 0.10.8, which now supports Python GPU via pip on macOS and Linux. As outlined in the [release notes](https://github.com/google/mediapipe/releases/tag/v0.10.8), we kindly request you to build using the latest version and inform us of your experience with GPU utilisation using Python Wheels.

Thank you
