### ISSUE TITLE
Training error : The model is not a valid Flatbuffer buffer

### ISSUE THREAD

**Issue by ezawadzki** [google/mediapipe#4593]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Linux - Debian 11

### MediaPipe Tasks SDK version

0.10.1

### Task name (e.g. Image classification, Gesture recognition etc.)

Object Detection

### Programming Language and version (e.g. C++, Python, Java)

Python / Web

### Describe the actual behavior

```shell
After trained the android's dataset from this example :

https://developers.google.com/mediapipe/solutions/customization/object_detector

I put my model into my web example of object detection (already tested and worked with provided models).
```

### Describe the expected behaviour

```shell
I should detect small android statue.
```

### Standalone code/steps you may have used to try to get what you need

```shell
import os
import json
import tensorflow as tf
assert tf.__version__.startswith('2')

from mediapipe_model_maker import object_detector
from mediapipe_model_maker import quantization


train_dataset_path = "android_figurine/train"
validation_dataset_path = "android_figurine/validation"

with open(os.path.join(train_dataset_path, "labels.json"), "r") as f:
  labels_json = json.load(f)
for category_item in labels_json["categories"]:
  print(f"{category_item['id']}: {category_item['name']}")

train_data = object_detector.Dataset.from_coco_folder(train_dataset_path, cache_dir="/tmp/od_data/train")
validation_data = object_detector.Dataset.from_coco_folder(validation_dataset_path, cache_dir="/tmp/od_data/validation")
print("train_data size: ", train_data.size)
print("validation_data size: ", validation_data.size)


spec = object_detector.SupportedModels.MOBILENET_MULTI_AVG
hparams = object_detector.HParams(export_dir='exported_model')
options = object_detector.ObjectDetectorOptions(
    supported_model=spec,
    hparams=hparams
)

model = object_detector.ObjectDetector.create(
    train_data=train_data,
    validation_data=validation_data,
    options=options)


quantization_config = quantization.QuantizationConfig.for_float16()
model.restore_float_ckpt()
model.export_model(model_name="model_fp16.tflite", quantization_config=quantization_config)
```

### Other info / Complete Logs

```shell
Uncaught (in promise) Error: StartGraph failed: $The model is not a valid Flatbuffer buffer; Initialize was not ok
    at u1.handleErrors (vision_bundle.js:1:456941)
    at u1.setGraph (vision_bundle.js:1:456625)
    at u1.refreshGraph (vision_bundle.js:1:849169)
    at vision_bundle.js:1:456019
    at async createTaskRunner (vision_bundle.js:1:454590)
    at async initializeObjectDetector (index.ts:49:20)
```

**Comment by vishalatkites** [comment]
How is the issue resolved? Facing the same issue
