### ISSUE TITLE
ERROR:Is it the python binary?

### ISSUE THREAD

**Issue by u431535** [google/mediapipe#4622]
### OS Platform and Distribution

Windows 11 

### Programming Language and version

VS 2022 build tools

### Installed using virtualenv? pip? Conda?(if python)

installed python from executable, Python 3.10.5

### Bazel version

6.2.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

3.4.15

### Describe the problem

```shell
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\python.exe'' is not executable. Is it the python binary?
```

### Complete Logs

```shell
(1) read previous issue and perform Python testing:
C:\Study\Python\mediapipe>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> os.path.dirname(sys.executable)
'C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310'

(2) running error log
C:\Study\Python\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH='C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\python.exe' mediapipe/examples/desktop/hello_world
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/0258a53521cfedf5cb80c2b1d4a66c942615de74.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/7d879c8b161085a4374ea481b93a52adb19c0529.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Repository local_execution_config_python instantiated at:
  C:/study/python/mediapipe/WORKSPACE:512:14: in <toplevel>
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:985:19: in workspace
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:100:27: in _tf_toolchains
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\python.exe'' is not executable. Is it the python binary?
ERROR: C:/study/python/mediapipe/WORKSPACE:512:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\python.exe'' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\python.exe'' is not executable. Is it the python binary?
INFO: Elapsed time: 0.740s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded, 9 targets configured)
```

**Comment by kuaashish** [comment]
@u431535,

Seems issue with the Bazel, Supported Version of Bazel is 6.1.1 as described in [.bazelversion](https://github.com/google/mediapipe/blob/master/.bazelversion). Could you please build using recommended version and let us know if this works for you. Thank you!!

**Comment by u431535** [comment]
Hi kuaashish,
I use Bazel 6.1.1 and still have same errors.

C:\Study\Python\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH='C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\Python.exe' mediapipe/examples/desktop/hello_world
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/study/python/mediapipe/WORKSPACE:512:14: in <toplevel>
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:985:19: in workspace
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:100:27: in _tf_toolchains
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\Python.exe'' is not executable. Is it the python binary?
ERROR: C:/study/python/mediapipe/WORKSPACE:512:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\Python.exe'' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH=''C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310\Python.exe'' is not executable. Is it the python binary?
INFO: Elapsed time: 4.857s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 9 targets configured)

C:\Study\Python\mediapipe>bazel --version
bazel 6.1.1

C:\Study\Python\mediapipe>python --version
Python 3.10.5

C:\Study\Python\mediapipe>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import sys
>>> os.path.dirname(sys.executable)
'C:\\Users\\albert.wang\\AppData\\Local\\Programs\\Python\\Python310'

**Comment by u431535** [comment]
> @u431535,
> 
> Seems issue with the Bazel, Supported Version of Bazel is 6.1.1 as described in [.bazelversion](https://github.com/google/mediapipe/blob/master/.bazelversion). Could you please build using recommended version and let us know if this works for you. Thank you!!
-------------------------

I have install Bazel 6.1.1, but still have same error.


C:\Study\Python\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH='C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe' mediapipe/examples/desktop/hello_world
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
C:/study/python/mediapipe/WORKSPACE:512:14: in
C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:985:19: in workspace
C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl💯27: in _tf_toolchains
C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
Traceback (most recent call last):
File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
_check_python_bin(repository_ctx, python_bin)
File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH=''C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe'' is not executable. Is it the python binary?
ERROR: C:/study/python/mediapipe/WORKSPACE:512:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
_check_python_bin(repository_ctx, python_bin)
File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH=''C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe'' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH=''C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe'' is not executable. Is it the python binary?
INFO: Elapsed time: 4.857s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 9 targets configured)

C:\Study\Python\mediapipe>bazel --version
bazel 6.1.1

C:\Study\Python\mediapipe>python --version
Python 3.10.5

C:\Study\Python\mediapipe>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun 6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import os
import sys
os.path.dirname(sys.executable)
'C:\Users\albert.wang\AppData\Local\Programs\Python\Python310'

**Comment by kuaashish** [comment]
@u431535,


Could you please run the below command and let us know if this works for you.

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe" mediapipe/examples/desktop/hello_world`

Thank you!

**Comment by kuaashish** [comment]
@u431535,

Could you please update the status of the above? Thank you

**Comment by u431535** [comment]
> @u431535,
> 
> Could you please update the status of the above? Thank you

Same error.
messages as follow:
C:\Study\Python\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe" mediapipe/examples/desktop/hello_world
Starting local Bazel server and connecting to it...
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  C:/study/python/mediapipe/WORKSPACE:512:14: in <toplevel>
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:985:19: in workspace
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/workspace2.bzl:100:27: in _tf_toolchains
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/tensorflow/tools/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe' is not executable. Is it the python binary?
ERROR: C:/study/python/mediapipe/WORKSPACE:512:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
                _check_python_bin(repository_ctx, python_bin)
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
                auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
        File "C:/users/albert.wang/_bazel_albert.wang/mwjrihxt/external/org_tensorflow/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
                fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:\Users\albert.wang\AppData\Local\Programs\Python\Python310\Python.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 6.830s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (42 packages loaded, 9 targets configured)

**Comment by merthankavak** [comment]
Any solutions

**Comment by daehwankim112** [comment]
I am using
Mediapipe 0.10.15
VC 14.40.33810
Windows SDK 10.0.26100.0
Tested with Python 3.6 and 3.9

The "python path" --verison gets recognized but when I use exactly same path for building mediapipe, it does not work. This is command I am using to build hello world example.

`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Users//username//AppData//Local//Programs//Python//Python39//python.exe" mediapipe/examples/desktop/hello_world --verbose_failures`

I am trying something. I will let you know if I fix this issue.

**Comment by kewell-tsao** [comment]
I had the same problem.
After trying, I set the following environment variables to solve this problem.
`set BAZEL_SH=C:\msys64\usr\bin\bash.exe`

**Comment by akashvverma1995** [comment]
Hi @u431535,

Please try latest version of MediaPipe.
