### ISSUE TITLE
TypeError: Cannot convert "full" to double

### ISSUE THREAD

**Issue by akanshSirohi** [google/mediapipe#4632]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Windows 11

### Browser and version if the issue happens on browser

All Browsers

### Programming Language and version

JavaScript

### MediaPipe version

0.4

### Solution

Handpose

### Describe the actual behavior

```shell
Showing error!
```

### Describe the expected behaviour

```shell
It should work properly
```

### Standalone code/steps you may have used to try to get what you need

```shell
HTML Code (index.html)


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hand Pose - Tensorflow</title>
    <!-- Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils@0.1/camera_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils@0.2/drawing_utils.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/hands.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
</head>
<body>
    <div class="text-center">
        <video autoplay="true" id="video" autoplay playsinline webkit-playsinline muted hidden></video>
        <canvas id="previewCanvas"></canvas>
    </div>
    <script src="script.js"></script>
</body>
</html>    


script.js
```js
const video = document.querySelector("#video");
const canvaselement = document.querySelector('#previewCanvas');
const ctx = canvaselement.getContext('2d');

let camera;

function onResultsHands(results) {
    console.log(results);
}

const loadModel = () => {
    modal_loading = true;
    hands = new Hands({
        locateFile: (file) => {
            return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/${file}`;
        }
    });
    hands.setOptions({
        maxNumHands: 1,
        minDetectionConfidence: 0.8,
        minTrackingConfidence: 0.9,
        modelComplexity: 'full',
        selfieMode: false,
    });
    hands.onResults(onResultsHands);
    camera.start();
};

$(document).ready(function() {
    video.width = window.innerWidth;
    video.height = video.width * aspect_ratio;
    canvaselement.width = video.width;
    canvaselement.height = video.height;
    camera = new Camera(video, {
        onFrame: async () => {
          await hands.send({image: video});
        },
        facingMode: 'environment', // user
        width: canvaselement.width,
        height: canvaselement.height
    });
    loadModel();
});
```
```


### Other info / Complete Logs

```shell
Using the Handpose Pretrained Model in the browser, 0.1 version was working fine but when I am trying to elevate the version to 0.4 then this error is occuring.


‣ Uncaught (in promise) TypeError: Cannot convert "full" to double  (hands_solution_simd_wasm_bin.js:9)
    at Object.towireType (hands_solution_simd_wasm_bin.js:9:139736) 
    at Object.write (hands_solution_simd_wasm_bin.js:9:115661) 
    at Object.toWire Type (hands_solution_simd_wasm_bin.js:9:116060) 
    at ClassHandle.push_back (hands_solution_simd_wasm_bin.js:9:131839) 
    at ra.i (hands.min.js:83:356) 
    at ua (hands.min.js:20:299) 
    at va.next (hands.min.js:21:91) 
    at b (hands.min.js:21:330)
```

**Comment by akanshSirohi** [comment]
@kuaashish Please take a look at this issue, and also inform me if you know any quick fix for it.

**Comment by schmidt-sebastian** [comment]
We are unfortunately not able to prioritize bug fixes in our legacy solutions codebase right now. Please use https://developers.google.com/mediapipe/solutions/vision/hand_landmarker

**Comment by akanshSirohi** [comment]
@schmidt-sebastian I am trying to use the code from here also, took the reference from this link: https://codepen.io/mediapipe-preview/pen/gOKBGPN
Everything seems working fine but when I called `handLandmarker.detectForVideo(video);` from Camera onFrame then I got this error:

![image](https://github.com/google/mediapipe/assets/34837239/f0fc32f6-4f52-4207-a525-a6c28ee83f22)
