### ISSUE TITLE
Pose Landmark Detection Fails at Prediction

### ISSUE THREAD

**Issue by shbhmbnsl1** [google/mediapipe#4699]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

MacOS 13.0

### Browser and version if the issue happens on browser

Google Chrome, Firefox, and all other browsers

### Programming Language and version

TS

### MediaPipe version

latest

### Solution

Pose Landmark detection

### Describe the actual behavior

```shell
Error message is thrown
```

### Describe the expected behaviour

```shell
No error message is thrown and pose landmarks are detected
```

### Standalone code/steps you may have used to try to get what you need

```shell
import { PoseLandmarker, FilesetResolver, PoseLandmarkerOptions } from "@mediapipe/tasks-vision";

const poseOptions: PoseLandmarkerOptions = {
  baseOptions: {
    modelAssetPath: `https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task`,
    delegate: "GPU"
  },
  numPoses: 1,
  runningMode: "VIDEO",
};

...

const filesetResolver = await FilesetResolver.forVisionTasks("https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm");
poseLandmarker = await PoseLandmarker.createFromOptions(filesetResolver, poseOptions);

...
// here this line is called every video frame for prediction and error is thrown
const poseLandmarkerResult = poseLandmarker.detectForVideo(video, nowInMs);
```

### Other info / Complete Logs

```shell
Encountered multiple errors: Graph has errors: 
Packet timestamp mismatch on a calculator receiving from stream "free_memory". Current minimum expected timestamp is 1 but received 0. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.; Adding proto packet of type mediapipe.NormalizedRect to stream norm_rect was not ok, CalculatorGraph::Run() failed in Run: 
Packet timestamp mismatch on a calculator receiving from stream "free_memory". Current minimum expected timestamp is 1 but received 0. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.; WaitUntilIdle failed
Error: Encountered multiple errors: Graph has errors: 
Packet timestamp mismatch on a calculator receiving from stream "free_memory". Current minimum expected timestamp is 1 but received 0. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.; Adding proto packet of type mediapipe.NormalizedRect to stream norm_rect was not ok, CalculatorGraph::Run() failed in Run: 
Packet timestamp mismatch on a calculator receiving from stream "free_memory". Current minimum expected timestamp is 1 but received 0. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.; WaitUntilIdle failed
    at _.handleErrors (http://localhost:3000/static/js/bundle.js:78134:24)
    at _.finishProcessing (http://localhost:3000/static/js/bundle.js:78122:47)
    at _.process (http://localhost:3000/static/js/bundle.js:78261:116)
    at _.processVideoData (http://localhost:3000/static/js/bundle.js:78231:10)
    at _.detectForVideo (http://localhost:3000/static/js/bundle.js:92490:92)
    at predict (http://localhost:3000/static/js/bundle.js:200:51)
```

**Comment by kuaashish** [comment]
@shbhmbnsl1,

Could you please go though the above comment and let us know the status of the issue. Thank you

**Comment by shbhmbnsl1** [comment]
@tyrmullen  

Thank you so much for your prompt reply. When I used `const nowInMs = performance.now();` it worked but my previous way of creating the nowInMs value was `const nowInMs = Date.now()` and that was working for the FaceLandmarker and HandLandmarker so I was using that only for PoseLandmarker also. 

But thank you again because now I understand the difference between performance.now() vs Date.now() after some reading from Stackoverflow answers and performance.now() is the right way for me here.
