### ISSUE TITLE
Object detection task on custom model failed on Raspberry Pi

### ISSUE THREAD

**Issue by robodhhb** [google/mediapipe#4744]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

PiOS Bullseye 64bit

### MediaPipe Tasks SDK version

0.10.3

### Task name (e.g. Image classification, Gesture recognition etc.)

Object detection on MOBILENET_V2_I320 model

### Programming Language and version (e.g. C++, Python, Java)

Python 3.9.2, Thonny 4.0.1, pip 23.2.1 

### Describe the actual behavior

```shell
Runtime error on line:
detection_result = detector.detect(mp_image)

Output of code execution:
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20230831 14:03:05.674636  1290 calculator_graph.cc:853] INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32
Traceback (most recent call last):
  File "/home/pi/Documents/10_TryAndLearn/MediaPipeTest1.py", line 21, in <module>
    detection_result = detector.detect(mp_image)
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 271, in detect
    output_packets = self._process_image_data({
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 95, in _process_image_data
    return self._runner.process(inputs)
RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/10_TryAndLearn/MediaPipeTest1.py", line 22, in <module>
    print(detection_result)
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 226, in __exit__
    self.close()
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 209, in close
    self._runner.close()
RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32
>>>
```

### Describe the expected behaviour

```shell
Calculate the detection_result (inference)
```

### Standalone code/steps you may have used to try to get what you need

```shell
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

model_path = 'model_int8.tflite' #Custom model, post-training quantization for int8 with
                                 # media pipe modelmaker on Github, 320x320 pixel
                                 # MOBILENET_V2_I320

BaseOptions = mp.tasks.BaseOptions
ObjectDetector = mp.tasks.vision.ObjectDetector
ObjectDetectorOptions = mp.tasks.vision.ObjectDetectorOptions
VisionRunningMode = mp.tasks.vision.RunningMode

options = ObjectDetectorOptions(
    base_options=BaseOptions(model_asset_path= model_path),
    max_results=5,
    running_mode=VisionRunningMode.IMAGE)

with ObjectDetector.create_from_options(options) as detector:
    # Load the input image from an image file.
    mp_image = mp.Image.create_from_file('a.jpg')
    # Perform object detection on the provided single image.
    detection_result = detector.detect(mp_image)
    print(detection_result)
```

**Comment by kuaashish** [comment]
@robodhhb,

Could you kindly construct an **Object Detection system for Raspberry Pi** by following the documentation provided [here](https://developers.googleblog.com/2023/08/mediapipe-for-raspberry-pi-and-ios.html)? 

Please ensure to make any requisite **adjustments according to your specific requirements** and kindly inform us if you encounter similar behaviour. Thank you

**Comment by robodhhb** [comment]
@kuaashish 
I did the following:
- New SD-Card with fresh PiOS Bullseye 64 bit
- python -m pip install --upgrade pip 
  Version now: 23.2.1
- sudo apt update and  sudo apt full-upgrade
- python -m pip install mediapipe
  Version is 0.10.3

Then I adapted my code following the code you mentioned. 
With the model efficientdet_lite0.tflite from the example it works. 
But with my custom model created with Media Pipe Model Maker I get the following error. The problem is the model! What went wrong during the training? It shows no error there.

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20230901 12:50:22.977418  2786 calculator_graph.cc:853] INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32
Traceback (most recent call last):
  File "/home/pi/Documents/10_TryAndLearn/10_MediaPipe/firstTestMP.py", line 20, in <module>
    detection_result = detector.detect(mp_image)
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 271, in detect
    output_packets = self._process_image_data({
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 95, in _process_image_data
    return self._runner.process(inputs)
RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32

**Comment by kuaashish** [comment]
Hi @robodhhb,

Could you please confirm whether you are still looking for resolution on this issue, or if it has been resolved from your end?

Thank you!

**Comment by robodhhb** [comment]
@kuaashish 
I am still looking for resolution.

**Comment by kuaashish** [comment]
Hi @joezoug,

Could you please look into this issue? Thank you

**Comment by joezoug** [comment]
Hi @robodhhb,

Did you export the model with any quantization? And can you provide the model tflite file so we can take a look?

**Comment by robodhhb** [comment]
Hi @joezoug,
yes, I exported the model with int8 quantization. Today I trained the model again and ran it on Raspberry Pi 4 with PiOS Bullseye (64bit). Again I get errors at inference time:

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2023-10-25 10:37:36.147876
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20231025 10:37:36.328037  2948 calculator_graph.cc:853] INTERNAL: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32
Traceback (most recent call last):
  File "/home/pi/Documents/10_TryAndLearn/10_MediaPipe/testMediaPipe.py", line 28, in <module>
    detection_result = detector.detect(mp_image)
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 271, in detect
    output_packets = self._process_image_data({
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 95, in _process_image_data
    return self._runner.process(inputs)
RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/10_TryAndLearn/10_MediaPipe/testMediaPipe.py", line 33, in <module>
    print(detection_result1)
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 226, in __exit__
    self.close()
  File "/home/pi/.local/lib/python3.9/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 209, in close
    self._runner.close()
RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Process() for node "mediapipe_tasks_vision_objectdetectorgraph__mediapipe_tasks_components_processors_detectionpostprocessinggraph__TensorsToDetectionsCalculator" failed: ; RET_CHECK failure (mediapipe/calculators/tensor/tensors_to_detections_calculator.cc:307) tensor.element_type() == Tensor::ElementType::kFloat32


I attach a zip file with the jupyter notebook for training and the resulted int8 quantized model.
[files4you.zip](https://github.com/google/mediapipe/files/13163466/files4you.zip)
Thanks for analysing it!! :-)

**Comment by robodhhb** [comment]
Hi @kuaashish,
thanks for the info. Would be nice if you add some hints in the API documentation that a quantized model is not supported. Hope it comes soon, as on Raspberry Pi only a quantized model is fast enough.

**Comment by kuaashish** [comment]
Hi @robodhhb,

Currently, We do not have any documentation which refers that quantized model is not supported. However, I will bring this up to team. Thank you

**Comment by kuaashish** [comment]
Hi @robodhhb,

Quantized model support has been incorporated in the latest release v0.10.8, as outlined in the [release page](https://github.com/google/mediapipe/releases/tag/v0.10.8) under "detection postprocessing support quantized tensor." We kindly request you to test it with the most recent release and inform us if the issue persists on your end.

Thank you

**Comment by robodhhb** [comment]
Hi @kuaashish,
thanks for the good news. I tried to get the new relase but I did not get it.  My pip version is 23.3.1

python -m pip install mediapipe
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
**Requirement already satisfied: mediapipe in ./.local/lib/python3.9/site-packages (0.10.3)**
Can you help me?

**Comment by kuaashish** [comment]
Hi @robodhhb,

It appears to be a permission issue. Could you please attempt to install by running the command provided below?

`python -m pip install mediapipe --user`

Thank you

**Comment by robodhhb** [comment]
Hi @kuaashish,
I tried it but did not get the new release:
python -m pip install mediapipe --user
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
**Requirement already satisfied: mediapipe in ./.local/lib/python3.9/site-packages (0.10.3)**

**Comment by kuaashish** [comment]
Hi @joezoug,

Could you please have look into this issue. Thank you

**Comment by joezoug** [comment]
Hi @robodhhb,
We do expect performance degradation in the qat int8 model compared to the float model. It is a tradeoff between size/latency vs accuracy. You can try to tune hyperparameters for the quantization_aware_training step to see if there is any additional improvement. It may also help to tune hyperparameters for the float model before the qat step as well.

Working on the quantized object detector model is not in our team's current roadmap.

**Comment by robodhhb** [comment]
Hi @joezoug,
thanks for your infos. After retraining and improving the lighting situation on my test case the situation improved significantly. 
With the int8 qat model I get with a score_threshold of 0.55:
- fps: 4.2 to 4.5 (that is nearly ok)
- good recognition between 58 and 75%
Thank you for your help so far.

**Comment by HTerminal** [comment]
Hi, @joezoug 
Can you share what QATH parameter settings you used i am also facing the slimier issue after int8 the model accuracy goes only till 0.2 threshold. 


Regards
Hitesh
