### ISSUE TITLE
Crash when minify is true

### ISSUE THREAD

**Issue by jonathaspayface** [google/mediapipe#4806]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android

### MediaPipe Tasks SDK version

mediapipe_tasks_vision 0.10.5

### Task name (e.g. Image classification, Gesture recognition etc.)

Face Landmarker

### Programming Language and version (e.g. C++, Python, Java)

Java Kotlin

### Describe the actual behavior

App crash when the task is started. It happens when minify is true in release mode. I believe it is the Proguard configuration, but I don't find any configuration in the manual.

SO: MacOS Ventura: Version 13.4.1 (c)
Device: Samsung A01 -> Android 12
Android Studio Giraffe | 2022.3.1

### Describe the expected behaviour

Do not crash. 

### Standalone code/steps you may have used to try to get what you need

```shell
You need to compile in release mode using minify as true to reproduce the error.
```

### Other info / Complete Logs

```shell
Process: com.fortface.sample, PID: 8218
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.google.mediapipe.tasks.core.a.c(SourceFile:163)
                                                                                                    	at t7.d.a(SourceFile:169)
                                                                                                    	at i2.a.b(SourceFile:87)
                                                                                                    	at f2.a.j(Unknown Source:3385)
                                                                                                    	at com.fortface.sample.ui.fragment.AuthenticationFragment.onCreateView(SourceFile:145)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(SourceFile:20)
                                                                                                    	at androidx.fragment.app.f0.e(SourceFile:188)
                                                                                                    	at androidx.fragment.app.f0.j(SourceFile:198)
                                                                                                    	at androidx.fragment.app.FragmentManager.B(SourceFile:13)
                                                                                                    	at androidx.fragment.app.FragmentManager.V(Unknown Source:91)
                                                                                                    	at androidx.fragment.app.FragmentManager.z(SourceFile:74)
                                                                                                    	at androidx.fragment.app.FragmentManager$f.run(Unknown Source:3)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalStateException: no caller found on the stack for: g5.b
                                                                                                    	at g5.b.b(SourceFile:50)
                                                                                                    	at com.google.mediapipe.framework.Graph.<clinit>(Unknown Source:0)
                                                                                                    	at com.google.mediapipe.tasks.core.a.c(SourceFile:163) 
                                                                                                    	at t7.d.a(SourceFile:169) 
                                                                                                    	at i2.a.b(SourceFile:87) 
                                                                                                    	at f2.a.j(Unknown Source:3385) 
                                                                                                    	at com.fortface.sample.ui.fragment.AuthenticationFragment.onCreateView(SourceFile:145) 
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(SourceFile:20) 
                                                                                                    	at androidx.fragment.app.f0.e(SourceFile:188) 
                                                                                                    	at androidx.fragment.app.f0.j(SourceFile:198) 
                                                                                                    	at androidx.fragment.app.FragmentManager.B(SourceFile:13) 
                                                                                                    	at androidx.fragment.app.FragmentManager.V(Unknown Source:91) 
                                                                                                    	at androidx.fragment.app.FragmentManager.z(SourceFile:74) 
                                                                                                    	at androidx.fragment.app.FragmentManager$f.run(Unknown Source:3) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by kuaashish** [comment]
@jonathaspayface,

We are pleased to inform you that we have recently released the latest iteration of MediaPipe, version [0.10.5](https://github.com/google/mediapipe/releases/tag/v0.10.5), as previously detailed in our [official release page](https://github.com/google/mediapipe/releases/tag/v0.10.5). We kindly request your assistance in conducting a test to build a face landmark solution using this most up-to-date version. 

If you encounter any errors or issues during this process, we would greatly appreciate your prompt notification. In the event that the issue persists with the newest version, we kindly request that you provide us with the following information: your operating system, specifications of the mobile device or Android emulator you are utilising, and the version of Android Studio in use. Thank you

**Comment by jonathaspayface** [comment]
Hi, I updated the version of Mediapipe. The same error happen: 
**SO**: MacOS Ventura: Version 13.4.1 (c)
**Device**: Samsung A01 -> Android 12
Android Studio Giraffe | 2022.3.1 

`FATAL EXCEPTION: main
                                                                                                    Process: com.fortface.sample, PID: 27405
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.google.mediapipe.tasks.core.a.c(SourceFile:163)
                                                                                                    	at t7.d.a(SourceFile:169)
                                                                                                    	at i2.a.b(SourceFile:87)
                                                                                                    	at f2.a.i(Unknown Source:3613)
                                                                                                    	at com.fortface.sample.ui.fragment.AuthenticationFragment.onCreateView(SourceFile:172)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(SourceFile:20)
                                                                                                    	at androidx.fragment.app.f0.e(SourceFile:188)
                                                                                                    	at androidx.fragment.app.f0.j(SourceFile:198)
                                                                                                    	at androidx.fragment.app.FragmentManager.B(SourceFile:13)
                                                                                                    	at androidx.fragment.app.FragmentManager.V(Unknown Source:91)
                                                                                                    	at androidx.fragment.app.FragmentManager.z(SourceFile:74)
                                                                                                    	at androidx.fragment.app.FragmentManager$f.run(Unknown Source:3)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    Caused by: java.lang.IllegalStateException: no caller found on the stack for: g5.b
                                                                                                    	at g5.b.b(SourceFile:50)
                                                                                                    	at com.google.mediapipe.framework.Graph.<clinit>(Unknown Source:0)
                                                                                                    	at com.google.mediapipe.tasks.core.a.c(SourceFile:163) 
                                                                                                    	at t7.d.a(SourceFile:169) 
                                                                                                    	at i2.a.b(SourceFile:87) 
                                                                                                    	at f2.a.i(Unknown Source:3613) 
                                                                                                    	at com.fortface.sample.ui.fragment.AuthenticationFragment.onCreateView(SourceFile:172) 
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(SourceFile:20) 
                                                                                                    	at androidx.fragment.app.f0.e(SourceFile:188) 
                                                                                                    	at androidx.fragment.app.f0.j(SourceFile:198) 
                                                                                                    	at androidx.fragment.app.FragmentManager.B(SourceFile:13) 
                                                                                                    	at androidx.fragment.app.FragmentManager.V(Unknown Source:91) 
                                                                                                    	at androidx.fragment.app.FragmentManager.z(SourceFile:74) 
                                                                                                    	at androidx.fragment.app.FragmentManager$f.run(Unknown Source:3) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) `

**Comment by kuaashish** [comment]
@jonathaspayface,

Thank you for reporting this. We have received confirmation of the crash report on the same device, and we are actively working on a solution for it. Meanwhile, we suggest that you please consider using an older version for these devices instead.

**Comment by rijalmyd** [comment]
@kuaashish I have the same issues. I have changed the task vision from 0.10.0 until 0.20230731, but the problem still occurred.

`Caused by java.lang.IllegalStateException: no caller found on the stack for: z8.c
       at com.google.common.flogger.backend.system.StackBasedCallerFinder.findLoggingClass(StackBasedCallerFinder.java:68)
       at com.google.common.flogger.FluentLogger.forEnclosingClass(FluentLogger.java:68)
       at com.google.mediapipe.framework.Graph.<clinit>(Graph.java)
       at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:165)
       at com.google.mediapipe.tasks.vision.objectdetector.ObjectDetector.createFromOptions(ObjectDetector.java:97)
       at unsiq.mtqmn23.jadda.presentation.screen.tajweeddetect.objectdetector.ObjectDetectorHelper.setupObjectDetector(ObjectDetectorHelper.java:146)
       at unsiq.mtqmn23.jadda.presentation.screen.tajweeddetect.objectdetector.ObjectDetectorHelper.<init>(ObjectDetectorHelper.java:1)
       at unsiq.mtqmn23.jadda.presentation.screen.tajweeddetect.objectdetector.ObjectDetectorHelper.<init>(ObjectDetectorHelper.java:2)
       at unsiq.mtqmn23.jadda.presentation.screen.tajweeddetect.TajweedDetectScreenKt$CameraView$4$1$1.invoke$lambda$2$lambda$1(TajweedDetectScreen.kt:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`

**Comment by rijalmyd** [comment]
@kuaashish @jonathaspayface Now, I solved it by adding these codes in progruad-rules.pro
`
-keep public class com.google.mediapipe.** { *; }
-keep public class com.google.mediapipe.framework.Graph { *; }
-keep public class com.google.common.** { *; }
-keep public interface com.google.common.** { *; }`

**Comment by jonathaspayface** [comment]
Thanks a lot @rijalmyd. It worked for me!

@kuaashish i'm gonna close the issue!
