### ISSUE TITLE
Fail to fetch bazel_skylib following your #3 instruction on MacOS Catalina

### ISSUE THREAD

**Issue by 87003697** [google/mediapipe#483]
Hi, developer! Looks like I got the same problem as [#19](https://github.com/google/mediapipe/issues/19) and [#3](https://github.com/google/mediapipe/issues/3#issuecomment-506926022) did when I'm gonna run Hand Tracking Demo with Webcam(CPU) following your Markdown Files. When I run this code 
```
$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
```
It returns 
```
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
```
```
ERROR: no such package '@bazel_skylib//lib': java.io.IOException: 
Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
```
```
ERROR: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
```
After reading your answer to [#3](https://github.com/google/mediapipe/issues/3#issuecomment-506926022), I modified your cmd to meet my need, which is
```
$ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
  --distdir=./bazel_skylib/ \
  --repository_cache=./bazel_skylib/ \
  --keep_going \
mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
```
Take note that the sub directory `bazel_skylib` is where  I downloaded, saved and tarred ( I mean decompress) your repo [bazel-skylib.0.8.0.tar.gz](https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz).
This time what printed is below
```
INFO: Writing tracer profile to '/private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/command.profile.gz'
INFO: Call stack for the definition of repository 'bazel_skylib' which is a http_archive (rule definition at /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /Users/zhiyuanma/Desktop/action_detection/mediapipe/WORKSPACE:6:1
WARNING: Download from https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'bazel_skylib':
   java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
ERROR: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2841)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
	at java.base/java.lang.Thread.run(Unknown Source)

INFO: Elapsed time: 57.719s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2841)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.IllegalStateException: no such package '@bazel_skylib//lib': java.io.IOException: Error downloading [https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz] to /private/var/tmp/_bazel_zhiyuanma/79a8e7d79be2c406b0c21b61381c7456/external/bazel_skylib/bazel-skylib.0.8.0.tar.gz: connect timed out
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.devtools.build.lib.skyframe.SkyframeExecutor.loadTargetPatterns(SkyframeExecutor.java:2841)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.evaluateTargetPatterns(AnalysisPhaseRunner.java:170)
	at com.google.devtools.build.lib.buildtool.AnalysisPhaseRunner.execute(AnalysisPhaseRunner.java:79)
	at com.google.devtools.build.lib.buildtool.BuildTool.buildTargets(BuildTool.java:141)
	at com.google.devtools.build.lib.buildtool.BuildTool.processRequest(BuildTool.java:268)
	at com.google.devtools.build.lib.runtime.commands.BuildCommand.exec(BuildCommand.java:99)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:540)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:204)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:596)
	at com.google.devtools.build.lib.server.GrpcServerImpl.lambda$run$2(GrpcServerImpl.java:647)
FAILED: Build did NOT complete successfully (0 packages loaded)
(tftf) zhiyuanma@ZhiyuanMas-MacBook-Pro mediapipe % $ bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 \
  --distdir=./bazel_skylib/ \
  --repository_cache=./bazel_skylib/ \
  --keep_going \
mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
```
So I don't know what's going wrong. Maybe I specified a wrong path to my caches package? Or in fact, I got blocked in the next step?
BTW, I found so many Chinese workers worrying about the network. Great Firewall is so TROUBLESOME!

**Comment by 87003697** [comment]
In addition, I've tried this cmd with a VPN on and off, but there's no difference. So I'm sort of feeling that the Wall blocks it no matter if I use VPN. I'm from Shandong Province, China.

**Comment by teafff** [comment]
我在尝试helloworld的例子的时候也有相关问题。在fetching：@org_tensorflow的会出错 请问有什么好的方案解决吗

**Comment by jiuqiant** [comment]
See https://github.com/google/mediapipe/issues/581#issuecomment-610356857

**Comment by EricHuiK** [comment]
download file to local,  such as  /home/xxx/xxx/ab.lib
modify  WORKSPACE  urls = [
        "http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz"]  to urls=[" /home/xxx/xxx/ab.lib"]

**Comment by 87003697** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
