### ISSUE TITLE
Build error  An error occurred during the fetch of repository 'npm':

### ISSUE THREAD

**Issue by zhaoqilong3031** [google/mediapipe#4844]
### OS Platform and Distribution

mac

### Programming Language and version

java

### MediaPipe version

0.91

### Android AAR (if android)

None

### Describe the problem

An error occurred during the fetch of repository 'npm':

### Complete Logs

```shell
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lex/ba6251f572cb2698d6ed74e3d9836e55/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 866, column 40, in _yarn_install_impl
		yarn_version = _detect_yarn_version(repository_ctx, yarn_cmd)
	File "/private/var/tmp/_bazel_lex/ba6251f572cb2698d6ed74e3d9836e55/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 844, column 13, in _detect_yarn_version
		fail("yarn --version failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn --version failed:  (/private/var/tmp/_bazel_lex/ba6251f572cb2698d6ed74e3d9836e55/external/nodejs_darwin_amd64/bin/nodejs/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
)
ERROR: /Users/lex/mediapipe/WORKSPACE:560:13: fetching yarn_install rule //external:npm: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_lex/ba6251f572cb2698d6ed74e3d9836e55/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 866, column 40, in _yarn_install_impl
		yarn_version = _detect_yarn_version(repository_ctx, yarn_cmd)
	File "/private/var/tmp/_bazel_lex/ba6251f572cb2698d6ed74e3d9836e55/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 844, column 13, in _detect_yarn_version
		fail("yarn --version failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn --version failed:  (/private/var/tmp/_bazel_lex/ba6251f572cb2698d6ed74e3d9836e55/external/nodejs_darwin_amd64/bin/nodejs/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by kuaashish** [comment]
@zhaoqilong3031,

Upon reviewing the issue description, it has come to our attention that you are currently utilising MediaPipe version 0.9.1. We recommend upgrading to the latest version, namely MediaPipe [0.10.5](https://github.com/google/mediapipe/releases/tag/v0.10.5), for optimal performance and compatibility.

Furthermore, should the issue persist, kindly provide us with the following details:

- A comprehensive overview of the steps taken, as outlined in the documentation.

- Clarification on whether you are using an Intel-based macOS or a Silicon chip-based macOS.

Thank you!
