### ISSUE TITLE
How to set GENERATED_IMAGE_WIDTH and GENERATED_IMAGE_HEIGHT using ImageGenerator API?

### ISSUE THREAD

**Issue by Kllin0219** [google/mediapipe#4857]
Crash when using default 512x512 size.

FATAL EXCEPTION: DefaultDispatcher-worker-2
 Process: com.google.mediapipe.examples.imagegeneration, PID: 12704
com.google.mediapipe.framework.MediaPipeException: internal: CalculatorGraph::Run() failed: 
                                                                                                    Calculator::Open() for node "mediapipe_tasks_vision_image_generator_imagegeneratorgraph__StableDiffusionIterateCalculator" failed: ; RET_CHECK failure (mediapipe/tasks/cc/vision/image_generator/diffuser/stable_diffusion_iterate_calculator.cc:237) context_
                                                                                                    	at com.google.mediapipe.framework.Graph.nativeWaitUntilGraphIdle(Native Method)
                                                                                                    	at com.google.mediapipe.framework.Graph.waitUntilGraphIdle(Graph.java:464)
                                                                                                    	at com.google.mediapipe.tasks.core.TaskRunner.create(TaskRunner.java:74)
                                                                                                    	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.createFromOptions(ImageGenerator.java:167)
                                                                                                    	at com.google.mediapipe.tasks.vision.imagegenerator.ImageGenerator.createFromOptions(ImageGenerator.java:96)
                                                                                                    	at com.google.mediapipe.examples.imagegeneration.ImageGenerationHelper.initializeImageGenerator(ImageGenerationHelper.kt:32)
                                                                                                    	at com.google.mediapipe.examples.imagegeneration.diffusion.DiffusionViewModel$initializeImageGenerator$3.invokeSuspend(DiffusionViewModel.kt:66)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5ee3f6f, Dispatchers.Default]

**Comment by kuaashish** [comment]
The image generator is based on stable diffusion model of runwayml/stable-diffusion-v1-5 as provided in the doc [here](https://developers.google.com/mediapipe/solutions/vision/image_generator/index#foundation_models). The runwayml model is fine tuned for resolution 512x512 as provided in the model card for runwayml/stable-diffusion model [here](https://huggingface.co/runwayml/stable-diffusion-v1-5)

**Comment by kuaashish** [comment]
@Kllin0219,

The image generator relies on the stable diffusion model of RunwayML version 1.5, documented [here](https://developers.google.com/mediapipe/solutions/vision/image_generator/index#foundation_models). The RunwayML model has been specifically fine-tuned for a resolution of 512x512, as detailed in the model card for the RunwayML stable diffusion model [here](https://huggingface.co/runwayml/stable-diffusion-v1-5). Regrettably, configuring customized output image width and height is presently not feasible.

**Comment by Maitreya25** [comment]
Hey @kuaashish, I can reproduce the same crash. What's the fix for it then? This causes the entire sample app provided by google to fail. One must expect a sample app for the API to work out of the box

**Comment by kuaashish** [comment]
Hi @Maitreya25,

Could you kindly provide us with comprehensive details, including the steps you are following from the documentation and the mobile device where the crash is occurring? This information will assist us in reproducing and comprehending the issue more effectively from our end. Thank you

**Comment by Kllin0219** [comment]
@kuaashish  The previous use of the preview app's demo version allowed me to configure the output size (width and height). When the default value was set to 512, it caused a crash, but it worked fine when set to 400. How can I configure the output size (width and height) using the current API?
![image](https://i.imgur.com/RgRBxOt.jpeg)

**Comment by Maitreya25** [comment]
> Hi @Maitreya25,
> 
> Could you kindly provide us with comprehensive details, including the steps you are following from the documentation and the mobile device where the crash is occurring? This information will assist us in reproducing and comprehending the issue more effectively from our end. Thank you

All I did was simply build the image generator app from media pipe examples. Converted a model with the script and ran the app.

**Comment by Maitreya25** [comment]
> @kuaashish The previous use of the preview app's demo version allowed me to configure the output size (width and height). When the default value was set to 512, it caused a crash, but it worked fine when set to 400. How can I configure the output size (width and height) using the current API? ![image](https://camo.githubusercontent.com/dc38d67b2aea0e09950b23fbadd0e5238c5af762d84bb8a9f1f58910cdbead13/68747470733a2f2f692e696d6775722e636f6d2f52675242784f742e6a706567)

Can you share this version? The source code funny enough has a string to let you set the output size but they didn't add an option!

**Comment by kuaashish** [comment]
Hi @khanhlvg,

Can you adjust the width and height of generated images using the Image Generator API, which we've recently made open source?  Thank you!

**Comment by Kllin0219** [comment]
Is there any update on this issue?

**Comment by Kllin0219** [comment]
@khanhlvg  Is there any update on this issue?

**Comment by khanhlvg** [comment]
We removed the feature to set the size of the output image because anything other than 512*512 will result in suboptimal image quality. If you need anything larger, consider combining the model with a super resolution model.
