### ISSUE TITLE
ByteBufferImageBuilder func throws Unhandled Exception

### ISSUE THREAD

**Issue by cjl84914** [google/mediapipe#4890]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

android

### MediaPipe version

 implementation 'com.google.mediapipe:tasks-vision:latest.release'

### Solution

pose

### Programming Language and version

kotlin

### Describe the actual behavior

val mpImage = ByteBufferImageBuilder(buffer, width.toInt(), height.toInt() , MPImage.IMAGE_FORMAT_YUV_420_888).build();

### Describe the expected behaviour

code run success

### Standalone code/steps you may have used to try to get what you need

```shell
I try to run code:
val mpImage = ByteBufferImageBuilder(buffer, width.toInt(), height.toInt() , MPImage.IMAGE_FORMAT_YUV_420_888).build();
but throw exception.
```

### Other info / Complete Logs

```shell
Unhandled Exception: PlatformException(UnsupportedOperationException, java.lang.UnsupportedOperationException: Unsupported MediaPipe Image image format: 7, Cause: null, Stacktrace: java.lang.UnsupportedOperationException: Unsupported MediaPipe Image image format: 7
at com.google.mediapipe.framework.AndroidPacketCreator.createImage(AndroidPacketCreator.java:90)
at com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.sendLiveStreamData(BaseVisionTaskApi.java:139)
at com.google.mediapipe.tasks.vision.poselandmarker.PoseLandmarker.detectAsync(PoseLandmarker.java:370)
at com.google.mediapipe.tasks.vision.poselandmarker.PoseLandmarker.detectAsync(PoseLandmarker.java:340)
at com.example.mediapipe_task_vision.helper.PoseLandmarkerHelper.detectAsync(PoseLandmarkerHelper.kt:204)
at com.example.mediapipe_task_vision.impl.PoseLandmarkerApiImpl.detectLiveStream(PoseLankmarkerApiImpl.kt:162)
at PoseLandmarkerApi$Companion.setUp$lambda-9$lambda-8(PoseLandmarkerApi.kt:108)
at PoseLandmarkerApi$Companion.$r8$lambda$o0GS7pFDzKkKMl9tdrUuLgX2Nm0(Unknown Source:0)
at PoseLandmarkerApi$Companion$$ExternalSyntheticLambda2.onMessage(Unknown Source:2)
at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:219)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:967)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:206)
at android.os.Looper.loop(Looper.java:296)
at android.app.ActivityThread.main(ActivityThread.java:9064)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:968)
, null)
```

**Comment by kuaashish** [comment]
Hi @cjl84914,

Kindly test with alternative MPImage formats, specifically IMAGE_FORMAT_RGB or IMAGE_FORMAT_RGBA as outlined in the [documentation](https://developers.google.com/mediapipe/api/solutions/java/com/google/mediapipe/framework/image/MPImage#constants_1). Please inform us if the observed behaviour remains consistent.

Thank you
