### ISSUE TITLE
How to send parameters to  calculator

### ISSUE THREAD

**Issue by zhaoqilong3031** [google/mediapipe#4898]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

android

### MediaPipe Tasks SDK version

MediaPipe 0.9.2.1

### Task name (e.g. Image classification, Gesture recognition etc.)

face

### Programming Language and version (e.g. C++, Python, Java)

java

### Describe the actual behavior

t

### Describe the expected behaviour

t

### Standalone code/steps you may have used to try to get what you need

```shell
private class LiveHandler implements FrameProcessor.OnWillAddFrameListener{
        @Override
        public void onWillAddFrame(long timestamp){
            Packet packet = processor.getPacketCreator().createString("20,30,20");
            processor.getGraph().addConsumablePacketToInputStream("screen_color",
                    packet,  timestamp);
            packet.release();
        }
    }
```
Exception occurs in this way 
``` 2023-10-20 14:01:25.719 29125-29263/com.example.face E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.example.face, PID: 29125
    com.google.mediapipe.framework.MediaPipeException: internal: 
        at com.google.mediapipe.framework.Graph.nativeMovePacketToInputStream(Native Method)
        at com.google.mediapipe.framework.Graph.addConsumablePacketToInputStream(Graph.java:407)
        at com.example.face.TestMActivity$LiveHandler.onWillAddFrame(TestMActivity.java:99)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:444)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:485)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread 
```

pbtxt file
```
input_stream: "input_video"

# Max number of faces to detect/process. (int)
input_side_packet: "num_faces"

input_stream: "screen_rgb"

input_stream: "back_image"
# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"
# Collection of detected/processed faces, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "multi_face_landmarks"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}
 

#
node {
   calculator: "GpuBufferToImageFrameCalculator"
   input_stream: "throttled_input_video"
   output_stream: "throttled_input_video_cpu"
}

node {
  calculator: "ReplaceCalculator"
  input_stream: "IMAGE:throttled_input_video_cpu"
  #input_stream: "BACK_IMAGE:back_image"
  input_stream: "SCREEN_RGB:screen_rgb"

  output_stream: "IMAGE:output_video_cpu"
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "output_video_cpu"

  output_stream: "output_video"
}
```

ReplaceCalculator.cc
```


// imports
#include <cmath>
#include <vector>

#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/port/ret_check.h"
#include "mediapipe/framework/port/status.h"
#include "mediapipe/framework/formats/image_frame.h"
#include "mediapipe/framework/formats/image_frame_opencv.h"
#include "mediapipe/framework/port/opencv_core_inc.h"
#include "mediapipe/framework/port/opencv_imgproc_inc.h"
#include "mediapipe/util/color.pb.h"

//#include <opencv2/mcc.hpp>
/*
node {
calculator:"ReplaceCalculator"
input_stream: "IMAGE"
input_stream: "MASK_FULL"
input_stream: "BACK_IMAGE"
output_stream:"IMAGE"

}
*/


//calculator ColoSlider
namespace mediapipe {
constexpr char kImageFrameTag[] = "IMAGE";
constexpr char MaskFullTag[] = "MASK_FULL";
constexpr char BackImageTag[] = "BACK_IMAGE";

constexpr char ScreenColorTag[] = "SCREEN_COLOR";
constexpr char ExtractStatusTag[] = "EXTRACT_STATUS";
 
class ReplaceCalculator : public CalculatorBase {
public:

    ReplaceCalculator() = default;
    ~ReplaceCalculator() override = default;
    //ReplaceCalculator() : initialized_(false){}

  static ::mediapipe::Status GetContract(CalculatorContract* cc);

  ::mediapipe::Status Open(CalculatorContext* cc) override;
  ::mediapipe::Status Process(CalculatorContext* cc) override;
  void make_array(int r,int g,int b,std::array<int,3>* out);
  
  std::vector<int> extractFacePoint;
  };

  REGISTER_CALCULATOR(ReplaceCalculator);


    //static
    ::mediapipe::Status ReplaceCalculator::GetContract (CalculatorContract *cc){

    RET_CHECK(cc->Inputs().HasTag(kImageFrameTag));

    if (cc->Inputs().HasTag(kImageFrameTag)) {
      cc->Inputs().Tag(kImageFrameTag).Set<ImageFrame>();
    }
    //if (cc->Inputs().HasTag(BackImageTag)) {
    //  cc->Inputs().Tag(BackImageTag).Set<ImageFrame>();
    //}
    if (cc->Inputs().HasTag("SCREEN_RGB")){
     cc->Inputs().Tag("SCREEN_RGB").Set<std::string>();
    }

    //---output
    
    if (cc->Outputs().HasTag(kImageFrameTag)){
     // cc->Outputs().Tag(FaceColorTag).Set<std::array<int,3>>();
      cc->Outputs().Tag(kImageFrameTag).Set<ImageFrame>();
    }

    return ::mediapipe::OkStatus();

    }

    ::mediapipe::Status ReplaceCalculator::Open(CalculatorContext* cc) {
      cc->SetOffset(TimestampDiff(0));
      return ::mediapipe::OkStatus();
    }

  ::mediapipe::Status ReplaceCalculator::Process(CalculatorContext* cc) {
    LOG(INFO) << "ml_replace" << " be" ;
    if (cc->Inputs().Tag(kImageFrameTag).IsEmpty()) {
         LOG(INFO) << "ml_replace" << " test2" ;
        cc->Outputs()
        .Tag(kImageFrameTag)
        .AddPacket(cc->Inputs().Tag(kImageFrameTag).Value());
         return absl::OkStatus();
    } else {
         LOG(INFO) << "ml_replace" << " test1" ;
    }
    cc->Outputs().Tag(kImageFrameTag).AddPacket(cc->Inputs().Tag(kImageFrameTag).Value());

   // cc->Outputs()
    //  .Tag(kImageFrameTag)
     // .Add(output_img.release(), cc->InputTimestamp());

    
    return absl::OkStatus();
  }

} //end namespace
// REGISTER_CALCULATOR(::mediapipe::ReplaceCalculator);

```
```


### Other info / Complete Logs

_No response_

**Comment by kuaashish** [comment]
Hi @zhaoqilong3031,

It seems you are attempting to build the older version of MP 0.9.2.1. A more recent version, 0.10.7, is currently available, as indicated [here](https://github.com/google/mediapipe/releases/tag/v0.10.7). We advise you to build using the newer version.

Additionally, could you kindly provide a detailed outline of the steps you are following, with reference to the documentation? This information will assist us in reproducing the issue and gaining a clearer understanding of it on our end. 

Thank you

**Comment by zhaoqilong3031** [comment]
@kuaashish  Hi, my Mac cannot compile 0.10.7. I found that many people are encountering the same problem, so I chose 0.9.2.1.

I want to pass a parameter to the computing service through Android
