### ISSUE TITLE
Error initializing PortAudio when started from Windows Service

### ISSUE THREAD

**Issue by jdlvwreygers** [google/mediapipe#4916]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows Server

### Programming Language and version

Python

### MediaPipe version

0.10.7

### Solution

regular importing

### Describe the actual behavior

Mediapipe cannot be used, because the Python script crashes

### Describe the expected behaviour

I can use mediapipe even tho it's started from a Windows service

### Standalone code/steps you may have used to try to get what you need

```shell
workarounds for Windows service and non-interactive behaviour, locally modifying sounddevice code to ignore exception and continue
```

### Other info / Complete Logs

```shell
Traceback (most recent call last):  
  File "main.py", line 13, in <module>
    import mediapipe as mp
  File "[site-packages]\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.tasks.python as tasks
  File "[site-packages]\mediapipe\tasks\python\__init__.py", line 17, in <module>
    from . import audio
  File "[site-packages]\mediapipe\tasks\python\audio\__init__.py", line 18, in <module>
    import mediapipe.tasks.python.audio.audio_classifier
  File "[site-packages]\mediapipe\tasks\python\audio\audio_classifier.py", line 26, in <module>
    from mediapipe.tasks.python.audio.core import base_audio_task_api
  File "[site-packages]\mediapipe\tasks\python\audio\core\base_audio_task_api.py", line 23, in <module>
    from mediapipe.tasks.python.audio.core import audio_record
  File "[site-packages]\mediapipe\tasks\python\audio\core\audio_record.py", line 19, in <module>
    import sounddevice as sd
  File "[site-packages]\sounddevice.py", line 2871, in <module>
    _initialize()
  File "[site-packages]\sounddevice.py", line 2835, in _initialize
    _check(_lib.Pa_Initialize(), 'Error initializing PortAudio')
  File "[site-packages]\sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error initializing PortAudio: Internal PortAudio error [PaErrorCode -9986]
```

**Comment by kuaashish** [comment]
Hi @jdlvwreygers,

Kindly outline the steps you are currently implementing based on the provided documentation. Additionally, sharing the version of Windows Server you are utilising would be beneficial for us to replicate the issue and gain a clearer understanding.

Thank you

**Comment by jdlvwreygers** [comment]
The issue occurs when a Python script is started from a Windows service. Windows services only run with non-interactive rules and thus cannot access any audio or video devices from the host system. When a service starts another process, the same rules apply to that process, and thus (in this case) the started Python process cannot access audio and video devices.

_Importing mediapipe is already enough_ to cause an exception (see issue description), because mediapipe imports its dependency `sounddevice`. `sounddevice` crashes, because the libary cannot access system audio ports.

Running on Windows Server 2019.

**Comment by kuaashish** [comment]
Hi @jdlvwreygers,

I am able to successfully import "mediapipe", and "audio" using the command "from mediapipe.tasks.python import audio" as guided in documentation [here](https://developers.google.com/mediapipe/solutions/audio/audio_classifier/python#imports), In "WIndows Server 2019 Datacenter" with "Python 3.11.6 Version", Without any error, as screenshot attached below:

<img width="966" alt="Screenshot 2023-11-07 at 3 42 40 PM" src="https://github.com/google/mediapipe/assets/98159216/1013cfd2-f802-4c89-bffc-76c4b59891e9">


Could you please try once with the above configurations? If the issue persists, you can share the complete steps or code you are following. This would be helpful for us to reproduce it and gain a better understanding of the issue from our end.

Thank you

**Comment by jdlvwreygers** [comment]
It can be imported without issue when the Python interpreter is started from a regular user. But when started from a _Windows Service_ the import fails.

**Comment by ehuijzer** [comment]
I had the same issue.
If you prevent Mediapipe from importing _sounddevice_, it does work.
Based on [this](https://stackoverflow.com/a/47854417) answer I created below code.
Just place it on the top your Python script.
```
import importlib
def selective_importer(name, globals=None, locals=None, fromlist=(), level=0):
    frommodule = globals['__name__'] if globals else None
    if name=='sounddevice' and 'mediapipe.tasks.python.audio' in frommodule:
        pass
    else:
        return importlib.__import__(name, globals, locals, fromlist, level)
__builtins__.__dict__['__import__'] = selective_importer
```

**Comment by gsarathkumar92** [comment]
I'm facing the same issue in mediapipe while it was running on  windows agent, how to avoid it

**Comment by wo-yashsinghvi** [comment]
@gsarathkumar92 Start the audio services and the error would be resolved.
- Open Services (services.msc).
- Locate Windows Audio and Windows Audio Endpoint Builder, set both to Automatic, and click Start
https://jeremypedersen.com/posts/2024-07-16-ec2-windows-desktop
