### ISSUE TITLE
build "Hello world" error in windows11 bazel

### ISSUE THREAD

**Issue by SakurabaJunIntense** [google/mediapipe#4920]
### OS Platform and Distribution

Windows11

### Programming Language and version

C++

### Installed using virtualenv? pip? Conda?(if python)

anaconda

### MediaPipe version

0.10.7

### Bazel version

6.1.1

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

3.4.10 

### Describe the problem

I'm unable to run the 'Hello World' program as per the official documentation in my environment. Is there a solution to this problem?

### Complete Logs

```shell
C:\Users\poyopoyolegend\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\poyopoyolegend\\AppData\\Local\\Programs\\Python\\Python311\\python.exe" mediapipe/examples/desktop/hello_world
Starting local Bazel server and connecting to it...
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/org_tensorflow/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
INFO: Repository npm instantiated at:
  C:/users/poyopoyolegend/mediapipe/WORKSPACE:561:13: in <toplevel>
  C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:1002:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 993, column 13, in _yarn_install_impl
                fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed:  ('"YARN_IGNORE_PATH="' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ﾃ｢ﾂﾂ廬NIT_CWD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
)
ERROR: C:/users/poyopoyolegend/mediapipe/WORKSPACE:561:13: fetching yarn_install rule //external:npm: Traceback (most recent call last):
        File "C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 993, column 13, in _yarn_install_impl
                fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed:  ('"YARN_IGNORE_PATH="' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ﾃ｢ﾂﾂ廬NIT_CWD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
)
ERROR: C:/users/poyopoyolegend/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:10: //mediapipe/examples/desktop/hello_world:hello_world depends on //mediapipe/calculators/core:pass_through_calculator in repository @ which failed to fetch. no such package '@npm//@bazel/typescript': yarn_install failed:  ('"YARN_IGNORE_PATH="' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ﾃ｢ﾂﾂ廬NIT_CWD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 7.125s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (51 packages loaded, 182 targets configured)
    currently loading: mediapipe/framework ... (2 packages)

C:\Users\poyopoyolegend\mediapipe>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C:\\Users\\poyopoyolegend\\AppData\\Local\\Programs\\Python\\Python311\\python.exe" mediapipe/examples/desktop/hello_world
INFO: Build option --python_path has changed, discarding analysis cache.
INFO: Repository npm instantiated at:
  C:/users/poyopoyolegend/mediapipe/WORKSPACE:561:13: in <toplevel>
  C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/index.bzl:83:18: in yarn_install
Repository rule yarn_install defined at:
  C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:1002:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 993, column 13, in _yarn_install_impl
                fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed:  ('"YARN_IGNORE_PATH="' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ﾃ｢ﾂﾂ廬NIT_CWD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
)
ERROR: C:/users/poyopoyolegend/mediapipe/WORKSPACE:561:13: fetching yarn_install rule //external:npm: Traceback (most recent call last):
        File "C:/users/poyopoyolegend/_bazel_poyopoyolegend/osfjw7ok/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 993, column 13, in _yarn_install_impl
                fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed:  ('"YARN_IGNORE_PATH="' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ﾃ｢ﾂﾂ廬NIT_CWD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
)
ERROR: C:/users/poyopoyolegend/mediapipe/mediapipe/examples/desktop/hello_world/BUILD:19:10: //mediapipe/examples/desktop/hello_world:hello_world depends on //mediapipe/calculators/core:pass_through_calculator in repository @ which failed to fetch. no such package '@npm//@bazel/typescript': yarn_install failed:  ('"YARN_IGNORE_PATH="' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'ﾃ｢ﾂﾂ廬NIT_CWD' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
)
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.424s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 182 targets configured)
    currently loading: mediapipe/framework ... (2 packages)

C:\Users\poyopoyolegend\mediapipe>
```

**Comment by kuaashish** [comment]
Hi @SakurabaJunIntense,

Apologies for the detailed response. We have recently launched version 0.10.8 of the MP, as indicated on the [release page](https://github.com/google/mediapipe/releases/tag/v0.10.8). Kindly attempt to build in the Windows 11 again and inform us if the issue persists on your end. If you are still seeking a resolution for this matter and it has not been resolved from your perspective, please let us know.

Thank you!
