### ISSUE TITLE
error facing during hand tracking model 

### ISSUE THREAD

**Issue by chhaviakku** [google/mediapipe#5042]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

windows 10

### Python Version

3.11

### MediaPipe Model Maker version

10.9

### Task name (e.g. Image classification, Gesture recognition etc.)

hand detector

### Describe the actual behavior

it should start tracing 

### Describe the expected behaviour

Could not find the DLL(s) 'msvcp140_1.dll'

### Standalone code/steps you may have used to try to get what you need

```shell
import cv2
from cvzone.HandTrackingModule import HandDetector

cap = cv2.VideoCapture(0)
cap.set(3,1288)
cap.set(4,728)

detector = HandDetector(detectionCon=0.8)

while True:
    success, img = cap.read()
    img=detector.findHands(img)
    lmList,bboxInfo= detector.findPosition(img)
    cv2.imshow("Image",img)
    cv2.waitKey(1)
```

### Other info / Complete Logs

```shell
errors:
Traceback (most recent call last):
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\main.py", line 2, in <module>
    from cvzone.HandTrackingModule import HandDetector
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\cvzone\HandTrackingModule.py", line 8, in <module>
    import mediapipe as mp
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.tasks.python as tasks
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\mediapipe\tasks\python\__init__.py", line 17, in <module>
    from . import audio
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\mediapipe\tasks\python\audio\__init__.py", line 18, in <module>
    import mediapipe.tasks.python.audio.audio_classifier
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\mediapipe\tasks\python\audio\audio_classifier.py", line 26, in <module>
    from mediapipe.tasks.python.audio.core import base_audio_task_api
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\mediapipe\tasks\python\audio\core\base_audio_task_api.py", line 25, in <module>
    from mediapipe.tasks.python.core.optional_dependencies import doc_controls
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\mediapipe\tasks\python\core\optional_dependencies.py", line 20, in <module>
    from tensorflow.tools.docs import doc_controls
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\__init__.py", line 48, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\python\framework\ops.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 34, in <module>
    self_check.preload_check()
  File "C:\Users\DELLPC\PycharmProjects\pythonProject\venv\Lib\site-packages\tensorflow\python\platform\self_check.py", line 50, in preload_check
    raise ImportError(
ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
```

**Comment by kuaashish** [comment]
Hi @chhaviakku,

Could you kindly identify the steps you are currently following in our documentation? It appears that you may be referencing the repository mentioned [here](https://github.com/cvzone/cvzone). If you are indeed using that specific repository, we kindly request you to initiate a new issue with them and follow up for additional assistance and resolution.

Thank you
