### ISSUE TITLE
ObjectDetector.createFromOptions crashes  on Android API > 30

### ISSUE THREAD

**Issue by BoHellgren** [google/mediapipe#5134]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 11, 12, 13

### Mobile device if the issue happens on mobile device

Emulated Pixel 5

### Programming Language and version

Kotlin

### MediaPipe version

implementation 'com.google.mediapipe:tasks-vision:latest.release'

### Solution

Object Detection

### Describe the actual behavior

Fatal exception if API level > 30

### Describe the expected behaviour

To work as it does on API level 30

### Standalone code/steps you may have used to try to get what you need

```shell
D/AndroidRuntime( 7815): Shutting down VM
E/AndroidRuntime( 7815): FATAL EXCEPTION: main
E/AndroidRuntime( 7815): Process: se.ndssoft.mycamx_example, PID: 7815
E/AndroidRuntime( 7815): java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
E/AndroidRuntime( 7815):        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
E/AndroidRuntime( 7815):        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
E/AndroidRuntime( 7815):        at java.lang.System.loadLibrary(System.java:1656)
E/AndroidRuntime( 7815):        at com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.<clinit>(BaseVisionTaskApi.java:37)
E/AndroidRuntime( 7815):        at com.google.mediapipe.tasks.vision.objectdetector.ObjectDetector.createFromOptions(ObjectDetector.java:174)
E/AndroidRuntime( 7815):        at se.ndssoft.mycamx.MycamxPlugin.startCamera$lambda-5(MycamxPlugin.kt:168)

MycamxPlugin.kt:168 follows
objectDetector = ObjectDetector.createFromOptions(mContext, options)
```

### Other info / Complete Logs

```shell
My app works on a real Samsung Galaxy S10e, an emulated Pixel 5 API 30 and an emulated Nexus 5 API 30. But it crashes on Pixel 5 API 31 and Nexus 5 API 33 with the message dlopen failed: library "libmediapipe_tasks_vision_jni.so" not found
```

**Comment by BoHellgren** [comment]
The medipipe/examples/objectdetection app also crashes when run on an emulator with API > 30. It seems that x86 images are OK, but with x86_64 images mediapipe crashes because libmediapipe_tasks_vision_jni.so cannot be found.

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

It appears to be similar to the issue https://github.com/google/mediapipe/issues/5100, which has already been reported and is causing crashes on Android emulators. Could you please investigate this issue as well?

Thank you!!!

**Comment by BoHellgren** [comment]
f I look at the APK file, both debug and release, there is a
libmediapipe_tasks_vision_jni.so for x86, arm64-v8a, and arme-abiv7a, **but
not for x86_64**. Have you for some reason not compiled MediaPipe for this
architecture??

This bug stops me from releasing my new app since I cannot test it
properly. I would be grateful if you fix this asap.

Den mån 12 feb. 2024 kl 09:36 skrev kuaashish ***@***.***>:

**Comment by BoHellgren** [comment]
@schmidt-sebastian When can you look at this?

**Comment by kuaashish** [comment]
Hi @BoHellgren,

We have identified that using an emulator to run this program might not be ideal due to hardware limitations and the program's reliance on specific hardware features for optimal performance. Using a physical device is highly recommended for the best experience and functionality.

Because, Machine learning programs often require direct interaction with real-world hardware resources to function effectively. Emulators, while valuable for development and testing, may not provide the necessary hardware capabilities for this program to run smoothly.  Unfortunately, due to limitations, We can not do much about this issue. 

Thank you!!

**Comment by BoHellgren** [comment]
I agree that testing ML apps in an emulator has its problems. For example, to test your Object Detection sample program, one has to use Extended Controls to mount an image on a wall in the emulated apartment, and then use mouse and QWERASDF keys to move the emulated camera to face the wall with the photo. This does not mean that testing on emulators is useless. On the contrary, unless you have a lot of physical devices, emulators are the only way to test that your app runs on all API levels. Testing on Google Test Lab is not an alternative for ML apps, since you then don't have any control of the camera whatsoever.

I am convinced that you can make MediaPipe run on emulators if you want to, and I urge you to fix this. I think many developers will say no thanks to MediaPipe if they hear that you only support testing on real devices.

**Comment by otro678** [comment]
> Unfortunately, due to limitations, We can not do much about this issue.

@kuaashish 
When added via gradle mediapipe literally provides x86 library and does not provide x86_64. 

It would crash on a real hardware x64 device. This crash is not due emulator limitations, this is due the missing jni library, lol.

Have you even read the issue, or did you just generated your response using ChatGPT?

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Could you please have look into this issue?

Thank you!!

**Comment by aartikov** [comment]
@kuaashish 
There are real devices with x86_64 architecture, such as the ASUS ZenFone Series and Lenovo K900. Do you have plans to support these devices?

Additionally, the absence of libmediapipe_tasks_vision_jni.so for x86_64 can result in rejection when publishing to the Google Play Store. What solutions do you suggest for this issue?

**Comment by BhasmaSur** [comment]
Hi, is there any solution to this problem? if not let me know the steps to fix this, i will look into it @kuaashish @schmidt-sebastian
