### ISSUE TITLE
Attribute Error in vision.ObjectDetector

### ISSUE THREAD

**Issue by rickypang0219** [google/mediapipe#5188]
# Operating System 
macOS Sonoma 14.2.1 M1 Macbook 

# Software Version 
mediapipe: 0.10.10

# Issue 
I encounter an attribute error when I run the [object detection example code](https://developers.google.com/mediapipe/solutions/vision/object_detector#get_started) locally on my MacBook. I downloaded the python script version and then run it but it return an attribute error of the detector part. However, I run the same code on Google Colab without any problem. I have no clue on how to solve this problem. 

# Code Snippet 
```python
# STEP 1: Import the necessary modules.
import numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

# STEP 2: Create an ObjectDetector object.
base_options = python.BaseOptions(model_asset_path='efficientdet.tflite')
options = vision.ObjectDetectorOptions(base_options=base_options,
                                       score_threshold=0.5)
detector = vision.ObjectDetector.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file(IMAGE_FILE)

# STEP 4: Detect objects in the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
image_copy = np.copy(image.numpy_view())
annotated_image = visualize(image_copy, detection_result)
rgb_annotated_image = cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB)
cv2_imshow(rgb_annotated_image)
```

# Error Log 
```
Traceback (most recent call last):
  File "/Users/ricky/testcode/object_detector.py", line 128, in <module>
    detector = vision.ObjectDetector.create_from_options(options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 235, in create_from_options
    task_info.generate_graph_config(
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/mediapipe/tasks/python/core/task_info.py", line 97, in generate_graph_config
    node_config.options.CopyFrom(task_subgraph_options)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/google/protobuf/message.py", line 129, in CopyFrom
    self.MergeFrom(other_msg)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1334, in MergeFrom
    field_value = field._default_constructor(self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FieldDescriptor' object has no attribute '_default_constructor'
```

**Comment by ayushgdev** [comment]
Hello @rickypang0219 
Thanks for raising this issue. We are able to reproduce the issue at our end as well. 
We shall fix it soon.

**Comment by WillowWisp** [comment]
I also encountered this error when running `ImageSegmenter.create_from_options`.
My OS: Mac M1 Pro 14.1.1

In the meantime, `pip install mediapipe==0.10.9` works for me.

**Comment by rickypang0219** [comment]
@WillowWisp Thank you for the suggestion on installing the `0.10.9` version. I test on my Mac and it works for me too. 

![Uploading Screenshot 2024-03-05 at 13.11.12.png…]()

**Comment by JC3** [comment]
I also encounter this issue on macOS with `PoseLandmarker.create_from_options`, version 0.10.11.

Installing version 0.10.9 instead fixed the problem.

**Comment by weuceda14** [comment]
> Still present in 0.10.11.
> 
> I also encounter this issue on macOS with `PoseLandmarker.create_from_options`.
> 
> Installing version 0.10.9 instead fixed the problem.

Any way I could get some example code? Im struggling to get it running even after installing 0.10.9

**Comment by JC3** [comment]
@weuceda14 

> Any way I could get some example code? Im struggling to get it running even after installing 0.10.9

There is an example here: https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/pose_landmarker/python/%5BMediaPipe_Python_Tasks%5D_Pose_Landmarker.ipynb

There is a description of the config options towards the middle of https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python

**Comment by schmidt-sebastian** [comment]
Which version of protobuf are you using? We are still using 3.x (protobuf>=3.11,<4)

**Comment by JC3** [comment]
> Which version of protobuf are you using? We are still using 3.x (protobuf>=3.11,<4)

3.20.3

**Comment by alejamp** [comment]
@alanwilter I found a solution to this problem. Install Mediapipe 0.10.9/10/11 whatever. Then update protobuf above 4, in my case I did:
```bash
pip install protobuf==4.25.3
```

And it works great!

**Comment by alanwilter** [comment]
I can confirm what @alejamp found.
I did:
```
pip install protobuf -U
...
Successfully installed protobuf-5.26.1
```
and now it works with `mediapipe 0.10.11` on my Mac M1.

However, `poetry add protobuf` does not work because `mediapipe` is still hooked to `protobuf 3.x`:

```
mediapipe 0.10.11 requires protobuf<4,>=3.11, but you have protobuf 5.26.1 which is incompatible.
```
