### ISSUE TITLE
Need official proguard-rules.pro file for release build in Android

### ISSUE THREAD

**Issue by albus-d** [google/mediapipe#5201]
### OS Platform and Distribution

Android

### Programming Language and version

Kotlin

### MediaPipe version

0.10.10

### Android SDK and NDK versions (if android)

33

### Android AAR (if android)

No

### Describe the problem

Hi, I am developing an Android program which use com.google.mediapipe:tasks-audio. It work fine in debug mode but crash in release mode with minifyEnabled = true. I added some rule in my proguard-rules.pro but it all from other developer so it seem like not enough to prevent all crash. So can you give us official rule or guide to build an Android app in release mode with minifyEnabled = true? Thanks

### Complete Logs

```shell
Rejecting re-init on previously-failed class java.lang.Class<com.google.mediapipe.framework.Graph>: java.lang.ExceptionInInitializerError: 
                                                                                                      at com.google.mediapipe.tasks.core.a com.google.mediapipe.tasks.core.a.b(android.content.Context, oa.b, k.m) (SourceFile:-1)
                                                                                                      at ia.d ia.d.b(android.content.Context, ia.f) (SourceFile:-1)
                                                                                                      at void mb.c.<init>(android.content.Context, float, com.example.audio.services.b) (SourceFile:-1)
                                                                                                      at java.lang.Object com.example.audio.services.SignalDetectionService$initTensorFlow$1.invokeSuspend(java.lang.Object) (SourceFile:-1)
                                                                                                      at void kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(java.lang.Object) (SourceFile:-1)
                                                                                                      at void kotlinx.coroutines.internal.a.d(kotlin.coroutines.Continuation, java.lang.Object, lc.l) (SourceFile:-1)
                                                                                                      at void com.example.audio.main.listringtone.ui.e.r(lc.p, java.lang.Object, kotlin.coroutines.Continuation) (SourceFile:-1)
                                                                                                      at void kotlinx.coroutines.CoroutineStart.invoke(lc.p, java.lang.Object, kotlin.coroutines.Continuation) (SourceFile:30)
                                                                                                      at kotlinx.coroutines.k1 androidx.fragment.app.e0.F(kotlinx.coroutines.v, kotlinx.coroutines.t, lc.p, int) (SourceFile:-1)
                                                                                                      at void com.example.audio.services.SignalDetectionService.d() (SourceFile:-1)
                                                                                                      at int com.example.audio.services.SignalDetectionService.onStartCommand(android.content.Intent, int, int) (SourceFile:-1)
                                                                                                      at void android.app.ActivityThread.handleServiceArgs(android.app.ActivityThread$ServiceArgsData) (ActivityThread.java:4326)
                                                                                                      at void android.app.ActivityThread.access$1800(android.app.ActivityThread, android.app.ActivityThread$ServiceArgsData) (ActivityThread.java:237)
                                                                                                      at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1951)
                                                                                                      at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:106)
                                                                                                      at void android.os.Looper.loop() (Looper.java:223)
                                                                                                      at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7656)
                                                                                                      at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
                                                                                                      at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:592)
                                                                                                      at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:947)
```

**Comment by kuaashish** [comment]
Hi @albus-d,

Please add the following lines to the proguard-rules.pro file to ensure the build stability:

```
-keep class com.google.mediapipe.solutioncore.** {;}
-keep class com.google.protobuf.** {;}
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {
;
}
```
And let us know if this works.

Thank you!!

**Comment by albus-d** [comment]
@kuaashish IDE show error when I paste your code 

<img width="665" alt="Screenshot 2024-03-20 at 10 14 49" src="https://github.com/google/mediapipe/assets/108171859/14a3a71c-e97c-49e8-ab5d-c0f85829e01f">

then I need to change to 
-keep class com.google.mediapipe.solutioncore.** { *; }
-keep class com.google.protobuf.** { *; }
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {
    *;
}

but still same error

**Comment by kuaashish** [comment]
Hi @albus-d,

Could you please try adding the following lines of code once to the "proguard-rules.pro" file:

```
-keep public class com.google.mediapipe.** { *; } 
-keep public class com.google.mediapipe.framework.Graph { *; } 
-keep public class com.google.common.** { *; }
-keep public interface com.google.common.** { *; }
```


Additionally, if you are still experiencing crashes, please provide the following details to help us to more understand and reproduce the issue:

- Android Studio Version:
- Complete code you are using, including steps from our documentation if available.
- Information about whether you are running on a physical device or emulator, and the Android version.

Thank you!!

**Comment by albus-d** [comment]
Hi @kuaashish, it working on my phone when building the release version now. I use pixel 2 XL. I will keep monitoring after releasing the new version to users and feedback to you later. Thanks in advance!

**Comment by kuaashish** [comment]
Hi @albus-d,

Thank you for confirming. May we consider this issue resolved and close its status? Please feel free to reopen it if you continue to experience the same crash.

Thank you!!

**Comment by xuzepei** [comment]
In my case, I was using the library 'com.google.mediapipe:tasks-vision:0.10.15'.

I have to add the code below in proguard-rules.pro to work well when building the apk/aab with obfuscation 

-keep public class com.google.mediapipe.** { *; }
-keep public class com.google.mediapipe.framework.Graph { *; }
-keep public class com.google.common.** { *; }
-keep public interface com.google.common.** { *; }
-keep class com.google.mediapipe.solutioncore.** {*;}
-keep class com.google.protobuf.** { *; }
-keepclassmembers class com.google.protobuf.** { *; }
-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite {
    *;
}
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate

**Comment by ochornenko** [comment]
Getting this crash, nothing helps, tried to keep different classes by using proguard-rules.pro

FATAL EXCEPTION: DefaultDispatcher-worker-1
01-07 00:46:31.432 27098 27129 E AndroidRuntime: Process: com.slapevents.staging, PID: 27098
01-07 00:46:31.432 27098 27129 E AndroidRuntime: java.lang.ExceptionInInitializerError
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at com.google.mediapipe.tasks.core.TaskRunner.create(Unknown Source:15)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at com.google.mediapipe.tasks.vision.imagesegmenter.ImageSegmenter.createFromOptions(Unknown Source:185)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at Ja.g.invokeSuspend(Unknown Source:193)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at hc.a.resumeWith(Unknown Source:7)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at Id.I.run(Unknown Source:114)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at y.e.run(Unknown Source:856)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at Pd.k.run(Unknown Source:2)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at Pd.b.run(Unknown Source:95)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	Suppressed: Nd.g: [t0{Cancelling}@aac6e2f, Dispatchers.IO]
01-07 00:46:31.432 27098 27129 E AndroidRuntime: Caused by: java.lang.IllegalStateException: no caller found on the stack for: i6.d
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at i6.d.b(Unknown Source:72)
01-07 00:46:31.432 27098 27129 E AndroidRuntime: 	at com.google.mediapipe.framework.Graph.<clinit>(Unknown Source:0)
