### ISSUE TITLE
issue with draw_landmarks() function defined in mp.solutions.drawing_utils 

### ISSUE THREAD

**Issue by akshat-1** [google/mediapipe#5202]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

WINDOWS 11

### Python Version

3.11.1

### MediaPipe Model Maker version

0.10.11

### Task name (e.g. Image classification, Gesture recognition etc.)

hand detection

### Describe the actual behavior

AttributeError: 'NormalizedLandmark' object has no attribute 'landmark' . I am using mp.solutions.holistic model

### Describe the expected behaviour

It should had run without a problem

### Standalone code/steps you may have used to try to get what you need

```shell
def draw_landmarks(
    image: np.ndarray,
    landmark_list: landmark_pb2.NormalizedLandmarkList,...)

'''this is the function written in drawing_utils , here is issue I am facing is with landmark_pb2.NormalizedLandmarkList.'''

'''Some part of code I wrote is -> '''

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.holistic

with mp_hands.Holistic(min_detection_confidence=0.8, min_tracking_confidence=0.5) as hands: 
    while cap.isOpened():
        ret, frame = cap.read()

        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        image = cv2.flip(image, 1)

        image.flags.writeable = False

        results = hands.process(image)

        image.flags.writeable = True

        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        if results.left_hand_landmarks:
           for hand_landmarks in results.left_hand_landmarks.landmark:
               mp_drawing.draw_landmarks(frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)
               keypoint_pos = []
               for i in range(21):
                   x = hand_landmarks.landmark[i].x * frame.shape[1]
                   y = hand_landmarks.landmark[i].y * frame.shape[0]
                   keypoint_pos.append((x, y))


'''It is throwing the error-'''

Traceback (most recent call last):
  File "d:\VIRTUAL PIANO\VIRTUAL-PIANO\mp_hand_gesture\mp_hand_detection.py", line 100, in <module>
    mp_drawing.draw_landmarks(frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)
  File "C:\Users\mpaks\AppData\Local\Programs\Python\Python311\Lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 160, in draw_landmarks      
    for idx, landmark in enumerate(landmark_list.landmark):
                                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NormalizedLandmark' object has no attribute 'landmark'
```

**Comment by kuaashish** [comment]
Hi @akshat-1,

You are presently utilizing the legacy Holistic solution. This solution has been enhanced to the new Holistic Task API starting from version 0.10.10. We have ceased support for legacy solutions entirely. Kindly test the [new Holistic Task API](https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/vision/holistic_landmarker.py) and inform us if you encounter similar errors.

Thank you!!
