### ISSUE TITLE
libllm_inference_engine_jni.so not found

### ISSUE THREAD

**Issue by warleysr** [google/mediapipe#5205]
### OS Platform and Distribution

Windows 11

### Programming Language and version

Kotlin

### Android SDK and NDK versions (if android)

34

### Android AAR (if android)

None

### Describe the problem

I'm building LLM Inference example app, tried both phyisical device and emulated ones, both Gemma model (.bin) and converted supported models (.tflite). 

### Complete Logs

```shell
FATAL EXCEPTION: main
Process: com.google.mediapipe.examples.llminference, PID: 11551
java.lang.UnsatisfiedLinkError: dlopen failed: library "libllm_inference_engine_jni.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.google.mediapipe.tasks.genai.llminference.LlmInference.<clinit>(LlmInference.java:27)
	at com.google.mediapipe.examples.llminference.InferenceModel.<init>(InferenceModel.kt:38)
	at com.google.mediapipe.examples.llminference.InferenceModel.<init>(Unknown Source:0)
	at com.google.mediapipe.examples.llminference.InferenceModel$Companion.getInstance(InferenceModel.kt:53)
	at com.google.mediapipe.examples.llminference.LoadingScreenKt$LoadingRoute$2$1.invokeSuspend(LoadingScreen.kt:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@c56a03a, androidx.compose.runtime.BroadcastFrameClock@c9014eb, StandaloneCoroutine{Cancelling}@87ab248, AndroidUiDispatcher@a4008e1]

```
```

**Comment by warleysr** [comment]
Closing this issue because I didn't installed MediaPipe framework correctly on this case. Switching to a Linux distro and installing the problem appear to be solved on physical devices, but a similar error occurs when trying to run on an emulated one, which I reported in #5232 .

**Comment by gsiddh** [comment]
@warleysr Could you elaborate a bit on how you fixed it?

I am building on macos and deploying to a physical android device. Did switching to Linux with no code changes just automagically worked in your case?

**Comment by warleysr** [comment]
@gsiddh Basically yes. I'm not sure about the MacOS but MediaPipe framework is not fully supported on Windows and I had troubles building the example apps. Note that the issue was related to MediaPipe installation itself (with Bazel to be specific) and switching to Linux and following the correct steps I managed to solve the problem.

**Comment by AstroGuy1** [comment]
@warleysr, could you tell me more about what you did on linux?

**Comment by warleysr** [comment]
@AstroGuy1 I followed the correct installation instructions:
1. Install MediaPipe framework: https://ai.google.dev/edge/mediapipe/framework/getting_started/install#installing_on_debian_and_ubuntu 
**P.S.:** Don't forget to install Bazel before trying to install MediaPipe: https://bazel.build/install/ubuntu

1. Build an Android example following the steps: https://ai.google.dev/edge/mediapipe/framework/getting_started/android
