### ISSUE TITLE
Unable to run Mediapipe on Android 6.0 ( Moto G4 Play)

### ISSUE THREAD

**Issue by AnubhavRoy132** [google/mediapipe#521]
So I am using Mediapipe in one of my projects . While it works on most of the device it does fail on Moto G4 Play with this stack trace.

`FATAL EXCEPTION: main
Process: com.fynd.ficto, PID: 14454
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.fynd.ficto-1/lib/arm/libmediapipe_jni.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at c.c.c.a.b.<clinit>()
	at com.fynd.ficto.MainActivity.onResume()
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1281)
	at android.app.Activity.performResume(Activity.java:6335)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3113)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3155)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2498)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

Device Specs

![image](https://user-images.githubusercontent.com/60560984/76681561-4f123e80-661a-11ea-914f-8999d0b82ec3.png)

**Comment by jiuqiant** [comment]
How do you build the app? Based  on the device specs you provided, the native platform is armeabi-v7a and you need to build the app with [`config=android_arm`](https://github.com/google/mediapipe/blob/master/.bazelrc#L35), rather than `config=android_arm64`. I provided more information about MediaPipe's Android compatibility in [one of my pervious comments](https://github.com/google/mediapipe/issues/178#issuecomment-547619564)

**Comment by AnubhavRoy132** [comment]
@jiuqiant  This was my build command 

` bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a  //mediapipe/examples/android/src/java/com/google/mediapipe/apps/aar_example:mp_hair_segmentation_aar --incompatible_disable_deprecated_attr_params=false
`

**Comment by jiuqiant** [comment]
Marshmallow was released with API level 23. It's worth a try to specify the api_level explicitly.

Can you add `api_level = 23` to the `android_ndk_repository` and `android_sdk_repository` rule in [the WORKSPACE file at line 280](https://github.com/google/mediapipe/blob/master/WORKSPACE#L280)?

```
android_ndk_repository(
    name = "androidndk",
    api_level = 23,
)

android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
)
```

Then, clean the cache by running `bazel clean --expunge` and rebuild the app.

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
