### ISSUE TITLE
Unable to install Mediapipe on venv

### ISSUE THREAD

**Issue by tushargahlaut** [google/mediapipe#5216]
Hi I have created a virtual environment [Python 3.12.1 pip 23.2.1], I am unable to install it through pip install mediapipe

ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe,

When I try to install it via cloning git repo, I get the following error.

`pip install git+https://github.com/google/mediapipe.git

Collecting git+https://github.com/google/mediapipe.git
  Cloning https://github.com/google/mediapipe.git to /private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-req-build-2h81kzuw
  Running command git clone --filter=blob:none --quiet https://github.com/google/mediapipe.git /private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-req-build-2h81kzuw
  Resolved https://github.com/google/mediapipe.git to commit 3b18b6a9974a5d48eb4459c06093e4125a76ce8e
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Traceback (most recent call last):
        File "/Users/tushargahlaut/PycharmProjects/HandTrackingBasics/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/tushargahlaut/PycharmProjects/HandTrackingBasics/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/tushargahlaut/PycharmProjects/HandTrackingBasics/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 520, in <module>
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 314, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 350, in _normalize_version
          normalized = str(Version(version))
                           ^^^^^^^^^^^^^^^^
        File "/private/var/folders/nj/y_ytny_95_gfqmsxj4xkg3f40000gq/T/pip-build-env-2i8vggr4/overlay/lib/python3.12/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'dev'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
`

Is there any workaround for this?

**Comment by kuaashish** [comment]
Hi @tushargahlaut,

It seems you are using an unsupported Python version. The recommended versions are between 3.8 and 3.11, as specified in the Python Setup [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). Version 3.12 is not yet supported in Mediapipe. Kindly use the recommended version and inform us if you encounter further issues.

Thank you!

**Comment by tushargahlaut** [comment]
Hi, Thank You, I was able to install mediapipe on python 3.11.5
