### ISSUE TITLE
can't finish the download

### ISSUE THREAD

**Issue by Kiritoita75** [google/mediapipe#5262]
### OS Platform and Distribution

linux Arch

### Programming Language and version

python3.11.8

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

idk

### Bazel version

idk

### Android AAR (if android)

None

### OpenCV version (if running on desktop)

4.9.0.80

### Describe the problem

when is time to download nvidia_cudnn it have an error

### Complete Logs

```shell
RROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/usr/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 102, in read
    self.__buf.write(data)
  File "/usr/lib/python3.11/tempfile.py", line 500, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] Spazio esaurito sul device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "/usr/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "/usr/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "/usr/lib/python3.11/site-packages/pip/_internal/network/download.py", line 183, in __call__
    for chunk in chunks:
  File "/usr/lib/python3.11/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/usr/lib/python3.11/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.11/site-packages/pip/_vendor/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'Spazio esaurito sul device')", OSError(28, 'Spazio esaurito sul device'))
```

**Comment by kuaashish** [comment]
Hi @Kiritoita75,

Could you please provide a detailed outline of the steps you are taking, including references to the documentation or sharing the standalone code if possible? Also, could you confirm the version of Linux/MediaPipe you are using? This information will assist us in reproducing and comprehensively understanding the issue on our end.

Thank you!!

**Comment by Kiritoita75** [comment]
hi @kuaashish sorry for be late, idk how to get the version of mediapipe, i just done pip install --break-system-packages mediapipe and i think it don't show the version, for linux i'm using arch(idk what version, when i type neofetch just show arch linux 86_64x). for standalone code what do you mean?(sorry i'm italian i don't now certain terms), and for documentation i follow the step that tell my friend  who haved installed mediapipe

thank you for the respost

**Comment by kuaashish** [comment]
Hi @Kiritoita75,

We refer the documentation means at this link for example: https://developers.google.com/mediapipe/solutions/guide steps which you are following. Additionally, when we mention standalone code, we are referring to the complete code you are executing, which resulting above error shared here. 

Thank you!!
