### ISSUE TITLE
CanvasRenderingContext2D is not defined in DrawingUtils constructor

### ISSUE THREAD

**Issue by ddgg-el** [google/mediapipe#5284]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

macOS 12.6

### MediaPipe Tasks SDK version

npm package version 0.10.12

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Landmarker

### Programming Language and version (e.g. C++, Python, Java)

Typescript

### Describe the actual behavior

Instanciating a DrawingUtils with an OffscreenCanvasRenderingContext2D as cpuContext in Worker returns an Uncaught ReferenceError: CanvasRenderingContext2D is not defined

### Describe the expected behaviour

a DrawingUtils is properly Instantiated

### Standalone code/steps you may have used to try to get what you need

```shell
//index.ts
const canvasCamera = document.getElementById("output_canvas") as HTMLCanvasElement
const offscreenVideoCanvas:OffscreenCanvas = canvasCamera.transferControlToOffscreen()
poseWorker.postMessage({canvas: offscreenVideoCanvas}, [offscreenVideoCanvas])


// pose pose_worker.ts
self.onmessage = (e) => {
    if ("canvas" in e.data ) {
        canvasCamera = e.data.canvas as OffscreenCanvas
	canvasCtxVideo = canvasCamera.getContext("2d") as OffscreenCanvasRenderingContext2D
	painter = new DrawingUtils(canvasCtxVideo)
    }
}
```

### Other info / Complete Logs

```shell
Uncaught ReferenceError: CanvasRenderingContext2D is not defined
    at new Ra (vision_bundle.mjs:1:58732)
    at self.onmessage (pose_worker.ts:29:13)
```

**Comment by JDBar** [comment]
I've got a goofy workaround, which is to define `CanvasRenderingContext2D` in the web worker context.

```ts
declare let self: WorkerGlobalScope &
	typeof globalThis & {
		CanvasRenderingContext2D: typeof OffscreenCanvasRenderingContext2D;
	};
self.CanvasRenderingContext2D = OffscreenCanvasRenderingContext2D;
```

`DrawingUtils` seems perfectly happy with this.

**Comment by kuaashish** [comment]
Hi @ddgg-el,

Could you please confirm if this is still an issue? A newer version of MediaPipe is available—could you check and let us know if it resolves the problem? If the issue is resolved, please inform us.

Thank you!!

**Comment by jeromecornet** [comment]
It is still an issue in 0.10.18

**Comment by decloak-cwang** [comment]
This still occurs in version 0.10.21, any update?
