### ISSUE TITLE
Handtracking GPU failing build

### ISSUE THREAD

**Issue by Meetem** [google/mediapipe#529]
Building from WSL, Android NDK version 21, Android SDK is 29

Building with 
`bazel build -c opt --config=android_arm64 --define 3D=true mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu` according to manual.

Producing following output:
`ERROR: /home/alex/.cache/bazel/_bazel_alex/0ebcbbdb3c1106709d085d51fe6bf742/external/maven/BUILD:324:1: Merging compiled Android resources for @maven//:androidx_drawerlayout_drawerlayout failed (Exit 1) ResourceProcessorBusyBox failed: error executing command bazel-out/host/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput ... (remaining 15 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Mar 17, 2020 5:33:01 PM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main
SEVERE: Unexpected
java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceTable(AndroidCompiledDataDeserializer.java:250)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:683)
        at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)

Mar 17, 2020 5:33:01 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during processing
java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceTable(AndroidCompiledDataDeserializer.java:250)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:683)
        at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)

Exception in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.readResourceTable(AndroidCompiledDataDeserializer.java:250)
        at com.google.devtools.build.android.AndroidCompiledDataDeserializer.read(AndroidCompiledDataDeserializer.java:683)
        at com.google.devtools.build.android.SerializedAndroidData.deserialize(SerializedAndroidData.java:105)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:255)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$7.call(ResourceProcessorBusyBox.java:102)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:237)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:198)
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build`

**Comment by PrinceP** [comment]
#261

**Comment by Meetem** [comment]
@PrinceP 
calculators/image/BUILD already has this fix
`
    deps = [
        ":image_cropping_calculator_cc_proto",
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/formats:rect_cc_proto",
        "//mediapipe/framework/port:opencv_core",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:ret_check",
        "//mediapipe/framework/port:status",
    ] + select({
        "//mediapipe/gpu:disable_gpu": [],
        "//conditions:default": [
            "//mediapipe/gpu:gl_calculator_helper",
            "//mediapipe/gpu:gl_simple_shaders",
            "//mediapipe/gpu:gl_quad_renderer",
            "//mediapipe/gpu:gpu_buffer",
            "//mediapipe/gpu:shader_util",
        ],
    }),
`

**Comment by jiuqiant** [comment]
I believe this issue is already fixed. Feel free tp reopen this if needed.

**Comment by DandyLorenz** [comment]
How did you solve it？
