### ISSUE TITLE
There seems to be something with the camera. HandtrackingGPU 

### ISSUE THREAD

**Issue by MashaKucherova** [google/mediapipe#547]
The project is built without errors, but when launched on the phone, it displays these errors. Please help, I do not know how to fix this.

`2020-03-22 18:27:39.017 31639-31639/com.example.handtracking E/libEGL: validate_display:92 error 3008 (EGL_BAD_DISPLAY)
2020-03-22 18:27:45.153 31639-31639/com.example.handtracking E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.handtracking, PID: 31639
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/camera/core/CameraX$LensFacing;
        at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:74)
        at com.google.mediapipe.apps.handtrackinggpu.MainActivity.startCamera(MainActivity.java:198)
        at com.google.mediapipe.apps.handtrackinggpu.MainActivity.onResume(MainActivity.java:133)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
        at android.app.Activity.performResume(Activity.java:7196)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.camera.core.CameraX$LensFacing" on path: DexPathList[[zip file "/data/app/com.example.handtracking-PTzr19QPh0imWWvKaffRqw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.handtracking-PTzr19QPh0imWWvKaffRqw==/lib/arm64, /data/app/com.example.handtracking-PTzr19QPh0imWWvKaffRqw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.mediapipe.components.CameraXPreviewHelper.startCamera(CameraXPreviewHelper.java:74) 
        at com.google.mediapipe.apps.handtrackinggpu.MainActivity.startCamera(MainActivity.java:198) 
        at com.google.mediapipe.apps.handtrackinggpu.MainActivity.onResume(MainActivity.java:133) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356) 
        at android.app.Activity.performResume(Activity.java:7196) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
`

**Comment by eknight7** [comment]
Please check that you are using this version of `CameraX`:

> androidx.camera:camera-core:1.0.0-alpha06

Please see https://github.com/google/mediapipe/issues/472 and https://github.com/google/mediapipe/issues/490 for updates about when the APIs will be updated.

**Comment by realapril** [comment]
I'm currently using version 1.0.0-beta10 and according to [the answer](https://github.com/google/mediapipe/issues/472#issuecomment-756891204) it seems right since I pulled the latest mediapipe version...
```
// CameraX core library
    def camerax_version = "1.0.0-beta10"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
```
I tested the old version and this one also shows black screen.   
```
    // CameraX core library
    def camerax_version = "1.0.0-alpha06"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
```
The difference is it showed shorter error log(EGL_BAD_DISPLAY only)
```
I/AdrenoGLES-0: PFP: 0x016dd091, ME: 0x00000000
I/DecorView: [INFO] isPopOver=false, config=true
I/DecorView: updateCaptionType >> DecorView@1c8975a[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
D/DecorView: setCaptionType = 0, this = DecorView@1c8975a[]
W/ealtimefacemes: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ealtimefacemes: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/native: I20210316 16:29:42.240309 31105 asset_manager_util.cc:59] Created global reference to asset manager.
E/libEGL: validate_display:213 error 3008 (EGL_BAD_DISPLAY)
I/native: I20210316 16:29:42.249696 31105 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I/native: I20210316 16:29:42.251705  4906 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 V@0502.0 (GIT@7c6959d1f7, Ifdda647016, 1599142814) (Date:09/03/20))
D/PermissionHelper: checkAndRequestCameraPermissions
D/GlThread: Starting GL thread ExternalTextureConverter
D/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
D/InputTransport: Input channel constructed: '9826443', fd=83
I/ViewRootImpl@74520c8[MainActivity]: setView = com.android.internal.policy.DecorView@1c8975a TM=true
D/GlThread: Stopping GL thread ExternalTextureConverter
I/SurfaceView: onWindowVisibilityChanged(0) false android.view.SurfaceView{3f566a G.E...... ......I. 0,0-0,0} of ViewRootImpl@74520c8[MainActivity]
I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x90418d1 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1787 android.view.ViewRootImpl.relayoutWindow:8953 android.view.ViewRootImpl.performTraversals:3312 android.view.ViewRootImpl.doTraversal:2575 android.view.ViewRootImpl$TraversalRunnable.run:9910 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
I/ViewRootImpl@74520c8[MainActivity]: Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=5 res=0x7 s={true 484738351376} ch=true fn=-1
I/SurfaceView: windowStopped(false) false android.view.SurfaceView{3f566a G.E...... ......I. 0,0-0,0} of ViewRootImpl@74520c8[MainActivity]
D/OpenGLRenderer: GPIS:: SetUp Pid : 31105    Tid : 4869
D/PermissionHelper: onRequestPermissionsResult
I/ViewRootImpl@74520c8[MainActivity]: stopped(false) old=false
D/GlThread: Starting GL thread ExternalTextureConverter
I/ViewRootImpl@74520c8[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager: prepareNavigationBarInfo() DecorView@1c8975a[MainActivity]
    getNavigationBarColor() -16711423
    prepareNavigationBarInfo() DecorView@1c8975a[MainActivity]
    getNavigationBarColor() -16711423
V/InputMethodManager: Starting input: tba=com.example.realtimefacemesh ic=null mNaviBarColor -16711423 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport: Input channel constructed: 'ClientS', fd=92
D/InputMethodManager: prepareNavigationBarInfo() DecorView@1c8975a[MainActivity]
    getNavigationBarColor() -16711423
V/InputMethodManager: Starting input: tba=com.example.realtimefacemesh ic=null mNaviBarColor -16711423 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager: startInputInner - Id : 0
D/SurfaceControl: hide : mNativeObject = 480443807536 - sc.mNativeObject = 480443822320 - Surface(name=Surface(name=e523180 InputMethod)/@0x303f4d6 - animation-leash)/@0x67cf3c
    nativeSetFlags Done : Surface(name=Surface(name=e523180 InputMethod)/@0x303f4d6 - animation-leash)/@0x67cf3c
I/SurfaceControl: release : mNativeObject = 480443448320 - Surface(name=Surface(name=5c0c919 NavigationBar0)/@0xedaabdb - animation-leash)/@0x1bfb4c5 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
    nativeRelease nativeObject s[480443448320]
    nativeRelease nativeObject e[480443448320]
I/SurfaceControl: release : mNativeObject = 480443448496 - Surface(name=Surface(name=cea89c8 StatusBar)/@0xca5c71d - animation-leash)/@0xd122e1a / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
    nativeRelease nativeObject s[480443448496]
    nativeRelease nativeObject e[480443448496]
```
