### ISSUE TITLE
building errors

### ISSUE THREAD

**Issue by melody-rain** [google/mediapipe#58]
With following commands:
```
bazel build -c opt --config=android_arm64     mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectiongpu     --incompatible_depset_is_not_iterable=false     --incompatible_disable_deprecated_attr_params=false     --incompatible_no_support_tools_in_action_inputs=false
```
I always get errors:
```
Starting local Bazel server and connecting to it...
INFO: An error occurred during the fetch of repository 'flatbuffers'
INFO: Call stack for the definition of repository 'flatbuffers':
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/org_tensorflow/third_party/flatbuffers/workspace.bzl:6:5
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/org_tensorflow/tensorflow/workspace.bzl:40:5
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/org_tensorflow/tensorflow/workspace.bzl:84:5
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/org_tensorflow/tensorflow/workspace.bzl:60:5
 - /home/melody/hdd1/develop/mediapipe/WORKSPACE:121:1
INFO: An error occurred during the fetch of repository 'android_tools'
INFO: An error occurred during the fetch of repository 'remote_java_tools_linux'
INFO: Call stack for the definition of repository 'android_tools':
 - /DEFAULT.WORKSPACE.SUFFIX:238:1
INFO: Call stack for the definition of repository 'remote_java_tools_linux':
 - /DEFAULT.WORKSPACE.SUFFIX:208:1
INFO: An error occurred during the fetch of repository 'eigen_archive'
INFO: Call stack for the definition of repository 'eigen_archive':
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/org_tensorflow/tensorflow/workspace.bzl:170:5
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/org_tensorflow/tensorflow/workspace.bzl:60:5
 - /home/melody/hdd1/develop/mediapipe/WORKSPACE:121:1
INFO: An error occurred during the fetch of repository 'android_opencv'
INFO: Call stack for the definition of repository 'android_opencv':
 - /home/melody/hdd1/develop/mediapipe/WORKSPACE:149:1
INFO: An error occurred during the fetch of repository 'maven'
INFO: Call stack for the definition of repository 'maven':
 - /home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244/external/rules_jvm_external/defs.bzl:41:5
 - /home/melody/hdd1/develop/mediapipe/WORKSPACE:182:1
INFO: An error occurred during the fetch of repository 'com_google_protobuf_javalite'
INFO: Call stack for the definition of repository 'com_google_protobuf_javalite':
 - /home/melody/hdd1/develop/mediapipe/WORKSPACE:76:1
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@linux_opencv//:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true' (requested by nodes '//third_party:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.4 and external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.1
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.buildMapIdentifierToArtifact(CcLibrary.java:682)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.convertPrecompiledLibrariesToLibraryToLink(CcLibrary.java:712)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:355)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:92)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:67)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more

INFO: Elapsed time: 7.247s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (86 packages loaded, 1971 targets configured)
    currently loading: @org_tensorflow//tensorflow/lite/delegates/gpu/gl ... (3 packages)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@linux_opencv//:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true' (requested by nodes '//third_party:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.4 and external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.1
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.buildMapIdentifierToArtifact(CcLibrary.java:682)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.convertPrecompiledLibrariesToLibraryToLink(CcLibrary.java:712)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:355)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:92)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:67)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@linux_opencv//:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true' (requested by nodes '//third_party:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.4 and external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.1
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.buildMapIdentifierToArtifact(CcLibrary.java:682)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.convertPrecompiledLibrariesToLibraryToLink(CcLibrary.java:712)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:355)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:92)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:67)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:453)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@linux_opencv//:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true' (requested by nodes '//third_party:opencv BuildConfigurationValue.Key[496c7b5cc2f253d07e7d790c95919827] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:530)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.4 and external/linux_opencv/local/lib/libopencv_core.so.3=File:[/home/melody/.cache/bazel/_bazel_melody/c3bb27c111a2a9a675e4f4c64d828244[source]]external/linux_opencv/local/lib/libopencv_core.so.3.1
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.buildMapIdentifierToArtifact(CcLibrary.java:682)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.convertPrecompiledLibrariesToLibraryToLink(CcLibrary.java:712)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.init(CcLibrary.java:355)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:92)
	at com.google.devtools.build.lib.rules.cpp.CcLibrary.create(CcLibrary.java:67)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:354)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:208)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:767)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:809)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:348)
FAILED: Build did NOT complete successfully (86 packages loaded, 1971 targets configured)
    currently loading: @org_tensorflow//tensorflow/lite/delegates/gpu/gl ... (3 packages)
```

**Comment by jiuqiant** [comment]
melody-rain@, this issue probably can be solved by modifying [third_party/ffmpeg_linux.BUILD](https://github.com/google/mediapipe/blob/master/third_party/ffmpeg_linux.BUILD) and
[third_party/opencv_linux.BUILD](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD) like the following:

```
--- a/third_party/ffmpeg_linux.BUILD
+++ b/third_party/ffmpeg_linux.BUILD
@@ -20,7 +20,7 @@ cc_library(
     name = "libffmpeg",
     srcs = glob(
         [
-            "lib/x86_64-linux-gnu/libav*.so*",
+            "lib/x86_64-linux-gnu/libav*.so",
         ],
     ),
     hdrs = glob(["include/x86_64-linux-gnu/libav*/*.h"]),
diff --git a/third_party/opencv_linux.BUILD b/third_party/opencv_linux.BUILD
index 48e8d9af..3e57c5c8 100644
--- a/third_party/opencv_linux.BUILD
+++ b/third_party/opencv_linux.BUILD
@@ -13,12 +13,12 @@ cc_library(
     name = "opencv",
     srcs = glob(
         [
-            "lib/x86_64-linux-gnu/libopencv_core.so*",
-            "lib/x86_64-linux-gnu/libopencv_highgui.so*",
-            "lib/x86_64-linux-gnu/libopencv_imgcodecs.so*",
-            "lib/x86_64-linux-gnu/libopencv_imgproc.so*",
-            "lib/x86_64-linux-gnu/libopencv_video.so*",
-            "lib/x86_64-linux-gnu/libopencv_videoio.so*",
+            "lib/x86_64-linux-gnu/libopencv_core.so",
+            "lib/x86_64-linux-gnu/libopencv_highgui.so",
+            "lib/x86_64-linux-gnu/libopencv_imgcodecs.so",
+            "lib/x86_64-linux-gnu/libopencv_imgproc.so",
+            "lib/x86_64-linux-gnu/libopencv_video.so",
+            "lib/x86_64-linux-gnu/libopencv_videoio.so",
         ],
```

Let me know if that works. If it does, we will fix this in the next release. Thanks.

**Comment by melody-rain** [comment]
@jiuqiant I can build it now. Thanks.
