### ISSUE TITLE
issue building android with docker

### ISSUE THREAD

**Issue by jitendersaini** [google/mediapipe#585]
I'm facing 2 issues while building android project with docker on my MAC machine.

1) while executing command - root@bca08b91ff63:/mediapipe# bash ./setup_android_sdk_and_ndk.sh

It is successfully executed and printed what was intended but it has generated duplicate PATH in WORKSPACE file for android_ndk_repository and android_sdk_repository that later on I've removed manually from docker bash container. refer the  following

```
# You may run setup_android.sh to install Android SDK and NDK.
# You may run setup_android.sh to install Android SDK and NDK.
android_sdk_repository(
    name = "androidsdk",
    #path = "/Users/username/Library/Android/sdk",
    path = "/root/Android/Sdk",
)

android_ndk_repository(
    name = "androidndk",
    path = "/root/Android/Sdk/ndk-bundle/android-ndk-r18b",
    api_level = 28,
    #path = "/Users/username/Library/Android/sdk/ndk/ndk-bundle",
)
```

2) It built the project but finally there is error after correcting the WORKSPACE file duplicate path issue:

**ERROR: ERROR: /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/maven/BUILD:117:1: Dexing external/maven/_dx/androidx_asynclayoutinflater_asynclayoutinflater/classes_and_libs_merged.jar_desugared.jar with applicable dexopts [] failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(Unknown Source)
	at java.base/java.io.OutputStream.write(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
	at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:126)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:353)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:190)
	at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:129)
	at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:225)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:122)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:87)
	at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
	at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:314)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:123)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:886)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1021)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:992)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:585)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:832)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:285)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:454)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/bazel-workers/worker-16-DexBuilder.log ---8<---8<---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/external/android_tools/all_android_tools_deploy.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
---8<---8<--- End of log ---8<---8<---
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1121.870s, Critical Path: 1118.36s
INFO: 283 processes: 211 processwrapper-sandbox, 72 worker.
FAILED: Build did NOT complete successfully**

**Comment by jiuqiant** [comment]
For the first question, is it possible that you accidentally edited the WORKSPACE file to add the ndk and sdk paths before running the script? The original [WORKSPACE](https://github.com/google/mediapipe/blob/master/WORKSPACE#L284) doesn't have the ndk and sdk paths, and [the script](https://github.com/google/mediapipe/blob/master/setup_android_sdk_and_ndk.sh#L103) should only insert the paths once. I verified that the Android NDK and SDK installation works okay in a docker container on Debian.

For the second issue, I can't reproduce it in a docker container on Debian. I can successfully build the app:
```
root@181a888cfa81:/mediapipe# date
Mon Apr  6 16:55:40 UTC 2020
root@181a888cfa81:/mediapipe# bazel build -c opt --config=android_arm64 //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/4884d566396e9b67b62185751879ad14/command.profile.gz'
......
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu up-to-date:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_deploy.jar
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_unsigned.apk
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk
INFO: Elapsed time: 198.196s, Critical Path: 89.31s
INFO: 2984 processes: 1 local, 2829 processwrapper-sandbox, 154 worker.
INFO: Build completed successfully, 3142 total actions
```
I also searched the error and it seems to be a known Bazel issue: https://github.com/tensorflow/tensorflow/issues/23191, https://github.com/bazelbuild/bazel/issues/9366, https://github.com/bazelbuild/rules_nodejs/issues/1027. We probably need a Mac to reproduce this issue in a docker container. Please allow us some time. 
 If you eager to build the app while we are investigating the issue, I believe the build command should work okay on the native macOS system.

**Comment by jitendersaini** [comment]
Hi jiuqiant,
Thank you very much for your prompt response on this, Your doubt on the first issue might be right because I was doing the setup with some other platforms so I could have included the android_sdk and ndk manually, I'll cross verify it again with the fresh setup. 
For second issue, I've run the command again with different project like objectdetectioncpu and surprisingly it has been built successfully without any error, then later on I run the same command with handtrackinggpu and it was also successful. I'm not sure it could be some caching issue.
But now I've build two apk files as follow:
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu_unsigned.apk
  bazel-bin/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu/handtrackinggpu.apk

When I'm installing the handtrackinggpu.apk in my phone (Galaxy s9 +) the same is getting crash, whereas if I install the same project from android studio to my phone it's working fine. So I'm not sure why there are difference in 2 apk files.

Thanks
Jitender
