### ISSUE TITLE
Cannot sync bazel on android studio

### ISSUE THREAD

**Issue by anhduy5689h** [google/mediapipe#621]
I did all steps same as https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md

But when I sync bazel, it shows errors:

Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: /usr/local/bin/bazel info --tool_tag=ijwb:AndroidStudio --curses=no --color=yes --progress_in_terminal_title=no --

Command: git diff --name-status --no-renames 024f7bf0f1e74149ea92b942cf168ccddf317073

Computing VCS working set...
  .aswb/.bazelproject (added)
  .aswb/.blaze/modules/.project-data-dir.iml (added)
  .aswb/.blaze/modules/.workspace.iml (added)
  .aswb/.idea/.gitignore (added)
  .aswb/.idea/.name (added)
  .aswb/.idea/codeStyles/Project.xml (added)
  .aswb/.idea/externalDependencies.xml (added)
  .aswb/.idea/misc.xml (added)
  .aswb/.idea/modules.xml (added)
  .aswb/.idea/runConfigurations.xml (added)
  .aswb/.idea/vcs.xml (added)
  WORKSPACE (modified)
  mediapipe/calculators/tflite/tflite_inference_calculator.cc (modified)
  mediapipe/docs/android_archive_library.md (modified)
  mediapipe/framework/calculator_graph_test.cc (modified)
  mediapipe/java/com/google/mediapipe/framework/jni/register_natives.cc (modified)
  mediapipe/java/com/google/mediapipe/mediapipe_aar.bzl (modified)

Sync targets from working set:
  //mediapipe/calculators/tflite:all
  //:all
  //mediapipe/java/com/google/mediapipe:all
  //mediapipe:all
  //mediapipe/java/com/google/mediapipe/framework/jni:all
  //mediapipe/framework:all

Sync targets from project view targets:
  //mediapipe/examples/android/...:all
  //mediapipe/java/...:all

Building Bazel targets...
Command: /usr/local/bin/bazel build --tool_tag=ijwb:AndroidStudio --keep_going --build_event_binary_file=/var/folders/c_/x1pbbywd1330zq8ghdjxcws40000gn/T/intellij-bep-7c58e491-c9ca-4254-a97f-ef1a04cb15c8 --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect "--override_repository=intellij_aspect=/Users/duy.p/Library/Application Support/AndroidStudio3.6/aswb/aspect" --output_groups=intellij-info-android,intellij-info-generic,intellij-info-java,intellij-resolve-android,intellij-resolve-java -- //mediapipe/calculators/tflite:all //:all //mediapipe/java/com/google/mediapipe:all //mediapipe:all //mediapipe/java/com/google/mediapipe/framework/jni:all //mediapipe/framework:all //mediapipe/examples/android/...:all //mediapipe/java/...:all

Loading: 
Loading: 0 packages loaded
Loading: 22 packages loaded
    currently loading: mediapipe/calculators/tflite ... (2 packages)
Loading: 22 packages loaded
    currently loading: mediapipe/calculators/tflite ... (2 packages)
Loading: 22 packages loaded
    currently loading: mediapipe/calculators/tflite ... (2 packages)
Loading: 22 packages loaded
    currently loading: mediapipe/calculators/tflite ... (2 packages)
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = ad1dcb34266e874c80f73a46ddff8f91be598c8487a44c9cb17994192cd4719c
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "ad1dcb34266e874c80f73a46ddff8f91be598c8487a44c9cb17994192cd4719c"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /Users/duy.p/AndroidStudioProjects/mediapipe/WORKSPACE:33:1
Analyzing: 244 targets (24 packages loaded)
Analyzing: 244 targets (24 packages loaded, 0 targets configured)
Analyzing: 244 targets (46 packages loaded, 185 targets configured)
Analyzing: 244 targets (47 packages loaded, 201 targets configured)
Analyzing: 244 targets (51 packages loaded, 217 targets configured)
Analyzing: 244 targets (58 packages loaded, 468 targets configured)
Analyzing: 244 targets (60 packages loaded, 468 targets configured)
Analyzing: 244 targets (67 packages loaded, 468 targets configured)
Analyzing: 244 targets (74 packages loaded, 495 targets configured)
INFO: Call stack for the definition of repository 'com_google_googletest' which is a http_archive (rule definition at /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /Users/duy.p/AndroidStudioProjects/mediapipe/WORKSPACE:40:1
INFO: Call stack for the definition of repository 'remotejdk11_macos' which is a http_archive (rule definition at /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:9
 - /DEFAULT.WORKSPACE.SUFFIX:155:1
ERROR: An error occurred during the fetch of repository 'com_google_googletest':
   java.io.IOException: thread interrupted
ERROR: An error occurred during the fetch of repository 'remotejdk11_macos':
   java.io.IOException: thread interrupted
INFO: Call stack for the definition of repository 'maven' which is a coursier_fetch (rule definition at /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/rules_jvm_external/coursier.bzl:798:18):
 - <builtin>
 - /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/rules_jvm_external/defs.bzl:94:5
 - /Users/duy.p/AndroidStudioProjects/mediapipe/WORKSPACE:273:1
ERROR: An error occurred during the fetch of repository 'maven':
   java.io.IOException: thread interrupted
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@google_toolbox_for_mac//:GTM_Defines BuildConfigurationValue.Key[b5ccf233523d78d5ce56dd02c50ebf5e0cad7197fcad68ecb0da870f834ec90e] true' (requested by nodes '//mediapipe/objc:mediapipe_framework_ios BuildConfigurationValue.Key[b5ccf233523d78d5ce56dd02c50ebf5e0cad7197fcad68ecb0da870f834ec90e] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:585)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:288)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:391)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1038)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1082)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:968)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:82)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:484)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:857)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:898)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more

INFO: Elapsed time: 22.801s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (112 packages loaded, 1757 targets configured)
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '@google_toolbox_for_mac//:GTM_Defines BuildConfigurationValue.Key[b5ccf233523d78d5ce56dd02c50ebf5e0cad7197fcad68ecb0da870f834ec90e] true' (requested by nodes '//mediapipe/objc:mediapipe_framework_ios BuildConfigurationValue.Key[b5ccf233523d78d5ce56dd02c50ebf5e0cad7197fcad68ecb0da870f834ec90e] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:585)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:288)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:391)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1038)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1082)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:968)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:82)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:484)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:857)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:898)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '@google_toolbox_for_mac//:GTM_Defines BuildConfigurationValue.Key[b5ccf233523d78d5ce56dd02c50ebf5e0cad7197fcad68ecb0da870f834ec90e] true' (requested by nodes '//mediapipe/objc:mediapipe_framework_ios BuildConfigurationValue.Key[b5ccf233523d78d5ce56dd02c50ebf5e0cad7197fcad68ecb0da870f834ec90e] true')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:515)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.getFeatureConfiguration(CompilationSupport.java:585)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.compile(CompilationSupport.java:288)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.ccCompileAndLink(CompilationSupport.java:391)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1038)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:1082)
	at com.google.devtools.build.lib.rules.objc.CompilationSupport.registerCompileAndArchiveActions(CompilationSupport.java:968)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:82)
	at com.google.devtools.build.lib.rules.objc.ObjcLibrary.create(ObjcLibrary.java:43)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:484)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:190)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:857)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:898)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:338)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
	... 7 more
FAILED: Build did NOT complete successfully (112 packages loaded, 1757 targets configured)
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (112 packages loaded, 1757 targets configured)
build invocation result: fatal_error
Sync finished

Timing summary:
BlazeInvocation: 23.4s, Prefetching: 0ms, Other: 0ms
Sync failed

------------------------------
I also try with bazel clean --expunge and bazel sync --configure

Duys-MacBook-Pro:mediapipe duy.p$ bazel clean --expunge
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
INFO: Starting clean.
Duys-MacBook-Pro:mediapipe duy.p$ bazel sync --configure
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
ERROR: /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/org_tensorflow/third_party/py/python_configure.bzl:271:27: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1223:25: in call to repository_rule(), parameter 'remotable' is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_repo_remote_exec
ERROR: error loading package '': in /private/var/tmp/_bazel_duy.p/67fe4255e8de5425a2cbad04588ea468/external/org_tensorflow/tensorflow/workspace.bzl: Extension file 'third_party/gpus/cuda_configure.bzl' has errors
Loading: loading...

 I searched a lot but I cannot still find any solution to fix this.

**Comment by anhduy5689h** [comment]
Could you help to build an example with aar file of hand tracking? Thanks!

**Comment by jiuqiant** [comment]
https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example

**Comment by jiuqiant** [comment]
We are closing this issue for now due to lack of activity.
