### ISSUE TITLE
Identify and switching tensorflow version

### ISSUE THREAD

**Issue by tjtanaa** [google/mediapipe#645]
Could I know what is the version of the Tensorflow and how to change the Tensorflow version?

**Comment by jiuqiant** [comment]
Yes, it's possible. [Here](https://github.com/google/mediapipe/blob/master/WORKSPACE#L121) is workspace rule that specifies the tensorflow version that MediaPipe depends on.  You can modify `_TENSORFLOW_GIT_COMMIT` to use another version of TensorFlow. Remember to modify `_TENSORFLOW_SHA256` as well. 

In general, MediaPipe tries to stick to the latest TensorFlow version. If you switch to an earlier version of TensorFlow, MediaPipe may not work.

**Comment by afsaredrisy** [comment]
Hey @jiuqiant I am trying to downgrade tensorflow to 2.3.0. I updated commit id and SHA256 but I am getting following error. 
```
INFO: Repository 'org_tensorflow' used the following cache hits instead of downloading the corresponding file.
 * Hash '67cdd7da47103fcfc9ce088cb945331a7d7d823fe9cf4bae333fef433257a260' for https://github.com/tensorflow/tensorflow/archive/82515cee8f36fe9f3abe25d5aef8218ce8bf48bb.tar.gz
If the definition of 'org_tensorflow' was updated, verify that the hashes were also updated.
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "3e6b0691fc57db8217d535393dcc2cf7c1d39fc87e9adb6e7d7bab1483915110"
DEBUG: Repository rules_foreign_cc instantiated at:
  /home/usrname/projectDir/mediapipe-master/WORKSPACE:41:13: in <toplevel>
Repository rule http_archive defined at:
  /home/usrname/.cache/bazel/_bazel_usrname/779131debdfa005bca7898ed75d6397c/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'org_tensorflow':
   Traceback (most recent call last):
	File "/home/usrname/.cache/bazel/_bazel_usrname/779131debdfa005bca7898ed75d6397c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
		patch(ctx)
	File "/home/usrname/.cache/bazel/_bazel_usrname/779131debdfa005bca7898ed75d6397c/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 135, column 22, in patch
		ctx.patch(patchfile, strip)
Error in patch: Error applying patch /home/usrname/projectDir/mediapipe-master/third_party/org_tensorflow_compatibility_fixes.diff: Incorrect Chunk: the chunk content doesn't match the target
**Original Position**: 42

```  

Here is what I changed in workspace. 
```

_TENSORFLOW_GIT_COMMIT = "82515cee8f36fe9f3abe25d5aef8218ce8bf48bb"
_TENSORFLOW_SHA256 = "67cdd7da47103fcfc9ce088cb945331a7d7d823fe9cf4bae333fef433257a260"

http_archive(
    name = "org_tensorflow",
    patch_args = [
        "-p1",
    ],
    patches = [
        "@//third_party:org_tensorflow_compatibility_fixes.diff",
    ],
    sha256 = _TENSORFLOW_SHA256,
    strip_prefix = "tensorflow-%s" % _TENSORFLOW_GIT_COMMIT,
    urls = [
        "https://github.com/tensorflow/tensorflow/archive/%s.tar.gz" % _TENSORFLOW_GIT_COMMIT,
    ],
)
```
