### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Zlobrynya** [google/mediapipe#66]
Hello, I am trying to build examples.
I follow the instructions: https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md
I get the following error:

```
INFO: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /Users/user/Desktop/code/test/mediapipe/WORKSPACE:251:1
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
		fail(("error running '%s' while worki...)))
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in fail
		" ".join(command)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
		fail(("error running '%s' while worki...)))
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in fail
		" ".join(command)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.

ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
INFO: Call stack for the definition of repository 'build_bazel_rules_apple' which is a git_repository (rule definition at /private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /Users/user/Desktop/code/test/mediapipe/WORKSPACE:251:1
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
		fail(("error running '%s' while worki...)))
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in fail
		" ".join(command)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
		fail(("error running '%s' while worki...)))
	File "/private/var/tmp/_bazel_user/a3001209bd0aba032e65f19a79746e9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in fail
		" ".join(command)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.

ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
ERROR: no such package '@build_bazel_rules_apple//apple': Traceback (most recent call last):
General failure: Bazel aspects could not be built.
```

Could you help?

**Comment by Lovekeshbhagat23** [comment]
hi i am facing same issue and you suggest any solution to this problem?
