### ISSUE TITLE
Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed

### ISSUE THREAD

**Issue by ihmc3jn09hk** [google/mediapipe#68]
Hey all, it has been smoothly testing and install the Mediapipe library and run the Helloworld test up-till trying to build the "facedetectioncpu", "handtracking" module. The following error pops up. OS Ubuntu 16.04 LTS.

````
Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (Exit 1) java failed: error executing command external/remotejdk11_linux/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp ... (remaining 4 argument(s) skipped)
````

```
Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: external/local_jdk
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.update(Locations.java:1853)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SystemModulesLocationHandler.handleOption(Locations.java:1798)
	at jdk.compiler/com.sun.tools.javac.file.Locations.handleOption(Locations.java:2062)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:269)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager$2.handleFileManagerOption(BaseFileManager.java:222)
	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1138)
	at jdk.compiler/com.sun.tools.javac.main.Option.handleOption(Option.java:1086)
	at jdk.compiler/com.sun.tools.javac.file.BaseFileManager.handleOption(BaseFileManager.java:232)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.doProcessArgs(Arguments.java:390)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.processArgs(Arguments.java:347)
	at jdk.compiler/com.sun.tools.javac.main.Arguments.init(Arguments.java:246)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:185)
	at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:106)
	at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)
```
````
$ java -version
$ openjdk version "9-internal"
$ OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
$ OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

````
I tried using the Android Studio approach for compilation which it installed the NDK 20.0.xxxxx and I think should not be a problem yet resulted in the above error. Then I tried install the Android SDK and NDK with the .sh and this time with NDK r18 but still resulted in the same error. ANDROID_HOME and ANDROID_NDK_HOME are set upon each method.

Have no idea how to fix the issue. Please help!

**Comment by ihmc3jn09hk** [comment]
Solved the problem.
My JDK was corrupted and reinstalling it solved the problem.

**Comment by yingshaoxo** [comment]
In other words: just use `sudo apt install default-jdk`.
