### ISSUE TITLE
Error when running HelloWorld

### ISSUE THREAD

**Issue by ahmed-shariff** [google/mediapipe#753]
When running the hello world I get the following:

```
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  /home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

INFO: Repository rules_java instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/py/python_configure.bzl", line 208
		get_python_bin(repository_ctx)
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/remote_config/common.bzl", line 44, in get_python_bin
		which(repository_ctx, "python")
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/remote_config/common.bzl", line 29, in which
		execute(repository_ctx, <1 more arguments>)
	File "/home/amsha/.cache/bazel/_bazel_amsha/955e294a1e8fb046811a0f2f766e6662/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Repository command failed

INFO: Elapsed time: 0.281s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @bazel_tools//tools/jdk
```

os: ubuntu 20.04
python: 3.8
bazel: 3.2

**Comment by jiuqiant** [comment]
The actual error is `com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found`. Can you verify your network setting? You probably can find some useful solutions at https://github.com/google/mediapipe/issues/, https://github.com/google/mediapipe/issues/581, and https://github.com/google/mediapipe/issues/601.
