### ISSUE TITLE
Couldn't find "libmediapipe_jni.so"

### ISSUE THREAD

**Issue by Dylan5100** [google/mediapipe#758]
I downloaded the MediaPipe multi-hand tracking gpu demo with MediaPipe's Android archive library [here](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example), and imported the project into Android Studio,  it came up with this error after building:

> The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

I refractored by removing the `minSdkVersion` and syncing the project again,  and the project is able to be built and run without error. However, when I attempt to run the project in the Android Emulator with two devices (API 22 with Android 5.1 ; API 28 with Android 9.0), it only ever shows the message: `MyMultiHandsTrackingApp keeps stopping`.

Here's the logcat:
```2020-06-01 17:15:08.137 3497-3497/? I/andstrackingap: Not late-enabling -Xcheck:jni (already on)
2020-06-01 17:15:08.228 3497-3497/? W/andstrackingap: Unexpected CPU variant for X86 using defaults: x86_64
2020-06-01 17:15:08.970 3497-3497/com.example.mediapipemultihandstrackingapp I/andstrackingap: The ClassLoaderContext is a special shared library.
2020-06-01 17:15:09.409 3497-3497/com.example.mediapipemultihandstrackingapp D/Camera2Initializer: CameraX initializing with Camera2 ...
2020-06-01 17:15:09.438 3497-3497/com.example.mediapipemultihandstrackingapp I/CameraManagerGlobal: Connecting to camera service
2020-06-01 17:15:10.103 3497-3497/com.example.mediapipemultihandstrackingapp W/andstrackingap: Verification of void androidx.camera.core.AutoValue_SurfaceSizeDefinition.<init>(android.util.Size, android.util.Size, android.util.Size) took 597.673ms
2020-06-01 17:15:10.167 3497-3497/com.example.mediapipemultihandstrackingapp D/CameraRepository: Added camera: 0
2020-06-01 17:15:10.199 3497-3529/com.example.mediapipemultihandstrackingapp D/UseCaseAttachState: Active and online use case: [] for camera: 0
2020-06-01 17:15:10.201 3497-3497/com.example.mediapipemultihandstrackingapp D/CameraRepository: Added camera: 1
2020-06-01 17:15:10.207 3497-3529/com.example.mediapipemultihandstrackingapp D/UseCaseAttachState: Active and online use case: [] for camera: 1
2020-06-01 17:15:10.250 3497-3497/com.example.mediapipemultihandstrackingapp D/AndroidRuntime: Shutting down VM
2020-06-01 17:15:10.260 3497-3497/com.example.mediapipemultihandstrackingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mediapipemultihandstrackingapp, PID: 3497
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.mediapipemultihandstrackingapp-xr2Y3qGpPY5HIlyiUsVbUw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.mediapipemultihandstrackingapp-xr2Y3qGpPY5HIlyiUsVbUw==/lib/x86_64, /system/lib64]]] couldn't find "libmediapipe_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.example.mediapipemultihandstrackingapp.MainActivity.<clinit>(MainActivity.java:38)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2020-06-01 17:15:13.937 3497-3497/com.example.mediapipemultihandstrackingapp I/Process: Sending signal. PID: 3497 SIG: 9
```
In there is shows _**AndroidRuntime: FATAL EXCEPTION: ..... couldn't find "libmediapipe_jni.so"**_
Any idea on what am I missing here? I'm to new to everything here sorry if this is a very basic question.

**Comment by jiuqiant** [comment]
The error seems to be`Unexpected CPU variant for X86 using defaults: x86_64`. 
The AAR you downloaded only supports armeabi and arm64. It doesn't have x86_64 support (mostly for emulators).

**Comment by Dylan5100** [comment]
@jiuqiant Thank you for your prompt reply. I tried using ADB to run instead and it worked :)

**Comment by Dylan5100** [comment]
@jiuqiant just an unrelated question here, but i would like to ask if the processed frame rate (multi-hand tracking) is dependant on the video capturing device, or it is actually constant across all device? If so what is the frame rate?
