### ISSUE TITLE
opencv imwrite

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#785]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKNSt6__ndk16vectorIiNS6_9allocatorIiEEEE" referenced by "/data/app/com.google.mediapipe.apps.hededgedetectiongpu-1/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:994)
        at java.lang.System.loadLibrary(System.java:1533)
        at com.google.mediapipe.apps.hededgedetectiongpu.MainActivity.<clinit>(MainActivity.java:52)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

The opencv lib has no imwrite in it?

**Comment by weinixuehao** [comment]
@jiuqiant 
Does not provide imwrite? Has libopencv_java3 linked static lib such as imgcodecs.a?
If libopencv_java3 has not imwrite it will cause an error(undefined reference to imwrite) at build time.

**Comment by weinixuehao** [comment]
nm -gDC libopencv_java3.so > symbols.txt 
![image](https://user-images.githubusercontent.com/17869361/84336439-ce87bd80-abc9-11ea-8cb5-bed32778a4da.png)

**Comment by duanyuanfu** [comment]
i have the same question, have you resolve it?
