### ISSUE TITLE
UnsatisfiedLinkError when building custom AAR in multi hand tracking app

### ISSUE THREAD

**Issue by anubhavagr27** [google/mediapipe#814]
I built my own custom AAR and hand tracking binary graph and tried to build the multi hand tracking apk given by jiuqiant. But I got the following error log. It is giving Unsatisfied Link Error when loading mediapipe_jni.so . I was able to successfully run the custom desktop solution but could not build the mobile apk. I tried many methods but found no solution.Please help me. Thanks. 

2020-06-17 16:34:04.968 22992-22992/com.example.mediapipemultihandstrackingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mediapipemultihandstrackingapp, PID: 22992
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "pcond" referenced by "/data/app/com.example.mediapipemultihandstrackingapp-nipd88fHmFF7IxiujdWFQw==/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.example.mediapipemultihandstrackingapp.MainActivity.<clinit>(MainActivity.java:38)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3436)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8019)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by jiuqiant** [comment]
Similar to https://github.com/google/mediapipe/issues/499?

**Comment by mmm2016** [comment]
You should update all assets related files

**Comment by anubhavagr27** [comment]
> Similar to #499?

Yeah, it seems same but there is no appropriate and exact solution of the same.

**Comment by anubhavagr27** [comment]
> You should update all assets related files

I am modifying it through "https://github.com/TheJLifeX/mediapipe/tree/hand-mouvement-recognition" . I updated corresponding AAR and binarypb file

**Comment by anubhavagr27** [comment]
Can you please help me in how to convert this desktop version code "https://github.com/TheJLifeX/mediapipe/tree/hand-mouvement-recognition"  to build in android studio with gradle. I followed steps mentioned in this: "https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-use-a-mediapipe-aar-in-android-studio-with-gradle " and updated corresponding AAR and binarypb file
but got the error mentioned in above comments. Am I missing something?

**Comment by sgowroji** [comment]
Hi @anubhavagr27, Could you please check the latest [documentation](https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-use-a-mediapipe-aar-in-android-studio-with-gradle) of building the android code with ARR in Android studio gradle.
