### ISSUE TITLE
Issue in TensorFlow CUDA Support on Jetson Nano

### ISSUE THREAD

**Issue by ruisebastiao** [google/mediapipe#852]
Hello,

i'm trying to build  the hand_tracking_gpu demo on a jetson nano board, but i'm getting the error `Expected even number of arguments` , building without cuda gives no error

```
rui@rui-jetson:~/pen/mediapipe$ bazel build -c opt --config=cuda --spawn_strategy=local     --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS  mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  /home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1235:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1205
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 931, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 578, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 480, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Expected even number of arguments
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /home/rui/pen/mediapipe/mediapipe/examples/desktop/hand_tracking/BUILD:36:10: //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu depends on @local_config_cuda//crosstool:toolchain in repository @local_config_cuda which failed to fetch. no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1205
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 931, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 578, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 480, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
Expected even number of arguments
ERROR: Analysis of target '//mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu' failed; build aborted: Analysis failed
INFO: Elapsed time: 0,747s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @local_config_cc; fetching
rui@rui-jetson:~/pen/mediapipe$ 

```

**Comment by jiuqiant** [comment]
Hi, it's a tensorflow config issue in its cuda_configure.bzl.

You should be able to bypass this by modifying [the line 576](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda_configure.bzl#L576) of `/home/rui/pen/bazel_cache/_bazel_rui/2863b3cfed4551e7bbfa622d9a9a5606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl` to be

```
        "cudnn": _check_cuda_lib_params(
            "cudnn",
            cpu_value,
            cuda_config.config["cudnn_library_dir"],
            '8', 
            static = False,
        ),
```

**Comment by ruisebastiao** [comment]
Now i'm getting the following error:
```

ERROR: /home/rui/pen/mediapipe/mediapipe/framework/tool/BUILD:97:10: Linking of rule '//mediapipe/framework/tool:encode_as_c_string' failed (Exit 1)
/usr/bin/ld: bazel-out/host/bin/external/com_google_absl/absl/strings/libstrings.a(charconv.o): undefined reference to symbol 'nanf@@GLIBC_2.17'
//lib/aarch64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 712,491s, Critical Path: 643,68s
INFO: 555 processes: 555 local.
FAILED: Build did NOT complete successfully

```

**Comment by jiuqiant** [comment]
https://github.com/tensorflow/tensorflow/issues/1171#issuecomment-244819545 might be helpful.

**Comment by ruisebastiao** [comment]
I solve the issue adding  `linkopts = ["-lm"],`  to  [mediapipe/framework/tool/BUILD#L103](https://github.com/google/mediapipe/blob/master/mediapipe/framework/tool/BUILD#L103). And now successfully build the app. Thanks

**Comment by jiuqiant** [comment]
Thanks for sharing your solution!

Just to clarify, for hand tracking gpu, you don't need to config TensorFlow CUDA for MediaPipe. Hand tracking gpu example is doing inference with TFLite and its underlying OpenGL backend. The only MediaPipe example that needs CUDA is `mediapipe/examples/desktop/object_detection:object_detection_tensorflow`. We are still investigate how to make that work on Jetson devices.

**Comment by tangX10086** [comment]
> 

hi, I meet the same problem as you, but when I adding `linkopts = ["-lm"],` to [mediapipe/framework/tool/BUILD#L103](https://github.com/google/mediapipe/blob/master/mediapipe/framework/tool/BUILD#L103).There will be an error 
```
Error: mediapipe_proto_library() got unexpected keyword argument: linkopts
```
do you have some ideas?

**Comment by Jayddy6** [comment]
INFO: Repository local_config_cuda instantiated at:
  /usr/lib/x86_64-linux-gnu/mediapipe/WORKSPACE:512:14: in <toplevel>
  /root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/tensorflow/workspace2.bzl:982:19: in workspace
  /root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/tensorflow/workspace2.bzl:101:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  /root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1484:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1437, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1013, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 695, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 672, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
Inconsistent CUDA toolkit path: /usr vs /usr/lib
ERROR: /usr/lib/x86_64-linux-gnu/mediapipe/WORKSPACE:512:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1437, column 38, in _cuda_autoconf_impl
		_create_local_cuda_repository(repository_ctx)
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1013, column 35, in _create_local_cuda_repository
		cuda_config = _get_cuda_config(repository_ctx, find_cuda_config_script)
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 695, column 30, in _get_cuda_config
		config = find_cuda_config(repository_ctx, find_cuda_config_script, ["cuda", "cudnn"])
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 672, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 666, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
Inconsistent CUDA toolkit path: /usr vs /usr/lib
ERROR: /root/.cache/bazel/_bazel_root/94f10d90b28875348bfe96592e3be585/external/bazel_tools/tools/cpp/BUILD:58:19: @bazel_tools//tools/cpp:current_cc_toolchain depends on @local_config_cuda//crosstool:toolchain in repository @local_config_cuda which failed to fetch. no such package '@local_config_cuda//crosstool': Repository command failed
Inconsistent CUDA toolkit path: /usr vs /usr/lib
ERROR: Analysis of target '//mediapipe/tasks/metadata:image_segmenter_metadata_schema_py' failed; build aborted: 

When installing Mediapipe gpu I encountered the following problem. Do you have any ideas on how to solve it?
I followed the following installation guide: https://github.com/riverzhou/mediapipe/tree/cuda/mediapipe/gpu

This happens when I run mediapipe setup.py.
