### ISSUE TITLE
ValidateRequiredSidePackets failed error when modifying the face tracking example to shoe detection. 

### ISSUE THREAD

**Issue by davitgoder** [google/mediapipe#855]
I've followed [these ](https://google.github.io/mediapipe/solutions/objectron) instructions to get assets and .aar file for shoe detection, then I imported them as shown [here](https://google.github.io/mediapipe/getting_started/android_archive_library.html)

- object_detection_3d_sneakers.tflite
- objectdetection3d.binarypb
- ssdlite_object_detection_labelmap.txt
into assets folder and 
and 
- mp_object_detection_3d.aar 

into libs folder

I used the most resembling example project in my opinion [face detection ](https://github.com/jiuqiant/mediapipe_face_detection_aar_example) and swapped respective files as mentioned above.

the build is successful, but after running it on the android device I get an error: 

2020-06-29 15:43:44.002 1114-1312/com.example.myfacedetectionapp E/native: E0629 15:43:44.002478  1312 graph.cc:415] INVALID_ARGUMENT: ValidateRequiredSidePackets failed to validate: 
    ; Side packet "box_asset_name" is required but was not provided.
    ; Side packet "box_texture" is required but was not provided.
    ; Side packet "obj_asset_name" is required but was not provided.
    ; Side packet "obj_texture" is required but was not provided.
2020-06-29 15:43:44.006 1114-1312/com.example.myfacedetectionapp E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.example.myfacedetectionapp, PID: 1114
    com.google.mediapipe.framework.MediaPipeException: invalid argument: ValidateRequiredSidePackets failed to validate: 
    ; Side packet "box_asset_name" is required but was not provided.
    ; Side packet "box_texture" is required but was not provided.
    ; Side packet "obj_asset_name" is required but was not provided.
    ; Side packet "obj_texture" is required but was not provided.
        at com.google.mediapipe.framework.Graph.nativeStartRunningGraph(Native Method)
        at com.google.mediapipe.framework.Graph.startRunningGraph(Graph.java:289)
        at com.google.mediapipe.components.FrameProcessor.startGraph(FrameProcessor.java:372)
        at com.google.mediapipe.components.FrameProcessor.maybeAcceptNewFrame(FrameProcessor.java:296)
        at com.google.mediapipe.components.FrameProcessor.onNewFrame(FrameProcessor.java:311)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:275)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:221)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$Y1vV_XyLsWZ0ebOvq-iwjQ0H3Sw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:134)

**Comment by jiuqiant** [comment]
Hi, unlike the face and hand examples, object detection 3d example requires extra input side packets. You need to send four input side packets into the graph in MainActivity.java. See https://github.com/google/mediapipe/blob/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetection3d/MainActivity.java#L50

**Comment by davitgoder** [comment]
Thanks, worked.

**Comment by Zulqurnain24** [comment]
> Thanks, worked.

Can you share the link for the project in which object_detection_3d_sneakers.tflite worked I am creating the project for ios and it will be a great help.

**Comment by davitgoder** [comment]
still working on it, will share it as soon as I solve the issues.

**Comment by z7212819** [comment]
> Thanks, worked.

Have you implemented shoe detection? Can you share the source code?
