### ISSUE TITLE
Unable to build example

### ISSUE THREAD

**Issue by Chandler-Shuyu-Xie** [google/mediapipe#876]
```
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository local_execution_config_python instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule local_python_configure defined at:
  /home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl", line 213
		_get_numpy_include(<2 more arguments>)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl", line 198, in _get_numpy_include
		execute(repository_ctx, [python_bin, "-c", "from __future__ import print_function;import numpy; print(numpy.get_include());"], error_msg = "Problem getting numpy include path.", error_details = "Is numpy installed?").stdout.splitlines()
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, in execute
		execute(repository_ctx, <3 more arguments>)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: Traceback (most recent call last):
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl", line 213
		_get_numpy_include(<2 more arguments>)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl", line 198, in _get_numpy_include
		execute(repository_ctx, [python_bin, "-c", "from __future__ import print_function;import numpy; print(numpy.get_include());"], error_msg = "Problem getting numpy include path.", error_details = "Is numpy installed?").stdout.splitlines()
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, in execute
		execute(repository_ctx, <3 more arguments>)
	File "/home/shuyu/.cache/bazel/_bazel_shuyu/62badf022f3ce22497c0d412433756ef/external/org_tensorflow/third_party/remote_config/common.bzl", line 208, in execute
		fail(<1 more arguments>)
Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
INFO: Elapsed time: 0.272s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured\
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured\
)
```

Procedutre:
clone this repo
install bazel using apt
use script to install and configure opencv
install python3-numpy package using apt

OS: Ubuntu 18.04.4

**Comment by jiuqiant** [comment]
The error message is `ImportError: No module named numpy Is numpy installed?`. Have you installed numpy via pip3?

**Comment by Chandler-Shuyu-Xie** [comment]
Installed numpy with pip3. Stil the same import error

**Comment by Chandler-Shuyu-Xie** [comment]
I build it in docker. Bypass this problem

**Comment by xiezhongzhao** [comment]
Run `sudo apt install python-numpy` command line to solve the problem
