### ISSUE TITLE
java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl

### ISSUE THREAD

**Issue by cangwang** [google/mediapipe#907]
2020-07-14 17:19:56.761 24749-24749/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mediapipe.apps.facedetectioncpu, PID: 24749
    java.lang.RuntimeException: Unable to create application com.google.devtools.build.android.incrementaldeployment.StubApplication: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6598)
        at android.app.ActivityThread.access$1400(ActivityThread.java:226)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7573)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
     Caused by: java.lang.IllegalStateException: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.monkeyPatchExistingResources(StubApplication.java:320)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.onCreate(StubApplication.java:569)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6593)
        at android.app.ActivityThread.access$1400(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7573) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953) 
     Caused by: java.lang.NoSuchFieldException: No field mAssets in class Landroid/content/res/MiuiResourcesImpl; (declaration of 'android.content.res.MiuiResourcesImpl' appears in /system/framework/framework.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.monkeyPatchExistingResources(StubApplication.java:312)
        at com.google.devtools.build.android.incrementaldeployment.StubApplication.onCreate(StubApplication.java:569) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6593) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7573)

**Comment by evan0929** [comment]
Excuse me,How do you solve this issue？
