### ISSUE TITLE
ERROR: An error occurred during the fetch of repository 'maven'

### ISSUE THREAD

**Issue by endersaka** [google/mediapipe#941]
Hi, I am following https://google.github.io/mediapipe/getting_started/hello_world_android.html and I am unable to compile.

This is the error.

I know nothing about Maven and I honestly would love to avoid to learn another package manager (and wathever else it is) but I have to make it work. So, I am guessing.

It looks like `maven` uses some cached version of the `coursier.jar` instead of downloading the latest one. My problem is that I don't have a clue of:

- how to force `maven` to dowload it
- which `maven` `bazel` is using (I think I have one installed on my machine sometime ago)
- and how to verify it

```
$ bazel build -c opt --config=android_arm64 saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
INFO: Repository maven instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule coursier_fetch defined at:
  /Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl:798:18: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '6598d9277705ad8369a4f9c64217fbc31c19234f2cbcca9b1e5c4300a3abb317' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC5-3/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   Traceback (most recent call last):
        File "/Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl", line 650
                artifact.update(<1 more arguments>)
        File "/Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl", line 650, in artifact.update
                shas[str(repository_ctx.path(file))]
key "/Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/maven/v1/https/maven.google.com/androidx/activity/activity/1.0.0-rc01/activity-1.0.0-rc01.aar" not found in dictionary
ERROR: /Users/<username>/Documents/GitHub/mediapipe/third_party/BUILD:116:1: //third_party:androidx_appcompat depends on @maven//:androidx_appcompat_appcompat in repository @maven which failed to fetch. no such package '@maven//': Traceback (most recent call last):
        File "/Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl", line 650
                artifact.update(<1 more arguments>)
        File "/Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl", line 650, in artifact.update
                shas[str(repository_ctx.path(file))]
key "/Volumes/TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/maven/v1/https/maven.google.com/androidx/activity/activity/1.0.0-rc01/activity-1.0.0-rc01.aar" not found in dictionary
ERROR: Analysis of target '//saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld' failed; build aborted: Analysis failed
INFO: Elapsed time: 95.341s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 6974 targets configured)
```

**Comment by endersaka** [comment]
Some update. I found the version of `maven` that I have installed some time ago on my machine.

```
$ cat ~/.bash_profile | grep maven
export PATH="/Applications/apache-maven-3.6.1/bin:$PATH"
$ ls /Applications/apache-maven-3.6.1/bin
m2.conf         mvn             mvn.cmd         mvnDebug        mvnDebug.cmd    mvnyjp
$ which mvn
/Applications/apache-maven-3.6.1/bin/mvn
$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /Applications/apache-maven-3.6.1
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: it_IT, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```
I tried to remove `~/.m2/repository/` and clean `bazel clean --expurge` but it didn't work.

**Comment by endersaka** [comment]
Ok this is weird. I managed to remove some errors and messages.

I installed latest Bazel.
I completelly removed ~/.m2 and Bazel output directory.
I installed NDK 20.1.5948944 so that Bazel does not complain for the NDK version (even if it was only a Warning).
I set $TEST_TMPDIR in the second try.

Bazel still fails but this time it can't find `@maven//:androidx_constraintlayout_constraintlayout` (see second try) and not `@maven//:androidx_appcompat_appcompat` (see first try) as it was until I set `$TEST_TMPDIR`.

```
$ export ANDROID_NDK_HOME=/Users/<username>/Library/Android/sdk/ndk/20.1.5948944

$ bazel build -c opt --config=android_arm64 saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld
INFO: Repository maven instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule coursier_fetch defined at:
  /Volumes/Disco Esterno TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
INFO: Repository 'maven' used the following cache hits instead of downloading the corresponding file.
 * Hash '6598d9277705ad8369a4f9c64217fbc31c19234f2cbcca9b1e5c4300a3abb317' for https://github.com/coursier/coursier/releases/download/v2.0.0-RC5-3/coursier.jar
If the definition of 'maven' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'maven':
   key "/Volumes/Disco Esterno TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/maven/v1/https/maven.google.com/androidx/activity/activity/1.0.0-rc01/activity-1.0.0-rc01.aar" not found in dictionary
ERROR: /Users/<username>/Documents/GitHub/mediapipe/third_party/BUILD:116:16: //third_party:androidx_appcompat depends on @maven//:androidx_appcompat_appcompat in repository @maven which failed to fetch. no such package '@maven//': key "/Volumes/Disco Esterno TrekStor/tmp/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/maven/v1/https/maven.google.com/androidx/activity/activity/1.0.0-rc01/activity-1.0.0-rc01.aar" not found in dictionary
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
ERROR: Analysis of target '//saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld' failed; build aborted: Analysis failed
INFO: Elapsed time: 28.630s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

$ export TEST_TMPDIR="/Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>"

$ bazel build -c opt --config=android_arm64 saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld
$TEST_TMPDIR defined: output root default is '/Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>' and max_idle_secs default is '15'.
WARNING: Output user root "/Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>/_bazel_<username>" contains a space. This will probably break the build. You should set a different --output_user_root.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/7c09d15f9fcc14343343c247ebf5b8e0afe3e4aa.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a07fc8b90c22e42962142504438a84b31567976adcd9ee1a4c9f75d2e3396f8d"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
INFO: Repository maven instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule coursier_fetch defined at:
  /Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/rules_jvm_external/coursier.bzl:798:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'maven':
   key "/Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/maven/v1/https/maven.google.com/androidx/activity/activity/1.0.0-rc01/activity-1.0.0-rc01.aar" not found in dictionary
ERROR: /Users/<username>/Documents/GitHub/mediapipe/third_party/BUILD:123:16: //third_party:androidx_constraint_layout depends on @maven//:androidx_constraintlayout_constraintlayout in repository @maven which failed to fetch. no such package '@maven//': key "/Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>/_bazel_<username>/fcb58a7ae07d9f9bce35a80cbb3eb208/external/maven/v1/https/maven.google.com/androidx/activity/activity/1.0.0-rc01/activity-1.0.0-rc01.aar" not found in dictionary
ERROR: Analysis of target '//saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld' failed; build aborted: Analysis failed
INFO: Elapsed time: 113.316s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (39 packages loaded, 6747 targets configured)
```

**Comment by endersaka** [comment]
Ok, I resolved. "And the reason is...".

```
WARNING: Output user root "/Volumes/Disco Esterno TrekStor/tmp/_test_bazel_<username>/_bazel_<username>" contains a space. This will probably break the build. You should set a different --output_user_root.
```
Meaning I can't use the external disk unless I rename it or mount to a different mount point, breaking paths used by other softwares.
