### ISSUE TITLE
oppo phone crash

### ISSUE THREAD

**Issue by weinixuehao** [google/mediapipe#964]
```
07-30 17:48:47.334 10806 10874 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__trunctfdf2" referenced by "/data/app/com.**.**-aoFgbEo3KSfKbQHBpagILA==/lib/arm64/libmediapipe_jni.so"...
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.reactnativecontourdetect.ContourScanner.<init>(ContourScanner.kt:57)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.reactnativecontourdetect.ContourDetectPackage.createViewManagers(ContourDetectPackage.kt:18)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:198)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
07-30 17:48:47.334 10806 10874 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

Phone Name:OPPO A5
Model:PBAM00
Android Version:8.1.0

**Comment by sgowroji** [comment]
Hi @weinixuehao, Could you please provide the steps to reproduce the above error. Thanks!
