### ISSUE TITLE
Example “handtrackinggpu” app crashed with GL error 0x505, memory leak？

### ISSUE THREAD

**Issue by lynneChan** [google/mediapipe#997]
I have successfully built the android apk from the example of [handtrackinggpu](https://github.com/google/mediapipe/tree/master/mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu) in `apps` directory，and run it on my android device `(OPPO Reno2)`, but the app was crashed after about one or two minutes， with the following logcat errors：
```
2020-08-12 11:20:13.611 13457-13484/? E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.google.mediapipe.apps.handtrackinggpu, PID: 13457
    java.lang.RuntimeException: glActiveTexture: GL error: 0x505
        at com.google.mediapipe.glutil.ShaderUtil.checkGlError(ShaderUtil.java:175)
        at com.google.mediapipe.glutil.ExternalTextureRenderer.render(ExternalTextureRenderer.java:93)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.updateOutputFrame(ExternalTextureConverter.java:433)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:336)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:295)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread$$Lambda$0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
```

I hava made some digs about the `GL error code 0x505`, it means `GL_OUT_OF_MEMORY`( [wiki](https://www.khronos.org/opengl/wiki/OpenGL_Error)). So i using the `adb` tools to connect to my android device and found that the memory usage was keeping increasing while the processing running till the error happened.

I have tried the suggestion from the issue [#969 ](https://github.com/google/mediapipe/issues/969) to reduce the memory usage, but it still not working.

Interesting things is, i also test the version from [TheJLifeX](https://github.com/TheJLifeX/mediapipe) which was forked after commit `d144e564d8f48737f1bf684ee741c9ccf6a5909d`, and that works all fine.

So is anyone knows how this happened? Is this some unknow bug which cause memory leak? Does anyone knows how to fix the problem? Or any suggestions?

**Comment by mcclanahoochie** [comment]
hi
a big update on gpu memory usage was recently made in [v0.7.9](https://github.com/google/mediapipe/blob/v0.7.9/) that reduces memory pressure quite a bit (the official fix for https://github.com/google/mediapipe/issues/969#issuecomment-667294219 ), can you try re-building with the latest version of mediapipe to see if it helps?

**Comment by lynneChan** [comment]
@mcclanahoochie Thanks for your reply, but the problem still exist. The app was crashed about one minutes later while the memory usage was keeping increasing.

**Comment by istoneyou** [comment]
@lynneChan I also meet the issue as you. When I try the handtracking, the memory keep increasing until the low memory killer. But I find that  the version which commit is b09cc090d464c02ee48d0837543b452a303a0e26 do not has this issue. @mcclanahoochie

**Comment by lynneChan** [comment]
This problem is very strange. I have done some test on different versions and found that, the memory cost was first keeping increasing to a very high level, and then it decreased to a much stable and lower cost. But most time, the app crashed and cannot survive the first stage. Till now, this phenomenon was first observed after commit `bdfdaef30585719ed2cd1bc598a3e9879bcc4a1c`, and i donnot know which reason caused this.

**Comment by mapleyuan** [comment]
I meet the same problem. Any update? thx @lynneChan @mcclanahoochie

**Comment by mcclanahoochie** [comment]
There have been other fixes in regards to memory handling over the past months, does the issue still appear in the latest mediapipe release?

**Comment by mcclanahoochie** [comment]
closing due to lack of activity

**Comment by abhimuktheeswarar** [comment]
Issue is still there:
```
2021-11-24 19:32:49.463 4813-9275/com.google.mediapipe.apps.hands E/BufferQueueProducer: [SurfaceTexture-294-4813-2](id:12cd00000002,api:4,p:1480,c:4813) queueBuffer: BufferQueue has been abandoned
2021-11-24 19:32:49.475 4813-9275/com.google.mediapipe.apps.hands E/BufferQueueProducer: [SurfaceTexture-294-4813-2](id:12cd00000002,api:4,p:1480,c:4813) dequeueBuffer: BufferQueue has been abandoned
2021-11-24 19:32:49.476 4813-9300/com.google.mediapipe.apps.hands E/AndroidRuntime: FATAL EXCEPTION: ExternalTextureConverter
    Process: com.google.mediapipe.apps.hands, PID: 4813
    java.lang.RuntimeException: glActiveTexture: GL error: 0x505
        at com.google.mediapipe.glutil.ShaderUtil.checkGlError(ShaderUtil.java:175)
        at com.google.mediapipe.glutil.ExternalTextureRenderer.render(ExternalTextureRenderer.java:115)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.updateOutputFrame(ExternalTextureConverter.java:486)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.renderNext(ExternalTextureConverter.java:389)
        at com.google.mediapipe.components.ExternalTextureConverter$RenderThread.lambda$onFrameAvailable$0$ExternalTextureConverter$RenderThread(ExternalTextureConverter.java:338)
        at com.google.mediapipe.components.-$$Lambda$ExternalTextureConverter$RenderThread$IXJjtE68JMV2CMJNQcFYhTUqhj8.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at com.google.mediapipe.glutil.GlThread.run(GlThread.java:141)
2021-11-24 19:32:49.517 4813-7721/com.google.mediapipe.apps.hands E/BufferQueueProducer: [SurfaceTexture-294-4813-2](id:12cd00000002,api:4,p:1480,c:4813) queueBuffer: BufferQueue has been abandoned
2021-11-24 19:32:49.559 4813-9275/com.google.mediapipe.apps.hands E/BufferQueueProducer: [SurfaceTexture-294-4813-2](id:12cd00000002,api:4,p:1480,c:4813) queueBuffer: BufferQueue has been abandoned
```
